image:
  repository: registry.k8s.io/autoscaling/cluster-autoscaler
  tag: v1.31.0

awsRegion: ""

autoDiscovery:
  clusterName: ""

extraArgs: {}

serviceAccount:
  create: true
  name: cluster-autoscaler
  annotations: {}

resources:
  requests:
    cpu: 100m
    memory: 300Mi
