#include "sovereign/checkpoint.hpp"
#include "sovereign/sha256.hpp"
#include <fstream>
#include <sstream>
#include <unistd.h>
namespace sovereign {
static std::string read_all(const std::filesystem::path& path){std::ifstream input(path,std::ios::binary);if(!input)throw std::runtime_error("cannot open checkpoint file");return{std::istreambuf_iterator<char>(input),std::istreambuf_iterator<char>()};}
static void durable(const std::filesystem::path& path,const std::string& data){auto temporary=path;temporary+=".pending";{std::ofstream output(temporary,std::ios::binary|std::ios::trunc);if(!output)throw std::runtime_error("cannot write checkpoint");output<<data;output.flush();if(!output)throw std::runtime_error("cannot flush checkpoint");}std::filesystem::rename(temporary,path);}
void CheckpointStore::save(const std::string& canonical,const std::string& digest,std::uint64_t generation){if(sha256_hex(canonical)!=digest)throw std::runtime_error("checkpoint digest mismatch");std::filesystem::create_directories(root_);auto directory=root_/("generation-"+std::to_string(generation));auto staging=root_/(".generation-"+std::to_string(generation)+"-pending");std::filesystem::remove_all(staging);std::filesystem::create_directories(staging);durable(staging/"snapshot.json",canonical);durable(staging/"digest",digest+"\n");durable(staging/"complete","complete\n");std::filesystem::remove_all(directory);std::filesystem::rename(staging,directory);durable(root_/"CURRENT",std::to_string(generation)+"\n");}
std::optional<Checkpoint> CheckpointStore::load(std::uint64_t generation)const{try{auto directory=root_/("generation-"+std::to_string(generation));if(!std::filesystem::exists(directory/"complete"))return std::nullopt;auto canonical=read_all(directory/"snapshot.json");auto digest=read_all(directory/"digest");while(!digest.empty()&&(digest.back()=='\n'||digest.back()=='\r'))digest.pop_back();if(sha256_hex(canonical)!=digest)return std::nullopt;auto snapshot=decode_snapshot(parse_json(canonical));if(snapshot->generation!=generation)return std::nullopt;return Checkpoint{snapshot,canonical,digest};}catch(...){return std::nullopt;}}
std::optional<Checkpoint> CheckpointStore::load_current()const{try{auto text=read_all(root_/"CURRENT");std::size_t consumed{};auto generation=std::stoull(text,&consumed);if(consumed==0)return std::nullopt;if(auto current=load(generation))return current;std::optional<Checkpoint> fallback;for(const auto& entry:std::filesystem::directory_iterator(root_)){auto name=entry.path().filename().string();if(!entry.is_directory()||name.rfind("generation-",0)!=0)continue;auto value=std::stoull(name.substr(11));auto candidate=load(value);if(candidate&&(!fallback||candidate->snapshot->generation>fallback->snapshot->generation))fallback=std::move(candidate);}return fallback;}catch(...){return std::nullopt;}}
}