#include "sovereign/connection.hpp"
#include <algorithm>
#include <arpa/inet.h>
#include <cstring>
#include <stdexcept>
#include <sys/socket.h>

namespace sovereign {
std::pair<std::uint8_t*,std::size_t> ByteBuffer::write_span(){if(writable()==0)return{nullptr,0};std::size_t contiguous=std::min(writable(),storage_.size()-write_);return{storage_.data()+write_,contiguous};}
std::pair<const std::uint8_t*,std::size_t> ByteBuffer::read_span()const{if(readable()==0)return{nullptr,0};std::size_t contiguous=std::min(readable(),storage_.size()-read_);return{storage_.data()+read_,contiguous};}
void ByteBuffer::produced(std::size_t amount){if(amount>writable())throw std::logic_error("buffer overflow");write_=(write_+amount)%storage_.size();size_+=amount;}
void ByteBuffer::consumed(std::size_t amount){if(amount>readable())throw std::logic_error("buffer underflow");read_=(read_+amount)%storage_.size();size_-=amount;}
bool ByteBuffer::append(const std::uint8_t* data,std::size_t size){if(size>writable())return false;while(size){auto [output,count]=write_span();count=std::min(count,size);std::memcpy(output,data,count);produced(count);data+=count;size-=count;}return true;}
Connection::Connection(std::uint64_t value,int client,std::shared_ptr<const Snapshot> runtime,const Listener* selected_listener,const Target* selected_target):id(value),client_fd(client),snapshot(std::move(runtime)),listener(selected_listener),target(selected_target),client_to_target(listener->buffer_bytes),target_to_client(listener->buffer_bytes),proxy_header_pending(listener->proxy_protocol_v2),accepted_at(std::chrono::steady_clock::now()),last_progress(accepted_at){}
bool Connection::complete()const{return(client_read_closed&&client_to_target.readable()==0&&target_write_closed)&&(target_read_closed&&target_to_client.readable()==0&&client_write_closed);}
std::shared_ptr<Connection> ConnectionRegistry::add(int client,std::shared_ptr<const Snapshot> snapshot,const Listener* listener,const Target* target){std::lock_guard lock(mutex_);if(values_.size()>=maximum_)return{};auto value=std::make_shared<Connection>(next_++,client,std::move(snapshot),listener,target);values_.emplace(value->id,value);descriptors_.emplace(client,value->id);return value;}
std::shared_ptr<Connection> ConnectionRegistry::by_fd(int descriptor)const{std::lock_guard lock(mutex_);auto found=descriptors_.find(descriptor);if(found==descriptors_.end())return{};auto value=values_.find(found->second);return value==values_.end()?std::shared_ptr<Connection>{}:value->second;}
void ConnectionRegistry::bind_target(const std::shared_ptr<Connection>& connection,int descriptor){std::lock_guard lock(mutex_);connection->target_fd=descriptor;descriptors_[descriptor]=connection->id;}
void ConnectionRegistry::remove(std::uint64_t id){std::lock_guard lock(mutex_);auto found=values_.find(id);if(found==values_.end())return;descriptors_.erase(found->second->client_fd);descriptors_.erase(found->second->target_fd);values_.erase(found);}
std::vector<std::shared_ptr<Connection>> ConnectionRegistry::snapshot(std::size_t limit)const{std::lock_guard lock(mutex_);std::vector<std::shared_ptr<Connection>> result;for(const auto& [id,value]:values_){(void)id;if(result.size()==limit)break;result.push_back(value);}return result;}
std::size_t ConnectionRegistry::size()const{std::lock_guard lock(mutex_);return values_.size();}

std::vector<std::uint8_t> proxy_v2_header(const sockaddr_storage& source,const sockaddr_storage& destination){static constexpr std::uint8_t signature[]={0x0d,0x0a,0x0d,0x0a,0x00,0x0d,0x0a,0x51,0x55,0x49,0x54,0x0a};std::vector<std::uint8_t> output(signature,signature+12);output.push_back(0x21);if(source.ss_family==AF_INET&&destination.ss_family==AF_INET){output.push_back(0x11);output.push_back(0);output.push_back(12);const auto* left=reinterpret_cast<const sockaddr_in*>(&source);const auto* right=reinterpret_cast<const sockaddr_in*>(&destination);const auto* a=reinterpret_cast<const std::uint8_t*>(&left->sin_addr);const auto* b=reinterpret_cast<const std::uint8_t*>(&right->sin_addr);output.insert(output.end(),a,a+4);output.insert(output.end(),b,b+4);auto source_port=reinterpret_cast<const std::uint8_t*>(&left->sin_port);auto destination_port=reinterpret_cast<const std::uint8_t*>(&right->sin_port);output.insert(output.end(),source_port,source_port+2);output.insert(output.end(),destination_port,destination_port+2);}else if(source.ss_family==AF_INET6&&destination.ss_family==AF_INET6){output.push_back(0x21);output.push_back(0);output.push_back(36);const auto* left=reinterpret_cast<const sockaddr_in6*>(&source);const auto* right=reinterpret_cast<const sockaddr_in6*>(&destination);const auto* a=reinterpret_cast<const std::uint8_t*>(&left->sin6_addr);const auto* b=reinterpret_cast<const std::uint8_t*>(&right->sin6_addr);output.insert(output.end(),a,a+16);output.insert(output.end(),b,b+16);auto source_port=reinterpret_cast<const std::uint8_t*>(&left->sin6_port);auto destination_port=reinterpret_cast<const std::uint8_t*>(&right->sin6_port);output.insert(output.end(),source_port,source_port+2);output.insert(output.end(),destination_port,destination_port+2);}else{output.push_back(0x00);output.push_back(0);output.push_back(0);}return output;}
}