#include "sovereign/control.hpp"
#include "sovereign/sha256.hpp"
#include <arpa/inet.h>
#include <chrono>
#include <fstream>
#include <netdb.h>
#include <sys/socket.h>
#include <thread>
#include <unistd.h>
namespace sovereign {
static std::string read_file(const std::string& path){std::ifstream input(path);if(!input)throw std::runtime_error("cannot read node config");return{std::istreambuf_iterator<char>(input),std::istreambuf_iterator<char>()};}
NodeConfig load_node_config(const std::string& path){Json root=parse_json(read_file(path));NodeConfig value;value.node_id=root.at("node_id").string();value.session_id=root.at("session_id").string();value.zone=root.at("zone").string();value.control_host=root.at("control_host").string();value.control_port=static_cast<std::uint16_t>(root.at("control_port").integer());value.status_address=root.at("status_address").string();value.state_root=root.at("state_root").string();if(root.contains("max_frame_bytes"))value.max_frame_bytes=static_cast<std::uint32_t>(root.at("max_frame_bytes").integer());if(root.contains("max_connections"))value.max_connections=static_cast<std::size_t>(root.at("max_connections").integer());if(value.node_id.empty()||value.session_id.empty()||value.zone.empty()||value.control_port==0)throw JsonError("invalid node config");return value;}
int ControlClient::connect_once()const{addrinfo hints{};hints.ai_socktype=SOCK_STREAM;hints.ai_family=AF_UNSPEC;addrinfo* addresses{};if(getaddrinfo(config_.control_host.c_str(),std::to_string(config_.control_port).c_str(),&hints,&addresses)!=0)return-1;int connected=-1;for(addrinfo* item=addresses;item;item=item->ai_next){int descriptor=socket(item->ai_family,item->ai_socktype|SOCK_CLOEXEC,item->ai_protocol);if(descriptor<0)continue;if(connect(descriptor,item->ai_addr,item->ai_addrlen)==0){connected=descriptor;break;}close(descriptor);}freeaddrinfo(addresses);return connected;}
static std::string timestamp(){auto value=std::chrono::system_clock::now().time_since_epoch();return std::to_string(std::chrono::duration_cast<std::chrono::milliseconds>(value).count());}
Envelope ControlClient::reply(const std::string& type,const Envelope& request,Json::Object body){return Envelope{type,config_.node_id,config_.session_id,sequence_++,timestamp(),request.generation,request.digest,Json(std::move(body))};}
void ControlClient::send(int descriptor,const Envelope& envelope){auto bytes=frame_payload(encode_envelope(envelope),config_.max_frame_bytes);std::size_t offset=0;while(offset<bytes.size()){ssize_t count=::send(descriptor,bytes.data()+offset,bytes.size()-offset,MSG_NOSIGNAL);if(count<=0)throw std::runtime_error("control write failed");offset+=static_cast<std::size_t>(count);}}
void ControlClient::session(int descriptor,std::atomic_bool& stopping){auto active=runtimes_.active();Json::Object hello_body{{"capabilities",Json(Json::Array{Json(std::string("proxy-v2")),Json(std::string("checkpoint-v1"))})},{"checkpoint_generation",Json(static_cast<std::int64_t>(active?active->generation:0))},{"software",Json(std::string("0.1.0"))},{"zone",Json(config_.zone)}};send(descriptor,Envelope{"hello",config_.node_id,config_.session_id,sequence_++,timestamp(),0,"",Json(std::move(hello_body))});FrameDecoder decoder(config_.max_frame_bytes);std::array<std::uint8_t,8192> input{};while(!stopping.load()){ssize_t count=recv(descriptor,input.data(),input.size(),0);if(count<=0)break;for(const auto& payload:decoder.push(input.data(),static_cast<std::size_t>(count))){Envelope request=decode_envelope(payload);if(request.node_id!=config_.node_id||request.session_id!=config_.session_id)throw JsonError("stale control session");try{if(request.type=="prepare"){const Json& source=request.body.at("snapshot");std::string canonical=write_json(source);if(sha256_hex(canonical)!=request.digest)throw JsonError("snapshot digest mismatch");auto candidate=decode_snapshot(source);if(candidate->generation!=request.generation)throw JsonError("snapshot generation mismatch");checkpoints_.save(canonical,request.digest,request.generation);runtimes_.prepare(std::move(candidate),request.digest);send(descriptor,reply("prepared",request));counters_.increment("prepare_total");}else if(request.type=="activate"){if(!runtimes_.activate(request.generation,request.digest))throw JsonError("candidate was not prepared");proxy_.publish();send(descriptor,reply("active",request,{{"listener_count",Json(static_cast<std::int64_t>(runtimes_.active()->listeners.size()))},{"ready",Json(true)}}));counters_.increment("activate_total");}else if(request.type=="status"){auto runtime=runtimes_.active();send(descriptor,reply("status",request,{{"active_generation",Json(static_cast<std::int64_t>(runtime?runtime->generation:0))},{"connections",Json(static_cast<std::int64_t>(proxy_.connections().size()))},{"ready",Json(runtime!=nullptr)}}));}}catch(const std::exception& error){send(descriptor,reply("rejected",request,{{"code",Json(std::string("snapshot_invalid"))},{"detail",Json(std::string(error.what()).substr(0,256))}}));counters_.increment("reject_total");}}}}
void ControlClient::run(std::atomic_bool& stopping){while(!stopping.load()){int descriptor=connect_once();if(descriptor<0){std::this_thread::sleep_for(std::chrono::seconds(1));continue;}try{session(descriptor,stopping);}catch(...){counters_.increment("control_error_total");}close(descriptor);if(!stopping.load())std::this_thread::sleep_for(std::chrono::seconds(1));}}
}