#include "sovereign/proxy.hpp"
#include <arpa/inet.h>
#include <cerrno>
#include <cstring>
#include <fcntl.h>
#include <stdexcept>
#include <sys/epoll.h>
#include <sys/socket.h>
#include <unistd.h>

namespace sovereign {
static void nonblocking(int descriptor){int flags=fcntl(descriptor,F_GETFL,0);if(flags<0||fcntl(descriptor,F_SETFL,flags|O_NONBLOCK)<0)throw std::runtime_error("cannot set nonblocking");}
static sockaddr_storage endpoint(const std::string& address,std::uint16_t port,socklen_t& length){sockaddr_storage storage{};if(address.find(':')!=std::string::npos){auto* value=reinterpret_cast<sockaddr_in6*>(&storage);value->sin6_family=AF_INET6;value->sin6_port=htons(port);if(inet_pton(AF_INET6,address.c_str(),&value->sin6_addr)!=1)throw std::runtime_error("invalid IPv6 address");length=sizeof(sockaddr_in6);}else{auto* value=reinterpret_cast<sockaddr_in*>(&storage);value->sin_family=AF_INET;value->sin_port=htons(port);if(inet_pton(AF_INET,address.c_str(),&value->sin_addr)!=1)throw std::runtime_error("invalid IPv4 address");length=sizeof(sockaddr_in);}return storage;}
Proxy::Proxy(RuntimeStore& runtimes,Eligibility& eligibility,std::string zone,std::size_t maximum_connections):runtimes_(runtimes),eligibility_(eligibility),zone_(std::move(zone)),connections_(maximum_connections){epoll_fd_=epoll_create1(EPOLL_CLOEXEC);if(epoll_fd_<0)throw std::runtime_error("epoll_create1 failed");}
Proxy::~Proxy(){for(auto&[fd,value]:listeners_){(void)value;close(fd);}if(epoll_fd_>=0)close(epoll_fd_);}
void Proxy::publish(){reconcile_listeners();}
void Proxy::stop_accepting(){accepting_=false;for(auto&[fd,value]:listeners_){(void)value;epoll_ctl(epoll_fd_,EPOLL_CTL_DEL,fd,nullptr);close(fd);}listeners_.clear();}
void Proxy::reconcile_listeners(){auto runtime=runtimes_.active();if(!runtime)return;stop_accepting();accepting_=true;for(const auto& listener:runtime->listeners){socklen_t length{};auto address=endpoint(listener.address,listener.port,length);int descriptor=socket(address.ss_family,SOCK_STREAM|SOCK_NONBLOCK|SOCK_CLOEXEC,0);if(descriptor<0)throw std::runtime_error("listener socket failed");int enabled=1;setsockopt(descriptor,SOL_SOCKET,SO_REUSEADDR,&enabled,sizeof(enabled));if(bind(descriptor,reinterpret_cast<sockaddr*>(&address),length)<0||listen(descriptor,512)<0){close(descriptor);throw std::runtime_error("listener bind failed");}epoll_event event{EPOLLIN,{}};event.data.fd=descriptor;if(epoll_ctl(epoll_fd_,EPOLL_CTL_ADD,descriptor,&event)<0){close(descriptor);throw std::runtime_error("listener epoll registration failed");}listeners_.emplace(descriptor,std::make_pair(runtime,&listener));}}
void Proxy::accept_client(int descriptor){auto listener= listeners_.at(descriptor);while(accepting_){sockaddr_storage source{};socklen_t length=sizeof(source);int client=accept4(descriptor,reinterpret_cast<sockaddr*>(&source),&length,SOCK_NONBLOCK|SOCK_CLOEXEC);if(client<0){if(errno==EAGAIN||errno==EWOULDBLOCK)return;throw std::runtime_error("accept failed");}const auto& group=listener.first->group(listener.second->target_group);auto candidates=eligibility_.eligible(group,zone_,std::chrono::steady_clock::now());char host[INET6_ADDRSTRLEN]{};if(source.ss_family==AF_INET)inet_ntop(AF_INET,&reinterpret_cast<sockaddr_in*>(&source)->sin_addr,host,sizeof(host));else inet_ntop(AF_INET6,&reinterpret_cast<sockaddr_in6*>(&source)->sin6_addr,host,sizeof(host));const Target* target=selector_.select(group,candidates,host,eligibility_);if(!target){close(client);continue;}auto connection=connections_.add(client,listener.first,listener.second,target);if(!connection){close(client);continue;}int backend=connect_target(*target);if(backend<0){close_connection(connection);continue;}connections_.bind_target(connection,backend);eligibility_.state(target->identity).active_connections++;if(connection->proxy_header_pending){sockaddr_storage destination{};socklen_t destination_length=sizeof(destination);getsockname(client,reinterpret_cast<sockaddr*>(&destination),&destination_length);auto header=proxy_v2_header(source,destination);if(!connection->client_to_target.append(header.data(),header.size())){close_connection(connection);continue;}connection->proxy_header_pending=false;}epoll_event client_event{EPOLLIN|EPOLLRDHUP,{}};client_event.data.fd=client;epoll_ctl(epoll_fd_,EPOLL_CTL_ADD,client,&client_event);epoll_event target_event{EPOLLIN|EPOLLOUT|EPOLLRDHUP,{}};target_event.data.fd=backend;epoll_ctl(epoll_fd_,EPOLL_CTL_ADD,backend,&target_event);}}
int Proxy::connect_target(const Target& target){socklen_t length{};auto address=endpoint(target.address,target.port,length);int descriptor=socket(address.ss_family,SOCK_STREAM|SOCK_NONBLOCK|SOCK_CLOEXEC,0);if(descriptor<0)return-1;if(connect(descriptor,reinterpret_cast<sockaddr*>(&address),length)<0&&errno!=EINPROGRESS){close(descriptor);return-1;}return descriptor;}
bool Proxy::transfer_read(int source,ByteBuffer& buffer,bool& closed){auto[output,size]=buffer.write_span();if(size==0)return true;ssize_t count=recv(source,output,size,0);if(count>0){buffer.produced(static_cast<std::size_t>(count));return true;}if(count==0){closed=true;return true;}return errno==EAGAIN||errno==EWOULDBLOCK;}
bool Proxy::transfer_write(int destination,ByteBuffer& buffer){auto[input,size]=buffer.read_span();if(size==0)return true;ssize_t count=send(destination,input,size,MSG_NOSIGNAL);if(count>0){buffer.consumed(static_cast<std::size_t>(count));return true;}return count<0&&(errno==EAGAIN||errno==EWOULDBLOCK);}
void Proxy::handle(int descriptor,std::uint32_t events){auto connection=connections_.by_fd(descriptor);if(!connection)return;bool client=descriptor==connection->client_fd;if(events&(EPOLLERR|EPOLLHUP)){close_connection(connection);return;}if(client){if((events&EPOLLIN)&&!transfer_read(descriptor,connection->client_to_target,connection->client_read_closed)){close_connection(connection);return;}if((events&EPOLLOUT)&&!transfer_write(descriptor,connection->target_to_client)){close_connection(connection);return;}if(events&EPOLLRDHUP)connection->client_read_closed=true;}else{if(connection->connect_state==ConnectState::connecting&&(events&EPOLLOUT)){int error=0;socklen_t size=sizeof(error);getsockopt(descriptor,SOL_SOCKET,SO_ERROR,&error,&size);if(error){close_connection(connection);return;}connection->connect_state=ConnectState::established;}if((events&EPOLLIN)&&!transfer_read(descriptor,connection->target_to_client,connection->target_read_closed)){close_connection(connection);return;}if((events&EPOLLOUT)&&!transfer_write(descriptor,connection->client_to_target)){close_connection(connection);return;}if(events&EPOLLRDHUP)connection->target_read_closed=true;}connection->last_progress=std::chrono::steady_clock::now();if(connection->client_read_closed&&connection->client_to_target.readable()==0&&!connection->target_write_closed){shutdown(connection->target_fd,SHUT_WR);connection->target_write_closed=true;}if(connection->target_read_closed&&connection->target_to_client.readable()==0&&!connection->client_write_closed){shutdown(connection->client_fd,SHUT_WR);connection->client_write_closed=true;}if(connection->complete())close_connection(connection);else update_interest(connection);}
void Proxy::update_interest(const std::shared_ptr<Connection>& connection){epoll_event client{EPOLLRDHUP,{}};client.data.fd=connection->client_fd;if(!connection->client_read_closed&&connection->client_to_target.writable())client.events|=EPOLLIN;if(connection->target_to_client.readable())client.events|=EPOLLOUT;epoll_ctl(epoll_fd_,EPOLL_CTL_MOD,connection->client_fd,&client);epoll_event target{EPOLLRDHUP,{}};target.data.fd=connection->target_fd;if(!connection->target_read_closed&&connection->target_to_client.writable())target.events|=EPOLLIN;if(connection->connect_state==ConnectState::connecting||connection->client_to_target.readable())target.events|=EPOLLOUT;epoll_ctl(epoll_fd_,EPOLL_CTL_MOD,connection->target_fd,&target);}
void Proxy::close_connection(const std::shared_ptr<Connection>& connection){epoll_ctl(epoll_fd_,EPOLL_CTL_DEL,connection->client_fd,nullptr);epoll_ctl(epoll_fd_,EPOLL_CTL_DEL,connection->target_fd,nullptr);if(connection->client_fd>=0)close(connection->client_fd);if(connection->target_fd>=0)close(connection->target_fd);auto& state=eligibility_.state(connection->target->identity);if(state.active_connections)state.active_connections--;connections_.remove(connection->id);}
void Proxy::expire(){auto now=std::chrono::steady_clock::now();for(const auto& connection:connections_.snapshot(10000)){auto connect_limit=connection->accepted_at+std::chrono::milliseconds(connection->listener->connect_timeout_ms);auto idle_limit=connection->last_progress+std::chrono::milliseconds(connection->listener->idle_timeout_ms);if((connection->connect_state==ConnectState::connecting&&now>connect_limit)||(now>idle_limit&&connection->client_to_target.readable()==0&&connection->target_to_client.readable()==0))close_connection(connection);}}
void Proxy::run(std::atomic_bool& stopping){reconcile_listeners();std::vector<epoll_event> events(256);while(!stopping.load()){int count=epoll_wait(epoll_fd_,events.data(),static_cast<int>(events.size()),250);if(count<0&&errno!=EINTR)throw std::runtime_error("epoll_wait failed");for(int index=0;index<count;index++){int descriptor=events[index].data.fd;if(listeners_.contains(descriptor))accept_client(descriptor);else handle(descriptor,events[index].events);}expire();}stop_accepting();for(const auto& connection:connections_.snapshot(10000))close_connection(connection);}
}