PROCESS-VOID.
    IF FUNCTION TRIM(E-REF(WS-IDX)) = SPACES OR FUNCTION TRIM(E-TRANSFER(WS-IDX)) = SPACES
        MOVE "BAD_TRANSFER" TO WS-REASON EXIT PARAGRAPH
    END-IF
    PERFORM FIND-ACCEPTED-REFERENCE
    IF WS-REF-IDX = 0 OR (E-TYPE(WS-REF-IDX) NOT = "D" AND E-TYPE(WS-REF-IDX) NOT = "R")
        MOVE "BAD_REFERENCE" TO WS-REASON EXIT PARAGRAPH
    END-IF
    IF E-TYPE(WS-REF-IDX) = "R"
        MOVE E-DISPATCH-INDEX(WS-REF-IDX) TO WS-DISPATCH-IDX
    ELSE
        MOVE WS-REF-IDX TO WS-DISPATCH-IDX
    END-IF
    IF E-TRANSFER(WS-IDX) NOT = E-ID(WS-DISPATCH-IDX)
        MOVE "BAD_TRANSFER" TO WS-REASON EXIT PARAGRAPH
    END-IF
    IF E-SOURCE(WS-IDX) NOT = E-SOURCE(WS-REF-IDX) OR E-DEST(WS-IDX) NOT = E-DEST(WS-REF-IDX) OR E-PART(WS-IDX) NOT = E-PART(WS-REF-IDX) OR E-COND(WS-IDX) NOT = E-COND(WS-REF-IDX) OR E-QTY(WS-IDX) NOT = E-QTY(WS-REF-IDX)
        MOVE "BAD_ROUTE" TO WS-REASON EXIT PARAGRAPH
    END-IF
    IF E-QTY-VALID(WS-IDX) NOT = "Y" OR E-QTY(WS-IDX) = 0
        MOVE "BAD_QUANTITY" TO WS-REASON EXIT PARAGRAPH
    END-IF
    IF E-VOIDED(WS-REF-IDX) = "Y"
        MOVE "ALREADY_VOID" TO WS-REASON EXIT PARAGRAPH
    END-IF
    IF E-TYPE(WS-REF-IDX) = "R"
        PERFORM VOID-RECEIPT
    ELSE
        PERFORM VOID-DISPATCH
    END-IF.

VOID-RECEIPT.
    PERFORM FIND-STOCKS
    IF WS-DEST-IDX = 0 MOVE "UNKNOWN_STOCK" TO WS-REASON EXIT PARAGRAPH END-IF
    IF S-QTY(WS-DEST-IDX) < E-QTY(WS-REF-IDX)
        MOVE "INSUFFICIENT_STOCK" TO WS-REASON EXIT PARAGRAPH
    END-IF
    SUBTRACT E-QTY(WS-REF-IDX) FROM S-QTY(WS-DEST-IDX)
    ADD E-QTY(WS-REF-IDX) TO E-OUTSTANDING(WS-DISPATCH-IDX)
    SUBTRACT E-QTY(WS-REF-IDX) FROM E-ACTIVE-RECEIVED(WS-DISPATCH-IDX)
    MOVE "Y" TO E-VOIDED(WS-REF-IDX) E-ACCEPTED(WS-IDX)
    MOVE WS-DISPATCH-IDX TO E-DISPATCH-INDEX(WS-IDX)
    ADD 1 TO WS-ACCEPTED-COUNT.

VOID-DISPATCH.
    IF E-ACTIVE-RECEIVED(WS-REF-IDX) > 0
        MOVE "RECEIPTS_ACTIVE" TO WS-REASON EXIT PARAGRAPH
    END-IF
    PERFORM FIND-STOCKS
    IF WS-SOURCE-IDX = 0 MOVE "UNKNOWN_STOCK" TO WS-REASON EXIT PARAGRAPH END-IF
    COMPUTE WS-PRODUCT = S-QTY(WS-SOURCE-IDX) + E-ORIGINAL(WS-REF-IDX) ON SIZE ERROR MOVE "OVERFLOW" TO WS-REASON END-COMPUTE
    IF WS-REASON NOT = SPACES OR WS-PRODUCT > 999999999
        MOVE "OVERFLOW" TO WS-REASON EXIT PARAGRAPH
    END-IF
    ADD E-ORIGINAL(WS-REF-IDX) TO S-QTY(WS-SOURCE-IDX)
    MOVE 0 TO E-OUTSTANDING(WS-REF-IDX)
    MOVE "Y" TO E-VOIDED(WS-REF-IDX) E-ACCEPTED(WS-IDX)
    MOVE WS-REF-IDX TO E-DISPATCH-INDEX(WS-IDX)
    ADD 1 TO WS-ACCEPTED-COUNT.
