image:
  repository: public.ecr.aws/eks/aws-load-balancer-controller
  tag: v2.11.0

clusterName: ""
region: ""
vpcId: ""

defaultTargetType: ip
enableShield: false
enableWaf: false
enableWafv2: false

serviceAccount:
  create: true
  name: aws-load-balancer-controller
  annotations: {}

resources:
  requests:
    cpu: 100m
    memory: 128Mi
