CHECK-DUPLICATE.
    IF FUNCTION TRIM(E-ID(WS-IDX)) = SPACES
        MOVE "BAD_TRANSFER" TO WS-REASON
        EXIT PARAGRAPH
    END-IF
    MOVE 0 TO WS-REF-IDX
    PERFORM VARYING WS-I FROM 1 BY 1 UNTIL WS-I >= WS-IDX OR WS-REF-IDX > 0
        IF E-ID(WS-I) = E-ID(WS-IDX) MOVE WS-I TO WS-REF-IDX END-IF
    END-PERFORM
    IF WS-REF-IDX > 0
        IF E-RAW(WS-REF-IDX) = E-RAW(WS-IDX)
            ADD 1 TO WS-DUPLICATE-COUNT
            MOVE "D" TO E-REJECTED(WS-IDX)
        ELSE
            MOVE "DUPLICATE_CONFLICT" TO WS-REASON
        END-IF
    END-IF.
