"""Reject codes and closed enumerations for the yard desk."""

from __future__ import annotations

VISIT_TYPES = ("LIVE_IN", "DROP_IN", "LIVE_OUT", "EMPTY_OUT", "LOADED_PICKUP")
LIVE_TYPES = ("LIVE_IN", "LIVE_OUT")
DROP_EQUIPMENT = ("DRY_53", "REEFER_53", "CONTAINER_40")
EQUIPMENT = ("DRY_53", "REEFER_53", "TANK", "CONTAINER_40")
HOLD_CODES = ("YARD_OSND", "YARD_SAFETY", "CARRIER_SEAL", "CARRIER_DOCS")
PAUSE_HOLDS = ("YARD_OSND", "YARD_SAFETY")
NONPAUSE_HOLDS = ("CARRIER_SEAL", "CARRIER_DOCS")
OPEN_STATES = ("ON_YARD", "MOVING", "DOCKED")
DOOR_CLASSES = ("DRY", "REEFER", "OUTBOUND")
ZONES = ("DROP_LOT", "STAGING", "DOCK_APRON", "CHASSIS_STACK")
MOVE_STATES = ("REQUESTED", "DISPATCHED", "IN_TRANSIT", "COMPLETED", "CANCELLED", "FAILED")

LOADED_TYPES = ("LIVE_IN", "LIVE_OUT", "LOADED_PICKUP")

APPOINTMENT_MISSING = "APPOINTMENT_MISSING"
APPOINTMENT_WINDOW = "APPOINTMENT_WINDOW"
VISIT_OPEN = "VISIT_OPEN"
VISIT_MISSING = "VISIT_MISSING"
SEAL_REQUIRED = "SEAL_REQUIRED"
SPOT_OCCUPIED = "SPOT_OCCUPIED"
DOOR_CLASS = "DOOR_CLASS"
DOOR_OCCUPIED = "DOOR_OCCUPIED"
CONTRACT_MISSING = "CONTRACT_MISSING"
EVENT_CONFLICT = "EVENT_CONFLICT"
HOLD_BLOCKS_OUT = "HOLD_BLOCKS_OUT"
MOVE_IN_FLIGHT = "MOVE_IN_FLIGHT"
CHASSIS_REQUIRED = "CHASSIS_REQUIRED"
HOLD_ACTIVE = "HOLD_ACTIVE"
HOLD_MISSING = "HOLD_MISSING"
CHASSIS_BUSY = "CHASSIS_BUSY"
MOVE_MISSING = "MOVE_MISSING"
SPOT_MISSING = "SPOT_MISSING"
DOOR_MISSING = "DOOR_MISSING"
CHASSIS_MISSING = "CHASSIS_MISSING"

USAGE_EXIT = 2
REJECT_EXIT = 1
OK_EXIT = 0
