apiVersion: v1
kind: Secret
metadata:
  name: jenkins-sonarqube-token
  namespace: jenkins
data:
  token: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-artifactory-credentials
  namespace: jenkins
data:
  username: admin
  password: ops-artifactory-admin
---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-admin-credentials
  namespace: jenkins
data:
  jenkins-admin-user: admin
  jenkins-admin-password: ops-jenkins-admin
---
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-db-credentials
  namespace: sonarqube
data:
  db-password: rds-sonar-pass
