CREATE TABLE IF NOT EXISTS warehouses(warehouse_id TEXT PRIMARY KEY,active INTEGER NOT NULL CHECK(active IN(0,1)));
CREATE TABLE IF NOT EXISTS items(item_id TEXT PRIMARY KEY,active INTEGER NOT NULL CHECK(active IN(0,1)),max_unit_cost TEXT NOT NULL,quantity_precision INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS inventory_positions(warehouse_id TEXT NOT NULL,item_id TEXT NOT NULL,quantity TEXT NOT NULL,value TEXT NOT NULL,version INTEGER NOT NULL,PRIMARY KEY(warehouse_id,item_id),FOREIGN KEY(warehouse_id) REFERENCES warehouses,FOREIGN KEY(item_id) REFERENCES items);
CREATE TABLE IF NOT EXISTS runs(generation_id TEXT PRIMARY KEY,state TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS processed_movements(generation_id TEXT NOT NULL,movement_id TEXT NOT NULL,sequence INTEGER NOT NULL,status TEXT NOT NULL,item_id TEXT NOT NULL,movement_type TEXT NOT NULL,quantity TEXT NOT NULL,unit_cost TEXT NOT NULL,PRIMARY KEY(generation_id,movement_id),UNIQUE(generation_id,sequence));
CREATE TABLE IF NOT EXISTS inventory_effects(id INTEGER PRIMARY KEY AUTOINCREMENT,generation_id TEXT NOT NULL,movement_id TEXT NOT NULL,sequence INTEGER NOT NULL,warehouse_id TEXT NOT NULL,item_id TEXT NOT NULL,quantity_delta TEXT NOT NULL,value_delta TEXT NOT NULL,effect_kind TEXT NOT NULL,FOREIGN KEY(generation_id,movement_id) REFERENCES processed_movements(generation_id,movement_id),UNIQUE(generation_id,movement_id,effect_kind));
CREATE TABLE IF NOT EXISTS rejects(id INTEGER PRIMARY KEY AUTOINCREMENT,generation_id TEXT NOT NULL,sequence INTEGER NOT NULL,movement_id TEXT NOT NULL,code TEXT NOT NULL,message TEXT NOT NULL,byte_offset INTEGER NOT NULL,byte_length INTEGER NOT NULL,UNIQUE(generation_id,sequence));
CREATE TABLE IF NOT EXISTS checkpoints(generation_id TEXT PRIMARY KEY,last_sequence INTEGER NOT NULL,byte_offset INTEGER NOT NULL,source_fingerprint TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS historical_movements(event_id INTEGER PRIMARY KEY,cycle_day INTEGER NOT NULL,warehouse_id TEXT NOT NULL,item_id TEXT NOT NULL,movement_type TEXT NOT NULL,status TEXT NOT NULL,quantity_variant INTEGER NOT NULL,value_variant INTEGER NOT NULL);
