package platform

var DependencyRules = []RuleDefinition{
	{
		Code:        "DEPENDENCY_MAVEN_NONPROD_SOURCE_ALLOWLIST",
		Surface:     "dependency",
		Manager:     "maven",
		Environment: "nonprod",
		Phase:       "source",
		Description: "require an approved artifact repository for maven in nonprod",
		Remediation: "configure an approved immutable source",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_MAVEN_NONPROD_DIGEST_REQUIRED",
		Surface:     "dependency",
		Manager:     "maven",
		Environment: "nonprod",
		Phase:       "identity",
		Description: "require immutable content identity for maven in nonprod",
		Remediation: "supply a verified sha256 digest",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_MAVEN_NONPROD_SCANNER_AVAILABLE",
		Surface:     "dependency",
		Manager:     "maven",
		Environment: "nonprod",
		Phase:       "scan",
		Description: "require scanner availability for maven in nonprod",
		Remediation: "restore scanner service before acquisition",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_MAVEN_NONPROD_SCANNER_FRESH",
		Surface:     "dependency",
		Manager:     "maven",
		Environment: "nonprod",
		Phase:       "scan",
		Description: "require current vulnerability database evidence for maven in nonprod",
		Remediation: "refresh scanner database and rescan",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_MAVEN_NONPROD_VULNERABILITY_THRESHOLD",
		Surface:     "dependency",
		Manager:     "maven",
		Environment: "nonprod",
		Phase:       "decision",
		Description: "enforce vulnerability severity threshold for maven in nonprod",
		Remediation: "remediate or obtain a scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_MAVEN_NONPROD_EXCEPTION_SCOPE",
		Surface:     "dependency",
		Manager:     "maven",
		Environment: "nonprod",
		Phase:       "exception",
		Description: "bind exceptions to exact artifact and context for maven in nonprod",
		Remediation: "issue a narrowly scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_MAVEN_NONPROD_PERMIT_BINDING",
		Surface:     "dependency",
		Manager:     "maven",
		Environment: "nonprod",
		Phase:       "permit",
		Description: "bind permit to request instance and artifact for maven in nonprod",
		Remediation: "request a new bound permit",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_MAVEN_NONPROD_PERMIT_EXPIRY",
		Surface:     "dependency",
		Manager:     "maven",
		Environment: "nonprod",
		Phase:       "permit",
		Description: "reject expired permits for maven in nonprod",
		Remediation: "reevaluate artifact policy",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_MAVEN_NONPROD_AUDIT_DURABILITY",
		Surface:     "dependency",
		Manager:     "maven",
		Environment: "nonprod",
		Phase:       "audit",
		Description: "durably journal every decision before success for maven in nonprod",
		Remediation: "repair audit storage and retry",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_MAVEN_NONPROD_REPLAY_PROTECTION",
		Surface:     "dependency",
		Manager:     "maven",
		Environment: "nonprod",
		Phase:       "replay",
		Description: "prevent permit reuse across processes and restarts for maven in nonprod",
		Remediation: "reevaluate and issue a new permit",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_MAVEN_PROD_SOURCE_ALLOWLIST",
		Surface:     "dependency",
		Manager:     "maven",
		Environment: "prod",
		Phase:       "source",
		Description: "require an approved artifact repository for maven in prod",
		Remediation: "configure an approved immutable source",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_MAVEN_PROD_DIGEST_REQUIRED",
		Surface:     "dependency",
		Manager:     "maven",
		Environment: "prod",
		Phase:       "identity",
		Description: "require immutable content identity for maven in prod",
		Remediation: "supply a verified sha256 digest",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_MAVEN_PROD_SCANNER_AVAILABLE",
		Surface:     "dependency",
		Manager:     "maven",
		Environment: "prod",
		Phase:       "scan",
		Description: "require scanner availability for maven in prod",
		Remediation: "restore scanner service before acquisition",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_MAVEN_PROD_SCANNER_FRESH",
		Surface:     "dependency",
		Manager:     "maven",
		Environment: "prod",
		Phase:       "scan",
		Description: "require current vulnerability database evidence for maven in prod",
		Remediation: "refresh scanner database and rescan",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_MAVEN_PROD_VULNERABILITY_THRESHOLD",
		Surface:     "dependency",
		Manager:     "maven",
		Environment: "prod",
		Phase:       "decision",
		Description: "enforce vulnerability severity threshold for maven in prod",
		Remediation: "remediate or obtain a scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_MAVEN_PROD_EXCEPTION_SCOPE",
		Surface:     "dependency",
		Manager:     "maven",
		Environment: "prod",
		Phase:       "exception",
		Description: "bind exceptions to exact artifact and context for maven in prod",
		Remediation: "issue a narrowly scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_MAVEN_PROD_PERMIT_BINDING",
		Surface:     "dependency",
		Manager:     "maven",
		Environment: "prod",
		Phase:       "permit",
		Description: "bind permit to request instance and artifact for maven in prod",
		Remediation: "request a new bound permit",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_MAVEN_PROD_PERMIT_EXPIRY",
		Surface:     "dependency",
		Manager:     "maven",
		Environment: "prod",
		Phase:       "permit",
		Description: "reject expired permits for maven in prod",
		Remediation: "reevaluate artifact policy",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_MAVEN_PROD_AUDIT_DURABILITY",
		Surface:     "dependency",
		Manager:     "maven",
		Environment: "prod",
		Phase:       "audit",
		Description: "durably journal every decision before success for maven in prod",
		Remediation: "repair audit storage and retry",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_MAVEN_PROD_REPLAY_PROTECTION",
		Surface:     "dependency",
		Manager:     "maven",
		Environment: "prod",
		Phase:       "replay",
		Description: "prevent permit reuse across processes and restarts for maven in prod",
		Remediation: "reevaluate and issue a new permit",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GRADLE_NONPROD_SOURCE_ALLOWLIST",
		Surface:     "dependency",
		Manager:     "gradle",
		Environment: "nonprod",
		Phase:       "source",
		Description: "require an approved artifact repository for gradle in nonprod",
		Remediation: "configure an approved immutable source",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GRADLE_NONPROD_DIGEST_REQUIRED",
		Surface:     "dependency",
		Manager:     "gradle",
		Environment: "nonprod",
		Phase:       "identity",
		Description: "require immutable content identity for gradle in nonprod",
		Remediation: "supply a verified sha256 digest",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GRADLE_NONPROD_SCANNER_AVAILABLE",
		Surface:     "dependency",
		Manager:     "gradle",
		Environment: "nonprod",
		Phase:       "scan",
		Description: "require scanner availability for gradle in nonprod",
		Remediation: "restore scanner service before acquisition",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GRADLE_NONPROD_SCANNER_FRESH",
		Surface:     "dependency",
		Manager:     "gradle",
		Environment: "nonprod",
		Phase:       "scan",
		Description: "require current vulnerability database evidence for gradle in nonprod",
		Remediation: "refresh scanner database and rescan",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GRADLE_NONPROD_VULNERABILITY_THRESHOLD",
		Surface:     "dependency",
		Manager:     "gradle",
		Environment: "nonprod",
		Phase:       "decision",
		Description: "enforce vulnerability severity threshold for gradle in nonprod",
		Remediation: "remediate or obtain a scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GRADLE_NONPROD_EXCEPTION_SCOPE",
		Surface:     "dependency",
		Manager:     "gradle",
		Environment: "nonprod",
		Phase:       "exception",
		Description: "bind exceptions to exact artifact and context for gradle in nonprod",
		Remediation: "issue a narrowly scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GRADLE_NONPROD_PERMIT_BINDING",
		Surface:     "dependency",
		Manager:     "gradle",
		Environment: "nonprod",
		Phase:       "permit",
		Description: "bind permit to request instance and artifact for gradle in nonprod",
		Remediation: "request a new bound permit",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GRADLE_NONPROD_PERMIT_EXPIRY",
		Surface:     "dependency",
		Manager:     "gradle",
		Environment: "nonprod",
		Phase:       "permit",
		Description: "reject expired permits for gradle in nonprod",
		Remediation: "reevaluate artifact policy",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GRADLE_NONPROD_AUDIT_DURABILITY",
		Surface:     "dependency",
		Manager:     "gradle",
		Environment: "nonprod",
		Phase:       "audit",
		Description: "durably journal every decision before success for gradle in nonprod",
		Remediation: "repair audit storage and retry",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GRADLE_NONPROD_REPLAY_PROTECTION",
		Surface:     "dependency",
		Manager:     "gradle",
		Environment: "nonprod",
		Phase:       "replay",
		Description: "prevent permit reuse across processes and restarts for gradle in nonprod",
		Remediation: "reevaluate and issue a new permit",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GRADLE_PROD_SOURCE_ALLOWLIST",
		Surface:     "dependency",
		Manager:     "gradle",
		Environment: "prod",
		Phase:       "source",
		Description: "require an approved artifact repository for gradle in prod",
		Remediation: "configure an approved immutable source",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GRADLE_PROD_DIGEST_REQUIRED",
		Surface:     "dependency",
		Manager:     "gradle",
		Environment: "prod",
		Phase:       "identity",
		Description: "require immutable content identity for gradle in prod",
		Remediation: "supply a verified sha256 digest",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GRADLE_PROD_SCANNER_AVAILABLE",
		Surface:     "dependency",
		Manager:     "gradle",
		Environment: "prod",
		Phase:       "scan",
		Description: "require scanner availability for gradle in prod",
		Remediation: "restore scanner service before acquisition",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GRADLE_PROD_SCANNER_FRESH",
		Surface:     "dependency",
		Manager:     "gradle",
		Environment: "prod",
		Phase:       "scan",
		Description: "require current vulnerability database evidence for gradle in prod",
		Remediation: "refresh scanner database and rescan",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GRADLE_PROD_VULNERABILITY_THRESHOLD",
		Surface:     "dependency",
		Manager:     "gradle",
		Environment: "prod",
		Phase:       "decision",
		Description: "enforce vulnerability severity threshold for gradle in prod",
		Remediation: "remediate or obtain a scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GRADLE_PROD_EXCEPTION_SCOPE",
		Surface:     "dependency",
		Manager:     "gradle",
		Environment: "prod",
		Phase:       "exception",
		Description: "bind exceptions to exact artifact and context for gradle in prod",
		Remediation: "issue a narrowly scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GRADLE_PROD_PERMIT_BINDING",
		Surface:     "dependency",
		Manager:     "gradle",
		Environment: "prod",
		Phase:       "permit",
		Description: "bind permit to request instance and artifact for gradle in prod",
		Remediation: "request a new bound permit",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GRADLE_PROD_PERMIT_EXPIRY",
		Surface:     "dependency",
		Manager:     "gradle",
		Environment: "prod",
		Phase:       "permit",
		Description: "reject expired permits for gradle in prod",
		Remediation: "reevaluate artifact policy",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GRADLE_PROD_AUDIT_DURABILITY",
		Surface:     "dependency",
		Manager:     "gradle",
		Environment: "prod",
		Phase:       "audit",
		Description: "durably journal every decision before success for gradle in prod",
		Remediation: "repair audit storage and retry",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GRADLE_PROD_REPLAY_PROTECTION",
		Surface:     "dependency",
		Manager:     "gradle",
		Environment: "prod",
		Phase:       "replay",
		Description: "prevent permit reuse across processes and restarts for gradle in prod",
		Remediation: "reevaluate and issue a new permit",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_NPM_NONPROD_SOURCE_ALLOWLIST",
		Surface:     "dependency",
		Manager:     "npm",
		Environment: "nonprod",
		Phase:       "source",
		Description: "require an approved artifact repository for npm in nonprod",
		Remediation: "configure an approved immutable source",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_NPM_NONPROD_DIGEST_REQUIRED",
		Surface:     "dependency",
		Manager:     "npm",
		Environment: "nonprod",
		Phase:       "identity",
		Description: "require immutable content identity for npm in nonprod",
		Remediation: "supply a verified sha256 digest",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_NPM_NONPROD_SCANNER_AVAILABLE",
		Surface:     "dependency",
		Manager:     "npm",
		Environment: "nonprod",
		Phase:       "scan",
		Description: "require scanner availability for npm in nonprod",
		Remediation: "restore scanner service before acquisition",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_NPM_NONPROD_SCANNER_FRESH",
		Surface:     "dependency",
		Manager:     "npm",
		Environment: "nonprod",
		Phase:       "scan",
		Description: "require current vulnerability database evidence for npm in nonprod",
		Remediation: "refresh scanner database and rescan",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_NPM_NONPROD_VULNERABILITY_THRESHOLD",
		Surface:     "dependency",
		Manager:     "npm",
		Environment: "nonprod",
		Phase:       "decision",
		Description: "enforce vulnerability severity threshold for npm in nonprod",
		Remediation: "remediate or obtain a scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_NPM_NONPROD_EXCEPTION_SCOPE",
		Surface:     "dependency",
		Manager:     "npm",
		Environment: "nonprod",
		Phase:       "exception",
		Description: "bind exceptions to exact artifact and context for npm in nonprod",
		Remediation: "issue a narrowly scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_NPM_NONPROD_PERMIT_BINDING",
		Surface:     "dependency",
		Manager:     "npm",
		Environment: "nonprod",
		Phase:       "permit",
		Description: "bind permit to request instance and artifact for npm in nonprod",
		Remediation: "request a new bound permit",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_NPM_NONPROD_PERMIT_EXPIRY",
		Surface:     "dependency",
		Manager:     "npm",
		Environment: "nonprod",
		Phase:       "permit",
		Description: "reject expired permits for npm in nonprod",
		Remediation: "reevaluate artifact policy",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_NPM_NONPROD_AUDIT_DURABILITY",
		Surface:     "dependency",
		Manager:     "npm",
		Environment: "nonprod",
		Phase:       "audit",
		Description: "durably journal every decision before success for npm in nonprod",
		Remediation: "repair audit storage and retry",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_NPM_NONPROD_REPLAY_PROTECTION",
		Surface:     "dependency",
		Manager:     "npm",
		Environment: "nonprod",
		Phase:       "replay",
		Description: "prevent permit reuse across processes and restarts for npm in nonprod",
		Remediation: "reevaluate and issue a new permit",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_NPM_PROD_SOURCE_ALLOWLIST",
		Surface:     "dependency",
		Manager:     "npm",
		Environment: "prod",
		Phase:       "source",
		Description: "require an approved artifact repository for npm in prod",
		Remediation: "configure an approved immutable source",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_NPM_PROD_DIGEST_REQUIRED",
		Surface:     "dependency",
		Manager:     "npm",
		Environment: "prod",
		Phase:       "identity",
		Description: "require immutable content identity for npm in prod",
		Remediation: "supply a verified sha256 digest",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_NPM_PROD_SCANNER_AVAILABLE",
		Surface:     "dependency",
		Manager:     "npm",
		Environment: "prod",
		Phase:       "scan",
		Description: "require scanner availability for npm in prod",
		Remediation: "restore scanner service before acquisition",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_NPM_PROD_SCANNER_FRESH",
		Surface:     "dependency",
		Manager:     "npm",
		Environment: "prod",
		Phase:       "scan",
		Description: "require current vulnerability database evidence for npm in prod",
		Remediation: "refresh scanner database and rescan",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_NPM_PROD_VULNERABILITY_THRESHOLD",
		Surface:     "dependency",
		Manager:     "npm",
		Environment: "prod",
		Phase:       "decision",
		Description: "enforce vulnerability severity threshold for npm in prod",
		Remediation: "remediate or obtain a scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_NPM_PROD_EXCEPTION_SCOPE",
		Surface:     "dependency",
		Manager:     "npm",
		Environment: "prod",
		Phase:       "exception",
		Description: "bind exceptions to exact artifact and context for npm in prod",
		Remediation: "issue a narrowly scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_NPM_PROD_PERMIT_BINDING",
		Surface:     "dependency",
		Manager:     "npm",
		Environment: "prod",
		Phase:       "permit",
		Description: "bind permit to request instance and artifact for npm in prod",
		Remediation: "request a new bound permit",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_NPM_PROD_PERMIT_EXPIRY",
		Surface:     "dependency",
		Manager:     "npm",
		Environment: "prod",
		Phase:       "permit",
		Description: "reject expired permits for npm in prod",
		Remediation: "reevaluate artifact policy",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_NPM_PROD_AUDIT_DURABILITY",
		Surface:     "dependency",
		Manager:     "npm",
		Environment: "prod",
		Phase:       "audit",
		Description: "durably journal every decision before success for npm in prod",
		Remediation: "repair audit storage and retry",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_NPM_PROD_REPLAY_PROTECTION",
		Surface:     "dependency",
		Manager:     "npm",
		Environment: "prod",
		Phase:       "replay",
		Description: "prevent permit reuse across processes and restarts for npm in prod",
		Remediation: "reevaluate and issue a new permit",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_PIP_NONPROD_SOURCE_ALLOWLIST",
		Surface:     "dependency",
		Manager:     "pip",
		Environment: "nonprod",
		Phase:       "source",
		Description: "require an approved artifact repository for pip in nonprod",
		Remediation: "configure an approved immutable source",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_PIP_NONPROD_DIGEST_REQUIRED",
		Surface:     "dependency",
		Manager:     "pip",
		Environment: "nonprod",
		Phase:       "identity",
		Description: "require immutable content identity for pip in nonprod",
		Remediation: "supply a verified sha256 digest",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_PIP_NONPROD_SCANNER_AVAILABLE",
		Surface:     "dependency",
		Manager:     "pip",
		Environment: "nonprod",
		Phase:       "scan",
		Description: "require scanner availability for pip in nonprod",
		Remediation: "restore scanner service before acquisition",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_PIP_NONPROD_SCANNER_FRESH",
		Surface:     "dependency",
		Manager:     "pip",
		Environment: "nonprod",
		Phase:       "scan",
		Description: "require current vulnerability database evidence for pip in nonprod",
		Remediation: "refresh scanner database and rescan",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_PIP_NONPROD_VULNERABILITY_THRESHOLD",
		Surface:     "dependency",
		Manager:     "pip",
		Environment: "nonprod",
		Phase:       "decision",
		Description: "enforce vulnerability severity threshold for pip in nonprod",
		Remediation: "remediate or obtain a scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_PIP_NONPROD_EXCEPTION_SCOPE",
		Surface:     "dependency",
		Manager:     "pip",
		Environment: "nonprod",
		Phase:       "exception",
		Description: "bind exceptions to exact artifact and context for pip in nonprod",
		Remediation: "issue a narrowly scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_PIP_NONPROD_PERMIT_BINDING",
		Surface:     "dependency",
		Manager:     "pip",
		Environment: "nonprod",
		Phase:       "permit",
		Description: "bind permit to request instance and artifact for pip in nonprod",
		Remediation: "request a new bound permit",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_PIP_NONPROD_PERMIT_EXPIRY",
		Surface:     "dependency",
		Manager:     "pip",
		Environment: "nonprod",
		Phase:       "permit",
		Description: "reject expired permits for pip in nonprod",
		Remediation: "reevaluate artifact policy",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_PIP_NONPROD_AUDIT_DURABILITY",
		Surface:     "dependency",
		Manager:     "pip",
		Environment: "nonprod",
		Phase:       "audit",
		Description: "durably journal every decision before success for pip in nonprod",
		Remediation: "repair audit storage and retry",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_PIP_NONPROD_REPLAY_PROTECTION",
		Surface:     "dependency",
		Manager:     "pip",
		Environment: "nonprod",
		Phase:       "replay",
		Description: "prevent permit reuse across processes and restarts for pip in nonprod",
		Remediation: "reevaluate and issue a new permit",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_PIP_PROD_SOURCE_ALLOWLIST",
		Surface:     "dependency",
		Manager:     "pip",
		Environment: "prod",
		Phase:       "source",
		Description: "require an approved artifact repository for pip in prod",
		Remediation: "configure an approved immutable source",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_PIP_PROD_DIGEST_REQUIRED",
		Surface:     "dependency",
		Manager:     "pip",
		Environment: "prod",
		Phase:       "identity",
		Description: "require immutable content identity for pip in prod",
		Remediation: "supply a verified sha256 digest",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_PIP_PROD_SCANNER_AVAILABLE",
		Surface:     "dependency",
		Manager:     "pip",
		Environment: "prod",
		Phase:       "scan",
		Description: "require scanner availability for pip in prod",
		Remediation: "restore scanner service before acquisition",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_PIP_PROD_SCANNER_FRESH",
		Surface:     "dependency",
		Manager:     "pip",
		Environment: "prod",
		Phase:       "scan",
		Description: "require current vulnerability database evidence for pip in prod",
		Remediation: "refresh scanner database and rescan",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_PIP_PROD_VULNERABILITY_THRESHOLD",
		Surface:     "dependency",
		Manager:     "pip",
		Environment: "prod",
		Phase:       "decision",
		Description: "enforce vulnerability severity threshold for pip in prod",
		Remediation: "remediate or obtain a scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_PIP_PROD_EXCEPTION_SCOPE",
		Surface:     "dependency",
		Manager:     "pip",
		Environment: "prod",
		Phase:       "exception",
		Description: "bind exceptions to exact artifact and context for pip in prod",
		Remediation: "issue a narrowly scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_PIP_PROD_PERMIT_BINDING",
		Surface:     "dependency",
		Manager:     "pip",
		Environment: "prod",
		Phase:       "permit",
		Description: "bind permit to request instance and artifact for pip in prod",
		Remediation: "request a new bound permit",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_PIP_PROD_PERMIT_EXPIRY",
		Surface:     "dependency",
		Manager:     "pip",
		Environment: "prod",
		Phase:       "permit",
		Description: "reject expired permits for pip in prod",
		Remediation: "reevaluate artifact policy",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_PIP_PROD_AUDIT_DURABILITY",
		Surface:     "dependency",
		Manager:     "pip",
		Environment: "prod",
		Phase:       "audit",
		Description: "durably journal every decision before success for pip in prod",
		Remediation: "repair audit storage and retry",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_PIP_PROD_REPLAY_PROTECTION",
		Surface:     "dependency",
		Manager:     "pip",
		Environment: "prod",
		Phase:       "replay",
		Description: "prevent permit reuse across processes and restarts for pip in prod",
		Remediation: "reevaluate and issue a new permit",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GO_NONPROD_SOURCE_ALLOWLIST",
		Surface:     "dependency",
		Manager:     "go",
		Environment: "nonprod",
		Phase:       "source",
		Description: "require an approved artifact repository for go in nonprod",
		Remediation: "configure an approved immutable source",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GO_NONPROD_DIGEST_REQUIRED",
		Surface:     "dependency",
		Manager:     "go",
		Environment: "nonprod",
		Phase:       "identity",
		Description: "require immutable content identity for go in nonprod",
		Remediation: "supply a verified sha256 digest",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GO_NONPROD_SCANNER_AVAILABLE",
		Surface:     "dependency",
		Manager:     "go",
		Environment: "nonprod",
		Phase:       "scan",
		Description: "require scanner availability for go in nonprod",
		Remediation: "restore scanner service before acquisition",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GO_NONPROD_SCANNER_FRESH",
		Surface:     "dependency",
		Manager:     "go",
		Environment: "nonprod",
		Phase:       "scan",
		Description: "require current vulnerability database evidence for go in nonprod",
		Remediation: "refresh scanner database and rescan",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GO_NONPROD_VULNERABILITY_THRESHOLD",
		Surface:     "dependency",
		Manager:     "go",
		Environment: "nonprod",
		Phase:       "decision",
		Description: "enforce vulnerability severity threshold for go in nonprod",
		Remediation: "remediate or obtain a scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GO_NONPROD_EXCEPTION_SCOPE",
		Surface:     "dependency",
		Manager:     "go",
		Environment: "nonprod",
		Phase:       "exception",
		Description: "bind exceptions to exact artifact and context for go in nonprod",
		Remediation: "issue a narrowly scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GO_NONPROD_PERMIT_BINDING",
		Surface:     "dependency",
		Manager:     "go",
		Environment: "nonprod",
		Phase:       "permit",
		Description: "bind permit to request instance and artifact for go in nonprod",
		Remediation: "request a new bound permit",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GO_NONPROD_PERMIT_EXPIRY",
		Surface:     "dependency",
		Manager:     "go",
		Environment: "nonprod",
		Phase:       "permit",
		Description: "reject expired permits for go in nonprod",
		Remediation: "reevaluate artifact policy",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GO_NONPROD_AUDIT_DURABILITY",
		Surface:     "dependency",
		Manager:     "go",
		Environment: "nonprod",
		Phase:       "audit",
		Description: "durably journal every decision before success for go in nonprod",
		Remediation: "repair audit storage and retry",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GO_NONPROD_REPLAY_PROTECTION",
		Surface:     "dependency",
		Manager:     "go",
		Environment: "nonprod",
		Phase:       "replay",
		Description: "prevent permit reuse across processes and restarts for go in nonprod",
		Remediation: "reevaluate and issue a new permit",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GO_PROD_SOURCE_ALLOWLIST",
		Surface:     "dependency",
		Manager:     "go",
		Environment: "prod",
		Phase:       "source",
		Description: "require an approved artifact repository for go in prod",
		Remediation: "configure an approved immutable source",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GO_PROD_DIGEST_REQUIRED",
		Surface:     "dependency",
		Manager:     "go",
		Environment: "prod",
		Phase:       "identity",
		Description: "require immutable content identity for go in prod",
		Remediation: "supply a verified sha256 digest",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GO_PROD_SCANNER_AVAILABLE",
		Surface:     "dependency",
		Manager:     "go",
		Environment: "prod",
		Phase:       "scan",
		Description: "require scanner availability for go in prod",
		Remediation: "restore scanner service before acquisition",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GO_PROD_SCANNER_FRESH",
		Surface:     "dependency",
		Manager:     "go",
		Environment: "prod",
		Phase:       "scan",
		Description: "require current vulnerability database evidence for go in prod",
		Remediation: "refresh scanner database and rescan",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GO_PROD_VULNERABILITY_THRESHOLD",
		Surface:     "dependency",
		Manager:     "go",
		Environment: "prod",
		Phase:       "decision",
		Description: "enforce vulnerability severity threshold for go in prod",
		Remediation: "remediate or obtain a scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GO_PROD_EXCEPTION_SCOPE",
		Surface:     "dependency",
		Manager:     "go",
		Environment: "prod",
		Phase:       "exception",
		Description: "bind exceptions to exact artifact and context for go in prod",
		Remediation: "issue a narrowly scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GO_PROD_PERMIT_BINDING",
		Surface:     "dependency",
		Manager:     "go",
		Environment: "prod",
		Phase:       "permit",
		Description: "bind permit to request instance and artifact for go in prod",
		Remediation: "request a new bound permit",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GO_PROD_PERMIT_EXPIRY",
		Surface:     "dependency",
		Manager:     "go",
		Environment: "prod",
		Phase:       "permit",
		Description: "reject expired permits for go in prod",
		Remediation: "reevaluate artifact policy",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GO_PROD_AUDIT_DURABILITY",
		Surface:     "dependency",
		Manager:     "go",
		Environment: "prod",
		Phase:       "audit",
		Description: "durably journal every decision before success for go in prod",
		Remediation: "repair audit storage and retry",
		FailClosed:  true,
	},
	{
		Code:        "DEPENDENCY_GO_PROD_REPLAY_PROTECTION",
		Surface:     "dependency",
		Manager:     "go",
		Environment: "prod",
		Phase:       "replay",
		Description: "prevent permit reuse across processes and restarts for go in prod",
		Remediation: "reevaluate and issue a new permit",
		FailClosed:  true,
	},
}
