package platform

var PackageRules = []RuleDefinition{
	{
		Code:        "PACKAGE_APT_NONPROD_SOURCE_ALLOWLIST",
		Surface:     "package",
		Manager:     "apt",
		Environment: "nonprod",
		Phase:       "source",
		Description: "require an approved artifact repository for apt in nonprod",
		Remediation: "configure an approved immutable source",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_NONPROD_DIGEST_REQUIRED",
		Surface:     "package",
		Manager:     "apt",
		Environment: "nonprod",
		Phase:       "identity",
		Description: "require immutable content identity for apt in nonprod",
		Remediation: "supply a verified sha256 digest",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_NONPROD_SCANNER_AVAILABLE",
		Surface:     "package",
		Manager:     "apt",
		Environment: "nonprod",
		Phase:       "scan",
		Description: "require scanner availability for apt in nonprod",
		Remediation: "restore scanner service before acquisition",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_NONPROD_SCANNER_FRESH",
		Surface:     "package",
		Manager:     "apt",
		Environment: "nonprod",
		Phase:       "scan",
		Description: "require current vulnerability database evidence for apt in nonprod",
		Remediation: "refresh scanner database and rescan",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_NONPROD_VULNERABILITY_THRESHOLD",
		Surface:     "package",
		Manager:     "apt",
		Environment: "nonprod",
		Phase:       "decision",
		Description: "enforce vulnerability severity threshold for apt in nonprod",
		Remediation: "remediate or obtain a scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_NONPROD_EXCEPTION_SCOPE",
		Surface:     "package",
		Manager:     "apt",
		Environment: "nonprod",
		Phase:       "exception",
		Description: "bind exceptions to exact artifact and context for apt in nonprod",
		Remediation: "issue a narrowly scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_NONPROD_PERMIT_BINDING",
		Surface:     "package",
		Manager:     "apt",
		Environment: "nonprod",
		Phase:       "permit",
		Description: "bind permit to request instance and artifact for apt in nonprod",
		Remediation: "request a new bound permit",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_NONPROD_PERMIT_EXPIRY",
		Surface:     "package",
		Manager:     "apt",
		Environment: "nonprod",
		Phase:       "permit",
		Description: "reject expired permits for apt in nonprod",
		Remediation: "reevaluate artifact policy",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_NONPROD_AUDIT_DURABILITY",
		Surface:     "package",
		Manager:     "apt",
		Environment: "nonprod",
		Phase:       "audit",
		Description: "durably journal every decision before success for apt in nonprod",
		Remediation: "repair audit storage and retry",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_NONPROD_REPLAY_PROTECTION",
		Surface:     "package",
		Manager:     "apt",
		Environment: "nonprod",
		Phase:       "replay",
		Description: "prevent permit reuse across processes and restarts for apt in nonprod",
		Remediation: "reevaluate and issue a new permit",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_PROD_SOURCE_ALLOWLIST",
		Surface:     "package",
		Manager:     "apt",
		Environment: "prod",
		Phase:       "source",
		Description: "require an approved artifact repository for apt in prod",
		Remediation: "configure an approved immutable source",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_PROD_DIGEST_REQUIRED",
		Surface:     "package",
		Manager:     "apt",
		Environment: "prod",
		Phase:       "identity",
		Description: "require immutable content identity for apt in prod",
		Remediation: "supply a verified sha256 digest",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_PROD_SCANNER_AVAILABLE",
		Surface:     "package",
		Manager:     "apt",
		Environment: "prod",
		Phase:       "scan",
		Description: "require scanner availability for apt in prod",
		Remediation: "restore scanner service before acquisition",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_PROD_SCANNER_FRESH",
		Surface:     "package",
		Manager:     "apt",
		Environment: "prod",
		Phase:       "scan",
		Description: "require current vulnerability database evidence for apt in prod",
		Remediation: "refresh scanner database and rescan",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_PROD_VULNERABILITY_THRESHOLD",
		Surface:     "package",
		Manager:     "apt",
		Environment: "prod",
		Phase:       "decision",
		Description: "enforce vulnerability severity threshold for apt in prod",
		Remediation: "remediate or obtain a scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_PROD_EXCEPTION_SCOPE",
		Surface:     "package",
		Manager:     "apt",
		Environment: "prod",
		Phase:       "exception",
		Description: "bind exceptions to exact artifact and context for apt in prod",
		Remediation: "issue a narrowly scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_PROD_PERMIT_BINDING",
		Surface:     "package",
		Manager:     "apt",
		Environment: "prod",
		Phase:       "permit",
		Description: "bind permit to request instance and artifact for apt in prod",
		Remediation: "request a new bound permit",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_PROD_PERMIT_EXPIRY",
		Surface:     "package",
		Manager:     "apt",
		Environment: "prod",
		Phase:       "permit",
		Description: "reject expired permits for apt in prod",
		Remediation: "reevaluate artifact policy",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_PROD_AUDIT_DURABILITY",
		Surface:     "package",
		Manager:     "apt",
		Environment: "prod",
		Phase:       "audit",
		Description: "durably journal every decision before success for apt in prod",
		Remediation: "repair audit storage and retry",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_PROD_REPLAY_PROTECTION",
		Surface:     "package",
		Manager:     "apt",
		Environment: "prod",
		Phase:       "replay",
		Description: "prevent permit reuse across processes and restarts for apt in prod",
		Remediation: "reevaluate and issue a new permit",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_GET_NONPROD_SOURCE_ALLOWLIST",
		Surface:     "package",
		Manager:     "apt-get",
		Environment: "nonprod",
		Phase:       "source",
		Description: "require an approved artifact repository for apt-get in nonprod",
		Remediation: "configure an approved immutable source",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_GET_NONPROD_DIGEST_REQUIRED",
		Surface:     "package",
		Manager:     "apt-get",
		Environment: "nonprod",
		Phase:       "identity",
		Description: "require immutable content identity for apt-get in nonprod",
		Remediation: "supply a verified sha256 digest",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_GET_NONPROD_SCANNER_AVAILABLE",
		Surface:     "package",
		Manager:     "apt-get",
		Environment: "nonprod",
		Phase:       "scan",
		Description: "require scanner availability for apt-get in nonprod",
		Remediation: "restore scanner service before acquisition",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_GET_NONPROD_SCANNER_FRESH",
		Surface:     "package",
		Manager:     "apt-get",
		Environment: "nonprod",
		Phase:       "scan",
		Description: "require current vulnerability database evidence for apt-get in nonprod",
		Remediation: "refresh scanner database and rescan",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_GET_NONPROD_VULNERABILITY_THRESHOLD",
		Surface:     "package",
		Manager:     "apt-get",
		Environment: "nonprod",
		Phase:       "decision",
		Description: "enforce vulnerability severity threshold for apt-get in nonprod",
		Remediation: "remediate or obtain a scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_GET_NONPROD_EXCEPTION_SCOPE",
		Surface:     "package",
		Manager:     "apt-get",
		Environment: "nonprod",
		Phase:       "exception",
		Description: "bind exceptions to exact artifact and context for apt-get in nonprod",
		Remediation: "issue a narrowly scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_GET_NONPROD_PERMIT_BINDING",
		Surface:     "package",
		Manager:     "apt-get",
		Environment: "nonprod",
		Phase:       "permit",
		Description: "bind permit to request instance and artifact for apt-get in nonprod",
		Remediation: "request a new bound permit",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_GET_NONPROD_PERMIT_EXPIRY",
		Surface:     "package",
		Manager:     "apt-get",
		Environment: "nonprod",
		Phase:       "permit",
		Description: "reject expired permits for apt-get in nonprod",
		Remediation: "reevaluate artifact policy",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_GET_NONPROD_AUDIT_DURABILITY",
		Surface:     "package",
		Manager:     "apt-get",
		Environment: "nonprod",
		Phase:       "audit",
		Description: "durably journal every decision before success for apt-get in nonprod",
		Remediation: "repair audit storage and retry",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_GET_NONPROD_REPLAY_PROTECTION",
		Surface:     "package",
		Manager:     "apt-get",
		Environment: "nonprod",
		Phase:       "replay",
		Description: "prevent permit reuse across processes and restarts for apt-get in nonprod",
		Remediation: "reevaluate and issue a new permit",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_GET_PROD_SOURCE_ALLOWLIST",
		Surface:     "package",
		Manager:     "apt-get",
		Environment: "prod",
		Phase:       "source",
		Description: "require an approved artifact repository for apt-get in prod",
		Remediation: "configure an approved immutable source",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_GET_PROD_DIGEST_REQUIRED",
		Surface:     "package",
		Manager:     "apt-get",
		Environment: "prod",
		Phase:       "identity",
		Description: "require immutable content identity for apt-get in prod",
		Remediation: "supply a verified sha256 digest",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_GET_PROD_SCANNER_AVAILABLE",
		Surface:     "package",
		Manager:     "apt-get",
		Environment: "prod",
		Phase:       "scan",
		Description: "require scanner availability for apt-get in prod",
		Remediation: "restore scanner service before acquisition",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_GET_PROD_SCANNER_FRESH",
		Surface:     "package",
		Manager:     "apt-get",
		Environment: "prod",
		Phase:       "scan",
		Description: "require current vulnerability database evidence for apt-get in prod",
		Remediation: "refresh scanner database and rescan",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_GET_PROD_VULNERABILITY_THRESHOLD",
		Surface:     "package",
		Manager:     "apt-get",
		Environment: "prod",
		Phase:       "decision",
		Description: "enforce vulnerability severity threshold for apt-get in prod",
		Remediation: "remediate or obtain a scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_GET_PROD_EXCEPTION_SCOPE",
		Surface:     "package",
		Manager:     "apt-get",
		Environment: "prod",
		Phase:       "exception",
		Description: "bind exceptions to exact artifact and context for apt-get in prod",
		Remediation: "issue a narrowly scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_GET_PROD_PERMIT_BINDING",
		Surface:     "package",
		Manager:     "apt-get",
		Environment: "prod",
		Phase:       "permit",
		Description: "bind permit to request instance and artifact for apt-get in prod",
		Remediation: "request a new bound permit",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_GET_PROD_PERMIT_EXPIRY",
		Surface:     "package",
		Manager:     "apt-get",
		Environment: "prod",
		Phase:       "permit",
		Description: "reject expired permits for apt-get in prod",
		Remediation: "reevaluate artifact policy",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_GET_PROD_AUDIT_DURABILITY",
		Surface:     "package",
		Manager:     "apt-get",
		Environment: "prod",
		Phase:       "audit",
		Description: "durably journal every decision before success for apt-get in prod",
		Remediation: "repair audit storage and retry",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_APT_GET_PROD_REPLAY_PROTECTION",
		Surface:     "package",
		Manager:     "apt-get",
		Environment: "prod",
		Phase:       "replay",
		Description: "prevent permit reuse across processes and restarts for apt-get in prod",
		Remediation: "reevaluate and issue a new permit",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DPKG_NONPROD_SOURCE_ALLOWLIST",
		Surface:     "package",
		Manager:     "dpkg",
		Environment: "nonprod",
		Phase:       "source",
		Description: "require an approved artifact repository for dpkg in nonprod",
		Remediation: "configure an approved immutable source",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DPKG_NONPROD_DIGEST_REQUIRED",
		Surface:     "package",
		Manager:     "dpkg",
		Environment: "nonprod",
		Phase:       "identity",
		Description: "require immutable content identity for dpkg in nonprod",
		Remediation: "supply a verified sha256 digest",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DPKG_NONPROD_SCANNER_AVAILABLE",
		Surface:     "package",
		Manager:     "dpkg",
		Environment: "nonprod",
		Phase:       "scan",
		Description: "require scanner availability for dpkg in nonprod",
		Remediation: "restore scanner service before acquisition",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DPKG_NONPROD_SCANNER_FRESH",
		Surface:     "package",
		Manager:     "dpkg",
		Environment: "nonprod",
		Phase:       "scan",
		Description: "require current vulnerability database evidence for dpkg in nonprod",
		Remediation: "refresh scanner database and rescan",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DPKG_NONPROD_VULNERABILITY_THRESHOLD",
		Surface:     "package",
		Manager:     "dpkg",
		Environment: "nonprod",
		Phase:       "decision",
		Description: "enforce vulnerability severity threshold for dpkg in nonprod",
		Remediation: "remediate or obtain a scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DPKG_NONPROD_EXCEPTION_SCOPE",
		Surface:     "package",
		Manager:     "dpkg",
		Environment: "nonprod",
		Phase:       "exception",
		Description: "bind exceptions to exact artifact and context for dpkg in nonprod",
		Remediation: "issue a narrowly scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DPKG_NONPROD_PERMIT_BINDING",
		Surface:     "package",
		Manager:     "dpkg",
		Environment: "nonprod",
		Phase:       "permit",
		Description: "bind permit to request instance and artifact for dpkg in nonprod",
		Remediation: "request a new bound permit",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DPKG_NONPROD_PERMIT_EXPIRY",
		Surface:     "package",
		Manager:     "dpkg",
		Environment: "nonprod",
		Phase:       "permit",
		Description: "reject expired permits for dpkg in nonprod",
		Remediation: "reevaluate artifact policy",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DPKG_NONPROD_AUDIT_DURABILITY",
		Surface:     "package",
		Manager:     "dpkg",
		Environment: "nonprod",
		Phase:       "audit",
		Description: "durably journal every decision before success for dpkg in nonprod",
		Remediation: "repair audit storage and retry",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DPKG_NONPROD_REPLAY_PROTECTION",
		Surface:     "package",
		Manager:     "dpkg",
		Environment: "nonprod",
		Phase:       "replay",
		Description: "prevent permit reuse across processes and restarts for dpkg in nonprod",
		Remediation: "reevaluate and issue a new permit",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DPKG_PROD_SOURCE_ALLOWLIST",
		Surface:     "package",
		Manager:     "dpkg",
		Environment: "prod",
		Phase:       "source",
		Description: "require an approved artifact repository for dpkg in prod",
		Remediation: "configure an approved immutable source",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DPKG_PROD_DIGEST_REQUIRED",
		Surface:     "package",
		Manager:     "dpkg",
		Environment: "prod",
		Phase:       "identity",
		Description: "require immutable content identity for dpkg in prod",
		Remediation: "supply a verified sha256 digest",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DPKG_PROD_SCANNER_AVAILABLE",
		Surface:     "package",
		Manager:     "dpkg",
		Environment: "prod",
		Phase:       "scan",
		Description: "require scanner availability for dpkg in prod",
		Remediation: "restore scanner service before acquisition",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DPKG_PROD_SCANNER_FRESH",
		Surface:     "package",
		Manager:     "dpkg",
		Environment: "prod",
		Phase:       "scan",
		Description: "require current vulnerability database evidence for dpkg in prod",
		Remediation: "refresh scanner database and rescan",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DPKG_PROD_VULNERABILITY_THRESHOLD",
		Surface:     "package",
		Manager:     "dpkg",
		Environment: "prod",
		Phase:       "decision",
		Description: "enforce vulnerability severity threshold for dpkg in prod",
		Remediation: "remediate or obtain a scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DPKG_PROD_EXCEPTION_SCOPE",
		Surface:     "package",
		Manager:     "dpkg",
		Environment: "prod",
		Phase:       "exception",
		Description: "bind exceptions to exact artifact and context for dpkg in prod",
		Remediation: "issue a narrowly scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DPKG_PROD_PERMIT_BINDING",
		Surface:     "package",
		Manager:     "dpkg",
		Environment: "prod",
		Phase:       "permit",
		Description: "bind permit to request instance and artifact for dpkg in prod",
		Remediation: "request a new bound permit",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DPKG_PROD_PERMIT_EXPIRY",
		Surface:     "package",
		Manager:     "dpkg",
		Environment: "prod",
		Phase:       "permit",
		Description: "reject expired permits for dpkg in prod",
		Remediation: "reevaluate artifact policy",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DPKG_PROD_AUDIT_DURABILITY",
		Surface:     "package",
		Manager:     "dpkg",
		Environment: "prod",
		Phase:       "audit",
		Description: "durably journal every decision before success for dpkg in prod",
		Remediation: "repair audit storage and retry",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DPKG_PROD_REPLAY_PROTECTION",
		Surface:     "package",
		Manager:     "dpkg",
		Environment: "prod",
		Phase:       "replay",
		Description: "prevent permit reuse across processes and restarts for dpkg in prod",
		Remediation: "reevaluate and issue a new permit",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_YUM_NONPROD_SOURCE_ALLOWLIST",
		Surface:     "package",
		Manager:     "yum",
		Environment: "nonprod",
		Phase:       "source",
		Description: "require an approved artifact repository for yum in nonprod",
		Remediation: "configure an approved immutable source",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_YUM_NONPROD_DIGEST_REQUIRED",
		Surface:     "package",
		Manager:     "yum",
		Environment: "nonprod",
		Phase:       "identity",
		Description: "require immutable content identity for yum in nonprod",
		Remediation: "supply a verified sha256 digest",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_YUM_NONPROD_SCANNER_AVAILABLE",
		Surface:     "package",
		Manager:     "yum",
		Environment: "nonprod",
		Phase:       "scan",
		Description: "require scanner availability for yum in nonprod",
		Remediation: "restore scanner service before acquisition",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_YUM_NONPROD_SCANNER_FRESH",
		Surface:     "package",
		Manager:     "yum",
		Environment: "nonprod",
		Phase:       "scan",
		Description: "require current vulnerability database evidence for yum in nonprod",
		Remediation: "refresh scanner database and rescan",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_YUM_NONPROD_VULNERABILITY_THRESHOLD",
		Surface:     "package",
		Manager:     "yum",
		Environment: "nonprod",
		Phase:       "decision",
		Description: "enforce vulnerability severity threshold for yum in nonprod",
		Remediation: "remediate or obtain a scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_YUM_NONPROD_EXCEPTION_SCOPE",
		Surface:     "package",
		Manager:     "yum",
		Environment: "nonprod",
		Phase:       "exception",
		Description: "bind exceptions to exact artifact and context for yum in nonprod",
		Remediation: "issue a narrowly scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_YUM_NONPROD_PERMIT_BINDING",
		Surface:     "package",
		Manager:     "yum",
		Environment: "nonprod",
		Phase:       "permit",
		Description: "bind permit to request instance and artifact for yum in nonprod",
		Remediation: "request a new bound permit",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_YUM_NONPROD_PERMIT_EXPIRY",
		Surface:     "package",
		Manager:     "yum",
		Environment: "nonprod",
		Phase:       "permit",
		Description: "reject expired permits for yum in nonprod",
		Remediation: "reevaluate artifact policy",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_YUM_NONPROD_AUDIT_DURABILITY",
		Surface:     "package",
		Manager:     "yum",
		Environment: "nonprod",
		Phase:       "audit",
		Description: "durably journal every decision before success for yum in nonprod",
		Remediation: "repair audit storage and retry",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_YUM_NONPROD_REPLAY_PROTECTION",
		Surface:     "package",
		Manager:     "yum",
		Environment: "nonprod",
		Phase:       "replay",
		Description: "prevent permit reuse across processes and restarts for yum in nonprod",
		Remediation: "reevaluate and issue a new permit",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_YUM_PROD_SOURCE_ALLOWLIST",
		Surface:     "package",
		Manager:     "yum",
		Environment: "prod",
		Phase:       "source",
		Description: "require an approved artifact repository for yum in prod",
		Remediation: "configure an approved immutable source",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_YUM_PROD_DIGEST_REQUIRED",
		Surface:     "package",
		Manager:     "yum",
		Environment: "prod",
		Phase:       "identity",
		Description: "require immutable content identity for yum in prod",
		Remediation: "supply a verified sha256 digest",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_YUM_PROD_SCANNER_AVAILABLE",
		Surface:     "package",
		Manager:     "yum",
		Environment: "prod",
		Phase:       "scan",
		Description: "require scanner availability for yum in prod",
		Remediation: "restore scanner service before acquisition",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_YUM_PROD_SCANNER_FRESH",
		Surface:     "package",
		Manager:     "yum",
		Environment: "prod",
		Phase:       "scan",
		Description: "require current vulnerability database evidence for yum in prod",
		Remediation: "refresh scanner database and rescan",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_YUM_PROD_VULNERABILITY_THRESHOLD",
		Surface:     "package",
		Manager:     "yum",
		Environment: "prod",
		Phase:       "decision",
		Description: "enforce vulnerability severity threshold for yum in prod",
		Remediation: "remediate or obtain a scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_YUM_PROD_EXCEPTION_SCOPE",
		Surface:     "package",
		Manager:     "yum",
		Environment: "prod",
		Phase:       "exception",
		Description: "bind exceptions to exact artifact and context for yum in prod",
		Remediation: "issue a narrowly scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_YUM_PROD_PERMIT_BINDING",
		Surface:     "package",
		Manager:     "yum",
		Environment: "prod",
		Phase:       "permit",
		Description: "bind permit to request instance and artifact for yum in prod",
		Remediation: "request a new bound permit",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_YUM_PROD_PERMIT_EXPIRY",
		Surface:     "package",
		Manager:     "yum",
		Environment: "prod",
		Phase:       "permit",
		Description: "reject expired permits for yum in prod",
		Remediation: "reevaluate artifact policy",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_YUM_PROD_AUDIT_DURABILITY",
		Surface:     "package",
		Manager:     "yum",
		Environment: "prod",
		Phase:       "audit",
		Description: "durably journal every decision before success for yum in prod",
		Remediation: "repair audit storage and retry",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_YUM_PROD_REPLAY_PROTECTION",
		Surface:     "package",
		Manager:     "yum",
		Environment: "prod",
		Phase:       "replay",
		Description: "prevent permit reuse across processes and restarts for yum in prod",
		Remediation: "reevaluate and issue a new permit",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DNF_NONPROD_SOURCE_ALLOWLIST",
		Surface:     "package",
		Manager:     "dnf",
		Environment: "nonprod",
		Phase:       "source",
		Description: "require an approved artifact repository for dnf in nonprod",
		Remediation: "configure an approved immutable source",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DNF_NONPROD_DIGEST_REQUIRED",
		Surface:     "package",
		Manager:     "dnf",
		Environment: "nonprod",
		Phase:       "identity",
		Description: "require immutable content identity for dnf in nonprod",
		Remediation: "supply a verified sha256 digest",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DNF_NONPROD_SCANNER_AVAILABLE",
		Surface:     "package",
		Manager:     "dnf",
		Environment: "nonprod",
		Phase:       "scan",
		Description: "require scanner availability for dnf in nonprod",
		Remediation: "restore scanner service before acquisition",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DNF_NONPROD_SCANNER_FRESH",
		Surface:     "package",
		Manager:     "dnf",
		Environment: "nonprod",
		Phase:       "scan",
		Description: "require current vulnerability database evidence for dnf in nonprod",
		Remediation: "refresh scanner database and rescan",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DNF_NONPROD_VULNERABILITY_THRESHOLD",
		Surface:     "package",
		Manager:     "dnf",
		Environment: "nonprod",
		Phase:       "decision",
		Description: "enforce vulnerability severity threshold for dnf in nonprod",
		Remediation: "remediate or obtain a scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DNF_NONPROD_EXCEPTION_SCOPE",
		Surface:     "package",
		Manager:     "dnf",
		Environment: "nonprod",
		Phase:       "exception",
		Description: "bind exceptions to exact artifact and context for dnf in nonprod",
		Remediation: "issue a narrowly scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DNF_NONPROD_PERMIT_BINDING",
		Surface:     "package",
		Manager:     "dnf",
		Environment: "nonprod",
		Phase:       "permit",
		Description: "bind permit to request instance and artifact for dnf in nonprod",
		Remediation: "request a new bound permit",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DNF_NONPROD_PERMIT_EXPIRY",
		Surface:     "package",
		Manager:     "dnf",
		Environment: "nonprod",
		Phase:       "permit",
		Description: "reject expired permits for dnf in nonprod",
		Remediation: "reevaluate artifact policy",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DNF_NONPROD_AUDIT_DURABILITY",
		Surface:     "package",
		Manager:     "dnf",
		Environment: "nonprod",
		Phase:       "audit",
		Description: "durably journal every decision before success for dnf in nonprod",
		Remediation: "repair audit storage and retry",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DNF_NONPROD_REPLAY_PROTECTION",
		Surface:     "package",
		Manager:     "dnf",
		Environment: "nonprod",
		Phase:       "replay",
		Description: "prevent permit reuse across processes and restarts for dnf in nonprod",
		Remediation: "reevaluate and issue a new permit",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DNF_PROD_SOURCE_ALLOWLIST",
		Surface:     "package",
		Manager:     "dnf",
		Environment: "prod",
		Phase:       "source",
		Description: "require an approved artifact repository for dnf in prod",
		Remediation: "configure an approved immutable source",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DNF_PROD_DIGEST_REQUIRED",
		Surface:     "package",
		Manager:     "dnf",
		Environment: "prod",
		Phase:       "identity",
		Description: "require immutable content identity for dnf in prod",
		Remediation: "supply a verified sha256 digest",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DNF_PROD_SCANNER_AVAILABLE",
		Surface:     "package",
		Manager:     "dnf",
		Environment: "prod",
		Phase:       "scan",
		Description: "require scanner availability for dnf in prod",
		Remediation: "restore scanner service before acquisition",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DNF_PROD_SCANNER_FRESH",
		Surface:     "package",
		Manager:     "dnf",
		Environment: "prod",
		Phase:       "scan",
		Description: "require current vulnerability database evidence for dnf in prod",
		Remediation: "refresh scanner database and rescan",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DNF_PROD_VULNERABILITY_THRESHOLD",
		Surface:     "package",
		Manager:     "dnf",
		Environment: "prod",
		Phase:       "decision",
		Description: "enforce vulnerability severity threshold for dnf in prod",
		Remediation: "remediate or obtain a scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DNF_PROD_EXCEPTION_SCOPE",
		Surface:     "package",
		Manager:     "dnf",
		Environment: "prod",
		Phase:       "exception",
		Description: "bind exceptions to exact artifact and context for dnf in prod",
		Remediation: "issue a narrowly scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DNF_PROD_PERMIT_BINDING",
		Surface:     "package",
		Manager:     "dnf",
		Environment: "prod",
		Phase:       "permit",
		Description: "bind permit to request instance and artifact for dnf in prod",
		Remediation: "request a new bound permit",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DNF_PROD_PERMIT_EXPIRY",
		Surface:     "package",
		Manager:     "dnf",
		Environment: "prod",
		Phase:       "permit",
		Description: "reject expired permits for dnf in prod",
		Remediation: "reevaluate artifact policy",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DNF_PROD_AUDIT_DURABILITY",
		Surface:     "package",
		Manager:     "dnf",
		Environment: "prod",
		Phase:       "audit",
		Description: "durably journal every decision before success for dnf in prod",
		Remediation: "repair audit storage and retry",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_DNF_PROD_REPLAY_PROTECTION",
		Surface:     "package",
		Manager:     "dnf",
		Environment: "prod",
		Phase:       "replay",
		Description: "prevent permit reuse across processes and restarts for dnf in prod",
		Remediation: "reevaluate and issue a new permit",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_RPM_NONPROD_SOURCE_ALLOWLIST",
		Surface:     "package",
		Manager:     "rpm",
		Environment: "nonprod",
		Phase:       "source",
		Description: "require an approved artifact repository for rpm in nonprod",
		Remediation: "configure an approved immutable source",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_RPM_NONPROD_DIGEST_REQUIRED",
		Surface:     "package",
		Manager:     "rpm",
		Environment: "nonprod",
		Phase:       "identity",
		Description: "require immutable content identity for rpm in nonprod",
		Remediation: "supply a verified sha256 digest",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_RPM_NONPROD_SCANNER_AVAILABLE",
		Surface:     "package",
		Manager:     "rpm",
		Environment: "nonprod",
		Phase:       "scan",
		Description: "require scanner availability for rpm in nonprod",
		Remediation: "restore scanner service before acquisition",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_RPM_NONPROD_SCANNER_FRESH",
		Surface:     "package",
		Manager:     "rpm",
		Environment: "nonprod",
		Phase:       "scan",
		Description: "require current vulnerability database evidence for rpm in nonprod",
		Remediation: "refresh scanner database and rescan",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_RPM_NONPROD_VULNERABILITY_THRESHOLD",
		Surface:     "package",
		Manager:     "rpm",
		Environment: "nonprod",
		Phase:       "decision",
		Description: "enforce vulnerability severity threshold for rpm in nonprod",
		Remediation: "remediate or obtain a scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_RPM_NONPROD_EXCEPTION_SCOPE",
		Surface:     "package",
		Manager:     "rpm",
		Environment: "nonprod",
		Phase:       "exception",
		Description: "bind exceptions to exact artifact and context for rpm in nonprod",
		Remediation: "issue a narrowly scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_RPM_NONPROD_PERMIT_BINDING",
		Surface:     "package",
		Manager:     "rpm",
		Environment: "nonprod",
		Phase:       "permit",
		Description: "bind permit to request instance and artifact for rpm in nonprod",
		Remediation: "request a new bound permit",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_RPM_NONPROD_PERMIT_EXPIRY",
		Surface:     "package",
		Manager:     "rpm",
		Environment: "nonprod",
		Phase:       "permit",
		Description: "reject expired permits for rpm in nonprod",
		Remediation: "reevaluate artifact policy",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_RPM_NONPROD_AUDIT_DURABILITY",
		Surface:     "package",
		Manager:     "rpm",
		Environment: "nonprod",
		Phase:       "audit",
		Description: "durably journal every decision before success for rpm in nonprod",
		Remediation: "repair audit storage and retry",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_RPM_NONPROD_REPLAY_PROTECTION",
		Surface:     "package",
		Manager:     "rpm",
		Environment: "nonprod",
		Phase:       "replay",
		Description: "prevent permit reuse across processes and restarts for rpm in nonprod",
		Remediation: "reevaluate and issue a new permit",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_RPM_PROD_SOURCE_ALLOWLIST",
		Surface:     "package",
		Manager:     "rpm",
		Environment: "prod",
		Phase:       "source",
		Description: "require an approved artifact repository for rpm in prod",
		Remediation: "configure an approved immutable source",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_RPM_PROD_DIGEST_REQUIRED",
		Surface:     "package",
		Manager:     "rpm",
		Environment: "prod",
		Phase:       "identity",
		Description: "require immutable content identity for rpm in prod",
		Remediation: "supply a verified sha256 digest",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_RPM_PROD_SCANNER_AVAILABLE",
		Surface:     "package",
		Manager:     "rpm",
		Environment: "prod",
		Phase:       "scan",
		Description: "require scanner availability for rpm in prod",
		Remediation: "restore scanner service before acquisition",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_RPM_PROD_SCANNER_FRESH",
		Surface:     "package",
		Manager:     "rpm",
		Environment: "prod",
		Phase:       "scan",
		Description: "require current vulnerability database evidence for rpm in prod",
		Remediation: "refresh scanner database and rescan",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_RPM_PROD_VULNERABILITY_THRESHOLD",
		Surface:     "package",
		Manager:     "rpm",
		Environment: "prod",
		Phase:       "decision",
		Description: "enforce vulnerability severity threshold for rpm in prod",
		Remediation: "remediate or obtain a scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_RPM_PROD_EXCEPTION_SCOPE",
		Surface:     "package",
		Manager:     "rpm",
		Environment: "prod",
		Phase:       "exception",
		Description: "bind exceptions to exact artifact and context for rpm in prod",
		Remediation: "issue a narrowly scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_RPM_PROD_PERMIT_BINDING",
		Surface:     "package",
		Manager:     "rpm",
		Environment: "prod",
		Phase:       "permit",
		Description: "bind permit to request instance and artifact for rpm in prod",
		Remediation: "request a new bound permit",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_RPM_PROD_PERMIT_EXPIRY",
		Surface:     "package",
		Manager:     "rpm",
		Environment: "prod",
		Phase:       "permit",
		Description: "reject expired permits for rpm in prod",
		Remediation: "reevaluate artifact policy",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_RPM_PROD_AUDIT_DURABILITY",
		Surface:     "package",
		Manager:     "rpm",
		Environment: "prod",
		Phase:       "audit",
		Description: "durably journal every decision before success for rpm in prod",
		Remediation: "repair audit storage and retry",
		FailClosed:  true,
	},
	{
		Code:        "PACKAGE_RPM_PROD_REPLAY_PROTECTION",
		Surface:     "package",
		Manager:     "rpm",
		Environment: "prod",
		Phase:       "replay",
		Description: "prevent permit reuse across processes and restarts for rpm in prod",
		Remediation: "reevaluate and issue a new permit",
		FailClosed:  true,
	},
}
