package platform

var ContainerRules = []RuleDefinition{
	{
		Code:        "CONTAINER_DOCKER_NONPROD_SOURCE_ALLOWLIST",
		Surface:     "container",
		Manager:     "docker",
		Environment: "nonprod",
		Phase:       "source",
		Description: "require an approved artifact repository for docker in nonprod",
		Remediation: "configure an approved immutable source",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_DOCKER_NONPROD_DIGEST_REQUIRED",
		Surface:     "container",
		Manager:     "docker",
		Environment: "nonprod",
		Phase:       "identity",
		Description: "require immutable content identity for docker in nonprod",
		Remediation: "supply a verified sha256 digest",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_DOCKER_NONPROD_SCANNER_AVAILABLE",
		Surface:     "container",
		Manager:     "docker",
		Environment: "nonprod",
		Phase:       "scan",
		Description: "require scanner availability for docker in nonprod",
		Remediation: "restore scanner service before acquisition",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_DOCKER_NONPROD_SCANNER_FRESH",
		Surface:     "container",
		Manager:     "docker",
		Environment: "nonprod",
		Phase:       "scan",
		Description: "require current vulnerability database evidence for docker in nonprod",
		Remediation: "refresh scanner database and rescan",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_DOCKER_NONPROD_VULNERABILITY_THRESHOLD",
		Surface:     "container",
		Manager:     "docker",
		Environment: "nonprod",
		Phase:       "decision",
		Description: "enforce vulnerability severity threshold for docker in nonprod",
		Remediation: "remediate or obtain a scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_DOCKER_NONPROD_EXCEPTION_SCOPE",
		Surface:     "container",
		Manager:     "docker",
		Environment: "nonprod",
		Phase:       "exception",
		Description: "bind exceptions to exact artifact and context for docker in nonprod",
		Remediation: "issue a narrowly scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_DOCKER_NONPROD_PERMIT_BINDING",
		Surface:     "container",
		Manager:     "docker",
		Environment: "nonprod",
		Phase:       "permit",
		Description: "bind permit to request instance and artifact for docker in nonprod",
		Remediation: "request a new bound permit",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_DOCKER_NONPROD_PERMIT_EXPIRY",
		Surface:     "container",
		Manager:     "docker",
		Environment: "nonprod",
		Phase:       "permit",
		Description: "reject expired permits for docker in nonprod",
		Remediation: "reevaluate artifact policy",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_DOCKER_NONPROD_AUDIT_DURABILITY",
		Surface:     "container",
		Manager:     "docker",
		Environment: "nonprod",
		Phase:       "audit",
		Description: "durably journal every decision before success for docker in nonprod",
		Remediation: "repair audit storage and retry",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_DOCKER_NONPROD_REPLAY_PROTECTION",
		Surface:     "container",
		Manager:     "docker",
		Environment: "nonprod",
		Phase:       "replay",
		Description: "prevent permit reuse across processes and restarts for docker in nonprod",
		Remediation: "reevaluate and issue a new permit",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_DOCKER_PROD_SOURCE_ALLOWLIST",
		Surface:     "container",
		Manager:     "docker",
		Environment: "prod",
		Phase:       "source",
		Description: "require an approved artifact repository for docker in prod",
		Remediation: "configure an approved immutable source",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_DOCKER_PROD_DIGEST_REQUIRED",
		Surface:     "container",
		Manager:     "docker",
		Environment: "prod",
		Phase:       "identity",
		Description: "require immutable content identity for docker in prod",
		Remediation: "supply a verified sha256 digest",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_DOCKER_PROD_SCANNER_AVAILABLE",
		Surface:     "container",
		Manager:     "docker",
		Environment: "prod",
		Phase:       "scan",
		Description: "require scanner availability for docker in prod",
		Remediation: "restore scanner service before acquisition",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_DOCKER_PROD_SCANNER_FRESH",
		Surface:     "container",
		Manager:     "docker",
		Environment: "prod",
		Phase:       "scan",
		Description: "require current vulnerability database evidence for docker in prod",
		Remediation: "refresh scanner database and rescan",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_DOCKER_PROD_VULNERABILITY_THRESHOLD",
		Surface:     "container",
		Manager:     "docker",
		Environment: "prod",
		Phase:       "decision",
		Description: "enforce vulnerability severity threshold for docker in prod",
		Remediation: "remediate or obtain a scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_DOCKER_PROD_EXCEPTION_SCOPE",
		Surface:     "container",
		Manager:     "docker",
		Environment: "prod",
		Phase:       "exception",
		Description: "bind exceptions to exact artifact and context for docker in prod",
		Remediation: "issue a narrowly scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_DOCKER_PROD_PERMIT_BINDING",
		Surface:     "container",
		Manager:     "docker",
		Environment: "prod",
		Phase:       "permit",
		Description: "bind permit to request instance and artifact for docker in prod",
		Remediation: "request a new bound permit",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_DOCKER_PROD_PERMIT_EXPIRY",
		Surface:     "container",
		Manager:     "docker",
		Environment: "prod",
		Phase:       "permit",
		Description: "reject expired permits for docker in prod",
		Remediation: "reevaluate artifact policy",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_DOCKER_PROD_AUDIT_DURABILITY",
		Surface:     "container",
		Manager:     "docker",
		Environment: "prod",
		Phase:       "audit",
		Description: "durably journal every decision before success for docker in prod",
		Remediation: "repair audit storage and retry",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_DOCKER_PROD_REPLAY_PROTECTION",
		Surface:     "container",
		Manager:     "docker",
		Environment: "prod",
		Phase:       "replay",
		Description: "prevent permit reuse across processes and restarts for docker in prod",
		Remediation: "reevaluate and issue a new permit",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CONTAINERD_NONPROD_SOURCE_ALLOWLIST",
		Surface:     "container",
		Manager:     "containerd",
		Environment: "nonprod",
		Phase:       "source",
		Description: "require an approved artifact repository for containerd in nonprod",
		Remediation: "configure an approved immutable source",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CONTAINERD_NONPROD_DIGEST_REQUIRED",
		Surface:     "container",
		Manager:     "containerd",
		Environment: "nonprod",
		Phase:       "identity",
		Description: "require immutable content identity for containerd in nonprod",
		Remediation: "supply a verified sha256 digest",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CONTAINERD_NONPROD_SCANNER_AVAILABLE",
		Surface:     "container",
		Manager:     "containerd",
		Environment: "nonprod",
		Phase:       "scan",
		Description: "require scanner availability for containerd in nonprod",
		Remediation: "restore scanner service before acquisition",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CONTAINERD_NONPROD_SCANNER_FRESH",
		Surface:     "container",
		Manager:     "containerd",
		Environment: "nonprod",
		Phase:       "scan",
		Description: "require current vulnerability database evidence for containerd in nonprod",
		Remediation: "refresh scanner database and rescan",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CONTAINERD_NONPROD_VULNERABILITY_THRESHOLD",
		Surface:     "container",
		Manager:     "containerd",
		Environment: "nonprod",
		Phase:       "decision",
		Description: "enforce vulnerability severity threshold for containerd in nonprod",
		Remediation: "remediate or obtain a scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CONTAINERD_NONPROD_EXCEPTION_SCOPE",
		Surface:     "container",
		Manager:     "containerd",
		Environment: "nonprod",
		Phase:       "exception",
		Description: "bind exceptions to exact artifact and context for containerd in nonprod",
		Remediation: "issue a narrowly scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CONTAINERD_NONPROD_PERMIT_BINDING",
		Surface:     "container",
		Manager:     "containerd",
		Environment: "nonprod",
		Phase:       "permit",
		Description: "bind permit to request instance and artifact for containerd in nonprod",
		Remediation: "request a new bound permit",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CONTAINERD_NONPROD_PERMIT_EXPIRY",
		Surface:     "container",
		Manager:     "containerd",
		Environment: "nonprod",
		Phase:       "permit",
		Description: "reject expired permits for containerd in nonprod",
		Remediation: "reevaluate artifact policy",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CONTAINERD_NONPROD_AUDIT_DURABILITY",
		Surface:     "container",
		Manager:     "containerd",
		Environment: "nonprod",
		Phase:       "audit",
		Description: "durably journal every decision before success for containerd in nonprod",
		Remediation: "repair audit storage and retry",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CONTAINERD_NONPROD_REPLAY_PROTECTION",
		Surface:     "container",
		Manager:     "containerd",
		Environment: "nonprod",
		Phase:       "replay",
		Description: "prevent permit reuse across processes and restarts for containerd in nonprod",
		Remediation: "reevaluate and issue a new permit",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CONTAINERD_PROD_SOURCE_ALLOWLIST",
		Surface:     "container",
		Manager:     "containerd",
		Environment: "prod",
		Phase:       "source",
		Description: "require an approved artifact repository for containerd in prod",
		Remediation: "configure an approved immutable source",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CONTAINERD_PROD_DIGEST_REQUIRED",
		Surface:     "container",
		Manager:     "containerd",
		Environment: "prod",
		Phase:       "identity",
		Description: "require immutable content identity for containerd in prod",
		Remediation: "supply a verified sha256 digest",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CONTAINERD_PROD_SCANNER_AVAILABLE",
		Surface:     "container",
		Manager:     "containerd",
		Environment: "prod",
		Phase:       "scan",
		Description: "require scanner availability for containerd in prod",
		Remediation: "restore scanner service before acquisition",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CONTAINERD_PROD_SCANNER_FRESH",
		Surface:     "container",
		Manager:     "containerd",
		Environment: "prod",
		Phase:       "scan",
		Description: "require current vulnerability database evidence for containerd in prod",
		Remediation: "refresh scanner database and rescan",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CONTAINERD_PROD_VULNERABILITY_THRESHOLD",
		Surface:     "container",
		Manager:     "containerd",
		Environment: "prod",
		Phase:       "decision",
		Description: "enforce vulnerability severity threshold for containerd in prod",
		Remediation: "remediate or obtain a scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CONTAINERD_PROD_EXCEPTION_SCOPE",
		Surface:     "container",
		Manager:     "containerd",
		Environment: "prod",
		Phase:       "exception",
		Description: "bind exceptions to exact artifact and context for containerd in prod",
		Remediation: "issue a narrowly scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CONTAINERD_PROD_PERMIT_BINDING",
		Surface:     "container",
		Manager:     "containerd",
		Environment: "prod",
		Phase:       "permit",
		Description: "bind permit to request instance and artifact for containerd in prod",
		Remediation: "request a new bound permit",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CONTAINERD_PROD_PERMIT_EXPIRY",
		Surface:     "container",
		Manager:     "containerd",
		Environment: "prod",
		Phase:       "permit",
		Description: "reject expired permits for containerd in prod",
		Remediation: "reevaluate artifact policy",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CONTAINERD_PROD_AUDIT_DURABILITY",
		Surface:     "container",
		Manager:     "containerd",
		Environment: "prod",
		Phase:       "audit",
		Description: "durably journal every decision before success for containerd in prod",
		Remediation: "repair audit storage and retry",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CONTAINERD_PROD_REPLAY_PROTECTION",
		Surface:     "container",
		Manager:     "containerd",
		Environment: "prod",
		Phase:       "replay",
		Description: "prevent permit reuse across processes and restarts for containerd in prod",
		Remediation: "reevaluate and issue a new permit",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_NERDCTL_NONPROD_SOURCE_ALLOWLIST",
		Surface:     "container",
		Manager:     "nerdctl",
		Environment: "nonprod",
		Phase:       "source",
		Description: "require an approved artifact repository for nerdctl in nonprod",
		Remediation: "configure an approved immutable source",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_NERDCTL_NONPROD_DIGEST_REQUIRED",
		Surface:     "container",
		Manager:     "nerdctl",
		Environment: "nonprod",
		Phase:       "identity",
		Description: "require immutable content identity for nerdctl in nonprod",
		Remediation: "supply a verified sha256 digest",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_NERDCTL_NONPROD_SCANNER_AVAILABLE",
		Surface:     "container",
		Manager:     "nerdctl",
		Environment: "nonprod",
		Phase:       "scan",
		Description: "require scanner availability for nerdctl in nonprod",
		Remediation: "restore scanner service before acquisition",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_NERDCTL_NONPROD_SCANNER_FRESH",
		Surface:     "container",
		Manager:     "nerdctl",
		Environment: "nonprod",
		Phase:       "scan",
		Description: "require current vulnerability database evidence for nerdctl in nonprod",
		Remediation: "refresh scanner database and rescan",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_NERDCTL_NONPROD_VULNERABILITY_THRESHOLD",
		Surface:     "container",
		Manager:     "nerdctl",
		Environment: "nonprod",
		Phase:       "decision",
		Description: "enforce vulnerability severity threshold for nerdctl in nonprod",
		Remediation: "remediate or obtain a scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_NERDCTL_NONPROD_EXCEPTION_SCOPE",
		Surface:     "container",
		Manager:     "nerdctl",
		Environment: "nonprod",
		Phase:       "exception",
		Description: "bind exceptions to exact artifact and context for nerdctl in nonprod",
		Remediation: "issue a narrowly scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_NERDCTL_NONPROD_PERMIT_BINDING",
		Surface:     "container",
		Manager:     "nerdctl",
		Environment: "nonprod",
		Phase:       "permit",
		Description: "bind permit to request instance and artifact for nerdctl in nonprod",
		Remediation: "request a new bound permit",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_NERDCTL_NONPROD_PERMIT_EXPIRY",
		Surface:     "container",
		Manager:     "nerdctl",
		Environment: "nonprod",
		Phase:       "permit",
		Description: "reject expired permits for nerdctl in nonprod",
		Remediation: "reevaluate artifact policy",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_NERDCTL_NONPROD_AUDIT_DURABILITY",
		Surface:     "container",
		Manager:     "nerdctl",
		Environment: "nonprod",
		Phase:       "audit",
		Description: "durably journal every decision before success for nerdctl in nonprod",
		Remediation: "repair audit storage and retry",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_NERDCTL_NONPROD_REPLAY_PROTECTION",
		Surface:     "container",
		Manager:     "nerdctl",
		Environment: "nonprod",
		Phase:       "replay",
		Description: "prevent permit reuse across processes and restarts for nerdctl in nonprod",
		Remediation: "reevaluate and issue a new permit",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_NERDCTL_PROD_SOURCE_ALLOWLIST",
		Surface:     "container",
		Manager:     "nerdctl",
		Environment: "prod",
		Phase:       "source",
		Description: "require an approved artifact repository for nerdctl in prod",
		Remediation: "configure an approved immutable source",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_NERDCTL_PROD_DIGEST_REQUIRED",
		Surface:     "container",
		Manager:     "nerdctl",
		Environment: "prod",
		Phase:       "identity",
		Description: "require immutable content identity for nerdctl in prod",
		Remediation: "supply a verified sha256 digest",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_NERDCTL_PROD_SCANNER_AVAILABLE",
		Surface:     "container",
		Manager:     "nerdctl",
		Environment: "prod",
		Phase:       "scan",
		Description: "require scanner availability for nerdctl in prod",
		Remediation: "restore scanner service before acquisition",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_NERDCTL_PROD_SCANNER_FRESH",
		Surface:     "container",
		Manager:     "nerdctl",
		Environment: "prod",
		Phase:       "scan",
		Description: "require current vulnerability database evidence for nerdctl in prod",
		Remediation: "refresh scanner database and rescan",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_NERDCTL_PROD_VULNERABILITY_THRESHOLD",
		Surface:     "container",
		Manager:     "nerdctl",
		Environment: "prod",
		Phase:       "decision",
		Description: "enforce vulnerability severity threshold for nerdctl in prod",
		Remediation: "remediate or obtain a scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_NERDCTL_PROD_EXCEPTION_SCOPE",
		Surface:     "container",
		Manager:     "nerdctl",
		Environment: "prod",
		Phase:       "exception",
		Description: "bind exceptions to exact artifact and context for nerdctl in prod",
		Remediation: "issue a narrowly scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_NERDCTL_PROD_PERMIT_BINDING",
		Surface:     "container",
		Manager:     "nerdctl",
		Environment: "prod",
		Phase:       "permit",
		Description: "bind permit to request instance and artifact for nerdctl in prod",
		Remediation: "request a new bound permit",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_NERDCTL_PROD_PERMIT_EXPIRY",
		Surface:     "container",
		Manager:     "nerdctl",
		Environment: "prod",
		Phase:       "permit",
		Description: "reject expired permits for nerdctl in prod",
		Remediation: "reevaluate artifact policy",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_NERDCTL_PROD_AUDIT_DURABILITY",
		Surface:     "container",
		Manager:     "nerdctl",
		Environment: "prod",
		Phase:       "audit",
		Description: "durably journal every decision before success for nerdctl in prod",
		Remediation: "repair audit storage and retry",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_NERDCTL_PROD_REPLAY_PROTECTION",
		Surface:     "container",
		Manager:     "nerdctl",
		Environment: "prod",
		Phase:       "replay",
		Description: "prevent permit reuse across processes and restarts for nerdctl in prod",
		Remediation: "reevaluate and issue a new permit",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CRICTL_NONPROD_SOURCE_ALLOWLIST",
		Surface:     "container",
		Manager:     "crictl",
		Environment: "nonprod",
		Phase:       "source",
		Description: "require an approved artifact repository for crictl in nonprod",
		Remediation: "configure an approved immutable source",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CRICTL_NONPROD_DIGEST_REQUIRED",
		Surface:     "container",
		Manager:     "crictl",
		Environment: "nonprod",
		Phase:       "identity",
		Description: "require immutable content identity for crictl in nonprod",
		Remediation: "supply a verified sha256 digest",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CRICTL_NONPROD_SCANNER_AVAILABLE",
		Surface:     "container",
		Manager:     "crictl",
		Environment: "nonprod",
		Phase:       "scan",
		Description: "require scanner availability for crictl in nonprod",
		Remediation: "restore scanner service before acquisition",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CRICTL_NONPROD_SCANNER_FRESH",
		Surface:     "container",
		Manager:     "crictl",
		Environment: "nonprod",
		Phase:       "scan",
		Description: "require current vulnerability database evidence for crictl in nonprod",
		Remediation: "refresh scanner database and rescan",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CRICTL_NONPROD_VULNERABILITY_THRESHOLD",
		Surface:     "container",
		Manager:     "crictl",
		Environment: "nonprod",
		Phase:       "decision",
		Description: "enforce vulnerability severity threshold for crictl in nonprod",
		Remediation: "remediate or obtain a scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CRICTL_NONPROD_EXCEPTION_SCOPE",
		Surface:     "container",
		Manager:     "crictl",
		Environment: "nonprod",
		Phase:       "exception",
		Description: "bind exceptions to exact artifact and context for crictl in nonprod",
		Remediation: "issue a narrowly scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CRICTL_NONPROD_PERMIT_BINDING",
		Surface:     "container",
		Manager:     "crictl",
		Environment: "nonprod",
		Phase:       "permit",
		Description: "bind permit to request instance and artifact for crictl in nonprod",
		Remediation: "request a new bound permit",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CRICTL_NONPROD_PERMIT_EXPIRY",
		Surface:     "container",
		Manager:     "crictl",
		Environment: "nonprod",
		Phase:       "permit",
		Description: "reject expired permits for crictl in nonprod",
		Remediation: "reevaluate artifact policy",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CRICTL_NONPROD_AUDIT_DURABILITY",
		Surface:     "container",
		Manager:     "crictl",
		Environment: "nonprod",
		Phase:       "audit",
		Description: "durably journal every decision before success for crictl in nonprod",
		Remediation: "repair audit storage and retry",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CRICTL_NONPROD_REPLAY_PROTECTION",
		Surface:     "container",
		Manager:     "crictl",
		Environment: "nonprod",
		Phase:       "replay",
		Description: "prevent permit reuse across processes and restarts for crictl in nonprod",
		Remediation: "reevaluate and issue a new permit",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CRICTL_PROD_SOURCE_ALLOWLIST",
		Surface:     "container",
		Manager:     "crictl",
		Environment: "prod",
		Phase:       "source",
		Description: "require an approved artifact repository for crictl in prod",
		Remediation: "configure an approved immutable source",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CRICTL_PROD_DIGEST_REQUIRED",
		Surface:     "container",
		Manager:     "crictl",
		Environment: "prod",
		Phase:       "identity",
		Description: "require immutable content identity for crictl in prod",
		Remediation: "supply a verified sha256 digest",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CRICTL_PROD_SCANNER_AVAILABLE",
		Surface:     "container",
		Manager:     "crictl",
		Environment: "prod",
		Phase:       "scan",
		Description: "require scanner availability for crictl in prod",
		Remediation: "restore scanner service before acquisition",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CRICTL_PROD_SCANNER_FRESH",
		Surface:     "container",
		Manager:     "crictl",
		Environment: "prod",
		Phase:       "scan",
		Description: "require current vulnerability database evidence for crictl in prod",
		Remediation: "refresh scanner database and rescan",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CRICTL_PROD_VULNERABILITY_THRESHOLD",
		Surface:     "container",
		Manager:     "crictl",
		Environment: "prod",
		Phase:       "decision",
		Description: "enforce vulnerability severity threshold for crictl in prod",
		Remediation: "remediate or obtain a scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CRICTL_PROD_EXCEPTION_SCOPE",
		Surface:     "container",
		Manager:     "crictl",
		Environment: "prod",
		Phase:       "exception",
		Description: "bind exceptions to exact artifact and context for crictl in prod",
		Remediation: "issue a narrowly scoped exception",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CRICTL_PROD_PERMIT_BINDING",
		Surface:     "container",
		Manager:     "crictl",
		Environment: "prod",
		Phase:       "permit",
		Description: "bind permit to request instance and artifact for crictl in prod",
		Remediation: "request a new bound permit",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CRICTL_PROD_PERMIT_EXPIRY",
		Surface:     "container",
		Manager:     "crictl",
		Environment: "prod",
		Phase:       "permit",
		Description: "reject expired permits for crictl in prod",
		Remediation: "reevaluate artifact policy",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CRICTL_PROD_AUDIT_DURABILITY",
		Surface:     "container",
		Manager:     "crictl",
		Environment: "prod",
		Phase:       "audit",
		Description: "durably journal every decision before success for crictl in prod",
		Remediation: "repair audit storage and retry",
		FailClosed:  true,
	},
	{
		Code:        "CONTAINER_CRICTL_PROD_REPLAY_PROTECTION",
		Surface:     "container",
		Manager:     "crictl",
		Environment: "prod",
		Phase:       "replay",
		Description: "prevent permit reuse across processes and restarts for crictl in prod",
		Remediation: "reevaluate and issue a new permit",
		FailClosed:  true,
	},
}
