package tablex

// carrierFill07 appends carrier rows 420..459.
func carrierFill07(out []CarrierRow) []CarrierRow {
	out = append(out, CarrierRow{CarrierCode: "C420", Scac: "BNPP", LegalName: "Carrier 420 Freight Systems", Region: "IND", InsuranceCents: 412500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C421", Scac: "QIBW", LegalName: "Carrier 421 Freight Systems", Region: "LAX", InsuranceCents: 425000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C422", Scac: "RRVR", LegalName: "Carrier 422 Freight Systems", Region: "YYZ", InsuranceCents: 437500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C423", Scac: "ZQGN", LegalName: "Carrier 423 Freight Systems", Region: "JAX", InsuranceCents: 450000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C424", Scac: "KRJS", LegalName: "Carrier 424 Freight Systems", Region: "DTW", InsuranceCents: 462500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C425", Scac: "RPLA", LegalName: "Carrier 425 Freight Systems", Region: "YVR", InsuranceCents: 475000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C426", Scac: "QUQB", LegalName: "Carrier 426 Freight Systems", Region: "DFW", InsuranceCents: 487500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C427", Scac: "SLOK", LegalName: "Carrier 427 Freight Systems", Region: "PDX", InsuranceCents: 500000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C428", Scac: "NKYS", LegalName: "Carrier 428 Freight Systems", Region: "PHX", InsuranceCents: 512500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C429", Scac: "CPGA", LegalName: "Carrier 429 Freight Systems", Region: "OKC", InsuranceCents: 525000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C430", Scac: "PKBR", LegalName: "Carrier 430 Freight Systems", Region: "PHX", InsuranceCents: 537500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C431", Scac: "MNNG", LegalName: "Carrier 431 Freight Systems", Region: "NSH", InsuranceCents: 550000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C432", Scac: "YYAO", LegalName: "Carrier 432 Freight Systems", Region: "BOS", InsuranceCents: 562500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C433", Scac: "JRLT", LegalName: "Carrier 433 Freight Systems", Region: "TPA", InsuranceCents: 575000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C434", Scac: "QSAL", LegalName: "Carrier 434 Freight Systems", Region: "RNO", InsuranceCents: 587500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C435", Scac: "VCJB", LegalName: "Carrier 435 Freight Systems", Region: "RNO", InsuranceCents: 600000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C436", Scac: "GRJZ", LegalName: "Carrier 436 Freight Systems", Region: "DTW", InsuranceCents: 612500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C437", Scac: "HSPA", LegalName: "Carrier 437 Freight Systems", Region: "DFW", InsuranceCents: 625000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C438", Scac: "ZLWQ", LegalName: "Carrier 438 Freight Systems", Region: "TPA", InsuranceCents: 637500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C439", Scac: "KTNH", LegalName: "Carrier 439 Freight Systems", Region: "IND", InsuranceCents: 650000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C440", Scac: "AAHY", LegalName: "Carrier 440 Freight Systems", Region: "DFW", InsuranceCents: 662500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C441", Scac: "XDKT", LegalName: "Carrier 441 Freight Systems", Region: "IND", InsuranceCents: 675000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C442", Scac: "TDNJ", LegalName: "Carrier 442 Freight Systems", Region: "MSP", InsuranceCents: 687500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C443", Scac: "EXAR", LegalName: "Carrier 443 Freight Systems", Region: "HOU", InsuranceCents: 700000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C444", Scac: "JUQU", LegalName: "Carrier 444 Freight Systems", Region: "LAX", InsuranceCents: 250000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C445", Scac: "SHJO", LegalName: "Carrier 445 Freight Systems", Region: "YVR", InsuranceCents: 262500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C446", Scac: "LIRB", LegalName: "Carrier 446 Freight Systems", Region: "KCK", InsuranceCents: 275000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C447", Scac: "DWII", LegalName: "Carrier 447 Freight Systems", Region: "DFW", InsuranceCents: 287500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C448", Scac: "DSQU", LegalName: "Carrier 448 Freight Systems", Region: "DFW", InsuranceCents: 300000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C449", Scac: "HTTD", LegalName: "Carrier 449 Freight Systems", Region: "YYZ", InsuranceCents: 312500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C450", Scac: "PBIR", LegalName: "Carrier 450 Freight Systems", Region: "TPA", InsuranceCents: 325000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C451", Scac: "QYPX", LegalName: "Carrier 451 Freight Systems", Region: "JAX", InsuranceCents: 337500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C452", Scac: "WIAV", LegalName: "Carrier 452 Freight Systems", Region: "SEA", InsuranceCents: 350000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C453", Scac: "WOLV", LegalName: "Carrier 453 Freight Systems", Region: "SLC", InsuranceCents: 362500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C454", Scac: "XDAE", LegalName: "Carrier 454 Freight Systems", Region: "IND", InsuranceCents: 375000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C455", Scac: "VRDQ", LegalName: "Carrier 455 Freight Systems", Region: "HOU", InsuranceCents: 387500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C456", Scac: "YKTQ", LegalName: "Carrier 456 Freight Systems", Region: "SLC", InsuranceCents: 400000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C457", Scac: "LLYQ", LegalName: "Carrier 457 Freight Systems", Region: "YYZ", InsuranceCents: 412500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C458", Scac: "TIWC", LegalName: "Carrier 458 Freight Systems", Region: "LAX", InsuranceCents: 425000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C459", Scac: "SNXP", LegalName: "Carrier 459 Freight Systems", Region: "YYZ", InsuranceCents: 437500, Bonded: false})
	return out
}
