package tablex

// carrierFill03 appends carrier rows 180..239.
func carrierFill03(out []CarrierRow) []CarrierRow {
	out = append(out, CarrierRow{CarrierCode: "C180", Scac: "ENUX", LegalName: "Carrier 180 Freight Systems", Region: "PDX", InsuranceCents: 650000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C181", Scac: "SYDI", LegalName: "Carrier 181 Freight Systems", Region: "SEA", InsuranceCents: 662500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C182", Scac: "ZLYZ", LegalName: "Carrier 182 Freight Systems", Region: "TPA", InsuranceCents: 675000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C183", Scac: "MYAJ", LegalName: "Carrier 183 Freight Systems", Region: "MEM", InsuranceCents: 687500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C184", Scac: "LMNM", LegalName: "Carrier 184 Freight Systems", Region: "LAX", InsuranceCents: 700000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C185", Scac: "PGIY", LegalName: "Carrier 185 Freight Systems", Region: "MEM", InsuranceCents: 250000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C186", Scac: "SLUH", LegalName: "Carrier 186 Freight Systems", Region: "PDX", InsuranceCents: 262500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C187", Scac: "RSDO", LegalName: "Carrier 187 Freight Systems", Region: "BOS", InsuranceCents: 275000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C188", Scac: "CWPQ", LegalName: "Carrier 188 Freight Systems", Region: "SEA", InsuranceCents: 287500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C189", Scac: "QYIY", LegalName: "Carrier 189 Freight Systems", Region: "PHX", InsuranceCents: 300000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C190", Scac: "MNWZ", LegalName: "Carrier 190 Freight Systems", Region: "NSH", InsuranceCents: 312500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C191", Scac: "TQYO", LegalName: "Carrier 191 Freight Systems", Region: "ATL", InsuranceCents: 325000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C192", Scac: "IFWQ", LegalName: "Carrier 192 Freight Systems", Region: "YVR", InsuranceCents: 337500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C193", Scac: "URXF", LegalName: "Carrier 193 Freight Systems", Region: "HOU", InsuranceCents: 350000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C194", Scac: "TKYO", LegalName: "Carrier 194 Freight Systems", Region: "RNO", InsuranceCents: 362500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C195", Scac: "SQCD", LegalName: "Carrier 195 Freight Systems", Region: "ATL", InsuranceCents: 375000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C196", Scac: "WHBC", LegalName: "Carrier 196 Freight Systems", Region: "STL", InsuranceCents: 387500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C197", Scac: "PXZO", LegalName: "Carrier 197 Freight Systems", Region: "STL", InsuranceCents: 400000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C198", Scac: "GWJO", LegalName: "Carrier 198 Freight Systems", Region: "DFW", InsuranceCents: 412500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C199", Scac: "FWJK", LegalName: "Carrier 199 Freight Systems", Region: "SEA", InsuranceCents: 425000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C200", Scac: "AARN", LegalName: "Carrier 200 Freight Systems", Region: "MEM", InsuranceCents: 437500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C201", Scac: "WALH", LegalName: "Carrier 201 Freight Systems", Region: "SLC", InsuranceCents: 450000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C202", Scac: "ZSXZ", LegalName: "Carrier 202 Freight Systems", Region: "LAX", InsuranceCents: 462500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C203", Scac: "VSOS", LegalName: "Carrier 203 Freight Systems", Region: "CHI", InsuranceCents: 475000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C204", Scac: "KOUT", LegalName: "Carrier 204 Freight Systems", Region: "ATL", InsuranceCents: 487500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C205", Scac: "GOHA", LegalName: "Carrier 205 Freight Systems", Region: "SEA", InsuranceCents: 500000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C206", Scac: "VMFM", LegalName: "Carrier 206 Freight Systems", Region: "ATL", InsuranceCents: 512500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C207", Scac: "AEQC", LegalName: "Carrier 207 Freight Systems", Region: "DFW", InsuranceCents: 525000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C208", Scac: "NNZB", LegalName: "Carrier 208 Freight Systems", Region: "TPA", InsuranceCents: 537500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C209", Scac: "VMLZ", LegalName: "Carrier 209 Freight Systems", Region: "PHX", InsuranceCents: 550000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C210", Scac: "DAOQ", LegalName: "Carrier 210 Freight Systems", Region: "PHX", InsuranceCents: 562500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C211", Scac: "MBOE", LegalName: "Carrier 211 Freight Systems", Region: "DEN", InsuranceCents: 575000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C212", Scac: "GPNM", LegalName: "Carrier 212 Freight Systems", Region: "OKC", InsuranceCents: 587500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C213", Scac: "FQPZ", LegalName: "Carrier 213 Freight Systems", Region: "RNO", InsuranceCents: 600000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C214", Scac: "LMCS", LegalName: "Carrier 214 Freight Systems", Region: "SLC", InsuranceCents: 612500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C215", Scac: "NOHC", LegalName: "Carrier 215 Freight Systems", Region: "ATL", InsuranceCents: 625000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C216", Scac: "BCVW", LegalName: "Carrier 216 Freight Systems", Region: "RNO", InsuranceCents: 637500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C217", Scac: "KHQS", LegalName: "Carrier 217 Freight Systems", Region: "YYZ", InsuranceCents: 650000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C218", Scac: "KQXG", LegalName: "Carrier 218 Freight Systems", Region: "LAX", InsuranceCents: 662500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C219", Scac: "IVGG", LegalName: "Carrier 219 Freight Systems", Region: "NSH", InsuranceCents: 675000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C220", Scac: "SYPE", LegalName: "Carrier 220 Freight Systems", Region: "MEM", InsuranceCents: 687500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C221", Scac: "DMED", LegalName: "Carrier 221 Freight Systems", Region: "KCK", InsuranceCents: 700000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C222", Scac: "TVQH", LegalName: "Carrier 222 Freight Systems", Region: "HOU", InsuranceCents: 250000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C223", Scac: "ZUCL", LegalName: "Carrier 223 Freight Systems", Region: "RNO", InsuranceCents: 262500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C224", Scac: "NQCA", LegalName: "Carrier 224 Freight Systems", Region: "CHI", InsuranceCents: 275000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C225", Scac: "SEKM", LegalName: "Carrier 225 Freight Systems", Region: "CHI", InsuranceCents: 287500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C226", Scac: "NCCY", LegalName: "Carrier 226 Freight Systems", Region: "MEM", InsuranceCents: 300000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C227", Scac: "DAMW", LegalName: "Carrier 227 Freight Systems", Region: "SEA", InsuranceCents: 312500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C228", Scac: "BQUB", LegalName: "Carrier 228 Freight Systems", Region: "RNO", InsuranceCents: 325000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C229", Scac: "JSDW", LegalName: "Carrier 229 Freight Systems", Region: "JAX", InsuranceCents: 337500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C230", Scac: "WMZG", LegalName: "Carrier 230 Freight Systems", Region: "ATL", InsuranceCents: 350000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C231", Scac: "MGBZ", LegalName: "Carrier 231 Freight Systems", Region: "MEM", InsuranceCents: 362500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C232", Scac: "VZVD", LegalName: "Carrier 232 Freight Systems", Region: "PDX", InsuranceCents: 375000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C233", Scac: "VZMT", LegalName: "Carrier 233 Freight Systems", Region: "YVR", InsuranceCents: 387500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C234", Scac: "WDMT", LegalName: "Carrier 234 Freight Systems", Region: "PDX", InsuranceCents: 400000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C235", Scac: "NTZG", LegalName: "Carrier 235 Freight Systems", Region: "DEN", InsuranceCents: 412500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C236", Scac: "XINK", LegalName: "Carrier 236 Freight Systems", Region: "ATL", InsuranceCents: 425000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C237", Scac: "MYRH", LegalName: "Carrier 237 Freight Systems", Region: "SEA", InsuranceCents: 437500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C238", Scac: "QPYC", LegalName: "Carrier 238 Freight Systems", Region: "MSP", InsuranceCents: 450000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C239", Scac: "WGBE", LegalName: "Carrier 239 Freight Systems", Region: "KCK", InsuranceCents: 462500, Bonded: false})
	return out
}
