package tablex

// carrierFill06 appends carrier rows 360..419.
func carrierFill06(out []CarrierRow) []CarrierRow {
	out = append(out, CarrierRow{CarrierCode: "C360", Scac: "KOTY", LegalName: "Carrier 360 Freight Systems", Region: "DFW", InsuranceCents: 587500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C361", Scac: "NOOS", LegalName: "Carrier 361 Freight Systems", Region: "ATL", InsuranceCents: 600000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C362", Scac: "NRIG", LegalName: "Carrier 362 Freight Systems", Region: "DTW", InsuranceCents: 612500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C363", Scac: "CNVV", LegalName: "Carrier 363 Freight Systems", Region: "YVR", InsuranceCents: 625000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C364", Scac: "GJSW", LegalName: "Carrier 364 Freight Systems", Region: "STL", InsuranceCents: 637500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C365", Scac: "IWMC", LegalName: "Carrier 365 Freight Systems", Region: "JAX", InsuranceCents: 650000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C366", Scac: "CSYK", LegalName: "Carrier 366 Freight Systems", Region: "MEM", InsuranceCents: 662500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C367", Scac: "HLDO", LegalName: "Carrier 367 Freight Systems", Region: "YYZ", InsuranceCents: 675000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C368", Scac: "RPLV", LegalName: "Carrier 368 Freight Systems", Region: "DEN", InsuranceCents: 687500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C369", Scac: "IMJE", LegalName: "Carrier 369 Freight Systems", Region: "KCK", InsuranceCents: 700000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C370", Scac: "TSHQ", LegalName: "Carrier 370 Freight Systems", Region: "RNO", InsuranceCents: 250000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C371", Scac: "NTLA", LegalName: "Carrier 371 Freight Systems", Region: "MSP", InsuranceCents: 262500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C372", Scac: "MLKE", LegalName: "Carrier 372 Freight Systems", Region: "PDX", InsuranceCents: 275000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C373", Scac: "STFS", LegalName: "Carrier 373 Freight Systems", Region: "DTW", InsuranceCents: 287500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C374", Scac: "XNQH", LegalName: "Carrier 374 Freight Systems", Region: "HOU", InsuranceCents: 300000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C375", Scac: "PVZZ", LegalName: "Carrier 375 Freight Systems", Region: "HOU", InsuranceCents: 312500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C376", Scac: "WQWJ", LegalName: "Carrier 376 Freight Systems", Region: "PHX", InsuranceCents: 325000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C377", Scac: "YJKG", LegalName: "Carrier 377 Freight Systems", Region: "YYZ", InsuranceCents: 337500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C378", Scac: "WBRL", LegalName: "Carrier 378 Freight Systems", Region: "YYZ", InsuranceCents: 350000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C379", Scac: "CNGY", LegalName: "Carrier 379 Freight Systems", Region: "IND", InsuranceCents: 362500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C380", Scac: "LTET", LegalName: "Carrier 380 Freight Systems", Region: "IND", InsuranceCents: 375000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C381", Scac: "ZGBM", LegalName: "Carrier 381 Freight Systems", Region: "RNO", InsuranceCents: 387500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C382", Scac: "TDEI", LegalName: "Carrier 382 Freight Systems", Region: "PDX", InsuranceCents: 400000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C383", Scac: "HWLW", LegalName: "Carrier 383 Freight Systems", Region: "SEA", InsuranceCents: 412500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C384", Scac: "GJMT", LegalName: "Carrier 384 Freight Systems", Region: "DEN", InsuranceCents: 425000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C385", Scac: "JCJX", LegalName: "Carrier 385 Freight Systems", Region: "SLC", InsuranceCents: 437500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C386", Scac: "ZPLU", LegalName: "Carrier 386 Freight Systems", Region: "NSH", InsuranceCents: 450000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C387", Scac: "LCNK", LegalName: "Carrier 387 Freight Systems", Region: "SEA", InsuranceCents: 462500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C388", Scac: "FDXV", LegalName: "Carrier 388 Freight Systems", Region: "NSH", InsuranceCents: 475000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C389", Scac: "ZWLE", LegalName: "Carrier 389 Freight Systems", Region: "CHI", InsuranceCents: 487500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C390", Scac: "UFZI", LegalName: "Carrier 390 Freight Systems", Region: "YYZ", InsuranceCents: 500000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C391", Scac: "PDTD", LegalName: "Carrier 391 Freight Systems", Region: "YYZ", InsuranceCents: 512500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C392", Scac: "CQPT", LegalName: "Carrier 392 Freight Systems", Region: "RNO", InsuranceCents: 525000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C393", Scac: "EHJZ", LegalName: "Carrier 393 Freight Systems", Region: "DTW", InsuranceCents: 537500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C394", Scac: "MZMA", LegalName: "Carrier 394 Freight Systems", Region: "YYZ", InsuranceCents: 550000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C395", Scac: "IUWG", LegalName: "Carrier 395 Freight Systems", Region: "LAX", InsuranceCents: 562500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C396", Scac: "PEOW", LegalName: "Carrier 396 Freight Systems", Region: "LAX", InsuranceCents: 575000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C397", Scac: "ZKPC", LegalName: "Carrier 397 Freight Systems", Region: "SLC", InsuranceCents: 587500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C398", Scac: "APLI", LegalName: "Carrier 398 Freight Systems", Region: "NSH", InsuranceCents: 600000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C399", Scac: "TITL", LegalName: "Carrier 399 Freight Systems", Region: "CHI", InsuranceCents: 612500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C400", Scac: "IKVZ", LegalName: "Carrier 400 Freight Systems", Region: "ATL", InsuranceCents: 625000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C401", Scac: "MPFP", LegalName: "Carrier 401 Freight Systems", Region: "DEN", InsuranceCents: 637500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C402", Scac: "ACFE", LegalName: "Carrier 402 Freight Systems", Region: "BOS", InsuranceCents: 650000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C403", Scac: "XZKJ", LegalName: "Carrier 403 Freight Systems", Region: "PDX", InsuranceCents: 662500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C404", Scac: "ARUW", LegalName: "Carrier 404 Freight Systems", Region: "YVR", InsuranceCents: 675000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C405", Scac: "UPNG", LegalName: "Carrier 405 Freight Systems", Region: "TPA", InsuranceCents: 687500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C406", Scac: "PPRR", LegalName: "Carrier 406 Freight Systems", Region: "STL", InsuranceCents: 700000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C407", Scac: "BKOT", LegalName: "Carrier 407 Freight Systems", Region: "CHI", InsuranceCents: 250000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C408", Scac: "FVJX", LegalName: "Carrier 408 Freight Systems", Region: "DTW", InsuranceCents: 262500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C409", Scac: "ZUCB", LegalName: "Carrier 409 Freight Systems", Region: "RNO", InsuranceCents: 275000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C410", Scac: "LXAM", LegalName: "Carrier 410 Freight Systems", Region: "YVR", InsuranceCents: 287500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C411", Scac: "IODB", LegalName: "Carrier 411 Freight Systems", Region: "JAX", InsuranceCents: 300000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C412", Scac: "ANOK", LegalName: "Carrier 412 Freight Systems", Region: "DEN", InsuranceCents: 312500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C413", Scac: "PHZV", LegalName: "Carrier 413 Freight Systems", Region: "YVR", InsuranceCents: 325000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C414", Scac: "OLFR", LegalName: "Carrier 414 Freight Systems", Region: "DEN", InsuranceCents: 337500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C415", Scac: "ZVXZ", LegalName: "Carrier 415 Freight Systems", Region: "IND", InsuranceCents: 350000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C416", Scac: "SZUA", LegalName: "Carrier 416 Freight Systems", Region: "PDX", InsuranceCents: 362500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C417", Scac: "QTLC", LegalName: "Carrier 417 Freight Systems", Region: "DEN", InsuranceCents: 375000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C418", Scac: "IFFW", LegalName: "Carrier 418 Freight Systems", Region: "DEN", InsuranceCents: 387500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C419", Scac: "ZOWA", LegalName: "Carrier 419 Freight Systems", Region: "CHI", InsuranceCents: 400000, Bonded: false})
	return out
}
