package tablex

// carrierFill04 appends carrier rows 240..299.
func carrierFill04(out []CarrierRow) []CarrierRow {
	out = append(out, CarrierRow{CarrierCode: "C240", Scac: "YRWV", LegalName: "Carrier 240 Freight Systems", Region: "IND", InsuranceCents: 475000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C241", Scac: "WIHF", LegalName: "Carrier 241 Freight Systems", Region: "JAX", InsuranceCents: 487500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C242", Scac: "SFAY", LegalName: "Carrier 242 Freight Systems", Region: "NSH", InsuranceCents: 500000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C243", Scac: "WFNS", LegalName: "Carrier 243 Freight Systems", Region: "OKC", InsuranceCents: 512500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C244", Scac: "XVMO", LegalName: "Carrier 244 Freight Systems", Region: "YVR", InsuranceCents: 525000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C245", Scac: "JXGJ", LegalName: "Carrier 245 Freight Systems", Region: "PDX", InsuranceCents: 537500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C246", Scac: "WIDF", LegalName: "Carrier 246 Freight Systems", Region: "DFW", InsuranceCents: 550000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C247", Scac: "NKTH", LegalName: "Carrier 247 Freight Systems", Region: "JAX", InsuranceCents: 562500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C248", Scac: "XTKB", LegalName: "Carrier 248 Freight Systems", Region: "TPA", InsuranceCents: 575000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C249", Scac: "MZJL", LegalName: "Carrier 249 Freight Systems", Region: "HOU", InsuranceCents: 587500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C250", Scac: "HUHI", LegalName: "Carrier 250 Freight Systems", Region: "CHI", InsuranceCents: 600000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C251", Scac: "JGWC", LegalName: "Carrier 251 Freight Systems", Region: "DFW", InsuranceCents: 612500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C252", Scac: "REUA", LegalName: "Carrier 252 Freight Systems", Region: "SLC", InsuranceCents: 625000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C253", Scac: "RYSK", LegalName: "Carrier 253 Freight Systems", Region: "DFW", InsuranceCents: 637500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C254", Scac: "GWMP", LegalName: "Carrier 254 Freight Systems", Region: "PHX", InsuranceCents: 650000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C255", Scac: "XSUB", LegalName: "Carrier 255 Freight Systems", Region: "SLC", InsuranceCents: 662500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C256", Scac: "USKO", LegalName: "Carrier 256 Freight Systems", Region: "LAX", InsuranceCents: 675000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C257", Scac: "PYTE", LegalName: "Carrier 257 Freight Systems", Region: "MEM", InsuranceCents: 687500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C258", Scac: "RKND", LegalName: "Carrier 258 Freight Systems", Region: "RNO", InsuranceCents: 700000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C259", Scac: "YORM", LegalName: "Carrier 259 Freight Systems", Region: "SLC", InsuranceCents: 250000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C260", Scac: "YMZZ", LegalName: "Carrier 260 Freight Systems", Region: "JAX", InsuranceCents: 262500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C261", Scac: "SPDT", LegalName: "Carrier 261 Freight Systems", Region: "DEN", InsuranceCents: 275000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C262", Scac: "XTOY", LegalName: "Carrier 262 Freight Systems", Region: "TPA", InsuranceCents: 287500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C263", Scac: "NSQO", LegalName: "Carrier 263 Freight Systems", Region: "BOS", InsuranceCents: 300000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C264", Scac: "PGPR", LegalName: "Carrier 264 Freight Systems", Region: "SEA", InsuranceCents: 312500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C265", Scac: "VXZT", LegalName: "Carrier 265 Freight Systems", Region: "NSH", InsuranceCents: 325000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C266", Scac: "JLOE", LegalName: "Carrier 266 Freight Systems", Region: "OKC", InsuranceCents: 337500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C267", Scac: "EKTU", LegalName: "Carrier 267 Freight Systems", Region: "CHI", InsuranceCents: 350000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C268", Scac: "NKNQ", LegalName: "Carrier 268 Freight Systems", Region: "SEA", InsuranceCents: 362500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C269", Scac: "PLTU", LegalName: "Carrier 269 Freight Systems", Region: "STL", InsuranceCents: 375000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C270", Scac: "RUUU", LegalName: "Carrier 270 Freight Systems", Region: "PHX", InsuranceCents: 387500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C271", Scac: "OBHH", LegalName: "Carrier 271 Freight Systems", Region: "DTW", InsuranceCents: 400000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C272", Scac: "YRUW", LegalName: "Carrier 272 Freight Systems", Region: "MSP", InsuranceCents: 412500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C273", Scac: "HPKS", LegalName: "Carrier 273 Freight Systems", Region: "YYZ", InsuranceCents: 425000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C274", Scac: "JGYY", LegalName: "Carrier 274 Freight Systems", Region: "SEA", InsuranceCents: 437500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C275", Scac: "TLWS", LegalName: "Carrier 275 Freight Systems", Region: "MSP", InsuranceCents: 450000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C276", Scac: "MXVF", LegalName: "Carrier 276 Freight Systems", Region: "PDX", InsuranceCents: 462500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C277", Scac: "BUEN", LegalName: "Carrier 277 Freight Systems", Region: "KCK", InsuranceCents: 475000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C278", Scac: "NFUA", LegalName: "Carrier 278 Freight Systems", Region: "TPA", InsuranceCents: 487500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C279", Scac: "GSCN", LegalName: "Carrier 279 Freight Systems", Region: "MEM", InsuranceCents: 500000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C280", Scac: "XZHW", LegalName: "Carrier 280 Freight Systems", Region: "PDX", InsuranceCents: 512500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C281", Scac: "BMBL", LegalName: "Carrier 281 Freight Systems", Region: "ATL", InsuranceCents: 525000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C282", Scac: "GJGB", LegalName: "Carrier 282 Freight Systems", Region: "IND", InsuranceCents: 537500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C283", Scac: "ZJTO", LegalName: "Carrier 283 Freight Systems", Region: "OKC", InsuranceCents: 550000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C284", Scac: "USYB", LegalName: "Carrier 284 Freight Systems", Region: "SLC", InsuranceCents: 562500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C285", Scac: "KBPQ", LegalName: "Carrier 285 Freight Systems", Region: "YVR", InsuranceCents: 575000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C286", Scac: "OLFC", LegalName: "Carrier 286 Freight Systems", Region: "MSP", InsuranceCents: 587500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C287", Scac: "LBNQ", LegalName: "Carrier 287 Freight Systems", Region: "YVR", InsuranceCents: 600000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C288", Scac: "PIWJ", LegalName: "Carrier 288 Freight Systems", Region: "LAX", InsuranceCents: 612500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C289", Scac: "OMAT", LegalName: "Carrier 289 Freight Systems", Region: "SLC", InsuranceCents: 625000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C290", Scac: "YOAL", LegalName: "Carrier 290 Freight Systems", Region: "CHI", InsuranceCents: 637500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C291", Scac: "RCWF", LegalName: "Carrier 291 Freight Systems", Region: "DFW", InsuranceCents: 650000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C292", Scac: "QOGR", LegalName: "Carrier 292 Freight Systems", Region: "RNO", InsuranceCents: 662500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C293", Scac: "PYRT", LegalName: "Carrier 293 Freight Systems", Region: "MEM", InsuranceCents: 675000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C294", Scac: "XRRK", LegalName: "Carrier 294 Freight Systems", Region: "IND", InsuranceCents: 687500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C295", Scac: "OLBA", LegalName: "Carrier 295 Freight Systems", Region: "YVR", InsuranceCents: 700000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C296", Scac: "LPRZ", LegalName: "Carrier 296 Freight Systems", Region: "YVR", InsuranceCents: 250000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C297", Scac: "CFXR", LegalName: "Carrier 297 Freight Systems", Region: "IND", InsuranceCents: 262500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C298", Scac: "DQQV", LegalName: "Carrier 298 Freight Systems", Region: "KCK", InsuranceCents: 275000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C299", Scac: "MNCG", LegalName: "Carrier 299 Freight Systems", Region: "DTW", InsuranceCents: 287500, Bonded: false})
	return out
}
