package tablex

// carrierFill02 appends carrier rows 120..179.
func carrierFill02(out []CarrierRow) []CarrierRow {
	out = append(out, CarrierRow{CarrierCode: "C120", Scac: "GJYP", LegalName: "Carrier 120 Freight Systems", Region: "YVR", InsuranceCents: 362500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C121", Scac: "WHJU", LegalName: "Carrier 121 Freight Systems", Region: "MSP", InsuranceCents: 375000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C122", Scac: "KBOW", LegalName: "Carrier 122 Freight Systems", Region: "MSP", InsuranceCents: 387500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C123", Scac: "MKGT", LegalName: "Carrier 123 Freight Systems", Region: "ATL", InsuranceCents: 400000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C124", Scac: "COLO", LegalName: "Carrier 124 Freight Systems", Region: "SLC", InsuranceCents: 412500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C125", Scac: "HPDV", LegalName: "Carrier 125 Freight Systems", Region: "HOU", InsuranceCents: 425000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C126", Scac: "PEYU", LegalName: "Carrier 126 Freight Systems", Region: "CHI", InsuranceCents: 437500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C127", Scac: "APYK", LegalName: "Carrier 127 Freight Systems", Region: "TPA", InsuranceCents: 450000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C128", Scac: "YSIL", LegalName: "Carrier 128 Freight Systems", Region: "SLC", InsuranceCents: 462500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C129", Scac: "PDLR", LegalName: "Carrier 129 Freight Systems", Region: "HOU", InsuranceCents: 475000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C130", Scac: "ENMR", LegalName: "Carrier 130 Freight Systems", Region: "MSP", InsuranceCents: 487500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C131", Scac: "EJYM", LegalName: "Carrier 131 Freight Systems", Region: "STL", InsuranceCents: 500000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C132", Scac: "YXRU", LegalName: "Carrier 132 Freight Systems", Region: "YYZ", InsuranceCents: 512500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C133", Scac: "QOYB", LegalName: "Carrier 133 Freight Systems", Region: "KCK", InsuranceCents: 525000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C134", Scac: "DIWK", LegalName: "Carrier 134 Freight Systems", Region: "PHX", InsuranceCents: 537500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C135", Scac: "NDRU", LegalName: "Carrier 135 Freight Systems", Region: "YYZ", InsuranceCents: 550000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C136", Scac: "WLTM", LegalName: "Carrier 136 Freight Systems", Region: "DTW", InsuranceCents: 562500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C137", Scac: "JJMU", LegalName: "Carrier 137 Freight Systems", Region: "DEN", InsuranceCents: 575000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C138", Scac: "CGLM", LegalName: "Carrier 138 Freight Systems", Region: "SLC", InsuranceCents: 587500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C139", Scac: "QHMP", LegalName: "Carrier 139 Freight Systems", Region: "YVR", InsuranceCents: 600000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C140", Scac: "VFXU", LegalName: "Carrier 140 Freight Systems", Region: "OKC", InsuranceCents: 612500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C141", Scac: "GWPJ", LegalName: "Carrier 141 Freight Systems", Region: "MEM", InsuranceCents: 625000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C142", Scac: "VJQW", LegalName: "Carrier 142 Freight Systems", Region: "YYZ", InsuranceCents: 637500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C143", Scac: "OUMC", LegalName: "Carrier 143 Freight Systems", Region: "DFW", InsuranceCents: 650000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C144", Scac: "CNYD", LegalName: "Carrier 144 Freight Systems", Region: "DEN", InsuranceCents: 662500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C145", Scac: "HBRB", LegalName: "Carrier 145 Freight Systems", Region: "DEN", InsuranceCents: 675000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C146", Scac: "NZEE", LegalName: "Carrier 146 Freight Systems", Region: "YYZ", InsuranceCents: 687500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C147", Scac: "FCLZ", LegalName: "Carrier 147 Freight Systems", Region: "LAX", InsuranceCents: 700000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C148", Scac: "JSDJ", LegalName: "Carrier 148 Freight Systems", Region: "PHX", InsuranceCents: 250000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C149", Scac: "NCWP", LegalName: "Carrier 149 Freight Systems", Region: "MEM", InsuranceCents: 262500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C150", Scac: "DVQB", LegalName: "Carrier 150 Freight Systems", Region: "DEN", InsuranceCents: 275000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C151", Scac: "SCFN", LegalName: "Carrier 151 Freight Systems", Region: "ATL", InsuranceCents: 287500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C152", Scac: "VHEV", LegalName: "Carrier 152 Freight Systems", Region: "STL", InsuranceCents: 300000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C153", Scac: "SIXV", LegalName: "Carrier 153 Freight Systems", Region: "CHI", InsuranceCents: 312500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C154", Scac: "RRQU", LegalName: "Carrier 154 Freight Systems", Region: "HOU", InsuranceCents: 325000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C155", Scac: "RSXX", LegalName: "Carrier 155 Freight Systems", Region: "BOS", InsuranceCents: 337500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C156", Scac: "IBUY", LegalName: "Carrier 156 Freight Systems", Region: "PDX", InsuranceCents: 350000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C157", Scac: "IRXO", LegalName: "Carrier 157 Freight Systems", Region: "DTW", InsuranceCents: 362500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C158", Scac: "PGWQ", LegalName: "Carrier 158 Freight Systems", Region: "ATL", InsuranceCents: 375000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C159", Scac: "FEFP", LegalName: "Carrier 159 Freight Systems", Region: "JAX", InsuranceCents: 387500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C160", Scac: "ACRE", LegalName: "Carrier 160 Freight Systems", Region: "RNO", InsuranceCents: 400000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C161", Scac: "JXKM", LegalName: "Carrier 161 Freight Systems", Region: "STL", InsuranceCents: 412500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C162", Scac: "LBAC", LegalName: "Carrier 162 Freight Systems", Region: "DEN", InsuranceCents: 425000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C163", Scac: "MTLN", LegalName: "Carrier 163 Freight Systems", Region: "STL", InsuranceCents: 437500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C164", Scac: "KVEU", LegalName: "Carrier 164 Freight Systems", Region: "NSH", InsuranceCents: 450000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C165", Scac: "BFGB", LegalName: "Carrier 165 Freight Systems", Region: "HOU", InsuranceCents: 462500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C166", Scac: "CYTS", LegalName: "Carrier 166 Freight Systems", Region: "KCK", InsuranceCents: 475000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C167", Scac: "CMRI", LegalName: "Carrier 167 Freight Systems", Region: "KCK", InsuranceCents: 487500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C168", Scac: "YZBK", LegalName: "Carrier 168 Freight Systems", Region: "MSP", InsuranceCents: 500000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C169", Scac: "QLGS", LegalName: "Carrier 169 Freight Systems", Region: "STL", InsuranceCents: 512500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C170", Scac: "WPDC", LegalName: "Carrier 170 Freight Systems", Region: "DTW", InsuranceCents: 525000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C171", Scac: "QPPD", LegalName: "Carrier 171 Freight Systems", Region: "STL", InsuranceCents: 537500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C172", Scac: "FRZR", LegalName: "Carrier 172 Freight Systems", Region: "DEN", InsuranceCents: 550000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C173", Scac: "OLXV", LegalName: "Carrier 173 Freight Systems", Region: "MSP", InsuranceCents: 562500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C174", Scac: "ZEXM", LegalName: "Carrier 174 Freight Systems", Region: "SEA", InsuranceCents: 575000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C175", Scac: "QUNZ", LegalName: "Carrier 175 Freight Systems", Region: "ATL", InsuranceCents: 587500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C176", Scac: "SUUL", LegalName: "Carrier 176 Freight Systems", Region: "SEA", InsuranceCents: 600000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C177", Scac: "SRCT", LegalName: "Carrier 177 Freight Systems", Region: "OKC", InsuranceCents: 612500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C178", Scac: "HKYG", LegalName: "Carrier 178 Freight Systems", Region: "DFW", InsuranceCents: 625000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C179", Scac: "ZQYI", LegalName: "Carrier 179 Freight Systems", Region: "PHX", InsuranceCents: 637500, Bonded: false})
	return out
}
