package tablex

// carrierFill00 appends carrier rows 0..59.
func carrierFill00(out []CarrierRow) []CarrierRow {
	out = append(out, CarrierRow{CarrierCode: "C000", Scac: "RQLN", LegalName: "Carrier 000 Freight Systems", Region: "MEM", InsuranceCents: 250000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C001", Scac: "MGSN", LegalName: "Carrier 001 Freight Systems", Region: "SEA", InsuranceCents: 262500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C002", Scac: "ANLX", LegalName: "Carrier 002 Freight Systems", Region: "STL", InsuranceCents: 275000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C003", Scac: "UUUS", LegalName: "Carrier 003 Freight Systems", Region: "JAX", InsuranceCents: 287500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C004", Scac: "BRWD", LegalName: "Carrier 004 Freight Systems", Region: "DEN", InsuranceCents: 300000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C005", Scac: "FKDE", LegalName: "Carrier 005 Freight Systems", Region: "CHI", InsuranceCents: 312500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C006", Scac: "GTZE", LegalName: "Carrier 006 Freight Systems", Region: "YYZ", InsuranceCents: 325000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C007", Scac: "XVZE", LegalName: "Carrier 007 Freight Systems", Region: "DEN", InsuranceCents: 337500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C008", Scac: "OGSY", LegalName: "Carrier 008 Freight Systems", Region: "DFW", InsuranceCents: 350000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C009", Scac: "CACN", LegalName: "Carrier 009 Freight Systems", Region: "MEM", InsuranceCents: 362500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C010", Scac: "WZRH", LegalName: "Carrier 010 Freight Systems", Region: "DEN", InsuranceCents: 375000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C011", Scac: "NGZI", LegalName: "Carrier 011 Freight Systems", Region: "MEM", InsuranceCents: 387500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C012", Scac: "EJFU", LegalName: "Carrier 012 Freight Systems", Region: "IND", InsuranceCents: 400000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C013", Scac: "KFEN", LegalName: "Carrier 013 Freight Systems", Region: "DEN", InsuranceCents: 412500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C014", Scac: "XMVA", LegalName: "Carrier 014 Freight Systems", Region: "DFW", InsuranceCents: 425000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C015", Scac: "OLHS", LegalName: "Carrier 015 Freight Systems", Region: "YVR", InsuranceCents: 437500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C016", Scac: "IOCW", LegalName: "Carrier 016 Freight Systems", Region: "PHX", InsuranceCents: 450000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C017", Scac: "SWWU", LegalName: "Carrier 017 Freight Systems", Region: "SLC", InsuranceCents: 462500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C018", Scac: "XVAF", LegalName: "Carrier 018 Freight Systems", Region: "YVR", InsuranceCents: 475000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C019", Scac: "SNOY", LegalName: "Carrier 019 Freight Systems", Region: "HOU", InsuranceCents: 487500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C020", Scac: "KIDE", LegalName: "Carrier 020 Freight Systems", Region: "BOS", InsuranceCents: 500000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C021", Scac: "TYHV", LegalName: "Carrier 021 Freight Systems", Region: "DFW", InsuranceCents: 512500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C022", Scac: "PKVA", LegalName: "Carrier 022 Freight Systems", Region: "PHX", InsuranceCents: 525000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C023", Scac: "OZAV", LegalName: "Carrier 023 Freight Systems", Region: "HOU", InsuranceCents: 537500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C024", Scac: "GAEK", LegalName: "Carrier 024 Freight Systems", Region: "PHX", InsuranceCents: 550000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C025", Scac: "GAOP", LegalName: "Carrier 025 Freight Systems", Region: "JAX", InsuranceCents: 562500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C026", Scac: "EZMV", LegalName: "Carrier 026 Freight Systems", Region: "DTW", InsuranceCents: 575000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C027", Scac: "WVQZ", LegalName: "Carrier 027 Freight Systems", Region: "STL", InsuranceCents: 587500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C028", Scac: "LOYE", LegalName: "Carrier 028 Freight Systems", Region: "PHX", InsuranceCents: 600000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C029", Scac: "ARAP", LegalName: "Carrier 029 Freight Systems", Region: "YVR", InsuranceCents: 612500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C030", Scac: "AWAL", LegalName: "Carrier 030 Freight Systems", Region: "DFW", InsuranceCents: 625000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C031", Scac: "CYAG", LegalName: "Carrier 031 Freight Systems", Region: "KCK", InsuranceCents: 637500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C032", Scac: "BMPA", LegalName: "Carrier 032 Freight Systems", Region: "PHX", InsuranceCents: 650000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C033", Scac: "MJAX", LegalName: "Carrier 033 Freight Systems", Region: "DTW", InsuranceCents: 662500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C034", Scac: "NEXK", LegalName: "Carrier 034 Freight Systems", Region: "RNO", InsuranceCents: 675000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C035", Scac: "JSPE", LegalName: "Carrier 035 Freight Systems", Region: "SEA", InsuranceCents: 687500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C036", Scac: "THRO", LegalName: "Carrier 036 Freight Systems", Region: "MSP", InsuranceCents: 700000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C037", Scac: "YNRE", LegalName: "Carrier 037 Freight Systems", Region: "IND", InsuranceCents: 250000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C038", Scac: "RUAX", LegalName: "Carrier 038 Freight Systems", Region: "ATL", InsuranceCents: 262500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C039", Scac: "WMCO", LegalName: "Carrier 039 Freight Systems", Region: "SEA", InsuranceCents: 275000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C040", Scac: "WJUA", LegalName: "Carrier 040 Freight Systems", Region: "YYZ", InsuranceCents: 287500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C041", Scac: "QPIN", LegalName: "Carrier 041 Freight Systems", Region: "YVR", InsuranceCents: 300000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C042", Scac: "KZUD", LegalName: "Carrier 042 Freight Systems", Region: "OKC", InsuranceCents: 312500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C043", Scac: "VMKR", LegalName: "Carrier 043 Freight Systems", Region: "SEA", InsuranceCents: 325000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C044", Scac: "TZTB", LegalName: "Carrier 044 Freight Systems", Region: "PDX", InsuranceCents: 337500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C045", Scac: "JOCG", LegalName: "Carrier 045 Freight Systems", Region: "PHX", InsuranceCents: 350000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C046", Scac: "WGBR", LegalName: "Carrier 046 Freight Systems", Region: "BOS", InsuranceCents: 362500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C047", Scac: "LFKU", LegalName: "Carrier 047 Freight Systems", Region: "DEN", InsuranceCents: 375000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C048", Scac: "DGIH", LegalName: "Carrier 048 Freight Systems", Region: "LAX", InsuranceCents: 387500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C049", Scac: "TWPV", LegalName: "Carrier 049 Freight Systems", Region: "LAX", InsuranceCents: 400000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C050", Scac: "CRCF", LegalName: "Carrier 050 Freight Systems", Region: "STL", InsuranceCents: 412500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C051", Scac: "RATY", LegalName: "Carrier 051 Freight Systems", Region: "LAX", InsuranceCents: 425000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C052", Scac: "QCHO", LegalName: "Carrier 052 Freight Systems", Region: "ATL", InsuranceCents: 437500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C053", Scac: "TBQE", LegalName: "Carrier 053 Freight Systems", Region: "NSH", InsuranceCents: 450000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C054", Scac: "VMOV", LegalName: "Carrier 054 Freight Systems", Region: "SEA", InsuranceCents: 462500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C055", Scac: "IWZW", LegalName: "Carrier 055 Freight Systems", Region: "JAX", InsuranceCents: 475000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C056", Scac: "MPCL", LegalName: "Carrier 056 Freight Systems", Region: "MSP", InsuranceCents: 487500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C057", Scac: "KNBR", LegalName: "Carrier 057 Freight Systems", Region: "DTW", InsuranceCents: 500000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C058", Scac: "ULGL", LegalName: "Carrier 058 Freight Systems", Region: "STL", InsuranceCents: 512500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C059", Scac: "BWCL", LegalName: "Carrier 059 Freight Systems", Region: "SEA", InsuranceCents: 525000, Bonded: false})
	return out
}
