package tablex

// carrierFill01 appends carrier rows 60..119.
func carrierFill01(out []CarrierRow) []CarrierRow {
	out = append(out, CarrierRow{CarrierCode: "C060", Scac: "RJUX", LegalName: "Carrier 060 Freight Systems", Region: "NSH", InsuranceCents: 537500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C061", Scac: "LTSA", LegalName: "Carrier 061 Freight Systems", Region: "YVR", InsuranceCents: 550000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C062", Scac: "NEAE", LegalName: "Carrier 062 Freight Systems", Region: "RNO", InsuranceCents: 562500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C063", Scac: "TLUB", LegalName: "Carrier 063 Freight Systems", Region: "MSP", InsuranceCents: 575000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C064", Scac: "UFJB", LegalName: "Carrier 064 Freight Systems", Region: "OKC", InsuranceCents: 587500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C065", Scac: "AGLA", LegalName: "Carrier 065 Freight Systems", Region: "CHI", InsuranceCents: 600000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C066", Scac: "QFUK", LegalName: "Carrier 066 Freight Systems", Region: "DTW", InsuranceCents: 612500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C067", Scac: "JJDZ", LegalName: "Carrier 067 Freight Systems", Region: "STL", InsuranceCents: 625000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C068", Scac: "ICLA", LegalName: "Carrier 068 Freight Systems", Region: "LAX", InsuranceCents: 637500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C069", Scac: "SDQW", LegalName: "Carrier 069 Freight Systems", Region: "PDX", InsuranceCents: 650000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C070", Scac: "YRCQ", LegalName: "Carrier 070 Freight Systems", Region: "STL", InsuranceCents: 662500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C071", Scac: "ZDZJ", LegalName: "Carrier 071 Freight Systems", Region: "DEN", InsuranceCents: 675000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C072", Scac: "WEZG", LegalName: "Carrier 072 Freight Systems", Region: "MEM", InsuranceCents: 687500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C073", Scac: "AKKM", LegalName: "Carrier 073 Freight Systems", Region: "LAX", InsuranceCents: 700000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C074", Scac: "JDQD", LegalName: "Carrier 074 Freight Systems", Region: "OKC", InsuranceCents: 250000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C075", Scac: "OWBQ", LegalName: "Carrier 075 Freight Systems", Region: "RNO", InsuranceCents: 262500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C076", Scac: "RPIT", LegalName: "Carrier 076 Freight Systems", Region: "YVR", InsuranceCents: 275000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C077", Scac: "GOZB", LegalName: "Carrier 077 Freight Systems", Region: "ATL", InsuranceCents: 287500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C078", Scac: "HGHP", LegalName: "Carrier 078 Freight Systems", Region: "CHI", InsuranceCents: 300000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C079", Scac: "HFYJ", LegalName: "Carrier 079 Freight Systems", Region: "YVR", InsuranceCents: 312500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C080", Scac: "UEOF", LegalName: "Carrier 080 Freight Systems", Region: "LAX", InsuranceCents: 325000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C081", Scac: "TXZU", LegalName: "Carrier 081 Freight Systems", Region: "TPA", InsuranceCents: 337500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C082", Scac: "YMKS", LegalName: "Carrier 082 Freight Systems", Region: "JAX", InsuranceCents: 350000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C083", Scac: "HJEJ", LegalName: "Carrier 083 Freight Systems", Region: "YVR", InsuranceCents: 362500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C084", Scac: "MGEX", LegalName: "Carrier 084 Freight Systems", Region: "MEM", InsuranceCents: 375000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C085", Scac: "BENT", LegalName: "Carrier 085 Freight Systems", Region: "DFW", InsuranceCents: 387500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C086", Scac: "KJUU", LegalName: "Carrier 086 Freight Systems", Region: "DTW", InsuranceCents: 400000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C087", Scac: "AVPE", LegalName: "Carrier 087 Freight Systems", Region: "STL", InsuranceCents: 412500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C088", Scac: "QUIR", LegalName: "Carrier 088 Freight Systems", Region: "SEA", InsuranceCents: 425000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C089", Scac: "CUYM", LegalName: "Carrier 089 Freight Systems", Region: "RNO", InsuranceCents: 437500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C090", Scac: "NJPW", LegalName: "Carrier 090 Freight Systems", Region: "NSH", InsuranceCents: 450000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C091", Scac: "EGHW", LegalName: "Carrier 091 Freight Systems", Region: "CHI", InsuranceCents: 462500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C092", Scac: "RZSM", LegalName: "Carrier 092 Freight Systems", Region: "YYZ", InsuranceCents: 475000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C093", Scac: "JQJT", LegalName: "Carrier 093 Freight Systems", Region: "SLC", InsuranceCents: 487500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C094", Scac: "RARL", LegalName: "Carrier 094 Freight Systems", Region: "SLC", InsuranceCents: 500000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C095", Scac: "KBOL", LegalName: "Carrier 095 Freight Systems", Region: "STL", InsuranceCents: 512500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C096", Scac: "WJSA", LegalName: "Carrier 096 Freight Systems", Region: "OKC", InsuranceCents: 525000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C097", Scac: "VUHY", LegalName: "Carrier 097 Freight Systems", Region: "PHX", InsuranceCents: 537500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C098", Scac: "BLCY", LegalName: "Carrier 098 Freight Systems", Region: "DTW", InsuranceCents: 550000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C099", Scac: "XZIT", LegalName: "Carrier 099 Freight Systems", Region: "MSP", InsuranceCents: 562500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C100", Scac: "LTTB", LegalName: "Carrier 100 Freight Systems", Region: "IND", InsuranceCents: 575000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C101", Scac: "OSFY", LegalName: "Carrier 101 Freight Systems", Region: "RNO", InsuranceCents: 587500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C102", Scac: "XPIE", LegalName: "Carrier 102 Freight Systems", Region: "DTW", InsuranceCents: 600000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C103", Scac: "RPRC", LegalName: "Carrier 103 Freight Systems", Region: "MSP", InsuranceCents: 612500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C104", Scac: "TNOF", LegalName: "Carrier 104 Freight Systems", Region: "YYZ", InsuranceCents: 625000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C105", Scac: "KDNC", LegalName: "Carrier 105 Freight Systems", Region: "YYZ", InsuranceCents: 637500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C106", Scac: "GNKZ", LegalName: "Carrier 106 Freight Systems", Region: "STL", InsuranceCents: 650000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C107", Scac: "XOWG", LegalName: "Carrier 107 Freight Systems", Region: "LAX", InsuranceCents: 662500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C108", Scac: "OGST", LegalName: "Carrier 108 Freight Systems", Region: "PHX", InsuranceCents: 675000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C109", Scac: "CBKK", LegalName: "Carrier 109 Freight Systems", Region: "YYZ", InsuranceCents: 687500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C110", Scac: "MSJM", LegalName: "Carrier 110 Freight Systems", Region: "RNO", InsuranceCents: 700000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C111", Scac: "BAAO", LegalName: "Carrier 111 Freight Systems", Region: "DFW", InsuranceCents: 250000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C112", Scac: "LXHK", LegalName: "Carrier 112 Freight Systems", Region: "IND", InsuranceCents: 262500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C113", Scac: "PGIU", LegalName: "Carrier 113 Freight Systems", Region: "JAX", InsuranceCents: 275000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C114", Scac: "EVMT", LegalName: "Carrier 114 Freight Systems", Region: "DTW", InsuranceCents: 287500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C115", Scac: "ORYD", LegalName: "Carrier 115 Freight Systems", Region: "YYZ", InsuranceCents: 300000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C116", Scac: "NGWN", LegalName: "Carrier 116 Freight Systems", Region: "ATL", InsuranceCents: 312500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C117", Scac: "VDER", LegalName: "Carrier 117 Freight Systems", Region: "DEN", InsuranceCents: 325000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C118", Scac: "WRWW", LegalName: "Carrier 118 Freight Systems", Region: "IND", InsuranceCents: 337500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C119", Scac: "RANG", LegalName: "Carrier 119 Freight Systems", Region: "LAX", InsuranceCents: 350000, Bonded: false})
	return out
}
