package tablex

// carrierFill05 appends carrier rows 300..359.
func carrierFill05(out []CarrierRow) []CarrierRow {
	out = append(out, CarrierRow{CarrierCode: "C300", Scac: "DWWD", LegalName: "Carrier 300 Freight Systems", Region: "ATL", InsuranceCents: 300000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C301", Scac: "JBSB", LegalName: "Carrier 301 Freight Systems", Region: "DEN", InsuranceCents: 312500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C302", Scac: "CLUD", LegalName: "Carrier 302 Freight Systems", Region: "DTW", InsuranceCents: 325000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C303", Scac: "OGZG", LegalName: "Carrier 303 Freight Systems", Region: "PHX", InsuranceCents: 337500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C304", Scac: "TESJ", LegalName: "Carrier 304 Freight Systems", Region: "CHI", InsuranceCents: 350000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C305", Scac: "UBQA", LegalName: "Carrier 305 Freight Systems", Region: "NSH", InsuranceCents: 362500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C306", Scac: "ZCWL", LegalName: "Carrier 306 Freight Systems", Region: "RNO", InsuranceCents: 375000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C307", Scac: "YTOP", LegalName: "Carrier 307 Freight Systems", Region: "TPA", InsuranceCents: 387500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C308", Scac: "ZDEE", LegalName: "Carrier 308 Freight Systems", Region: "STL", InsuranceCents: 400000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C309", Scac: "FUQD", LegalName: "Carrier 309 Freight Systems", Region: "BOS", InsuranceCents: 412500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C310", Scac: "OQNK", LegalName: "Carrier 310 Freight Systems", Region: "CHI", InsuranceCents: 425000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C311", Scac: "DIYK", LegalName: "Carrier 311 Freight Systems", Region: "ATL", InsuranceCents: 437500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C312", Scac: "TWBI", LegalName: "Carrier 312 Freight Systems", Region: "SLC", InsuranceCents: 450000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C313", Scac: "TGOS", LegalName: "Carrier 313 Freight Systems", Region: "RNO", InsuranceCents: 462500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C314", Scac: "ALYN", LegalName: "Carrier 314 Freight Systems", Region: "NSH", InsuranceCents: 475000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C315", Scac: "OXIK", LegalName: "Carrier 315 Freight Systems", Region: "DEN", InsuranceCents: 487500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C316", Scac: "ZFEG", LegalName: "Carrier 316 Freight Systems", Region: "HOU", InsuranceCents: 500000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C317", Scac: "EFDT", LegalName: "Carrier 317 Freight Systems", Region: "MSP", InsuranceCents: 512500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C318", Scac: "DYEX", LegalName: "Carrier 318 Freight Systems", Region: "RNO", InsuranceCents: 525000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C319", Scac: "JEPG", LegalName: "Carrier 319 Freight Systems", Region: "RNO", InsuranceCents: 537500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C320", Scac: "URMW", LegalName: "Carrier 320 Freight Systems", Region: "HOU", InsuranceCents: 550000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C321", Scac: "PRHX", LegalName: "Carrier 321 Freight Systems", Region: "OKC", InsuranceCents: 562500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C322", Scac: "LLGO", LegalName: "Carrier 322 Freight Systems", Region: "OKC", InsuranceCents: 575000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C323", Scac: "PTNZ", LegalName: "Carrier 323 Freight Systems", Region: "DEN", InsuranceCents: 587500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C324", Scac: "SQJK", LegalName: "Carrier 324 Freight Systems", Region: "SEA", InsuranceCents: 600000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C325", Scac: "BTKE", LegalName: "Carrier 325 Freight Systems", Region: "OKC", InsuranceCents: 612500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C326", Scac: "VRPN", LegalName: "Carrier 326 Freight Systems", Region: "OKC", InsuranceCents: 625000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C327", Scac: "FKJZ", LegalName: "Carrier 327 Freight Systems", Region: "SLC", InsuranceCents: 637500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C328", Scac: "YXPE", LegalName: "Carrier 328 Freight Systems", Region: "OKC", InsuranceCents: 650000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C329", Scac: "DKSH", LegalName: "Carrier 329 Freight Systems", Region: "SLC", InsuranceCents: 662500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C330", Scac: "SIVW", LegalName: "Carrier 330 Freight Systems", Region: "CHI", InsuranceCents: 675000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C331", Scac: "YQBF", LegalName: "Carrier 331 Freight Systems", Region: "PHX", InsuranceCents: 687500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C332", Scac: "HORM", LegalName: "Carrier 332 Freight Systems", Region: "JAX", InsuranceCents: 700000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C333", Scac: "YYJU", LegalName: "Carrier 333 Freight Systems", Region: "BOS", InsuranceCents: 250000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C334", Scac: "OYUN", LegalName: "Carrier 334 Freight Systems", Region: "MEM", InsuranceCents: 262500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C335", Scac: "HJHE", LegalName: "Carrier 335 Freight Systems", Region: "PDX", InsuranceCents: 275000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C336", Scac: "TXOP", LegalName: "Carrier 336 Freight Systems", Region: "TPA", InsuranceCents: 287500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C337", Scac: "OGVS", LegalName: "Carrier 337 Freight Systems", Region: "PHX", InsuranceCents: 300000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C338", Scac: "WZLE", LegalName: "Carrier 338 Freight Systems", Region: "STL", InsuranceCents: 312500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C339", Scac: "SDRS", LegalName: "Carrier 339 Freight Systems", Region: "YVR", InsuranceCents: 325000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C340", Scac: "RNMX", LegalName: "Carrier 340 Freight Systems", Region: "OKC", InsuranceCents: 337500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C341", Scac: "PRLB", LegalName: "Carrier 341 Freight Systems", Region: "YYZ", InsuranceCents: 350000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C342", Scac: "FNDX", LegalName: "Carrier 342 Freight Systems", Region: "PDX", InsuranceCents: 362500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C343", Scac: "MGDW", LegalName: "Carrier 343 Freight Systems", Region: "JAX", InsuranceCents: 375000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C344", Scac: "PPAY", LegalName: "Carrier 344 Freight Systems", Region: "STL", InsuranceCents: 387500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C345", Scac: "CQSR", LegalName: "Carrier 345 Freight Systems", Region: "RNO", InsuranceCents: 400000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C346", Scac: "ZMPE", LegalName: "Carrier 346 Freight Systems", Region: "PHX", InsuranceCents: 412500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C347", Scac: "FNTH", LegalName: "Carrier 347 Freight Systems", Region: "YVR", InsuranceCents: 425000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C348", Scac: "FIEB", LegalName: "Carrier 348 Freight Systems", Region: "RNO", InsuranceCents: 437500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C349", Scac: "HQNX", LegalName: "Carrier 349 Freight Systems", Region: "KCK", InsuranceCents: 450000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C350", Scac: "VVVH", LegalName: "Carrier 350 Freight Systems", Region: "PDX", InsuranceCents: 462500, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C351", Scac: "TGSK", LegalName: "Carrier 351 Freight Systems", Region: "KCK", InsuranceCents: 475000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C352", Scac: "WHSC", LegalName: "Carrier 352 Freight Systems", Region: "STL", InsuranceCents: 487500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C353", Scac: "NIXD", LegalName: "Carrier 353 Freight Systems", Region: "LAX", InsuranceCents: 500000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C354", Scac: "NLGO", LegalName: "Carrier 354 Freight Systems", Region: "PDX", InsuranceCents: 512500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C355", Scac: "JCUQ", LegalName: "Carrier 355 Freight Systems", Region: "LAX", InsuranceCents: 525000, Bonded: true})
	out = append(out, CarrierRow{CarrierCode: "C356", Scac: "TGFO", LegalName: "Carrier 356 Freight Systems", Region: "KCK", InsuranceCents: 537500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C357", Scac: "MYDV", LegalName: "Carrier 357 Freight Systems", Region: "MEM", InsuranceCents: 550000, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C358", Scac: "JTHL", LegalName: "Carrier 358 Freight Systems", Region: "YVR", InsuranceCents: 562500, Bonded: false})
	out = append(out, CarrierRow{CarrierCode: "C359", Scac: "DMUX", LegalName: "Carrier 359 Freight Systems", Region: "KCK", InsuranceCents: 575000, Bonded: false})
	return out
}
