package tablex

// commodityFill01 appends commodity rows 60..119.
func commodityFill01(out []CommodityRow) []CommodityRow {
	out = append(out, CommodityRow{CommodityCode: "CM-0060", GroupCode: "G00", Description: "Commodity class 0060", HazmatDefault: 6, DensityKgM3: 187, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0061", GroupCode: "G01", Description: "Commodity class 0061", HazmatDefault: 0, DensityKgM3: 327, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0062", GroupCode: "G02", Description: "Commodity class 0062", HazmatDefault: 0, DensityKgM3: 603, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0063", GroupCode: "G03", Description: "Commodity class 0063", HazmatDefault: 0, DensityKgM3: 977, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0064", GroupCode: "G04", Description: "Commodity class 0064", HazmatDefault: 0, DensityKgM3: 344, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0065", GroupCode: "G05", Description: "Commodity class 0065", HazmatDefault: 2, DensityKgM3: 1096, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0066", GroupCode: "G06", Description: "Commodity class 0066", HazmatDefault: 0, DensityKgM3: 784, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0067", GroupCode: "G07", Description: "Commodity class 0067", HazmatDefault: 0, DensityKgM3: 1497, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0068", GroupCode: "G08", Description: "Commodity class 0068", HazmatDefault: 0, DensityKgM3: 425, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0069", GroupCode: "G09", Description: "Commodity class 0069", HazmatDefault: 0, DensityKgM3: 1272, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0070", GroupCode: "G10", Description: "Commodity class 0070", HazmatDefault: 7, DensityKgM3: 1490, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0071", GroupCode: "G11", Description: "Commodity class 0071", HazmatDefault: 0, DensityKgM3: 1394, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0072", GroupCode: "G00", Description: "Commodity class 0072", HazmatDefault: 0, DensityKgM3: 1050, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0073", GroupCode: "G01", Description: "Commodity class 0073", HazmatDefault: 0, DensityKgM3: 1247, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0074", GroupCode: "G02", Description: "Commodity class 0074", HazmatDefault: 0, DensityKgM3: 1079, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0075", GroupCode: "G03", Description: "Commodity class 0075", HazmatDefault: 3, DensityKgM3: 716, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0076", GroupCode: "G04", Description: "Commodity class 0076", HazmatDefault: 0, DensityKgM3: 837, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0077", GroupCode: "G05", Description: "Commodity class 0077", HazmatDefault: 0, DensityKgM3: 252, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0078", GroupCode: "G06", Description: "Commodity class 0078", HazmatDefault: 0, DensityKgM3: 1199, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0079", GroupCode: "G07", Description: "Commodity class 0079", HazmatDefault: 0, DensityKgM3: 368, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0080", GroupCode: "G08", Description: "Commodity class 0080", HazmatDefault: 8, DensityKgM3: 279, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0081", GroupCode: "G09", Description: "Commodity class 0081", HazmatDefault: 0, DensityKgM3: 1038, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0082", GroupCode: "G10", Description: "Commodity class 0082", HazmatDefault: 0, DensityKgM3: 377, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0083", GroupCode: "G11", Description: "Commodity class 0083", HazmatDefault: 0, DensityKgM3: 377, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0084", GroupCode: "G00", Description: "Commodity class 0084", HazmatDefault: 0, DensityKgM3: 650, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0085", GroupCode: "G01", Description: "Commodity class 0085", HazmatDefault: 4, DensityKgM3: 454, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0086", GroupCode: "G02", Description: "Commodity class 0086", HazmatDefault: 0, DensityKgM3: 1423, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0087", GroupCode: "G03", Description: "Commodity class 0087", HazmatDefault: 0, DensityKgM3: 1068, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0088", GroupCode: "G04", Description: "Commodity class 0088", HazmatDefault: 0, DensityKgM3: 1278, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0089", GroupCode: "G05", Description: "Commodity class 0089", HazmatDefault: 0, DensityKgM3: 1249, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0090", GroupCode: "G06", Description: "Commodity class 0090", HazmatDefault: 0, DensityKgM3: 612, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0091", GroupCode: "G07", Description: "Commodity class 0091", HazmatDefault: 0, DensityKgM3: 1371, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0092", GroupCode: "G08", Description: "Commodity class 0092", HazmatDefault: 0, DensityKgM3: 1436, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0093", GroupCode: "G09", Description: "Commodity class 0093", HazmatDefault: 0, DensityKgM3: 959, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0094", GroupCode: "G10", Description: "Commodity class 0094", HazmatDefault: 0, DensityKgM3: 772, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0095", GroupCode: "G11", Description: "Commodity class 0095", HazmatDefault: 5, DensityKgM3: 556, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0096", GroupCode: "G00", Description: "Commodity class 0096", HazmatDefault: 0, DensityKgM3: 1372, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0097", GroupCode: "G01", Description: "Commodity class 0097", HazmatDefault: 0, DensityKgM3: 465, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0098", GroupCode: "G02", Description: "Commodity class 0098", HazmatDefault: 0, DensityKgM3: 1135, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0099", GroupCode: "G03", Description: "Commodity class 0099", HazmatDefault: 0, DensityKgM3: 807, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0100", GroupCode: "G04", Description: "Commodity class 0100", HazmatDefault: 1, DensityKgM3: 338, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0101", GroupCode: "G05", Description: "Commodity class 0101", HazmatDefault: 0, DensityKgM3: 1440, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0102", GroupCode: "G06", Description: "Commodity class 0102", HazmatDefault: 0, DensityKgM3: 1301, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0103", GroupCode: "G07", Description: "Commodity class 0103", HazmatDefault: 0, DensityKgM3: 385, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0104", GroupCode: "G08", Description: "Commodity class 0104", HazmatDefault: 0, DensityKgM3: 411, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0105", GroupCode: "G09", Description: "Commodity class 0105", HazmatDefault: 6, DensityKgM3: 1453, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0106", GroupCode: "G10", Description: "Commodity class 0106", HazmatDefault: 0, DensityKgM3: 1041, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0107", GroupCode: "G11", Description: "Commodity class 0107", HazmatDefault: 0, DensityKgM3: 1120, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0108", GroupCode: "G00", Description: "Commodity class 0108", HazmatDefault: 0, DensityKgM3: 412, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0109", GroupCode: "G01", Description: "Commodity class 0109", HazmatDefault: 0, DensityKgM3: 737, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0110", GroupCode: "G02", Description: "Commodity class 0110", HazmatDefault: 2, DensityKgM3: 602, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0111", GroupCode: "G03", Description: "Commodity class 0111", HazmatDefault: 0, DensityKgM3: 683, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0112", GroupCode: "G04", Description: "Commodity class 0112", HazmatDefault: 0, DensityKgM3: 529, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0113", GroupCode: "G05", Description: "Commodity class 0113", HazmatDefault: 0, DensityKgM3: 1147, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0114", GroupCode: "G06", Description: "Commodity class 0114", HazmatDefault: 0, DensityKgM3: 151, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0115", GroupCode: "G07", Description: "Commodity class 0115", HazmatDefault: 7, DensityKgM3: 573, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0116", GroupCode: "G08", Description: "Commodity class 0116", HazmatDefault: 0, DensityKgM3: 561, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0117", GroupCode: "G09", Description: "Commodity class 0117", HazmatDefault: 0, DensityKgM3: 1388, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0118", GroupCode: "G10", Description: "Commodity class 0118", HazmatDefault: 0, DensityKgM3: 313, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0119", GroupCode: "G11", Description: "Commodity class 0119", HazmatDefault: 0, DensityKgM3: 1147, Stackable: true})
	return out
}
