package tablex

// commodityFill00 appends commodity rows 0..59.
func commodityFill00(out []CommodityRow) []CommodityRow {
	out = append(out, CommodityRow{CommodityCode: "CM-0000", GroupCode: "G00", Description: "Commodity class 0000", HazmatDefault: 0, DensityKgM3: 192, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0001", GroupCode: "G01", Description: "Commodity class 0001", HazmatDefault: 0, DensityKgM3: 826, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0002", GroupCode: "G02", Description: "Commodity class 0002", HazmatDefault: 0, DensityKgM3: 1401, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0003", GroupCode: "G03", Description: "Commodity class 0003", HazmatDefault: 0, DensityKgM3: 539, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0004", GroupCode: "G04", Description: "Commodity class 0004", HazmatDefault: 0, DensityKgM3: 394, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0005", GroupCode: "G05", Description: "Commodity class 0005", HazmatDefault: 5, DensityKgM3: 419, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0006", GroupCode: "G06", Description: "Commodity class 0006", HazmatDefault: 0, DensityKgM3: 264, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0007", GroupCode: "G07", Description: "Commodity class 0007", HazmatDefault: 0, DensityKgM3: 780, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0008", GroupCode: "G08", Description: "Commodity class 0008", HazmatDefault: 0, DensityKgM3: 1392, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0009", GroupCode: "G09", Description: "Commodity class 0009", HazmatDefault: 0, DensityKgM3: 990, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0010", GroupCode: "G10", Description: "Commodity class 0010", HazmatDefault: 1, DensityKgM3: 467, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0011", GroupCode: "G11", Description: "Commodity class 0011", HazmatDefault: 0, DensityKgM3: 1187, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0012", GroupCode: "G00", Description: "Commodity class 0012", HazmatDefault: 0, DensityKgM3: 1210, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0013", GroupCode: "G01", Description: "Commodity class 0013", HazmatDefault: 0, DensityKgM3: 1456, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0014", GroupCode: "G02", Description: "Commodity class 0014", HazmatDefault: 0, DensityKgM3: 134, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0015", GroupCode: "G03", Description: "Commodity class 0015", HazmatDefault: 6, DensityKgM3: 333, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0016", GroupCode: "G04", Description: "Commodity class 0016", HazmatDefault: 0, DensityKgM3: 442, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0017", GroupCode: "G05", Description: "Commodity class 0017", HazmatDefault: 0, DensityKgM3: 639, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0018", GroupCode: "G06", Description: "Commodity class 0018", HazmatDefault: 0, DensityKgM3: 343, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0019", GroupCode: "G07", Description: "Commodity class 0019", HazmatDefault: 0, DensityKgM3: 1294, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0020", GroupCode: "G08", Description: "Commodity class 0020", HazmatDefault: 2, DensityKgM3: 879, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0021", GroupCode: "G09", Description: "Commodity class 0021", HazmatDefault: 0, DensityKgM3: 703, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0022", GroupCode: "G10", Description: "Commodity class 0022", HazmatDefault: 0, DensityKgM3: 758, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0023", GroupCode: "G11", Description: "Commodity class 0023", HazmatDefault: 0, DensityKgM3: 1191, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0024", GroupCode: "G00", Description: "Commodity class 0024", HazmatDefault: 0, DensityKgM3: 1051, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0025", GroupCode: "G01", Description: "Commodity class 0025", HazmatDefault: 7, DensityKgM3: 338, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0026", GroupCode: "G02", Description: "Commodity class 0026", HazmatDefault: 0, DensityKgM3: 760, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0027", GroupCode: "G03", Description: "Commodity class 0027", HazmatDefault: 0, DensityKgM3: 626, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0028", GroupCode: "G04", Description: "Commodity class 0028", HazmatDefault: 0, DensityKgM3: 1191, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0029", GroupCode: "G05", Description: "Commodity class 0029", HazmatDefault: 0, DensityKgM3: 836, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0030", GroupCode: "G06", Description: "Commodity class 0030", HazmatDefault: 3, DensityKgM3: 405, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0031", GroupCode: "G07", Description: "Commodity class 0031", HazmatDefault: 0, DensityKgM3: 931, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0032", GroupCode: "G08", Description: "Commodity class 0032", HazmatDefault: 0, DensityKgM3: 192, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0033", GroupCode: "G09", Description: "Commodity class 0033", HazmatDefault: 0, DensityKgM3: 1182, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0034", GroupCode: "G10", Description: "Commodity class 0034", HazmatDefault: 0, DensityKgM3: 121, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0035", GroupCode: "G11", Description: "Commodity class 0035", HazmatDefault: 8, DensityKgM3: 1145, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0036", GroupCode: "G00", Description: "Commodity class 0036", HazmatDefault: 0, DensityKgM3: 1001, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0037", GroupCode: "G01", Description: "Commodity class 0037", HazmatDefault: 0, DensityKgM3: 1002, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0038", GroupCode: "G02", Description: "Commodity class 0038", HazmatDefault: 0, DensityKgM3: 1515, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0039", GroupCode: "G03", Description: "Commodity class 0039", HazmatDefault: 0, DensityKgM3: 974, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0040", GroupCode: "G04", Description: "Commodity class 0040", HazmatDefault: 4, DensityKgM3: 1166, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0041", GroupCode: "G05", Description: "Commodity class 0041", HazmatDefault: 0, DensityKgM3: 1182, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0042", GroupCode: "G06", Description: "Commodity class 0042", HazmatDefault: 0, DensityKgM3: 1248, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0043", GroupCode: "G07", Description: "Commodity class 0043", HazmatDefault: 0, DensityKgM3: 1079, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0044", GroupCode: "G08", Description: "Commodity class 0044", HazmatDefault: 0, DensityKgM3: 238, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0045", GroupCode: "G09", Description: "Commodity class 0045", HazmatDefault: 0, DensityKgM3: 1419, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0046", GroupCode: "G10", Description: "Commodity class 0046", HazmatDefault: 0, DensityKgM3: 751, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0047", GroupCode: "G11", Description: "Commodity class 0047", HazmatDefault: 0, DensityKgM3: 995, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0048", GroupCode: "G00", Description: "Commodity class 0048", HazmatDefault: 0, DensityKgM3: 1142, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0049", GroupCode: "G01", Description: "Commodity class 0049", HazmatDefault: 0, DensityKgM3: 1185, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0050", GroupCode: "G02", Description: "Commodity class 0050", HazmatDefault: 5, DensityKgM3: 848, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0051", GroupCode: "G03", Description: "Commodity class 0051", HazmatDefault: 0, DensityKgM3: 1004, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0052", GroupCode: "G04", Description: "Commodity class 0052", HazmatDefault: 0, DensityKgM3: 594, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0053", GroupCode: "G05", Description: "Commodity class 0053", HazmatDefault: 0, DensityKgM3: 498, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0054", GroupCode: "G06", Description: "Commodity class 0054", HazmatDefault: 0, DensityKgM3: 1202, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0055", GroupCode: "G07", Description: "Commodity class 0055", HazmatDefault: 1, DensityKgM3: 384, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0056", GroupCode: "G08", Description: "Commodity class 0056", HazmatDefault: 0, DensityKgM3: 1450, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0057", GroupCode: "G09", Description: "Commodity class 0057", HazmatDefault: 0, DensityKgM3: 441, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0058", GroupCode: "G10", Description: "Commodity class 0058", HazmatDefault: 0, DensityKgM3: 141, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0059", GroupCode: "G11", Description: "Commodity class 0059", HazmatDefault: 0, DensityKgM3: 475, Stackable: true})
	return out
}
