package tablex

// commodityFill03 appends commodity rows 180..239.
func commodityFill03(out []CommodityRow) []CommodityRow {
	out = append(out, CommodityRow{CommodityCode: "CM-0180", GroupCode: "G00", Description: "Commodity class 0180", HazmatDefault: 0, DensityKgM3: 564, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0181", GroupCode: "G01", Description: "Commodity class 0181", HazmatDefault: 0, DensityKgM3: 819, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0182", GroupCode: "G02", Description: "Commodity class 0182", HazmatDefault: 0, DensityKgM3: 1055, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0183", GroupCode: "G03", Description: "Commodity class 0183", HazmatDefault: 0, DensityKgM3: 190, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0184", GroupCode: "G04", Description: "Commodity class 0184", HazmatDefault: 0, DensityKgM3: 644, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0185", GroupCode: "G05", Description: "Commodity class 0185", HazmatDefault: 5, DensityKgM3: 1131, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0186", GroupCode: "G06", Description: "Commodity class 0186", HazmatDefault: 0, DensityKgM3: 771, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0187", GroupCode: "G07", Description: "Commodity class 0187", HazmatDefault: 0, DensityKgM3: 950, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0188", GroupCode: "G08", Description: "Commodity class 0188", HazmatDefault: 0, DensityKgM3: 1392, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0189", GroupCode: "G09", Description: "Commodity class 0189", HazmatDefault: 0, DensityKgM3: 693, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0190", GroupCode: "G10", Description: "Commodity class 0190", HazmatDefault: 1, DensityKgM3: 535, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0191", GroupCode: "G11", Description: "Commodity class 0191", HazmatDefault: 0, DensityKgM3: 407, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0192", GroupCode: "G00", Description: "Commodity class 0192", HazmatDefault: 0, DensityKgM3: 553, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0193", GroupCode: "G01", Description: "Commodity class 0193", HazmatDefault: 0, DensityKgM3: 1341, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0194", GroupCode: "G02", Description: "Commodity class 0194", HazmatDefault: 0, DensityKgM3: 888, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0195", GroupCode: "G03", Description: "Commodity class 0195", HazmatDefault: 6, DensityKgM3: 298, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0196", GroupCode: "G04", Description: "Commodity class 0196", HazmatDefault: 0, DensityKgM3: 1394, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0197", GroupCode: "G05", Description: "Commodity class 0197", HazmatDefault: 0, DensityKgM3: 1253, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0198", GroupCode: "G06", Description: "Commodity class 0198", HazmatDefault: 0, DensityKgM3: 273, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0199", GroupCode: "G07", Description: "Commodity class 0199", HazmatDefault: 0, DensityKgM3: 308, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0200", GroupCode: "G08", Description: "Commodity class 0200", HazmatDefault: 2, DensityKgM3: 1082, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0201", GroupCode: "G09", Description: "Commodity class 0201", HazmatDefault: 0, DensityKgM3: 1059, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0202", GroupCode: "G10", Description: "Commodity class 0202", HazmatDefault: 0, DensityKgM3: 648, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0203", GroupCode: "G11", Description: "Commodity class 0203", HazmatDefault: 0, DensityKgM3: 1463, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0204", GroupCode: "G00", Description: "Commodity class 0204", HazmatDefault: 0, DensityKgM3: 313, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0205", GroupCode: "G01", Description: "Commodity class 0205", HazmatDefault: 7, DensityKgM3: 258, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0206", GroupCode: "G02", Description: "Commodity class 0206", HazmatDefault: 0, DensityKgM3: 1093, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0207", GroupCode: "G03", Description: "Commodity class 0207", HazmatDefault: 0, DensityKgM3: 1506, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0208", GroupCode: "G04", Description: "Commodity class 0208", HazmatDefault: 0, DensityKgM3: 1352, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0209", GroupCode: "G05", Description: "Commodity class 0209", HazmatDefault: 0, DensityKgM3: 1069, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0210", GroupCode: "G06", Description: "Commodity class 0210", HazmatDefault: 3, DensityKgM3: 166, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0211", GroupCode: "G07", Description: "Commodity class 0211", HazmatDefault: 0, DensityKgM3: 186, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0212", GroupCode: "G08", Description: "Commodity class 0212", HazmatDefault: 0, DensityKgM3: 1452, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0213", GroupCode: "G09", Description: "Commodity class 0213", HazmatDefault: 0, DensityKgM3: 354, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0214", GroupCode: "G10", Description: "Commodity class 0214", HazmatDefault: 0, DensityKgM3: 263, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0215", GroupCode: "G11", Description: "Commodity class 0215", HazmatDefault: 8, DensityKgM3: 234, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0216", GroupCode: "G00", Description: "Commodity class 0216", HazmatDefault: 0, DensityKgM3: 672, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0217", GroupCode: "G01", Description: "Commodity class 0217", HazmatDefault: 0, DensityKgM3: 583, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0218", GroupCode: "G02", Description: "Commodity class 0218", HazmatDefault: 0, DensityKgM3: 600, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0219", GroupCode: "G03", Description: "Commodity class 0219", HazmatDefault: 0, DensityKgM3: 970, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0220", GroupCode: "G04", Description: "Commodity class 0220", HazmatDefault: 4, DensityKgM3: 294, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0221", GroupCode: "G05", Description: "Commodity class 0221", HazmatDefault: 0, DensityKgM3: 383, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0222", GroupCode: "G06", Description: "Commodity class 0222", HazmatDefault: 0, DensityKgM3: 776, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0223", GroupCode: "G07", Description: "Commodity class 0223", HazmatDefault: 0, DensityKgM3: 405, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0224", GroupCode: "G08", Description: "Commodity class 0224", HazmatDefault: 0, DensityKgM3: 1259, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0225", GroupCode: "G09", Description: "Commodity class 0225", HazmatDefault: 0, DensityKgM3: 821, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0226", GroupCode: "G10", Description: "Commodity class 0226", HazmatDefault: 0, DensityKgM3: 925, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0227", GroupCode: "G11", Description: "Commodity class 0227", HazmatDefault: 0, DensityKgM3: 208, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0228", GroupCode: "G00", Description: "Commodity class 0228", HazmatDefault: 0, DensityKgM3: 884, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0229", GroupCode: "G01", Description: "Commodity class 0229", HazmatDefault: 0, DensityKgM3: 801, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0230", GroupCode: "G02", Description: "Commodity class 0230", HazmatDefault: 5, DensityKgM3: 880, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0231", GroupCode: "G03", Description: "Commodity class 0231", HazmatDefault: 0, DensityKgM3: 165, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0232", GroupCode: "G04", Description: "Commodity class 0232", HazmatDefault: 0, DensityKgM3: 355, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0233", GroupCode: "G05", Description: "Commodity class 0233", HazmatDefault: 0, DensityKgM3: 541, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0234", GroupCode: "G06", Description: "Commodity class 0234", HazmatDefault: 0, DensityKgM3: 261, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0235", GroupCode: "G07", Description: "Commodity class 0235", HazmatDefault: 1, DensityKgM3: 141, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0236", GroupCode: "G08", Description: "Commodity class 0236", HazmatDefault: 0, DensityKgM3: 1406, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0237", GroupCode: "G09", Description: "Commodity class 0237", HazmatDefault: 0, DensityKgM3: 1216, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0238", GroupCode: "G10", Description: "Commodity class 0238", HazmatDefault: 0, DensityKgM3: 473, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0239", GroupCode: "G11", Description: "Commodity class 0239", HazmatDefault: 0, DensityKgM3: 331, Stackable: true})
	return out
}
