package tablex

// commodityFill15 appends commodity rows 900..959.
func commodityFill15(out []CommodityRow) []CommodityRow {
	out = append(out, CommodityRow{CommodityCode: "CM-0900", GroupCode: "G00", Description: "Commodity class 0900", HazmatDefault: 0, DensityKgM3: 617, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0901", GroupCode: "G01", Description: "Commodity class 0901", HazmatDefault: 0, DensityKgM3: 1166, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0902", GroupCode: "G02", Description: "Commodity class 0902", HazmatDefault: 0, DensityKgM3: 1022, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0903", GroupCode: "G03", Description: "Commodity class 0903", HazmatDefault: 0, DensityKgM3: 1237, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0904", GroupCode: "G04", Description: "Commodity class 0904", HazmatDefault: 0, DensityKgM3: 1145, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0905", GroupCode: "G05", Description: "Commodity class 0905", HazmatDefault: 5, DensityKgM3: 1315, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0906", GroupCode: "G06", Description: "Commodity class 0906", HazmatDefault: 0, DensityKgM3: 1140, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0907", GroupCode: "G07", Description: "Commodity class 0907", HazmatDefault: 0, DensityKgM3: 731, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0908", GroupCode: "G08", Description: "Commodity class 0908", HazmatDefault: 0, DensityKgM3: 146, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0909", GroupCode: "G09", Description: "Commodity class 0909", HazmatDefault: 0, DensityKgM3: 895, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0910", GroupCode: "G10", Description: "Commodity class 0910", HazmatDefault: 1, DensityKgM3: 236, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0911", GroupCode: "G11", Description: "Commodity class 0911", HazmatDefault: 0, DensityKgM3: 573, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0912", GroupCode: "G00", Description: "Commodity class 0912", HazmatDefault: 0, DensityKgM3: 410, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0913", GroupCode: "G01", Description: "Commodity class 0913", HazmatDefault: 0, DensityKgM3: 766, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0914", GroupCode: "G02", Description: "Commodity class 0914", HazmatDefault: 0, DensityKgM3: 1150, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0915", GroupCode: "G03", Description: "Commodity class 0915", HazmatDefault: 6, DensityKgM3: 797, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0916", GroupCode: "G04", Description: "Commodity class 0916", HazmatDefault: 0, DensityKgM3: 316, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0917", GroupCode: "G05", Description: "Commodity class 0917", HazmatDefault: 0, DensityKgM3: 865, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0918", GroupCode: "G06", Description: "Commodity class 0918", HazmatDefault: 0, DensityKgM3: 1206, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0919", GroupCode: "G07", Description: "Commodity class 0919", HazmatDefault: 0, DensityKgM3: 1117, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0920", GroupCode: "G08", Description: "Commodity class 0920", HazmatDefault: 2, DensityKgM3: 1369, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0921", GroupCode: "G09", Description: "Commodity class 0921", HazmatDefault: 0, DensityKgM3: 881, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0922", GroupCode: "G10", Description: "Commodity class 0922", HazmatDefault: 0, DensityKgM3: 1218, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0923", GroupCode: "G11", Description: "Commodity class 0923", HazmatDefault: 0, DensityKgM3: 214, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0924", GroupCode: "G00", Description: "Commodity class 0924", HazmatDefault: 0, DensityKgM3: 1289, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0925", GroupCode: "G01", Description: "Commodity class 0925", HazmatDefault: 7, DensityKgM3: 1183, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0926", GroupCode: "G02", Description: "Commodity class 0926", HazmatDefault: 0, DensityKgM3: 1142, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0927", GroupCode: "G03", Description: "Commodity class 0927", HazmatDefault: 0, DensityKgM3: 514, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0928", GroupCode: "G04", Description: "Commodity class 0928", HazmatDefault: 0, DensityKgM3: 366, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0929", GroupCode: "G05", Description: "Commodity class 0929", HazmatDefault: 0, DensityKgM3: 906, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0930", GroupCode: "G06", Description: "Commodity class 0930", HazmatDefault: 3, DensityKgM3: 1205, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0931", GroupCode: "G07", Description: "Commodity class 0931", HazmatDefault: 0, DensityKgM3: 386, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0932", GroupCode: "G08", Description: "Commodity class 0932", HazmatDefault: 0, DensityKgM3: 400, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0933", GroupCode: "G09", Description: "Commodity class 0933", HazmatDefault: 0, DensityKgM3: 212, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0934", GroupCode: "G10", Description: "Commodity class 0934", HazmatDefault: 0, DensityKgM3: 1167, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0935", GroupCode: "G11", Description: "Commodity class 0935", HazmatDefault: 8, DensityKgM3: 634, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0936", GroupCode: "G00", Description: "Commodity class 0936", HazmatDefault: 0, DensityKgM3: 1298, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0937", GroupCode: "G01", Description: "Commodity class 0937", HazmatDefault: 0, DensityKgM3: 475, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0938", GroupCode: "G02", Description: "Commodity class 0938", HazmatDefault: 0, DensityKgM3: 263, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0939", GroupCode: "G03", Description: "Commodity class 0939", HazmatDefault: 0, DensityKgM3: 766, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0940", GroupCode: "G04", Description: "Commodity class 0940", HazmatDefault: 4, DensityKgM3: 363, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0941", GroupCode: "G05", Description: "Commodity class 0941", HazmatDefault: 0, DensityKgM3: 1276, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0942", GroupCode: "G06", Description: "Commodity class 0942", HazmatDefault: 0, DensityKgM3: 1162, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0943", GroupCode: "G07", Description: "Commodity class 0943", HazmatDefault: 0, DensityKgM3: 550, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0944", GroupCode: "G08", Description: "Commodity class 0944", HazmatDefault: 0, DensityKgM3: 1155, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0945", GroupCode: "G09", Description: "Commodity class 0945", HazmatDefault: 0, DensityKgM3: 861, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0946", GroupCode: "G10", Description: "Commodity class 0946", HazmatDefault: 0, DensityKgM3: 1420, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0947", GroupCode: "G11", Description: "Commodity class 0947", HazmatDefault: 0, DensityKgM3: 1442, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0948", GroupCode: "G00", Description: "Commodity class 0948", HazmatDefault: 0, DensityKgM3: 544, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0949", GroupCode: "G01", Description: "Commodity class 0949", HazmatDefault: 0, DensityKgM3: 738, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0950", GroupCode: "G02", Description: "Commodity class 0950", HazmatDefault: 5, DensityKgM3: 838, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0951", GroupCode: "G03", Description: "Commodity class 0951", HazmatDefault: 0, DensityKgM3: 594, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0952", GroupCode: "G04", Description: "Commodity class 0952", HazmatDefault: 0, DensityKgM3: 636, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0953", GroupCode: "G05", Description: "Commodity class 0953", HazmatDefault: 0, DensityKgM3: 383, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0954", GroupCode: "G06", Description: "Commodity class 0954", HazmatDefault: 0, DensityKgM3: 638, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0955", GroupCode: "G07", Description: "Commodity class 0955", HazmatDefault: 1, DensityKgM3: 578, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0956", GroupCode: "G08", Description: "Commodity class 0956", HazmatDefault: 0, DensityKgM3: 965, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0957", GroupCode: "G09", Description: "Commodity class 0957", HazmatDefault: 0, DensityKgM3: 1378, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0958", GroupCode: "G10", Description: "Commodity class 0958", HazmatDefault: 0, DensityKgM3: 1418, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0959", GroupCode: "G11", Description: "Commodity class 0959", HazmatDefault: 0, DensityKgM3: 659, Stackable: true})
	return out
}
