package tablex

// commodityFill11 appends commodity rows 660..719.
func commodityFill11(out []CommodityRow) []CommodityRow {
	out = append(out, CommodityRow{CommodityCode: "CM-0660", GroupCode: "G00", Description: "Commodity class 0660", HazmatDefault: 3, DensityKgM3: 1119, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0661", GroupCode: "G01", Description: "Commodity class 0661", HazmatDefault: 0, DensityKgM3: 566, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0662", GroupCode: "G02", Description: "Commodity class 0662", HazmatDefault: 0, DensityKgM3: 1103, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0663", GroupCode: "G03", Description: "Commodity class 0663", HazmatDefault: 0, DensityKgM3: 837, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0664", GroupCode: "G04", Description: "Commodity class 0664", HazmatDefault: 0, DensityKgM3: 917, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0665", GroupCode: "G05", Description: "Commodity class 0665", HazmatDefault: 8, DensityKgM3: 617, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0666", GroupCode: "G06", Description: "Commodity class 0666", HazmatDefault: 0, DensityKgM3: 1081, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0667", GroupCode: "G07", Description: "Commodity class 0667", HazmatDefault: 0, DensityKgM3: 267, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0668", GroupCode: "G08", Description: "Commodity class 0668", HazmatDefault: 0, DensityKgM3: 198, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0669", GroupCode: "G09", Description: "Commodity class 0669", HazmatDefault: 0, DensityKgM3: 1056, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0670", GroupCode: "G10", Description: "Commodity class 0670", HazmatDefault: 4, DensityKgM3: 457, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0671", GroupCode: "G11", Description: "Commodity class 0671", HazmatDefault: 0, DensityKgM3: 809, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0672", GroupCode: "G00", Description: "Commodity class 0672", HazmatDefault: 0, DensityKgM3: 1023, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0673", GroupCode: "G01", Description: "Commodity class 0673", HazmatDefault: 0, DensityKgM3: 295, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0674", GroupCode: "G02", Description: "Commodity class 0674", HazmatDefault: 0, DensityKgM3: 623, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0675", GroupCode: "G03", Description: "Commodity class 0675", HazmatDefault: 0, DensityKgM3: 214, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0676", GroupCode: "G04", Description: "Commodity class 0676", HazmatDefault: 0, DensityKgM3: 536, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0677", GroupCode: "G05", Description: "Commodity class 0677", HazmatDefault: 0, DensityKgM3: 1067, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0678", GroupCode: "G06", Description: "Commodity class 0678", HazmatDefault: 0, DensityKgM3: 1227, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0679", GroupCode: "G07", Description: "Commodity class 0679", HazmatDefault: 0, DensityKgM3: 1137, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0680", GroupCode: "G08", Description: "Commodity class 0680", HazmatDefault: 5, DensityKgM3: 608, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0681", GroupCode: "G09", Description: "Commodity class 0681", HazmatDefault: 0, DensityKgM3: 1217, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0682", GroupCode: "G10", Description: "Commodity class 0682", HazmatDefault: 0, DensityKgM3: 630, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0683", GroupCode: "G11", Description: "Commodity class 0683", HazmatDefault: 0, DensityKgM3: 584, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0684", GroupCode: "G00", Description: "Commodity class 0684", HazmatDefault: 0, DensityKgM3: 314, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0685", GroupCode: "G01", Description: "Commodity class 0685", HazmatDefault: 1, DensityKgM3: 1362, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0686", GroupCode: "G02", Description: "Commodity class 0686", HazmatDefault: 0, DensityKgM3: 705, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0687", GroupCode: "G03", Description: "Commodity class 0687", HazmatDefault: 0, DensityKgM3: 1277, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0688", GroupCode: "G04", Description: "Commodity class 0688", HazmatDefault: 0, DensityKgM3: 847, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0689", GroupCode: "G05", Description: "Commodity class 0689", HazmatDefault: 0, DensityKgM3: 604, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0690", GroupCode: "G06", Description: "Commodity class 0690", HazmatDefault: 6, DensityKgM3: 1209, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0691", GroupCode: "G07", Description: "Commodity class 0691", HazmatDefault: 0, DensityKgM3: 938, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0692", GroupCode: "G08", Description: "Commodity class 0692", HazmatDefault: 0, DensityKgM3: 133, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0693", GroupCode: "G09", Description: "Commodity class 0693", HazmatDefault: 0, DensityKgM3: 906, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0694", GroupCode: "G10", Description: "Commodity class 0694", HazmatDefault: 0, DensityKgM3: 945, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0695", GroupCode: "G11", Description: "Commodity class 0695", HazmatDefault: 2, DensityKgM3: 159, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0696", GroupCode: "G00", Description: "Commodity class 0696", HazmatDefault: 0, DensityKgM3: 468, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0697", GroupCode: "G01", Description: "Commodity class 0697", HazmatDefault: 0, DensityKgM3: 1288, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0698", GroupCode: "G02", Description: "Commodity class 0698", HazmatDefault: 0, DensityKgM3: 165, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0699", GroupCode: "G03", Description: "Commodity class 0699", HazmatDefault: 0, DensityKgM3: 185, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0700", GroupCode: "G04", Description: "Commodity class 0700", HazmatDefault: 7, DensityKgM3: 738, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0701", GroupCode: "G05", Description: "Commodity class 0701", HazmatDefault: 0, DensityKgM3: 1449, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0702", GroupCode: "G06", Description: "Commodity class 0702", HazmatDefault: 0, DensityKgM3: 1081, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0703", GroupCode: "G07", Description: "Commodity class 0703", HazmatDefault: 0, DensityKgM3: 1187, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0704", GroupCode: "G08", Description: "Commodity class 0704", HazmatDefault: 0, DensityKgM3: 731, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0705", GroupCode: "G09", Description: "Commodity class 0705", HazmatDefault: 3, DensityKgM3: 542, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0706", GroupCode: "G10", Description: "Commodity class 0706", HazmatDefault: 0, DensityKgM3: 216, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0707", GroupCode: "G11", Description: "Commodity class 0707", HazmatDefault: 0, DensityKgM3: 344, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0708", GroupCode: "G00", Description: "Commodity class 0708", HazmatDefault: 0, DensityKgM3: 173, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0709", GroupCode: "G01", Description: "Commodity class 0709", HazmatDefault: 0, DensityKgM3: 997, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0710", GroupCode: "G02", Description: "Commodity class 0710", HazmatDefault: 8, DensityKgM3: 454, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0711", GroupCode: "G03", Description: "Commodity class 0711", HazmatDefault: 0, DensityKgM3: 583, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0712", GroupCode: "G04", Description: "Commodity class 0712", HazmatDefault: 0, DensityKgM3: 947, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0713", GroupCode: "G05", Description: "Commodity class 0713", HazmatDefault: 0, DensityKgM3: 500, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0714", GroupCode: "G06", Description: "Commodity class 0714", HazmatDefault: 0, DensityKgM3: 1508, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0715", GroupCode: "G07", Description: "Commodity class 0715", HazmatDefault: 4, DensityKgM3: 377, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0716", GroupCode: "G08", Description: "Commodity class 0716", HazmatDefault: 0, DensityKgM3: 1479, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0717", GroupCode: "G09", Description: "Commodity class 0717", HazmatDefault: 0, DensityKgM3: 361, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0718", GroupCode: "G10", Description: "Commodity class 0718", HazmatDefault: 0, DensityKgM3: 1367, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0719", GroupCode: "G11", Description: "Commodity class 0719", HazmatDefault: 0, DensityKgM3: 833, Stackable: true})
	return out
}
