package tablex

// commodityFill02 appends commodity rows 120..179.
func commodityFill02(out []CommodityRow) []CommodityRow {
	out = append(out, CommodityRow{CommodityCode: "CM-0120", GroupCode: "G00", Description: "Commodity class 0120", HazmatDefault: 3, DensityKgM3: 1089, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0121", GroupCode: "G01", Description: "Commodity class 0121", HazmatDefault: 0, DensityKgM3: 799, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0122", GroupCode: "G02", Description: "Commodity class 0122", HazmatDefault: 0, DensityKgM3: 957, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0123", GroupCode: "G03", Description: "Commodity class 0123", HazmatDefault: 0, DensityKgM3: 422, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0124", GroupCode: "G04", Description: "Commodity class 0124", HazmatDefault: 0, DensityKgM3: 337, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0125", GroupCode: "G05", Description: "Commodity class 0125", HazmatDefault: 8, DensityKgM3: 1169, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0126", GroupCode: "G06", Description: "Commodity class 0126", HazmatDefault: 0, DensityKgM3: 805, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0127", GroupCode: "G07", Description: "Commodity class 0127", HazmatDefault: 0, DensityKgM3: 960, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0128", GroupCode: "G08", Description: "Commodity class 0128", HazmatDefault: 0, DensityKgM3: 915, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0129", GroupCode: "G09", Description: "Commodity class 0129", HazmatDefault: 0, DensityKgM3: 829, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0130", GroupCode: "G10", Description: "Commodity class 0130", HazmatDefault: 4, DensityKgM3: 240, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0131", GroupCode: "G11", Description: "Commodity class 0131", HazmatDefault: 0, DensityKgM3: 943, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0132", GroupCode: "G00", Description: "Commodity class 0132", HazmatDefault: 0, DensityKgM3: 1469, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0133", GroupCode: "G01", Description: "Commodity class 0133", HazmatDefault: 0, DensityKgM3: 454, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0134", GroupCode: "G02", Description: "Commodity class 0134", HazmatDefault: 0, DensityKgM3: 1429, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0135", GroupCode: "G03", Description: "Commodity class 0135", HazmatDefault: 0, DensityKgM3: 1304, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0136", GroupCode: "G04", Description: "Commodity class 0136", HazmatDefault: 0, DensityKgM3: 296, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0137", GroupCode: "G05", Description: "Commodity class 0137", HazmatDefault: 0, DensityKgM3: 628, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0138", GroupCode: "G06", Description: "Commodity class 0138", HazmatDefault: 0, DensityKgM3: 1136, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0139", GroupCode: "G07", Description: "Commodity class 0139", HazmatDefault: 0, DensityKgM3: 1516, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0140", GroupCode: "G08", Description: "Commodity class 0140", HazmatDefault: 5, DensityKgM3: 1155, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0141", GroupCode: "G09", Description: "Commodity class 0141", HazmatDefault: 0, DensityKgM3: 592, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0142", GroupCode: "G10", Description: "Commodity class 0142", HazmatDefault: 0, DensityKgM3: 1489, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0143", GroupCode: "G11", Description: "Commodity class 0143", HazmatDefault: 0, DensityKgM3: 278, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0144", GroupCode: "G00", Description: "Commodity class 0144", HazmatDefault: 0, DensityKgM3: 227, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0145", GroupCode: "G01", Description: "Commodity class 0145", HazmatDefault: 1, DensityKgM3: 259, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0146", GroupCode: "G02", Description: "Commodity class 0146", HazmatDefault: 0, DensityKgM3: 430, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0147", GroupCode: "G03", Description: "Commodity class 0147", HazmatDefault: 0, DensityKgM3: 1032, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0148", GroupCode: "G04", Description: "Commodity class 0148", HazmatDefault: 0, DensityKgM3: 136, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0149", GroupCode: "G05", Description: "Commodity class 0149", HazmatDefault: 0, DensityKgM3: 436, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0150", GroupCode: "G06", Description: "Commodity class 0150", HazmatDefault: 6, DensityKgM3: 1319, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0151", GroupCode: "G07", Description: "Commodity class 0151", HazmatDefault: 0, DensityKgM3: 402, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0152", GroupCode: "G08", Description: "Commodity class 0152", HazmatDefault: 0, DensityKgM3: 474, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0153", GroupCode: "G09", Description: "Commodity class 0153", HazmatDefault: 0, DensityKgM3: 185, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0154", GroupCode: "G10", Description: "Commodity class 0154", HazmatDefault: 0, DensityKgM3: 628, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0155", GroupCode: "G11", Description: "Commodity class 0155", HazmatDefault: 2, DensityKgM3: 567, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0156", GroupCode: "G00", Description: "Commodity class 0156", HazmatDefault: 0, DensityKgM3: 1443, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0157", GroupCode: "G01", Description: "Commodity class 0157", HazmatDefault: 0, DensityKgM3: 224, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0158", GroupCode: "G02", Description: "Commodity class 0158", HazmatDefault: 0, DensityKgM3: 1189, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0159", GroupCode: "G03", Description: "Commodity class 0159", HazmatDefault: 0, DensityKgM3: 498, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0160", GroupCode: "G04", Description: "Commodity class 0160", HazmatDefault: 7, DensityKgM3: 1006, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0161", GroupCode: "G05", Description: "Commodity class 0161", HazmatDefault: 0, DensityKgM3: 894, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0162", GroupCode: "G06", Description: "Commodity class 0162", HazmatDefault: 0, DensityKgM3: 735, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0163", GroupCode: "G07", Description: "Commodity class 0163", HazmatDefault: 0, DensityKgM3: 869, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0164", GroupCode: "G08", Description: "Commodity class 0164", HazmatDefault: 0, DensityKgM3: 846, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0165", GroupCode: "G09", Description: "Commodity class 0165", HazmatDefault: 3, DensityKgM3: 1416, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0166", GroupCode: "G10", Description: "Commodity class 0166", HazmatDefault: 0, DensityKgM3: 225, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0167", GroupCode: "G11", Description: "Commodity class 0167", HazmatDefault: 0, DensityKgM3: 349, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0168", GroupCode: "G00", Description: "Commodity class 0168", HazmatDefault: 0, DensityKgM3: 516, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0169", GroupCode: "G01", Description: "Commodity class 0169", HazmatDefault: 0, DensityKgM3: 588, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0170", GroupCode: "G02", Description: "Commodity class 0170", HazmatDefault: 8, DensityKgM3: 1323, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0171", GroupCode: "G03", Description: "Commodity class 0171", HazmatDefault: 0, DensityKgM3: 716, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0172", GroupCode: "G04", Description: "Commodity class 0172", HazmatDefault: 0, DensityKgM3: 438, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0173", GroupCode: "G05", Description: "Commodity class 0173", HazmatDefault: 0, DensityKgM3: 1195, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0174", GroupCode: "G06", Description: "Commodity class 0174", HazmatDefault: 0, DensityKgM3: 1078, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0175", GroupCode: "G07", Description: "Commodity class 0175", HazmatDefault: 4, DensityKgM3: 171, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0176", GroupCode: "G08", Description: "Commodity class 0176", HazmatDefault: 0, DensityKgM3: 750, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0177", GroupCode: "G09", Description: "Commodity class 0177", HazmatDefault: 0, DensityKgM3: 194, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0178", GroupCode: "G10", Description: "Commodity class 0178", HazmatDefault: 0, DensityKgM3: 743, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0179", GroupCode: "G11", Description: "Commodity class 0179", HazmatDefault: 0, DensityKgM3: 219, Stackable: true})
	return out
}
