package tablex

// commodityFill07 appends commodity rows 420..479.
func commodityFill07(out []CommodityRow) []CommodityRow {
	out = append(out, CommodityRow{CommodityCode: "CM-0420", GroupCode: "G00", Description: "Commodity class 0420", HazmatDefault: 6, DensityKgM3: 1362, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0421", GroupCode: "G01", Description: "Commodity class 0421", HazmatDefault: 0, DensityKgM3: 1480, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0422", GroupCode: "G02", Description: "Commodity class 0422", HazmatDefault: 0, DensityKgM3: 1086, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0423", GroupCode: "G03", Description: "Commodity class 0423", HazmatDefault: 0, DensityKgM3: 433, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0424", GroupCode: "G04", Description: "Commodity class 0424", HazmatDefault: 0, DensityKgM3: 703, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0425", GroupCode: "G05", Description: "Commodity class 0425", HazmatDefault: 2, DensityKgM3: 1069, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0426", GroupCode: "G06", Description: "Commodity class 0426", HazmatDefault: 0, DensityKgM3: 132, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0427", GroupCode: "G07", Description: "Commodity class 0427", HazmatDefault: 0, DensityKgM3: 411, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0428", GroupCode: "G08", Description: "Commodity class 0428", HazmatDefault: 0, DensityKgM3: 671, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0429", GroupCode: "G09", Description: "Commodity class 0429", HazmatDefault: 0, DensityKgM3: 532, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0430", GroupCode: "G10", Description: "Commodity class 0430", HazmatDefault: 7, DensityKgM3: 504, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0431", GroupCode: "G11", Description: "Commodity class 0431", HazmatDefault: 0, DensityKgM3: 129, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0432", GroupCode: "G00", Description: "Commodity class 0432", HazmatDefault: 0, DensityKgM3: 446, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0433", GroupCode: "G01", Description: "Commodity class 0433", HazmatDefault: 0, DensityKgM3: 843, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0434", GroupCode: "G02", Description: "Commodity class 0434", HazmatDefault: 0, DensityKgM3: 1365, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0435", GroupCode: "G03", Description: "Commodity class 0435", HazmatDefault: 3, DensityKgM3: 224, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0436", GroupCode: "G04", Description: "Commodity class 0436", HazmatDefault: 0, DensityKgM3: 177, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0437", GroupCode: "G05", Description: "Commodity class 0437", HazmatDefault: 0, DensityKgM3: 939, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0438", GroupCode: "G06", Description: "Commodity class 0438", HazmatDefault: 0, DensityKgM3: 178, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0439", GroupCode: "G07", Description: "Commodity class 0439", HazmatDefault: 0, DensityKgM3: 1145, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0440", GroupCode: "G08", Description: "Commodity class 0440", HazmatDefault: 8, DensityKgM3: 1273, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0441", GroupCode: "G09", Description: "Commodity class 0441", HazmatDefault: 0, DensityKgM3: 546, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0442", GroupCode: "G10", Description: "Commodity class 0442", HazmatDefault: 0, DensityKgM3: 1192, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0443", GroupCode: "G11", Description: "Commodity class 0443", HazmatDefault: 0, DensityKgM3: 1140, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0444", GroupCode: "G00", Description: "Commodity class 0444", HazmatDefault: 0, DensityKgM3: 1496, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0445", GroupCode: "G01", Description: "Commodity class 0445", HazmatDefault: 4, DensityKgM3: 289, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0446", GroupCode: "G02", Description: "Commodity class 0446", HazmatDefault: 0, DensityKgM3: 404, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0447", GroupCode: "G03", Description: "Commodity class 0447", HazmatDefault: 0, DensityKgM3: 1515, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0448", GroupCode: "G04", Description: "Commodity class 0448", HazmatDefault: 0, DensityKgM3: 661, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0449", GroupCode: "G05", Description: "Commodity class 0449", HazmatDefault: 0, DensityKgM3: 157, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0450", GroupCode: "G06", Description: "Commodity class 0450", HazmatDefault: 0, DensityKgM3: 782, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0451", GroupCode: "G07", Description: "Commodity class 0451", HazmatDefault: 0, DensityKgM3: 1295, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0452", GroupCode: "G08", Description: "Commodity class 0452", HazmatDefault: 0, DensityKgM3: 495, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0453", GroupCode: "G09", Description: "Commodity class 0453", HazmatDefault: 0, DensityKgM3: 1095, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0454", GroupCode: "G10", Description: "Commodity class 0454", HazmatDefault: 0, DensityKgM3: 629, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0455", GroupCode: "G11", Description: "Commodity class 0455", HazmatDefault: 5, DensityKgM3: 816, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0456", GroupCode: "G00", Description: "Commodity class 0456", HazmatDefault: 0, DensityKgM3: 1008, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0457", GroupCode: "G01", Description: "Commodity class 0457", HazmatDefault: 0, DensityKgM3: 139, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0458", GroupCode: "G02", Description: "Commodity class 0458", HazmatDefault: 0, DensityKgM3: 1005, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0459", GroupCode: "G03", Description: "Commodity class 0459", HazmatDefault: 0, DensityKgM3: 1199, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0460", GroupCode: "G04", Description: "Commodity class 0460", HazmatDefault: 1, DensityKgM3: 665, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0461", GroupCode: "G05", Description: "Commodity class 0461", HazmatDefault: 0, DensityKgM3: 387, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0462", GroupCode: "G06", Description: "Commodity class 0462", HazmatDefault: 0, DensityKgM3: 790, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0463", GroupCode: "G07", Description: "Commodity class 0463", HazmatDefault: 0, DensityKgM3: 408, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0464", GroupCode: "G08", Description: "Commodity class 0464", HazmatDefault: 0, DensityKgM3: 691, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0465", GroupCode: "G09", Description: "Commodity class 0465", HazmatDefault: 6, DensityKgM3: 1310, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0466", GroupCode: "G10", Description: "Commodity class 0466", HazmatDefault: 0, DensityKgM3: 463, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0467", GroupCode: "G11", Description: "Commodity class 0467", HazmatDefault: 0, DensityKgM3: 1518, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0468", GroupCode: "G00", Description: "Commodity class 0468", HazmatDefault: 0, DensityKgM3: 1038, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0469", GroupCode: "G01", Description: "Commodity class 0469", HazmatDefault: 0, DensityKgM3: 855, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0470", GroupCode: "G02", Description: "Commodity class 0470", HazmatDefault: 2, DensityKgM3: 985, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0471", GroupCode: "G03", Description: "Commodity class 0471", HazmatDefault: 0, DensityKgM3: 1429, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0472", GroupCode: "G04", Description: "Commodity class 0472", HazmatDefault: 0, DensityKgM3: 787, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0473", GroupCode: "G05", Description: "Commodity class 0473", HazmatDefault: 0, DensityKgM3: 1097, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0474", GroupCode: "G06", Description: "Commodity class 0474", HazmatDefault: 0, DensityKgM3: 1455, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0475", GroupCode: "G07", Description: "Commodity class 0475", HazmatDefault: 7, DensityKgM3: 615, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0476", GroupCode: "G08", Description: "Commodity class 0476", HazmatDefault: 0, DensityKgM3: 417, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0477", GroupCode: "G09", Description: "Commodity class 0477", HazmatDefault: 0, DensityKgM3: 1416, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0478", GroupCode: "G10", Description: "Commodity class 0478", HazmatDefault: 0, DensityKgM3: 425, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0479", GroupCode: "G11", Description: "Commodity class 0479", HazmatDefault: 0, DensityKgM3: 912, Stackable: true})
	return out
}
