package tablex

// commodityFill10 appends commodity rows 600..659.
func commodityFill10(out []CommodityRow) []CommodityRow {
	out = append(out, CommodityRow{CommodityCode: "CM-0600", GroupCode: "G00", Description: "Commodity class 0600", HazmatDefault: 6, DensityKgM3: 1394, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0601", GroupCode: "G01", Description: "Commodity class 0601", HazmatDefault: 0, DensityKgM3: 812, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0602", GroupCode: "G02", Description: "Commodity class 0602", HazmatDefault: 0, DensityKgM3: 399, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0603", GroupCode: "G03", Description: "Commodity class 0603", HazmatDefault: 0, DensityKgM3: 1287, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0604", GroupCode: "G04", Description: "Commodity class 0604", HazmatDefault: 0, DensityKgM3: 1261, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0605", GroupCode: "G05", Description: "Commodity class 0605", HazmatDefault: 2, DensityKgM3: 173, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0606", GroupCode: "G06", Description: "Commodity class 0606", HazmatDefault: 0, DensityKgM3: 1015, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0607", GroupCode: "G07", Description: "Commodity class 0607", HazmatDefault: 0, DensityKgM3: 1274, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0608", GroupCode: "G08", Description: "Commodity class 0608", HazmatDefault: 0, DensityKgM3: 1304, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0609", GroupCode: "G09", Description: "Commodity class 0609", HazmatDefault: 0, DensityKgM3: 143, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0610", GroupCode: "G10", Description: "Commodity class 0610", HazmatDefault: 7, DensityKgM3: 1504, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0611", GroupCode: "G11", Description: "Commodity class 0611", HazmatDefault: 0, DensityKgM3: 868, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0612", GroupCode: "G00", Description: "Commodity class 0612", HazmatDefault: 0, DensityKgM3: 1431, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0613", GroupCode: "G01", Description: "Commodity class 0613", HazmatDefault: 0, DensityKgM3: 156, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0614", GroupCode: "G02", Description: "Commodity class 0614", HazmatDefault: 0, DensityKgM3: 797, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0615", GroupCode: "G03", Description: "Commodity class 0615", HazmatDefault: 3, DensityKgM3: 1057, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0616", GroupCode: "G04", Description: "Commodity class 0616", HazmatDefault: 0, DensityKgM3: 910, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0617", GroupCode: "G05", Description: "Commodity class 0617", HazmatDefault: 0, DensityKgM3: 790, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0618", GroupCode: "G06", Description: "Commodity class 0618", HazmatDefault: 0, DensityKgM3: 1500, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0619", GroupCode: "G07", Description: "Commodity class 0619", HazmatDefault: 0, DensityKgM3: 535, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0620", GroupCode: "G08", Description: "Commodity class 0620", HazmatDefault: 8, DensityKgM3: 1262, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0621", GroupCode: "G09", Description: "Commodity class 0621", HazmatDefault: 0, DensityKgM3: 730, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0622", GroupCode: "G10", Description: "Commodity class 0622", HazmatDefault: 0, DensityKgM3: 210, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0623", GroupCode: "G11", Description: "Commodity class 0623", HazmatDefault: 0, DensityKgM3: 343, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0624", GroupCode: "G00", Description: "Commodity class 0624", HazmatDefault: 0, DensityKgM3: 618, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0625", GroupCode: "G01", Description: "Commodity class 0625", HazmatDefault: 4, DensityKgM3: 1117, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0626", GroupCode: "G02", Description: "Commodity class 0626", HazmatDefault: 0, DensityKgM3: 1410, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0627", GroupCode: "G03", Description: "Commodity class 0627", HazmatDefault: 0, DensityKgM3: 508, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0628", GroupCode: "G04", Description: "Commodity class 0628", HazmatDefault: 0, DensityKgM3: 1181, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0629", GroupCode: "G05", Description: "Commodity class 0629", HazmatDefault: 0, DensityKgM3: 1304, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0630", GroupCode: "G06", Description: "Commodity class 0630", HazmatDefault: 0, DensityKgM3: 290, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0631", GroupCode: "G07", Description: "Commodity class 0631", HazmatDefault: 0, DensityKgM3: 1509, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0632", GroupCode: "G08", Description: "Commodity class 0632", HazmatDefault: 0, DensityKgM3: 851, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0633", GroupCode: "G09", Description: "Commodity class 0633", HazmatDefault: 0, DensityKgM3: 1483, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0634", GroupCode: "G10", Description: "Commodity class 0634", HazmatDefault: 0, DensityKgM3: 348, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0635", GroupCode: "G11", Description: "Commodity class 0635", HazmatDefault: 5, DensityKgM3: 695, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0636", GroupCode: "G00", Description: "Commodity class 0636", HazmatDefault: 0, DensityKgM3: 143, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0637", GroupCode: "G01", Description: "Commodity class 0637", HazmatDefault: 0, DensityKgM3: 644, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0638", GroupCode: "G02", Description: "Commodity class 0638", HazmatDefault: 0, DensityKgM3: 895, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0639", GroupCode: "G03", Description: "Commodity class 0639", HazmatDefault: 0, DensityKgM3: 1003, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0640", GroupCode: "G04", Description: "Commodity class 0640", HazmatDefault: 1, DensityKgM3: 1303, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0641", GroupCode: "G05", Description: "Commodity class 0641", HazmatDefault: 0, DensityKgM3: 1246, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0642", GroupCode: "G06", Description: "Commodity class 0642", HazmatDefault: 0, DensityKgM3: 1087, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0643", GroupCode: "G07", Description: "Commodity class 0643", HazmatDefault: 0, DensityKgM3: 1436, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0644", GroupCode: "G08", Description: "Commodity class 0644", HazmatDefault: 0, DensityKgM3: 1154, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0645", GroupCode: "G09", Description: "Commodity class 0645", HazmatDefault: 6, DensityKgM3: 1475, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0646", GroupCode: "G10", Description: "Commodity class 0646", HazmatDefault: 0, DensityKgM3: 383, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0647", GroupCode: "G11", Description: "Commodity class 0647", HazmatDefault: 0, DensityKgM3: 281, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0648", GroupCode: "G00", Description: "Commodity class 0648", HazmatDefault: 0, DensityKgM3: 257, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0649", GroupCode: "G01", Description: "Commodity class 0649", HazmatDefault: 0, DensityKgM3: 633, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0650", GroupCode: "G02", Description: "Commodity class 0650", HazmatDefault: 2, DensityKgM3: 274, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0651", GroupCode: "G03", Description: "Commodity class 0651", HazmatDefault: 0, DensityKgM3: 1518, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0652", GroupCode: "G04", Description: "Commodity class 0652", HazmatDefault: 0, DensityKgM3: 1464, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0653", GroupCode: "G05", Description: "Commodity class 0653", HazmatDefault: 0, DensityKgM3: 779, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0654", GroupCode: "G06", Description: "Commodity class 0654", HazmatDefault: 0, DensityKgM3: 830, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0655", GroupCode: "G07", Description: "Commodity class 0655", HazmatDefault: 7, DensityKgM3: 1391, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0656", GroupCode: "G08", Description: "Commodity class 0656", HazmatDefault: 0, DensityKgM3: 823, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0657", GroupCode: "G09", Description: "Commodity class 0657", HazmatDefault: 0, DensityKgM3: 957, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0658", GroupCode: "G10", Description: "Commodity class 0658", HazmatDefault: 0, DensityKgM3: 1450, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0659", GroupCode: "G11", Description: "Commodity class 0659", HazmatDefault: 0, DensityKgM3: 1451, Stackable: true})
	return out
}
