package tablex

// commodityFill08 appends commodity rows 480..539.
func commodityFill08(out []CommodityRow) []CommodityRow {
	out = append(out, CommodityRow{CommodityCode: "CM-0480", GroupCode: "G00", Description: "Commodity class 0480", HazmatDefault: 3, DensityKgM3: 234, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0481", GroupCode: "G01", Description: "Commodity class 0481", HazmatDefault: 0, DensityKgM3: 631, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0482", GroupCode: "G02", Description: "Commodity class 0482", HazmatDefault: 0, DensityKgM3: 148, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0483", GroupCode: "G03", Description: "Commodity class 0483", HazmatDefault: 0, DensityKgM3: 775, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0484", GroupCode: "G04", Description: "Commodity class 0484", HazmatDefault: 0, DensityKgM3: 393, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0485", GroupCode: "G05", Description: "Commodity class 0485", HazmatDefault: 8, DensityKgM3: 485, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0486", GroupCode: "G06", Description: "Commodity class 0486", HazmatDefault: 0, DensityKgM3: 406, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0487", GroupCode: "G07", Description: "Commodity class 0487", HazmatDefault: 0, DensityKgM3: 1234, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0488", GroupCode: "G08", Description: "Commodity class 0488", HazmatDefault: 0, DensityKgM3: 673, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0489", GroupCode: "G09", Description: "Commodity class 0489", HazmatDefault: 0, DensityKgM3: 1468, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0490", GroupCode: "G10", Description: "Commodity class 0490", HazmatDefault: 4, DensityKgM3: 910, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0491", GroupCode: "G11", Description: "Commodity class 0491", HazmatDefault: 0, DensityKgM3: 353, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0492", GroupCode: "G00", Description: "Commodity class 0492", HazmatDefault: 0, DensityKgM3: 975, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0493", GroupCode: "G01", Description: "Commodity class 0493", HazmatDefault: 0, DensityKgM3: 959, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0494", GroupCode: "G02", Description: "Commodity class 0494", HazmatDefault: 0, DensityKgM3: 282, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0495", GroupCode: "G03", Description: "Commodity class 0495", HazmatDefault: 0, DensityKgM3: 892, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0496", GroupCode: "G04", Description: "Commodity class 0496", HazmatDefault: 0, DensityKgM3: 914, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0497", GroupCode: "G05", Description: "Commodity class 0497", HazmatDefault: 0, DensityKgM3: 482, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0498", GroupCode: "G06", Description: "Commodity class 0498", HazmatDefault: 0, DensityKgM3: 1234, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0499", GroupCode: "G07", Description: "Commodity class 0499", HazmatDefault: 0, DensityKgM3: 1413, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0500", GroupCode: "G08", Description: "Commodity class 0500", HazmatDefault: 5, DensityKgM3: 1375, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0501", GroupCode: "G09", Description: "Commodity class 0501", HazmatDefault: 0, DensityKgM3: 299, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0502", GroupCode: "G10", Description: "Commodity class 0502", HazmatDefault: 0, DensityKgM3: 534, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0503", GroupCode: "G11", Description: "Commodity class 0503", HazmatDefault: 0, DensityKgM3: 726, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0504", GroupCode: "G00", Description: "Commodity class 0504", HazmatDefault: 0, DensityKgM3: 1430, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0505", GroupCode: "G01", Description: "Commodity class 0505", HazmatDefault: 1, DensityKgM3: 262, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0506", GroupCode: "G02", Description: "Commodity class 0506", HazmatDefault: 0, DensityKgM3: 1076, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0507", GroupCode: "G03", Description: "Commodity class 0507", HazmatDefault: 0, DensityKgM3: 194, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0508", GroupCode: "G04", Description: "Commodity class 0508", HazmatDefault: 0, DensityKgM3: 1428, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0509", GroupCode: "G05", Description: "Commodity class 0509", HazmatDefault: 0, DensityKgM3: 807, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0510", GroupCode: "G06", Description: "Commodity class 0510", HazmatDefault: 6, DensityKgM3: 1514, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0511", GroupCode: "G07", Description: "Commodity class 0511", HazmatDefault: 0, DensityKgM3: 630, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0512", GroupCode: "G08", Description: "Commodity class 0512", HazmatDefault: 0, DensityKgM3: 594, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0513", GroupCode: "G09", Description: "Commodity class 0513", HazmatDefault: 0, DensityKgM3: 573, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0514", GroupCode: "G10", Description: "Commodity class 0514", HazmatDefault: 0, DensityKgM3: 1251, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0515", GroupCode: "G11", Description: "Commodity class 0515", HazmatDefault: 2, DensityKgM3: 793, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0516", GroupCode: "G00", Description: "Commodity class 0516", HazmatDefault: 0, DensityKgM3: 710, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0517", GroupCode: "G01", Description: "Commodity class 0517", HazmatDefault: 0, DensityKgM3: 1397, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0518", GroupCode: "G02", Description: "Commodity class 0518", HazmatDefault: 0, DensityKgM3: 380, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0519", GroupCode: "G03", Description: "Commodity class 0519", HazmatDefault: 0, DensityKgM3: 734, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0520", GroupCode: "G04", Description: "Commodity class 0520", HazmatDefault: 7, DensityKgM3: 1231, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0521", GroupCode: "G05", Description: "Commodity class 0521", HazmatDefault: 0, DensityKgM3: 874, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0522", GroupCode: "G06", Description: "Commodity class 0522", HazmatDefault: 0, DensityKgM3: 555, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0523", GroupCode: "G07", Description: "Commodity class 0523", HazmatDefault: 0, DensityKgM3: 197, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0524", GroupCode: "G08", Description: "Commodity class 0524", HazmatDefault: 0, DensityKgM3: 1514, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0525", GroupCode: "G09", Description: "Commodity class 0525", HazmatDefault: 3, DensityKgM3: 1196, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0526", GroupCode: "G10", Description: "Commodity class 0526", HazmatDefault: 0, DensityKgM3: 455, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0527", GroupCode: "G11", Description: "Commodity class 0527", HazmatDefault: 0, DensityKgM3: 810, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0528", GroupCode: "G00", Description: "Commodity class 0528", HazmatDefault: 0, DensityKgM3: 909, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0529", GroupCode: "G01", Description: "Commodity class 0529", HazmatDefault: 0, DensityKgM3: 1335, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0530", GroupCode: "G02", Description: "Commodity class 0530", HazmatDefault: 8, DensityKgM3: 669, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0531", GroupCode: "G03", Description: "Commodity class 0531", HazmatDefault: 0, DensityKgM3: 1312, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0532", GroupCode: "G04", Description: "Commodity class 0532", HazmatDefault: 0, DensityKgM3: 1257, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0533", GroupCode: "G05", Description: "Commodity class 0533", HazmatDefault: 0, DensityKgM3: 184, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0534", GroupCode: "G06", Description: "Commodity class 0534", HazmatDefault: 0, DensityKgM3: 1040, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0535", GroupCode: "G07", Description: "Commodity class 0535", HazmatDefault: 4, DensityKgM3: 719, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0536", GroupCode: "G08", Description: "Commodity class 0536", HazmatDefault: 0, DensityKgM3: 199, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0537", GroupCode: "G09", Description: "Commodity class 0537", HazmatDefault: 0, DensityKgM3: 1142, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0538", GroupCode: "G10", Description: "Commodity class 0538", HazmatDefault: 0, DensityKgM3: 339, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0539", GroupCode: "G11", Description: "Commodity class 0539", HazmatDefault: 0, DensityKgM3: 1514, Stackable: true})
	return out
}
