package tablex

// commodityFill09 appends commodity rows 540..599.
func commodityFill09(out []CommodityRow) []CommodityRow {
	out = append(out, CommodityRow{CommodityCode: "CM-0540", GroupCode: "G00", Description: "Commodity class 0540", HazmatDefault: 0, DensityKgM3: 1078, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0541", GroupCode: "G01", Description: "Commodity class 0541", HazmatDefault: 0, DensityKgM3: 808, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0542", GroupCode: "G02", Description: "Commodity class 0542", HazmatDefault: 0, DensityKgM3: 910, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0543", GroupCode: "G03", Description: "Commodity class 0543", HazmatDefault: 0, DensityKgM3: 846, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0544", GroupCode: "G04", Description: "Commodity class 0544", HazmatDefault: 0, DensityKgM3: 1361, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0545", GroupCode: "G05", Description: "Commodity class 0545", HazmatDefault: 5, DensityKgM3: 1144, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0546", GroupCode: "G06", Description: "Commodity class 0546", HazmatDefault: 0, DensityKgM3: 148, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0547", GroupCode: "G07", Description: "Commodity class 0547", HazmatDefault: 0, DensityKgM3: 271, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0548", GroupCode: "G08", Description: "Commodity class 0548", HazmatDefault: 0, DensityKgM3: 769, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0549", GroupCode: "G09", Description: "Commodity class 0549", HazmatDefault: 0, DensityKgM3: 1473, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0550", GroupCode: "G10", Description: "Commodity class 0550", HazmatDefault: 1, DensityKgM3: 1434, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0551", GroupCode: "G11", Description: "Commodity class 0551", HazmatDefault: 0, DensityKgM3: 1207, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0552", GroupCode: "G00", Description: "Commodity class 0552", HazmatDefault: 0, DensityKgM3: 1450, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0553", GroupCode: "G01", Description: "Commodity class 0553", HazmatDefault: 0, DensityKgM3: 1000, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0554", GroupCode: "G02", Description: "Commodity class 0554", HazmatDefault: 0, DensityKgM3: 1333, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0555", GroupCode: "G03", Description: "Commodity class 0555", HazmatDefault: 6, DensityKgM3: 396, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0556", GroupCode: "G04", Description: "Commodity class 0556", HazmatDefault: 0, DensityKgM3: 263, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0557", GroupCode: "G05", Description: "Commodity class 0557", HazmatDefault: 0, DensityKgM3: 1384, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0558", GroupCode: "G06", Description: "Commodity class 0558", HazmatDefault: 0, DensityKgM3: 1297, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0559", GroupCode: "G07", Description: "Commodity class 0559", HazmatDefault: 0, DensityKgM3: 806, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0560", GroupCode: "G08", Description: "Commodity class 0560", HazmatDefault: 2, DensityKgM3: 1374, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0561", GroupCode: "G09", Description: "Commodity class 0561", HazmatDefault: 0, DensityKgM3: 428, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0562", GroupCode: "G10", Description: "Commodity class 0562", HazmatDefault: 0, DensityKgM3: 238, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0563", GroupCode: "G11", Description: "Commodity class 0563", HazmatDefault: 0, DensityKgM3: 1285, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0564", GroupCode: "G00", Description: "Commodity class 0564", HazmatDefault: 0, DensityKgM3: 1325, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0565", GroupCode: "G01", Description: "Commodity class 0565", HazmatDefault: 7, DensityKgM3: 1514, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0566", GroupCode: "G02", Description: "Commodity class 0566", HazmatDefault: 0, DensityKgM3: 1441, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0567", GroupCode: "G03", Description: "Commodity class 0567", HazmatDefault: 0, DensityKgM3: 519, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0568", GroupCode: "G04", Description: "Commodity class 0568", HazmatDefault: 0, DensityKgM3: 234, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0569", GroupCode: "G05", Description: "Commodity class 0569", HazmatDefault: 0, DensityKgM3: 201, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0570", GroupCode: "G06", Description: "Commodity class 0570", HazmatDefault: 3, DensityKgM3: 753, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0571", GroupCode: "G07", Description: "Commodity class 0571", HazmatDefault: 0, DensityKgM3: 1142, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0572", GroupCode: "G08", Description: "Commodity class 0572", HazmatDefault: 0, DensityKgM3: 919, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0573", GroupCode: "G09", Description: "Commodity class 0573", HazmatDefault: 0, DensityKgM3: 1460, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0574", GroupCode: "G10", Description: "Commodity class 0574", HazmatDefault: 0, DensityKgM3: 488, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0575", GroupCode: "G11", Description: "Commodity class 0575", HazmatDefault: 8, DensityKgM3: 1279, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0576", GroupCode: "G00", Description: "Commodity class 0576", HazmatDefault: 0, DensityKgM3: 538, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0577", GroupCode: "G01", Description: "Commodity class 0577", HazmatDefault: 0, DensityKgM3: 625, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0578", GroupCode: "G02", Description: "Commodity class 0578", HazmatDefault: 0, DensityKgM3: 1370, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0579", GroupCode: "G03", Description: "Commodity class 0579", HazmatDefault: 0, DensityKgM3: 987, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0580", GroupCode: "G04", Description: "Commodity class 0580", HazmatDefault: 4, DensityKgM3: 485, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0581", GroupCode: "G05", Description: "Commodity class 0581", HazmatDefault: 0, DensityKgM3: 1177, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0582", GroupCode: "G06", Description: "Commodity class 0582", HazmatDefault: 0, DensityKgM3: 1256, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0583", GroupCode: "G07", Description: "Commodity class 0583", HazmatDefault: 0, DensityKgM3: 965, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0584", GroupCode: "G08", Description: "Commodity class 0584", HazmatDefault: 0, DensityKgM3: 1269, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0585", GroupCode: "G09", Description: "Commodity class 0585", HazmatDefault: 0, DensityKgM3: 651, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0586", GroupCode: "G10", Description: "Commodity class 0586", HazmatDefault: 0, DensityKgM3: 295, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0587", GroupCode: "G11", Description: "Commodity class 0587", HazmatDefault: 0, DensityKgM3: 570, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0588", GroupCode: "G00", Description: "Commodity class 0588", HazmatDefault: 0, DensityKgM3: 294, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0589", GroupCode: "G01", Description: "Commodity class 0589", HazmatDefault: 0, DensityKgM3: 784, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0590", GroupCode: "G02", Description: "Commodity class 0590", HazmatDefault: 5, DensityKgM3: 155, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0591", GroupCode: "G03", Description: "Commodity class 0591", HazmatDefault: 0, DensityKgM3: 866, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0592", GroupCode: "G04", Description: "Commodity class 0592", HazmatDefault: 0, DensityKgM3: 738, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0593", GroupCode: "G05", Description: "Commodity class 0593", HazmatDefault: 0, DensityKgM3: 377, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0594", GroupCode: "G06", Description: "Commodity class 0594", HazmatDefault: 0, DensityKgM3: 1234, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0595", GroupCode: "G07", Description: "Commodity class 0595", HazmatDefault: 1, DensityKgM3: 504, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0596", GroupCode: "G08", Description: "Commodity class 0596", HazmatDefault: 0, DensityKgM3: 1301, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0597", GroupCode: "G09", Description: "Commodity class 0597", HazmatDefault: 0, DensityKgM3: 381, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0598", GroupCode: "G10", Description: "Commodity class 0598", HazmatDefault: 0, DensityKgM3: 190, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0599", GroupCode: "G11", Description: "Commodity class 0599", HazmatDefault: 0, DensityKgM3: 256, Stackable: true})
	return out
}
