package tablex

// commodityFill05 appends commodity rows 300..359.
func commodityFill05(out []CommodityRow) []CommodityRow {
	out = append(out, CommodityRow{CommodityCode: "CM-0300", GroupCode: "G00", Description: "Commodity class 0300", HazmatDefault: 3, DensityKgM3: 1464, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0301", GroupCode: "G01", Description: "Commodity class 0301", HazmatDefault: 0, DensityKgM3: 268, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0302", GroupCode: "G02", Description: "Commodity class 0302", HazmatDefault: 0, DensityKgM3: 268, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0303", GroupCode: "G03", Description: "Commodity class 0303", HazmatDefault: 0, DensityKgM3: 800, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0304", GroupCode: "G04", Description: "Commodity class 0304", HazmatDefault: 0, DensityKgM3: 1510, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0305", GroupCode: "G05", Description: "Commodity class 0305", HazmatDefault: 8, DensityKgM3: 1156, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0306", GroupCode: "G06", Description: "Commodity class 0306", HazmatDefault: 0, DensityKgM3: 463, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0307", GroupCode: "G07", Description: "Commodity class 0307", HazmatDefault: 0, DensityKgM3: 670, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0308", GroupCode: "G08", Description: "Commodity class 0308", HazmatDefault: 0, DensityKgM3: 614, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0309", GroupCode: "G09", Description: "Commodity class 0309", HazmatDefault: 0, DensityKgM3: 864, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0310", GroupCode: "G10", Description: "Commodity class 0310", HazmatDefault: 4, DensityKgM3: 898, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0311", GroupCode: "G11", Description: "Commodity class 0311", HazmatDefault: 0, DensityKgM3: 1094, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0312", GroupCode: "G00", Description: "Commodity class 0312", HazmatDefault: 0, DensityKgM3: 1256, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0313", GroupCode: "G01", Description: "Commodity class 0313", HazmatDefault: 0, DensityKgM3: 355, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0314", GroupCode: "G02", Description: "Commodity class 0314", HazmatDefault: 0, DensityKgM3: 502, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0315", GroupCode: "G03", Description: "Commodity class 0315", HazmatDefault: 0, DensityKgM3: 884, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0316", GroupCode: "G04", Description: "Commodity class 0316", HazmatDefault: 0, DensityKgM3: 426, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0317", GroupCode: "G05", Description: "Commodity class 0317", HazmatDefault: 0, DensityKgM3: 1221, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0318", GroupCode: "G06", Description: "Commodity class 0318", HazmatDefault: 0, DensityKgM3: 128, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0319", GroupCode: "G07", Description: "Commodity class 0319", HazmatDefault: 0, DensityKgM3: 798, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0320", GroupCode: "G08", Description: "Commodity class 0320", HazmatDefault: 5, DensityKgM3: 665, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0321", GroupCode: "G09", Description: "Commodity class 0321", HazmatDefault: 0, DensityKgM3: 686, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0322", GroupCode: "G10", Description: "Commodity class 0322", HazmatDefault: 0, DensityKgM3: 1246, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0323", GroupCode: "G11", Description: "Commodity class 0323", HazmatDefault: 0, DensityKgM3: 297, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0324", GroupCode: "G00", Description: "Commodity class 0324", HazmatDefault: 0, DensityKgM3: 164, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0325", GroupCode: "G01", Description: "Commodity class 0325", HazmatDefault: 1, DensityKgM3: 679, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0326", GroupCode: "G02", Description: "Commodity class 0326", HazmatDefault: 0, DensityKgM3: 1271, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0327", GroupCode: "G03", Description: "Commodity class 0327", HazmatDefault: 0, DensityKgM3: 614, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0328", GroupCode: "G04", Description: "Commodity class 0328", HazmatDefault: 0, DensityKgM3: 721, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0329", GroupCode: "G05", Description: "Commodity class 0329", HazmatDefault: 0, DensityKgM3: 1368, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0330", GroupCode: "G06", Description: "Commodity class 0330", HazmatDefault: 6, DensityKgM3: 1085, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0331", GroupCode: "G07", Description: "Commodity class 0331", HazmatDefault: 0, DensityKgM3: 1222, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0332", GroupCode: "G08", Description: "Commodity class 0332", HazmatDefault: 0, DensityKgM3: 1435, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0333", GroupCode: "G09", Description: "Commodity class 0333", HazmatDefault: 0, DensityKgM3: 650, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0334", GroupCode: "G10", Description: "Commodity class 0334", HazmatDefault: 0, DensityKgM3: 1317, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0335", GroupCode: "G11", Description: "Commodity class 0335", HazmatDefault: 2, DensityKgM3: 975, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0336", GroupCode: "G00", Description: "Commodity class 0336", HazmatDefault: 0, DensityKgM3: 929, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0337", GroupCode: "G01", Description: "Commodity class 0337", HazmatDefault: 0, DensityKgM3: 1428, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0338", GroupCode: "G02", Description: "Commodity class 0338", HazmatDefault: 0, DensityKgM3: 481, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0339", GroupCode: "G03", Description: "Commodity class 0339", HazmatDefault: 0, DensityKgM3: 420, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0340", GroupCode: "G04", Description: "Commodity class 0340", HazmatDefault: 7, DensityKgM3: 742, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0341", GroupCode: "G05", Description: "Commodity class 0341", HazmatDefault: 0, DensityKgM3: 915, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0342", GroupCode: "G06", Description: "Commodity class 0342", HazmatDefault: 0, DensityKgM3: 605, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0343", GroupCode: "G07", Description: "Commodity class 0343", HazmatDefault: 0, DensityKgM3: 927, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0344", GroupCode: "G08", Description: "Commodity class 0344", HazmatDefault: 0, DensityKgM3: 1072, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0345", GroupCode: "G09", Description: "Commodity class 0345", HazmatDefault: 3, DensityKgM3: 1383, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0346", GroupCode: "G10", Description: "Commodity class 0346", HazmatDefault: 0, DensityKgM3: 718, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0347", GroupCode: "G11", Description: "Commodity class 0347", HazmatDefault: 0, DensityKgM3: 1024, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0348", GroupCode: "G00", Description: "Commodity class 0348", HazmatDefault: 0, DensityKgM3: 255, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0349", GroupCode: "G01", Description: "Commodity class 0349", HazmatDefault: 0, DensityKgM3: 1130, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0350", GroupCode: "G02", Description: "Commodity class 0350", HazmatDefault: 8, DensityKgM3: 651, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0351", GroupCode: "G03", Description: "Commodity class 0351", HazmatDefault: 0, DensityKgM3: 720, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0352", GroupCode: "G04", Description: "Commodity class 0352", HazmatDefault: 0, DensityKgM3: 400, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0353", GroupCode: "G05", Description: "Commodity class 0353", HazmatDefault: 0, DensityKgM3: 730, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0354", GroupCode: "G06", Description: "Commodity class 0354", HazmatDefault: 0, DensityKgM3: 446, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0355", GroupCode: "G07", Description: "Commodity class 0355", HazmatDefault: 4, DensityKgM3: 249, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0356", GroupCode: "G08", Description: "Commodity class 0356", HazmatDefault: 0, DensityKgM3: 775, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0357", GroupCode: "G09", Description: "Commodity class 0357", HazmatDefault: 0, DensityKgM3: 495, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0358", GroupCode: "G10", Description: "Commodity class 0358", HazmatDefault: 0, DensityKgM3: 1149, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0359", GroupCode: "G11", Description: "Commodity class 0359", HazmatDefault: 0, DensityKgM3: 1430, Stackable: true})
	return out
}
