package tablex

// commodityFill16 appends commodity rows 960..1019.
func commodityFill16(out []CommodityRow) []CommodityRow {
	out = append(out, CommodityRow{CommodityCode: "CM-0960", GroupCode: "G00", Description: "Commodity class 0960", HazmatDefault: 6, DensityKgM3: 1186, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0961", GroupCode: "G01", Description: "Commodity class 0961", HazmatDefault: 0, DensityKgM3: 786, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0962", GroupCode: "G02", Description: "Commodity class 0962", HazmatDefault: 0, DensityKgM3: 1304, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0963", GroupCode: "G03", Description: "Commodity class 0963", HazmatDefault: 0, DensityKgM3: 683, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0964", GroupCode: "G04", Description: "Commodity class 0964", HazmatDefault: 0, DensityKgM3: 1478, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0965", GroupCode: "G05", Description: "Commodity class 0965", HazmatDefault: 2, DensityKgM3: 851, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0966", GroupCode: "G06", Description: "Commodity class 0966", HazmatDefault: 0, DensityKgM3: 330, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0967", GroupCode: "G07", Description: "Commodity class 0967", HazmatDefault: 0, DensityKgM3: 932, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0968", GroupCode: "G08", Description: "Commodity class 0968", HazmatDefault: 0, DensityKgM3: 567, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0969", GroupCode: "G09", Description: "Commodity class 0969", HazmatDefault: 0, DensityKgM3: 428, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0970", GroupCode: "G10", Description: "Commodity class 0970", HazmatDefault: 7, DensityKgM3: 1456, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0971", GroupCode: "G11", Description: "Commodity class 0971", HazmatDefault: 0, DensityKgM3: 236, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0972", GroupCode: "G00", Description: "Commodity class 0972", HazmatDefault: 0, DensityKgM3: 542, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0973", GroupCode: "G01", Description: "Commodity class 0973", HazmatDefault: 0, DensityKgM3: 1004, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0974", GroupCode: "G02", Description: "Commodity class 0974", HazmatDefault: 0, DensityKgM3: 1075, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0975", GroupCode: "G03", Description: "Commodity class 0975", HazmatDefault: 3, DensityKgM3: 602, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0976", GroupCode: "G04", Description: "Commodity class 0976", HazmatDefault: 0, DensityKgM3: 1291, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0977", GroupCode: "G05", Description: "Commodity class 0977", HazmatDefault: 0, DensityKgM3: 1382, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0978", GroupCode: "G06", Description: "Commodity class 0978", HazmatDefault: 0, DensityKgM3: 571, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0979", GroupCode: "G07", Description: "Commodity class 0979", HazmatDefault: 0, DensityKgM3: 1151, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0980", GroupCode: "G08", Description: "Commodity class 0980", HazmatDefault: 8, DensityKgM3: 1365, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0981", GroupCode: "G09", Description: "Commodity class 0981", HazmatDefault: 0, DensityKgM3: 1371, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0982", GroupCode: "G10", Description: "Commodity class 0982", HazmatDefault: 0, DensityKgM3: 1130, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0983", GroupCode: "G11", Description: "Commodity class 0983", HazmatDefault: 0, DensityKgM3: 1215, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0984", GroupCode: "G00", Description: "Commodity class 0984", HazmatDefault: 0, DensityKgM3: 1015, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0985", GroupCode: "G01", Description: "Commodity class 0985", HazmatDefault: 4, DensityKgM3: 980, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0986", GroupCode: "G02", Description: "Commodity class 0986", HazmatDefault: 0, DensityKgM3: 1404, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0987", GroupCode: "G03", Description: "Commodity class 0987", HazmatDefault: 0, DensityKgM3: 170, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0988", GroupCode: "G04", Description: "Commodity class 0988", HazmatDefault: 0, DensityKgM3: 642, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0989", GroupCode: "G05", Description: "Commodity class 0989", HazmatDefault: 0, DensityKgM3: 486, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0990", GroupCode: "G06", Description: "Commodity class 0990", HazmatDefault: 0, DensityKgM3: 1346, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0991", GroupCode: "G07", Description: "Commodity class 0991", HazmatDefault: 0, DensityKgM3: 311, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0992", GroupCode: "G08", Description: "Commodity class 0992", HazmatDefault: 0, DensityKgM3: 393, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0993", GroupCode: "G09", Description: "Commodity class 0993", HazmatDefault: 0, DensityKgM3: 933, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0994", GroupCode: "G10", Description: "Commodity class 0994", HazmatDefault: 0, DensityKgM3: 1456, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0995", GroupCode: "G11", Description: "Commodity class 0995", HazmatDefault: 5, DensityKgM3: 1337, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0996", GroupCode: "G00", Description: "Commodity class 0996", HazmatDefault: 0, DensityKgM3: 682, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0997", GroupCode: "G01", Description: "Commodity class 0997", HazmatDefault: 0, DensityKgM3: 982, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0998", GroupCode: "G02", Description: "Commodity class 0998", HazmatDefault: 0, DensityKgM3: 1432, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0999", GroupCode: "G03", Description: "Commodity class 0999", HazmatDefault: 0, DensityKgM3: 385, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-1000", GroupCode: "G04", Description: "Commodity class 1000", HazmatDefault: 1, DensityKgM3: 827, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1001", GroupCode: "G05", Description: "Commodity class 1001", HazmatDefault: 0, DensityKgM3: 1431, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1002", GroupCode: "G06", Description: "Commodity class 1002", HazmatDefault: 0, DensityKgM3: 948, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-1003", GroupCode: "G07", Description: "Commodity class 1003", HazmatDefault: 0, DensityKgM3: 393, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1004", GroupCode: "G08", Description: "Commodity class 1004", HazmatDefault: 0, DensityKgM3: 627, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1005", GroupCode: "G09", Description: "Commodity class 1005", HazmatDefault: 6, DensityKgM3: 1167, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-1006", GroupCode: "G10", Description: "Commodity class 1006", HazmatDefault: 0, DensityKgM3: 717, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1007", GroupCode: "G11", Description: "Commodity class 1007", HazmatDefault: 0, DensityKgM3: 750, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1008", GroupCode: "G00", Description: "Commodity class 1008", HazmatDefault: 0, DensityKgM3: 554, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-1009", GroupCode: "G01", Description: "Commodity class 1009", HazmatDefault: 0, DensityKgM3: 407, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1010", GroupCode: "G02", Description: "Commodity class 1010", HazmatDefault: 2, DensityKgM3: 1500, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1011", GroupCode: "G03", Description: "Commodity class 1011", HazmatDefault: 0, DensityKgM3: 434, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-1012", GroupCode: "G04", Description: "Commodity class 1012", HazmatDefault: 0, DensityKgM3: 293, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1013", GroupCode: "G05", Description: "Commodity class 1013", HazmatDefault: 0, DensityKgM3: 324, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1014", GroupCode: "G06", Description: "Commodity class 1014", HazmatDefault: 0, DensityKgM3: 1413, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-1015", GroupCode: "G07", Description: "Commodity class 1015", HazmatDefault: 7, DensityKgM3: 1394, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1016", GroupCode: "G08", Description: "Commodity class 1016", HazmatDefault: 0, DensityKgM3: 953, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1017", GroupCode: "G09", Description: "Commodity class 1017", HazmatDefault: 0, DensityKgM3: 794, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-1018", GroupCode: "G10", Description: "Commodity class 1018", HazmatDefault: 0, DensityKgM3: 810, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1019", GroupCode: "G11", Description: "Commodity class 1019", HazmatDefault: 0, DensityKgM3: 396, Stackable: true})
	return out
}
