package tablex

// commodityFill14 appends commodity rows 840..899.
func commodityFill14(out []CommodityRow) []CommodityRow {
	out = append(out, CommodityRow{CommodityCode: "CM-0840", GroupCode: "G00", Description: "Commodity class 0840", HazmatDefault: 3, DensityKgM3: 186, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0841", GroupCode: "G01", Description: "Commodity class 0841", HazmatDefault: 0, DensityKgM3: 589, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0842", GroupCode: "G02", Description: "Commodity class 0842", HazmatDefault: 0, DensityKgM3: 152, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0843", GroupCode: "G03", Description: "Commodity class 0843", HazmatDefault: 0, DensityKgM3: 794, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0844", GroupCode: "G04", Description: "Commodity class 0844", HazmatDefault: 0, DensityKgM3: 136, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0845", GroupCode: "G05", Description: "Commodity class 0845", HazmatDefault: 8, DensityKgM3: 306, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0846", GroupCode: "G06", Description: "Commodity class 0846", HazmatDefault: 0, DensityKgM3: 753, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0847", GroupCode: "G07", Description: "Commodity class 0847", HazmatDefault: 0, DensityKgM3: 152, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0848", GroupCode: "G08", Description: "Commodity class 0848", HazmatDefault: 0, DensityKgM3: 798, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0849", GroupCode: "G09", Description: "Commodity class 0849", HazmatDefault: 0, DensityKgM3: 170, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0850", GroupCode: "G10", Description: "Commodity class 0850", HazmatDefault: 4, DensityKgM3: 1033, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0851", GroupCode: "G11", Description: "Commodity class 0851", HazmatDefault: 0, DensityKgM3: 1516, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0852", GroupCode: "G00", Description: "Commodity class 0852", HazmatDefault: 0, DensityKgM3: 995, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0853", GroupCode: "G01", Description: "Commodity class 0853", HazmatDefault: 0, DensityKgM3: 920, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0854", GroupCode: "G02", Description: "Commodity class 0854", HazmatDefault: 0, DensityKgM3: 1428, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0855", GroupCode: "G03", Description: "Commodity class 0855", HazmatDefault: 0, DensityKgM3: 315, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0856", GroupCode: "G04", Description: "Commodity class 0856", HazmatDefault: 0, DensityKgM3: 677, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0857", GroupCode: "G05", Description: "Commodity class 0857", HazmatDefault: 0, DensityKgM3: 1447, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0858", GroupCode: "G06", Description: "Commodity class 0858", HazmatDefault: 0, DensityKgM3: 430, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0859", GroupCode: "G07", Description: "Commodity class 0859", HazmatDefault: 0, DensityKgM3: 1137, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0860", GroupCode: "G08", Description: "Commodity class 0860", HazmatDefault: 5, DensityKgM3: 883, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0861", GroupCode: "G09", Description: "Commodity class 0861", HazmatDefault: 0, DensityKgM3: 1121, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0862", GroupCode: "G10", Description: "Commodity class 0862", HazmatDefault: 0, DensityKgM3: 575, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0863", GroupCode: "G11", Description: "Commodity class 0863", HazmatDefault: 0, DensityKgM3: 1174, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0864", GroupCode: "G00", Description: "Commodity class 0864", HazmatDefault: 0, DensityKgM3: 1105, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0865", GroupCode: "G01", Description: "Commodity class 0865", HazmatDefault: 1, DensityKgM3: 1169, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0866", GroupCode: "G02", Description: "Commodity class 0866", HazmatDefault: 0, DensityKgM3: 1381, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0867", GroupCode: "G03", Description: "Commodity class 0867", HazmatDefault: 0, DensityKgM3: 296, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0868", GroupCode: "G04", Description: "Commodity class 0868", HazmatDefault: 0, DensityKgM3: 761, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0869", GroupCode: "G05", Description: "Commodity class 0869", HazmatDefault: 0, DensityKgM3: 849, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0870", GroupCode: "G06", Description: "Commodity class 0870", HazmatDefault: 6, DensityKgM3: 1400, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0871", GroupCode: "G07", Description: "Commodity class 0871", HazmatDefault: 0, DensityKgM3: 333, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0872", GroupCode: "G08", Description: "Commodity class 0872", HazmatDefault: 0, DensityKgM3: 323, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0873", GroupCode: "G09", Description: "Commodity class 0873", HazmatDefault: 0, DensityKgM3: 1366, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0874", GroupCode: "G10", Description: "Commodity class 0874", HazmatDefault: 0, DensityKgM3: 894, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0875", GroupCode: "G11", Description: "Commodity class 0875", HazmatDefault: 2, DensityKgM3: 1397, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0876", GroupCode: "G00", Description: "Commodity class 0876", HazmatDefault: 0, DensityKgM3: 1082, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0877", GroupCode: "G01", Description: "Commodity class 0877", HazmatDefault: 0, DensityKgM3: 966, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0878", GroupCode: "G02", Description: "Commodity class 0878", HazmatDefault: 0, DensityKgM3: 564, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0879", GroupCode: "G03", Description: "Commodity class 0879", HazmatDefault: 0, DensityKgM3: 541, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0880", GroupCode: "G04", Description: "Commodity class 0880", HazmatDefault: 7, DensityKgM3: 446, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0881", GroupCode: "G05", Description: "Commodity class 0881", HazmatDefault: 0, DensityKgM3: 1324, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0882", GroupCode: "G06", Description: "Commodity class 0882", HazmatDefault: 0, DensityKgM3: 1133, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0883", GroupCode: "G07", Description: "Commodity class 0883", HazmatDefault: 0, DensityKgM3: 709, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0884", GroupCode: "G08", Description: "Commodity class 0884", HazmatDefault: 0, DensityKgM3: 194, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0885", GroupCode: "G09", Description: "Commodity class 0885", HazmatDefault: 3, DensityKgM3: 997, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0886", GroupCode: "G10", Description: "Commodity class 0886", HazmatDefault: 0, DensityKgM3: 679, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0887", GroupCode: "G11", Description: "Commodity class 0887", HazmatDefault: 0, DensityKgM3: 456, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0888", GroupCode: "G00", Description: "Commodity class 0888", HazmatDefault: 0, DensityKgM3: 432, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0889", GroupCode: "G01", Description: "Commodity class 0889", HazmatDefault: 0, DensityKgM3: 965, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0890", GroupCode: "G02", Description: "Commodity class 0890", HazmatDefault: 8, DensityKgM3: 441, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0891", GroupCode: "G03", Description: "Commodity class 0891", HazmatDefault: 0, DensityKgM3: 648, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0892", GroupCode: "G04", Description: "Commodity class 0892", HazmatDefault: 0, DensityKgM3: 1286, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0893", GroupCode: "G05", Description: "Commodity class 0893", HazmatDefault: 0, DensityKgM3: 877, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0894", GroupCode: "G06", Description: "Commodity class 0894", HazmatDefault: 0, DensityKgM3: 633, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0895", GroupCode: "G07", Description: "Commodity class 0895", HazmatDefault: 4, DensityKgM3: 951, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0896", GroupCode: "G08", Description: "Commodity class 0896", HazmatDefault: 0, DensityKgM3: 415, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0897", GroupCode: "G09", Description: "Commodity class 0897", HazmatDefault: 0, DensityKgM3: 656, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0898", GroupCode: "G10", Description: "Commodity class 0898", HazmatDefault: 0, DensityKgM3: 642, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0899", GroupCode: "G11", Description: "Commodity class 0899", HazmatDefault: 0, DensityKgM3: 207, Stackable: true})
	return out
}
