package tablex

// commodityFill04 appends commodity rows 240..299.
func commodityFill04(out []CommodityRow) []CommodityRow {
	out = append(out, CommodityRow{CommodityCode: "CM-0240", GroupCode: "G00", Description: "Commodity class 0240", HazmatDefault: 6, DensityKgM3: 130, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0241", GroupCode: "G01", Description: "Commodity class 0241", HazmatDefault: 0, DensityKgM3: 1219, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0242", GroupCode: "G02", Description: "Commodity class 0242", HazmatDefault: 0, DensityKgM3: 806, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0243", GroupCode: "G03", Description: "Commodity class 0243", HazmatDefault: 0, DensityKgM3: 167, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0244", GroupCode: "G04", Description: "Commodity class 0244", HazmatDefault: 0, DensityKgM3: 1291, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0245", GroupCode: "G05", Description: "Commodity class 0245", HazmatDefault: 2, DensityKgM3: 1317, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0246", GroupCode: "G06", Description: "Commodity class 0246", HazmatDefault: 0, DensityKgM3: 460, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0247", GroupCode: "G07", Description: "Commodity class 0247", HazmatDefault: 0, DensityKgM3: 1103, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0248", GroupCode: "G08", Description: "Commodity class 0248", HazmatDefault: 0, DensityKgM3: 1429, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0249", GroupCode: "G09", Description: "Commodity class 0249", HazmatDefault: 0, DensityKgM3: 1009, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0250", GroupCode: "G10", Description: "Commodity class 0250", HazmatDefault: 7, DensityKgM3: 501, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0251", GroupCode: "G11", Description: "Commodity class 0251", HazmatDefault: 0, DensityKgM3: 1225, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0252", GroupCode: "G00", Description: "Commodity class 0252", HazmatDefault: 0, DensityKgM3: 754, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0253", GroupCode: "G01", Description: "Commodity class 0253", HazmatDefault: 0, DensityKgM3: 331, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0254", GroupCode: "G02", Description: "Commodity class 0254", HazmatDefault: 0, DensityKgM3: 1139, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0255", GroupCode: "G03", Description: "Commodity class 0255", HazmatDefault: 3, DensityKgM3: 922, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0256", GroupCode: "G04", Description: "Commodity class 0256", HazmatDefault: 0, DensityKgM3: 1223, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0257", GroupCode: "G05", Description: "Commodity class 0257", HazmatDefault: 0, DensityKgM3: 527, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0258", GroupCode: "G06", Description: "Commodity class 0258", HazmatDefault: 0, DensityKgM3: 258, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0259", GroupCode: "G07", Description: "Commodity class 0259", HazmatDefault: 0, DensityKgM3: 813, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0260", GroupCode: "G08", Description: "Commodity class 0260", HazmatDefault: 8, DensityKgM3: 589, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0261", GroupCode: "G09", Description: "Commodity class 0261", HazmatDefault: 0, DensityKgM3: 710, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0262", GroupCode: "G10", Description: "Commodity class 0262", HazmatDefault: 0, DensityKgM3: 1504, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0263", GroupCode: "G11", Description: "Commodity class 0263", HazmatDefault: 0, DensityKgM3: 887, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0264", GroupCode: "G00", Description: "Commodity class 0264", HazmatDefault: 0, DensityKgM3: 1303, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0265", GroupCode: "G01", Description: "Commodity class 0265", HazmatDefault: 4, DensityKgM3: 503, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0266", GroupCode: "G02", Description: "Commodity class 0266", HazmatDefault: 0, DensityKgM3: 992, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0267", GroupCode: "G03", Description: "Commodity class 0267", HazmatDefault: 0, DensityKgM3: 1331, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0268", GroupCode: "G04", Description: "Commodity class 0268", HazmatDefault: 0, DensityKgM3: 768, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0269", GroupCode: "G05", Description: "Commodity class 0269", HazmatDefault: 0, DensityKgM3: 412, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0270", GroupCode: "G06", Description: "Commodity class 0270", HazmatDefault: 0, DensityKgM3: 1032, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0271", GroupCode: "G07", Description: "Commodity class 0271", HazmatDefault: 0, DensityKgM3: 362, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0272", GroupCode: "G08", Description: "Commodity class 0272", HazmatDefault: 0, DensityKgM3: 845, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0273", GroupCode: "G09", Description: "Commodity class 0273", HazmatDefault: 0, DensityKgM3: 486, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0274", GroupCode: "G10", Description: "Commodity class 0274", HazmatDefault: 0, DensityKgM3: 949, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0275", GroupCode: "G11", Description: "Commodity class 0275", HazmatDefault: 5, DensityKgM3: 983, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0276", GroupCode: "G00", Description: "Commodity class 0276", HazmatDefault: 0, DensityKgM3: 1136, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0277", GroupCode: "G01", Description: "Commodity class 0277", HazmatDefault: 0, DensityKgM3: 1227, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0278", GroupCode: "G02", Description: "Commodity class 0278", HazmatDefault: 0, DensityKgM3: 351, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0279", GroupCode: "G03", Description: "Commodity class 0279", HazmatDefault: 0, DensityKgM3: 190, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0280", GroupCode: "G04", Description: "Commodity class 0280", HazmatDefault: 1, DensityKgM3: 1455, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0281", GroupCode: "G05", Description: "Commodity class 0281", HazmatDefault: 0, DensityKgM3: 175, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0282", GroupCode: "G06", Description: "Commodity class 0282", HazmatDefault: 0, DensityKgM3: 1008, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0283", GroupCode: "G07", Description: "Commodity class 0283", HazmatDefault: 0, DensityKgM3: 1464, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0284", GroupCode: "G08", Description: "Commodity class 0284", HazmatDefault: 0, DensityKgM3: 720, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0285", GroupCode: "G09", Description: "Commodity class 0285", HazmatDefault: 6, DensityKgM3: 246, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0286", GroupCode: "G10", Description: "Commodity class 0286", HazmatDefault: 0, DensityKgM3: 471, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0287", GroupCode: "G11", Description: "Commodity class 0287", HazmatDefault: 0, DensityKgM3: 1165, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0288", GroupCode: "G00", Description: "Commodity class 0288", HazmatDefault: 0, DensityKgM3: 504, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0289", GroupCode: "G01", Description: "Commodity class 0289", HazmatDefault: 0, DensityKgM3: 300, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0290", GroupCode: "G02", Description: "Commodity class 0290", HazmatDefault: 2, DensityKgM3: 721, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0291", GroupCode: "G03", Description: "Commodity class 0291", HazmatDefault: 0, DensityKgM3: 1190, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0292", GroupCode: "G04", Description: "Commodity class 0292", HazmatDefault: 0, DensityKgM3: 292, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0293", GroupCode: "G05", Description: "Commodity class 0293", HazmatDefault: 0, DensityKgM3: 716, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0294", GroupCode: "G06", Description: "Commodity class 0294", HazmatDefault: 0, DensityKgM3: 1044, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0295", GroupCode: "G07", Description: "Commodity class 0295", HazmatDefault: 7, DensityKgM3: 713, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0296", GroupCode: "G08", Description: "Commodity class 0296", HazmatDefault: 0, DensityKgM3: 1385, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0297", GroupCode: "G09", Description: "Commodity class 0297", HazmatDefault: 0, DensityKgM3: 560, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0298", GroupCode: "G10", Description: "Commodity class 0298", HazmatDefault: 0, DensityKgM3: 965, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0299", GroupCode: "G11", Description: "Commodity class 0299", HazmatDefault: 0, DensityKgM3: 977, Stackable: true})
	return out
}
