package tablex

// commodityFill06 appends commodity rows 360..419.
func commodityFill06(out []CommodityRow) []CommodityRow {
	out = append(out, CommodityRow{CommodityCode: "CM-0360", GroupCode: "G00", Description: "Commodity class 0360", HazmatDefault: 0, DensityKgM3: 581, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0361", GroupCode: "G01", Description: "Commodity class 0361", HazmatDefault: 0, DensityKgM3: 1315, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0362", GroupCode: "G02", Description: "Commodity class 0362", HazmatDefault: 0, DensityKgM3: 668, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0363", GroupCode: "G03", Description: "Commodity class 0363", HazmatDefault: 0, DensityKgM3: 501, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0364", GroupCode: "G04", Description: "Commodity class 0364", HazmatDefault: 0, DensityKgM3: 973, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0365", GroupCode: "G05", Description: "Commodity class 0365", HazmatDefault: 5, DensityKgM3: 598, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0366", GroupCode: "G06", Description: "Commodity class 0366", HazmatDefault: 0, DensityKgM3: 508, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0367", GroupCode: "G07", Description: "Commodity class 0367", HazmatDefault: 0, DensityKgM3: 899, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0368", GroupCode: "G08", Description: "Commodity class 0368", HazmatDefault: 0, DensityKgM3: 705, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0369", GroupCode: "G09", Description: "Commodity class 0369", HazmatDefault: 0, DensityKgM3: 124, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0370", GroupCode: "G10", Description: "Commodity class 0370", HazmatDefault: 1, DensityKgM3: 633, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0371", GroupCode: "G11", Description: "Commodity class 0371", HazmatDefault: 0, DensityKgM3: 586, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0372", GroupCode: "G00", Description: "Commodity class 0372", HazmatDefault: 0, DensityKgM3: 958, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0373", GroupCode: "G01", Description: "Commodity class 0373", HazmatDefault: 0, DensityKgM3: 688, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0374", GroupCode: "G02", Description: "Commodity class 0374", HazmatDefault: 0, DensityKgM3: 867, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0375", GroupCode: "G03", Description: "Commodity class 0375", HazmatDefault: 6, DensityKgM3: 647, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0376", GroupCode: "G04", Description: "Commodity class 0376", HazmatDefault: 0, DensityKgM3: 990, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0377", GroupCode: "G05", Description: "Commodity class 0377", HazmatDefault: 0, DensityKgM3: 926, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0378", GroupCode: "G06", Description: "Commodity class 0378", HazmatDefault: 0, DensityKgM3: 655, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0379", GroupCode: "G07", Description: "Commodity class 0379", HazmatDefault: 0, DensityKgM3: 880, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0380", GroupCode: "G08", Description: "Commodity class 0380", HazmatDefault: 2, DensityKgM3: 1033, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0381", GroupCode: "G09", Description: "Commodity class 0381", HazmatDefault: 0, DensityKgM3: 294, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0382", GroupCode: "G10", Description: "Commodity class 0382", HazmatDefault: 0, DensityKgM3: 1241, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0383", GroupCode: "G11", Description: "Commodity class 0383", HazmatDefault: 0, DensityKgM3: 1214, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0384", GroupCode: "G00", Description: "Commodity class 0384", HazmatDefault: 0, DensityKgM3: 372, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0385", GroupCode: "G01", Description: "Commodity class 0385", HazmatDefault: 7, DensityKgM3: 329, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0386", GroupCode: "G02", Description: "Commodity class 0386", HazmatDefault: 0, DensityKgM3: 902, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0387", GroupCode: "G03", Description: "Commodity class 0387", HazmatDefault: 0, DensityKgM3: 1233, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0388", GroupCode: "G04", Description: "Commodity class 0388", HazmatDefault: 0, DensityKgM3: 402, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0389", GroupCode: "G05", Description: "Commodity class 0389", HazmatDefault: 0, DensityKgM3: 378, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0390", GroupCode: "G06", Description: "Commodity class 0390", HazmatDefault: 3, DensityKgM3: 323, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0391", GroupCode: "G07", Description: "Commodity class 0391", HazmatDefault: 0, DensityKgM3: 234, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0392", GroupCode: "G08", Description: "Commodity class 0392", HazmatDefault: 0, DensityKgM3: 927, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0393", GroupCode: "G09", Description: "Commodity class 0393", HazmatDefault: 0, DensityKgM3: 1149, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0394", GroupCode: "G10", Description: "Commodity class 0394", HazmatDefault: 0, DensityKgM3: 1409, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0395", GroupCode: "G11", Description: "Commodity class 0395", HazmatDefault: 8, DensityKgM3: 176, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0396", GroupCode: "G00", Description: "Commodity class 0396", HazmatDefault: 0, DensityKgM3: 327, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0397", GroupCode: "G01", Description: "Commodity class 0397", HazmatDefault: 0, DensityKgM3: 366, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0398", GroupCode: "G02", Description: "Commodity class 0398", HazmatDefault: 0, DensityKgM3: 263, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0399", GroupCode: "G03", Description: "Commodity class 0399", HazmatDefault: 0, DensityKgM3: 1240, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0400", GroupCode: "G04", Description: "Commodity class 0400", HazmatDefault: 4, DensityKgM3: 1049, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0401", GroupCode: "G05", Description: "Commodity class 0401", HazmatDefault: 0, DensityKgM3: 981, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0402", GroupCode: "G06", Description: "Commodity class 0402", HazmatDefault: 0, DensityKgM3: 633, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0403", GroupCode: "G07", Description: "Commodity class 0403", HazmatDefault: 0, DensityKgM3: 168, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0404", GroupCode: "G08", Description: "Commodity class 0404", HazmatDefault: 0, DensityKgM3: 124, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0405", GroupCode: "G09", Description: "Commodity class 0405", HazmatDefault: 0, DensityKgM3: 689, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0406", GroupCode: "G10", Description: "Commodity class 0406", HazmatDefault: 0, DensityKgM3: 1398, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0407", GroupCode: "G11", Description: "Commodity class 0407", HazmatDefault: 0, DensityKgM3: 1518, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0408", GroupCode: "G00", Description: "Commodity class 0408", HazmatDefault: 0, DensityKgM3: 178, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0409", GroupCode: "G01", Description: "Commodity class 0409", HazmatDefault: 0, DensityKgM3: 503, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0410", GroupCode: "G02", Description: "Commodity class 0410", HazmatDefault: 5, DensityKgM3: 487, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0411", GroupCode: "G03", Description: "Commodity class 0411", HazmatDefault: 0, DensityKgM3: 1438, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0412", GroupCode: "G04", Description: "Commodity class 0412", HazmatDefault: 0, DensityKgM3: 386, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0413", GroupCode: "G05", Description: "Commodity class 0413", HazmatDefault: 0, DensityKgM3: 135, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0414", GroupCode: "G06", Description: "Commodity class 0414", HazmatDefault: 0, DensityKgM3: 524, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0415", GroupCode: "G07", Description: "Commodity class 0415", HazmatDefault: 1, DensityKgM3: 150, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0416", GroupCode: "G08", Description: "Commodity class 0416", HazmatDefault: 0, DensityKgM3: 1344, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0417", GroupCode: "G09", Description: "Commodity class 0417", HazmatDefault: 0, DensityKgM3: 646, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0418", GroupCode: "G10", Description: "Commodity class 0418", HazmatDefault: 0, DensityKgM3: 394, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0419", GroupCode: "G11", Description: "Commodity class 0419", HazmatDefault: 0, DensityKgM3: 999, Stackable: true})
	return out
}
