package tablex

// commodityFill17 appends commodity rows 1020..1079.
func commodityFill17(out []CommodityRow) []CommodityRow {
	out = append(out, CommodityRow{CommodityCode: "CM-1020", GroupCode: "G00", Description: "Commodity class 1020", HazmatDefault: 3, DensityKgM3: 324, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-1021", GroupCode: "G01", Description: "Commodity class 1021", HazmatDefault: 0, DensityKgM3: 944, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1022", GroupCode: "G02", Description: "Commodity class 1022", HazmatDefault: 0, DensityKgM3: 1066, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1023", GroupCode: "G03", Description: "Commodity class 1023", HazmatDefault: 0, DensityKgM3: 350, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-1024", GroupCode: "G04", Description: "Commodity class 1024", HazmatDefault: 0, DensityKgM3: 1129, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1025", GroupCode: "G05", Description: "Commodity class 1025", HazmatDefault: 8, DensityKgM3: 478, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1026", GroupCode: "G06", Description: "Commodity class 1026", HazmatDefault: 0, DensityKgM3: 738, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-1027", GroupCode: "G07", Description: "Commodity class 1027", HazmatDefault: 0, DensityKgM3: 197, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1028", GroupCode: "G08", Description: "Commodity class 1028", HazmatDefault: 0, DensityKgM3: 882, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1029", GroupCode: "G09", Description: "Commodity class 1029", HazmatDefault: 0, DensityKgM3: 333, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-1030", GroupCode: "G10", Description: "Commodity class 1030", HazmatDefault: 4, DensityKgM3: 1320, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1031", GroupCode: "G11", Description: "Commodity class 1031", HazmatDefault: 0, DensityKgM3: 1275, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1032", GroupCode: "G00", Description: "Commodity class 1032", HazmatDefault: 0, DensityKgM3: 1444, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-1033", GroupCode: "G01", Description: "Commodity class 1033", HazmatDefault: 0, DensityKgM3: 799, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1034", GroupCode: "G02", Description: "Commodity class 1034", HazmatDefault: 0, DensityKgM3: 1237, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1035", GroupCode: "G03", Description: "Commodity class 1035", HazmatDefault: 0, DensityKgM3: 873, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-1036", GroupCode: "G04", Description: "Commodity class 1036", HazmatDefault: 0, DensityKgM3: 543, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1037", GroupCode: "G05", Description: "Commodity class 1037", HazmatDefault: 0, DensityKgM3: 202, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1038", GroupCode: "G06", Description: "Commodity class 1038", HazmatDefault: 0, DensityKgM3: 618, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-1039", GroupCode: "G07", Description: "Commodity class 1039", HazmatDefault: 0, DensityKgM3: 365, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1040", GroupCode: "G08", Description: "Commodity class 1040", HazmatDefault: 5, DensityKgM3: 980, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1041", GroupCode: "G09", Description: "Commodity class 1041", HazmatDefault: 0, DensityKgM3: 247, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-1042", GroupCode: "G10", Description: "Commodity class 1042", HazmatDefault: 0, DensityKgM3: 616, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1043", GroupCode: "G11", Description: "Commodity class 1043", HazmatDefault: 0, DensityKgM3: 1267, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1044", GroupCode: "G00", Description: "Commodity class 1044", HazmatDefault: 0, DensityKgM3: 162, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-1045", GroupCode: "G01", Description: "Commodity class 1045", HazmatDefault: 1, DensityKgM3: 1251, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1046", GroupCode: "G02", Description: "Commodity class 1046", HazmatDefault: 0, DensityKgM3: 990, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1047", GroupCode: "G03", Description: "Commodity class 1047", HazmatDefault: 0, DensityKgM3: 221, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-1048", GroupCode: "G04", Description: "Commodity class 1048", HazmatDefault: 0, DensityKgM3: 512, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1049", GroupCode: "G05", Description: "Commodity class 1049", HazmatDefault: 0, DensityKgM3: 396, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1050", GroupCode: "G06", Description: "Commodity class 1050", HazmatDefault: 6, DensityKgM3: 506, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-1051", GroupCode: "G07", Description: "Commodity class 1051", HazmatDefault: 0, DensityKgM3: 442, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1052", GroupCode: "G08", Description: "Commodity class 1052", HazmatDefault: 0, DensityKgM3: 1388, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1053", GroupCode: "G09", Description: "Commodity class 1053", HazmatDefault: 0, DensityKgM3: 853, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-1054", GroupCode: "G10", Description: "Commodity class 1054", HazmatDefault: 0, DensityKgM3: 239, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1055", GroupCode: "G11", Description: "Commodity class 1055", HazmatDefault: 2, DensityKgM3: 767, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1056", GroupCode: "G00", Description: "Commodity class 1056", HazmatDefault: 0, DensityKgM3: 776, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-1057", GroupCode: "G01", Description: "Commodity class 1057", HazmatDefault: 0, DensityKgM3: 442, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1058", GroupCode: "G02", Description: "Commodity class 1058", HazmatDefault: 0, DensityKgM3: 1383, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1059", GroupCode: "G03", Description: "Commodity class 1059", HazmatDefault: 0, DensityKgM3: 212, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-1060", GroupCode: "G04", Description: "Commodity class 1060", HazmatDefault: 7, DensityKgM3: 1454, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1061", GroupCode: "G05", Description: "Commodity class 1061", HazmatDefault: 0, DensityKgM3: 490, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1062", GroupCode: "G06", Description: "Commodity class 1062", HazmatDefault: 0, DensityKgM3: 1062, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-1063", GroupCode: "G07", Description: "Commodity class 1063", HazmatDefault: 0, DensityKgM3: 185, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1064", GroupCode: "G08", Description: "Commodity class 1064", HazmatDefault: 0, DensityKgM3: 1292, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1065", GroupCode: "G09", Description: "Commodity class 1065", HazmatDefault: 3, DensityKgM3: 759, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-1066", GroupCode: "G10", Description: "Commodity class 1066", HazmatDefault: 0, DensityKgM3: 442, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1067", GroupCode: "G11", Description: "Commodity class 1067", HazmatDefault: 0, DensityKgM3: 413, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1068", GroupCode: "G00", Description: "Commodity class 1068", HazmatDefault: 0, DensityKgM3: 332, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-1069", GroupCode: "G01", Description: "Commodity class 1069", HazmatDefault: 0, DensityKgM3: 380, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1070", GroupCode: "G02", Description: "Commodity class 1070", HazmatDefault: 8, DensityKgM3: 1168, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1071", GroupCode: "G03", Description: "Commodity class 1071", HazmatDefault: 0, DensityKgM3: 1280, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-1072", GroupCode: "G04", Description: "Commodity class 1072", HazmatDefault: 0, DensityKgM3: 846, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1073", GroupCode: "G05", Description: "Commodity class 1073", HazmatDefault: 0, DensityKgM3: 535, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1074", GroupCode: "G06", Description: "Commodity class 1074", HazmatDefault: 0, DensityKgM3: 578, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-1075", GroupCode: "G07", Description: "Commodity class 1075", HazmatDefault: 4, DensityKgM3: 427, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1076", GroupCode: "G08", Description: "Commodity class 1076", HazmatDefault: 0, DensityKgM3: 654, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1077", GroupCode: "G09", Description: "Commodity class 1077", HazmatDefault: 0, DensityKgM3: 1338, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-1078", GroupCode: "G10", Description: "Commodity class 1078", HazmatDefault: 0, DensityKgM3: 339, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-1079", GroupCode: "G11", Description: "Commodity class 1079", HazmatDefault: 0, DensityKgM3: 185, Stackable: true})
	return out
}
