package tablex

// commodityFill12 appends commodity rows 720..779.
func commodityFill12(out []CommodityRow) []CommodityRow {
	out = append(out, CommodityRow{CommodityCode: "CM-0720", GroupCode: "G00", Description: "Commodity class 0720", HazmatDefault: 0, DensityKgM3: 941, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0721", GroupCode: "G01", Description: "Commodity class 0721", HazmatDefault: 0, DensityKgM3: 856, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0722", GroupCode: "G02", Description: "Commodity class 0722", HazmatDefault: 0, DensityKgM3: 583, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0723", GroupCode: "G03", Description: "Commodity class 0723", HazmatDefault: 0, DensityKgM3: 655, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0724", GroupCode: "G04", Description: "Commodity class 0724", HazmatDefault: 0, DensityKgM3: 589, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0725", GroupCode: "G05", Description: "Commodity class 0725", HazmatDefault: 5, DensityKgM3: 210, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0726", GroupCode: "G06", Description: "Commodity class 0726", HazmatDefault: 0, DensityKgM3: 1456, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0727", GroupCode: "G07", Description: "Commodity class 0727", HazmatDefault: 0, DensityKgM3: 130, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0728", GroupCode: "G08", Description: "Commodity class 0728", HazmatDefault: 0, DensityKgM3: 754, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0729", GroupCode: "G09", Description: "Commodity class 0729", HazmatDefault: 0, DensityKgM3: 225, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0730", GroupCode: "G10", Description: "Commodity class 0730", HazmatDefault: 1, DensityKgM3: 601, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0731", GroupCode: "G11", Description: "Commodity class 0731", HazmatDefault: 0, DensityKgM3: 1458, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0732", GroupCode: "G00", Description: "Commodity class 0732", HazmatDefault: 0, DensityKgM3: 343, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0733", GroupCode: "G01", Description: "Commodity class 0733", HazmatDefault: 0, DensityKgM3: 477, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0734", GroupCode: "G02", Description: "Commodity class 0734", HazmatDefault: 0, DensityKgM3: 826, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0735", GroupCode: "G03", Description: "Commodity class 0735", HazmatDefault: 6, DensityKgM3: 1371, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0736", GroupCode: "G04", Description: "Commodity class 0736", HazmatDefault: 0, DensityKgM3: 824, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0737", GroupCode: "G05", Description: "Commodity class 0737", HazmatDefault: 0, DensityKgM3: 1021, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0738", GroupCode: "G06", Description: "Commodity class 0738", HazmatDefault: 0, DensityKgM3: 1328, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0739", GroupCode: "G07", Description: "Commodity class 0739", HazmatDefault: 0, DensityKgM3: 775, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0740", GroupCode: "G08", Description: "Commodity class 0740", HazmatDefault: 2, DensityKgM3: 965, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0741", GroupCode: "G09", Description: "Commodity class 0741", HazmatDefault: 0, DensityKgM3: 694, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0742", GroupCode: "G10", Description: "Commodity class 0742", HazmatDefault: 0, DensityKgM3: 840, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0743", GroupCode: "G11", Description: "Commodity class 0743", HazmatDefault: 0, DensityKgM3: 137, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0744", GroupCode: "G00", Description: "Commodity class 0744", HazmatDefault: 0, DensityKgM3: 318, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0745", GroupCode: "G01", Description: "Commodity class 0745", HazmatDefault: 7, DensityKgM3: 1358, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0746", GroupCode: "G02", Description: "Commodity class 0746", HazmatDefault: 0, DensityKgM3: 124, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0747", GroupCode: "G03", Description: "Commodity class 0747", HazmatDefault: 0, DensityKgM3: 292, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0748", GroupCode: "G04", Description: "Commodity class 0748", HazmatDefault: 0, DensityKgM3: 1358, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0749", GroupCode: "G05", Description: "Commodity class 0749", HazmatDefault: 0, DensityKgM3: 1178, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0750", GroupCode: "G06", Description: "Commodity class 0750", HazmatDefault: 3, DensityKgM3: 1109, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0751", GroupCode: "G07", Description: "Commodity class 0751", HazmatDefault: 0, DensityKgM3: 733, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0752", GroupCode: "G08", Description: "Commodity class 0752", HazmatDefault: 0, DensityKgM3: 1351, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0753", GroupCode: "G09", Description: "Commodity class 0753", HazmatDefault: 0, DensityKgM3: 587, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0754", GroupCode: "G10", Description: "Commodity class 0754", HazmatDefault: 0, DensityKgM3: 1358, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0755", GroupCode: "G11", Description: "Commodity class 0755", HazmatDefault: 8, DensityKgM3: 627, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0756", GroupCode: "G00", Description: "Commodity class 0756", HazmatDefault: 0, DensityKgM3: 1517, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0757", GroupCode: "G01", Description: "Commodity class 0757", HazmatDefault: 0, DensityKgM3: 346, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0758", GroupCode: "G02", Description: "Commodity class 0758", HazmatDefault: 0, DensityKgM3: 295, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0759", GroupCode: "G03", Description: "Commodity class 0759", HazmatDefault: 0, DensityKgM3: 166, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0760", GroupCode: "G04", Description: "Commodity class 0760", HazmatDefault: 4, DensityKgM3: 1119, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0761", GroupCode: "G05", Description: "Commodity class 0761", HazmatDefault: 0, DensityKgM3: 1000, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0762", GroupCode: "G06", Description: "Commodity class 0762", HazmatDefault: 0, DensityKgM3: 930, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0763", GroupCode: "G07", Description: "Commodity class 0763", HazmatDefault: 0, DensityKgM3: 1093, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0764", GroupCode: "G08", Description: "Commodity class 0764", HazmatDefault: 0, DensityKgM3: 1398, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0765", GroupCode: "G09", Description: "Commodity class 0765", HazmatDefault: 0, DensityKgM3: 1337, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0766", GroupCode: "G10", Description: "Commodity class 0766", HazmatDefault: 0, DensityKgM3: 724, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0767", GroupCode: "G11", Description: "Commodity class 0767", HazmatDefault: 0, DensityKgM3: 510, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0768", GroupCode: "G00", Description: "Commodity class 0768", HazmatDefault: 0, DensityKgM3: 1511, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0769", GroupCode: "G01", Description: "Commodity class 0769", HazmatDefault: 0, DensityKgM3: 1449, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0770", GroupCode: "G02", Description: "Commodity class 0770", HazmatDefault: 5, DensityKgM3: 579, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0771", GroupCode: "G03", Description: "Commodity class 0771", HazmatDefault: 0, DensityKgM3: 176, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0772", GroupCode: "G04", Description: "Commodity class 0772", HazmatDefault: 0, DensityKgM3: 1264, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0773", GroupCode: "G05", Description: "Commodity class 0773", HazmatDefault: 0, DensityKgM3: 603, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0774", GroupCode: "G06", Description: "Commodity class 0774", HazmatDefault: 0, DensityKgM3: 730, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0775", GroupCode: "G07", Description: "Commodity class 0775", HazmatDefault: 1, DensityKgM3: 1369, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0776", GroupCode: "G08", Description: "Commodity class 0776", HazmatDefault: 0, DensityKgM3: 1205, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0777", GroupCode: "G09", Description: "Commodity class 0777", HazmatDefault: 0, DensityKgM3: 577, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0778", GroupCode: "G10", Description: "Commodity class 0778", HazmatDefault: 0, DensityKgM3: 825, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0779", GroupCode: "G11", Description: "Commodity class 0779", HazmatDefault: 0, DensityKgM3: 229, Stackable: true})
	return out
}
