package tablex

// commodityFill13 appends commodity rows 780..839.
func commodityFill13(out []CommodityRow) []CommodityRow {
	out = append(out, CommodityRow{CommodityCode: "CM-0780", GroupCode: "G00", Description: "Commodity class 0780", HazmatDefault: 6, DensityKgM3: 679, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0781", GroupCode: "G01", Description: "Commodity class 0781", HazmatDefault: 0, DensityKgM3: 690, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0782", GroupCode: "G02", Description: "Commodity class 0782", HazmatDefault: 0, DensityKgM3: 647, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0783", GroupCode: "G03", Description: "Commodity class 0783", HazmatDefault: 0, DensityKgM3: 189, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0784", GroupCode: "G04", Description: "Commodity class 0784", HazmatDefault: 0, DensityKgM3: 461, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0785", GroupCode: "G05", Description: "Commodity class 0785", HazmatDefault: 2, DensityKgM3: 894, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0786", GroupCode: "G06", Description: "Commodity class 0786", HazmatDefault: 0, DensityKgM3: 307, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0787", GroupCode: "G07", Description: "Commodity class 0787", HazmatDefault: 0, DensityKgM3: 799, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0788", GroupCode: "G08", Description: "Commodity class 0788", HazmatDefault: 0, DensityKgM3: 1417, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0789", GroupCode: "G09", Description: "Commodity class 0789", HazmatDefault: 0, DensityKgM3: 560, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0790", GroupCode: "G10", Description: "Commodity class 0790", HazmatDefault: 7, DensityKgM3: 822, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0791", GroupCode: "G11", Description: "Commodity class 0791", HazmatDefault: 0, DensityKgM3: 192, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0792", GroupCode: "G00", Description: "Commodity class 0792", HazmatDefault: 0, DensityKgM3: 1444, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0793", GroupCode: "G01", Description: "Commodity class 0793", HazmatDefault: 0, DensityKgM3: 201, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0794", GroupCode: "G02", Description: "Commodity class 0794", HazmatDefault: 0, DensityKgM3: 925, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0795", GroupCode: "G03", Description: "Commodity class 0795", HazmatDefault: 3, DensityKgM3: 584, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0796", GroupCode: "G04", Description: "Commodity class 0796", HazmatDefault: 0, DensityKgM3: 1379, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0797", GroupCode: "G05", Description: "Commodity class 0797", HazmatDefault: 0, DensityKgM3: 281, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0798", GroupCode: "G06", Description: "Commodity class 0798", HazmatDefault: 0, DensityKgM3: 439, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0799", GroupCode: "G07", Description: "Commodity class 0799", HazmatDefault: 0, DensityKgM3: 1416, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0800", GroupCode: "G08", Description: "Commodity class 0800", HazmatDefault: 8, DensityKgM3: 593, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0801", GroupCode: "G09", Description: "Commodity class 0801", HazmatDefault: 0, DensityKgM3: 961, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0802", GroupCode: "G10", Description: "Commodity class 0802", HazmatDefault: 0, DensityKgM3: 554, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0803", GroupCode: "G11", Description: "Commodity class 0803", HazmatDefault: 0, DensityKgM3: 799, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0804", GroupCode: "G00", Description: "Commodity class 0804", HazmatDefault: 0, DensityKgM3: 620, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0805", GroupCode: "G01", Description: "Commodity class 0805", HazmatDefault: 4, DensityKgM3: 944, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0806", GroupCode: "G02", Description: "Commodity class 0806", HazmatDefault: 0, DensityKgM3: 266, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0807", GroupCode: "G03", Description: "Commodity class 0807", HazmatDefault: 0, DensityKgM3: 186, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0808", GroupCode: "G04", Description: "Commodity class 0808", HazmatDefault: 0, DensityKgM3: 1069, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0809", GroupCode: "G05", Description: "Commodity class 0809", HazmatDefault: 0, DensityKgM3: 661, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0810", GroupCode: "G06", Description: "Commodity class 0810", HazmatDefault: 0, DensityKgM3: 798, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0811", GroupCode: "G07", Description: "Commodity class 0811", HazmatDefault: 0, DensityKgM3: 1289, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0812", GroupCode: "G08", Description: "Commodity class 0812", HazmatDefault: 0, DensityKgM3: 1048, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0813", GroupCode: "G09", Description: "Commodity class 0813", HazmatDefault: 0, DensityKgM3: 906, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0814", GroupCode: "G10", Description: "Commodity class 0814", HazmatDefault: 0, DensityKgM3: 1116, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0815", GroupCode: "G11", Description: "Commodity class 0815", HazmatDefault: 5, DensityKgM3: 1064, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0816", GroupCode: "G00", Description: "Commodity class 0816", HazmatDefault: 0, DensityKgM3: 1051, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0817", GroupCode: "G01", Description: "Commodity class 0817", HazmatDefault: 0, DensityKgM3: 907, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0818", GroupCode: "G02", Description: "Commodity class 0818", HazmatDefault: 0, DensityKgM3: 426, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0819", GroupCode: "G03", Description: "Commodity class 0819", HazmatDefault: 0, DensityKgM3: 1173, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0820", GroupCode: "G04", Description: "Commodity class 0820", HazmatDefault: 1, DensityKgM3: 1095, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0821", GroupCode: "G05", Description: "Commodity class 0821", HazmatDefault: 0, DensityKgM3: 401, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0822", GroupCode: "G06", Description: "Commodity class 0822", HazmatDefault: 0, DensityKgM3: 1351, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0823", GroupCode: "G07", Description: "Commodity class 0823", HazmatDefault: 0, DensityKgM3: 1405, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0824", GroupCode: "G08", Description: "Commodity class 0824", HazmatDefault: 0, DensityKgM3: 1362, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0825", GroupCode: "G09", Description: "Commodity class 0825", HazmatDefault: 6, DensityKgM3: 1445, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0826", GroupCode: "G10", Description: "Commodity class 0826", HazmatDefault: 0, DensityKgM3: 1497, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0827", GroupCode: "G11", Description: "Commodity class 0827", HazmatDefault: 0, DensityKgM3: 898, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0828", GroupCode: "G00", Description: "Commodity class 0828", HazmatDefault: 0, DensityKgM3: 1058, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0829", GroupCode: "G01", Description: "Commodity class 0829", HazmatDefault: 0, DensityKgM3: 653, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0830", GroupCode: "G02", Description: "Commodity class 0830", HazmatDefault: 2, DensityKgM3: 377, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0831", GroupCode: "G03", Description: "Commodity class 0831", HazmatDefault: 0, DensityKgM3: 1475, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0832", GroupCode: "G04", Description: "Commodity class 0832", HazmatDefault: 0, DensityKgM3: 1141, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0833", GroupCode: "G05", Description: "Commodity class 0833", HazmatDefault: 0, DensityKgM3: 368, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0834", GroupCode: "G06", Description: "Commodity class 0834", HazmatDefault: 0, DensityKgM3: 582, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0835", GroupCode: "G07", Description: "Commodity class 0835", HazmatDefault: 7, DensityKgM3: 406, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0836", GroupCode: "G08", Description: "Commodity class 0836", HazmatDefault: 0, DensityKgM3: 1384, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0837", GroupCode: "G09", Description: "Commodity class 0837", HazmatDefault: 0, DensityKgM3: 1120, Stackable: false})
	out = append(out, CommodityRow{CommodityCode: "CM-0838", GroupCode: "G10", Description: "Commodity class 0838", HazmatDefault: 0, DensityKgM3: 1338, Stackable: true})
	out = append(out, CommodityRow{CommodityCode: "CM-0839", GroupCode: "G11", Description: "Commodity class 0839", HazmatDefault: 0, DensityKgM3: 489, Stackable: true})
	return out
}
