package tablex

// hazmatFill00 appends hazmat rows 0..59.
func hazmatFill00(out []HazmatRow) []HazmatRow {
	out = append(out, HazmatRow{RuleID: "HZ-00", HazmatClass: 0, MinEscortPriority: 0, SegregationCode: "S00", MaxSlotKg: 4000})
	out = append(out, HazmatRow{RuleID: "HZ-01", HazmatClass: 1, MinEscortPriority: 1, SegregationCode: "S13", MaxSlotKg: 4900})
	out = append(out, HazmatRow{RuleID: "HZ-02", HazmatClass: 2, MinEscortPriority: 2, SegregationCode: "S26", MaxSlotKg: 5800})
	out = append(out, HazmatRow{RuleID: "HZ-03", HazmatClass: 3, MinEscortPriority: 3, SegregationCode: "S32", MaxSlotKg: 6700})
	out = append(out, HazmatRow{RuleID: "HZ-04", HazmatClass: 4, MinEscortPriority: 4, SegregationCode: "S45", MaxSlotKg: 7600})
	out = append(out, HazmatRow{RuleID: "HZ-05", HazmatClass: 5, MinEscortPriority: 0, SegregationCode: "S51", MaxSlotKg: 8500})
	out = append(out, HazmatRow{RuleID: "HZ-06", HazmatClass: 6, MinEscortPriority: 1, SegregationCode: "S64", MaxSlotKg: 9400})
	out = append(out, HazmatRow{RuleID: "HZ-07", HazmatClass: 7, MinEscortPriority: 2, SegregationCode: "S00", MaxSlotKg: 10300})
	out = append(out, HazmatRow{RuleID: "HZ-08", HazmatClass: 8, MinEscortPriority: 3, SegregationCode: "S13", MaxSlotKg: 11200})
	out = append(out, HazmatRow{RuleID: "HZ-09", HazmatClass: 0, MinEscortPriority: 4, SegregationCode: "S26", MaxSlotKg: 12100})
	out = append(out, HazmatRow{RuleID: "HZ-10", HazmatClass: 1, MinEscortPriority: 0, SegregationCode: "S32", MaxSlotKg: 13000})
	out = append(out, HazmatRow{RuleID: "HZ-11", HazmatClass: 2, MinEscortPriority: 1, SegregationCode: "S45", MaxSlotKg: 13900})
	out = append(out, HazmatRow{RuleID: "HZ-12", HazmatClass: 3, MinEscortPriority: 2, SegregationCode: "S51", MaxSlotKg: 14800})
	out = append(out, HazmatRow{RuleID: "HZ-13", HazmatClass: 4, MinEscortPriority: 3, SegregationCode: "S64", MaxSlotKg: 4000})
	out = append(out, HazmatRow{RuleID: "HZ-14", HazmatClass: 5, MinEscortPriority: 4, SegregationCode: "S00", MaxSlotKg: 4900})
	out = append(out, HazmatRow{RuleID: "HZ-15", HazmatClass: 6, MinEscortPriority: 0, SegregationCode: "S13", MaxSlotKg: 5800})
	out = append(out, HazmatRow{RuleID: "HZ-16", HazmatClass: 7, MinEscortPriority: 1, SegregationCode: "S26", MaxSlotKg: 6700})
	out = append(out, HazmatRow{RuleID: "HZ-17", HazmatClass: 8, MinEscortPriority: 2, SegregationCode: "S32", MaxSlotKg: 7600})
	out = append(out, HazmatRow{RuleID: "HZ-18", HazmatClass: 0, MinEscortPriority: 3, SegregationCode: "S45", MaxSlotKg: 8500})
	out = append(out, HazmatRow{RuleID: "HZ-19", HazmatClass: 1, MinEscortPriority: 4, SegregationCode: "S51", MaxSlotKg: 9400})
	out = append(out, HazmatRow{RuleID: "HZ-20", HazmatClass: 2, MinEscortPriority: 0, SegregationCode: "S64", MaxSlotKg: 10300})
	out = append(out, HazmatRow{RuleID: "HZ-21", HazmatClass: 3, MinEscortPriority: 1, SegregationCode: "S00", MaxSlotKg: 11200})
	out = append(out, HazmatRow{RuleID: "HZ-22", HazmatClass: 4, MinEscortPriority: 2, SegregationCode: "S13", MaxSlotKg: 12100})
	out = append(out, HazmatRow{RuleID: "HZ-23", HazmatClass: 5, MinEscortPriority: 3, SegregationCode: "S26", MaxSlotKg: 13000})
	out = append(out, HazmatRow{RuleID: "HZ-24", HazmatClass: 6, MinEscortPriority: 4, SegregationCode: "S32", MaxSlotKg: 13900})
	out = append(out, HazmatRow{RuleID: "HZ-25", HazmatClass: 7, MinEscortPriority: 0, SegregationCode: "S45", MaxSlotKg: 14800})
	out = append(out, HazmatRow{RuleID: "HZ-26", HazmatClass: 8, MinEscortPriority: 1, SegregationCode: "S51", MaxSlotKg: 4000})
	out = append(out, HazmatRow{RuleID: "HZ-27", HazmatClass: 0, MinEscortPriority: 2, SegregationCode: "S64", MaxSlotKg: 4900})
	out = append(out, HazmatRow{RuleID: "HZ-28", HazmatClass: 1, MinEscortPriority: 3, SegregationCode: "S00", MaxSlotKg: 5800})
	out = append(out, HazmatRow{RuleID: "HZ-29", HazmatClass: 2, MinEscortPriority: 4, SegregationCode: "S13", MaxSlotKg: 6700})
	out = append(out, HazmatRow{RuleID: "HZ-30", HazmatClass: 3, MinEscortPriority: 0, SegregationCode: "S26", MaxSlotKg: 7600})
	out = append(out, HazmatRow{RuleID: "HZ-31", HazmatClass: 4, MinEscortPriority: 1, SegregationCode: "S32", MaxSlotKg: 8500})
	out = append(out, HazmatRow{RuleID: "HZ-32", HazmatClass: 5, MinEscortPriority: 2, SegregationCode: "S45", MaxSlotKg: 9400})
	out = append(out, HazmatRow{RuleID: "HZ-33", HazmatClass: 6, MinEscortPriority: 3, SegregationCode: "S51", MaxSlotKg: 10300})
	out = append(out, HazmatRow{RuleID: "HZ-34", HazmatClass: 7, MinEscortPriority: 4, SegregationCode: "S64", MaxSlotKg: 11200})
	out = append(out, HazmatRow{RuleID: "HZ-35", HazmatClass: 8, MinEscortPriority: 0, SegregationCode: "S00", MaxSlotKg: 12100})
	out = append(out, HazmatRow{RuleID: "HZ-36", HazmatClass: 0, MinEscortPriority: 1, SegregationCode: "S13", MaxSlotKg: 13000})
	out = append(out, HazmatRow{RuleID: "HZ-37", HazmatClass: 1, MinEscortPriority: 2, SegregationCode: "S26", MaxSlotKg: 13900})
	out = append(out, HazmatRow{RuleID: "HZ-38", HazmatClass: 2, MinEscortPriority: 3, SegregationCode: "S32", MaxSlotKg: 14800})
	out = append(out, HazmatRow{RuleID: "HZ-39", HazmatClass: 3, MinEscortPriority: 4, SegregationCode: "S45", MaxSlotKg: 4000})
	out = append(out, HazmatRow{RuleID: "HZ-40", HazmatClass: 4, MinEscortPriority: 0, SegregationCode: "S51", MaxSlotKg: 4900})
	out = append(out, HazmatRow{RuleID: "HZ-41", HazmatClass: 5, MinEscortPriority: 1, SegregationCode: "S64", MaxSlotKg: 5800})
	out = append(out, HazmatRow{RuleID: "HZ-42", HazmatClass: 6, MinEscortPriority: 2, SegregationCode: "S00", MaxSlotKg: 6700})
	out = append(out, HazmatRow{RuleID: "HZ-43", HazmatClass: 7, MinEscortPriority: 3, SegregationCode: "S13", MaxSlotKg: 7600})
	out = append(out, HazmatRow{RuleID: "HZ-44", HazmatClass: 8, MinEscortPriority: 4, SegregationCode: "S26", MaxSlotKg: 8500})
	out = append(out, HazmatRow{RuleID: "HZ-45", HazmatClass: 0, MinEscortPriority: 0, SegregationCode: "S32", MaxSlotKg: 9400})
	out = append(out, HazmatRow{RuleID: "HZ-46", HazmatClass: 1, MinEscortPriority: 1, SegregationCode: "S45", MaxSlotKg: 10300})
	out = append(out, HazmatRow{RuleID: "HZ-47", HazmatClass: 2, MinEscortPriority: 2, SegregationCode: "S51", MaxSlotKg: 11200})
	out = append(out, HazmatRow{RuleID: "HZ-48", HazmatClass: 3, MinEscortPriority: 3, SegregationCode: "S64", MaxSlotKg: 12100})
	out = append(out, HazmatRow{RuleID: "HZ-49", HazmatClass: 4, MinEscortPriority: 4, SegregationCode: "S00", MaxSlotKg: 13000})
	out = append(out, HazmatRow{RuleID: "HZ-50", HazmatClass: 5, MinEscortPriority: 0, SegregationCode: "S13", MaxSlotKg: 13900})
	out = append(out, HazmatRow{RuleID: "HZ-51", HazmatClass: 6, MinEscortPriority: 1, SegregationCode: "S26", MaxSlotKg: 14800})
	out = append(out, HazmatRow{RuleID: "HZ-52", HazmatClass: 7, MinEscortPriority: 2, SegregationCode: "S32", MaxSlotKg: 4000})
	out = append(out, HazmatRow{RuleID: "HZ-53", HazmatClass: 8, MinEscortPriority: 3, SegregationCode: "S45", MaxSlotKg: 4900})
	out = append(out, HazmatRow{RuleID: "HZ-54", HazmatClass: 0, MinEscortPriority: 4, SegregationCode: "S51", MaxSlotKg: 5800})
	out = append(out, HazmatRow{RuleID: "HZ-55", HazmatClass: 1, MinEscortPriority: 0, SegregationCode: "S64", MaxSlotKg: 6700})
	out = append(out, HazmatRow{RuleID: "HZ-56", HazmatClass: 2, MinEscortPriority: 1, SegregationCode: "S00", MaxSlotKg: 7600})
	out = append(out, HazmatRow{RuleID: "HZ-57", HazmatClass: 3, MinEscortPriority: 2, SegregationCode: "S13", MaxSlotKg: 8500})
	out = append(out, HazmatRow{RuleID: "HZ-58", HazmatClass: 4, MinEscortPriority: 3, SegregationCode: "S26", MaxSlotKg: 9400})
	out = append(out, HazmatRow{RuleID: "HZ-59", HazmatClass: 5, MinEscortPriority: 4, SegregationCode: "S32", MaxSlotKg: 10300})
	return out
}
