package tablex

// hazmatFill01 appends hazmat rows 60..119.
func hazmatFill01(out []HazmatRow) []HazmatRow {
	out = append(out, HazmatRow{RuleID: "HZ-60", HazmatClass: 6, MinEscortPriority: 0, SegregationCode: "S45", MaxSlotKg: 11200})
	out = append(out, HazmatRow{RuleID: "HZ-61", HazmatClass: 7, MinEscortPriority: 1, SegregationCode: "S51", MaxSlotKg: 12100})
	out = append(out, HazmatRow{RuleID: "HZ-62", HazmatClass: 8, MinEscortPriority: 2, SegregationCode: "S64", MaxSlotKg: 13000})
	out = append(out, HazmatRow{RuleID: "HZ-63", HazmatClass: 0, MinEscortPriority: 3, SegregationCode: "S00", MaxSlotKg: 13900})
	out = append(out, HazmatRow{RuleID: "HZ-64", HazmatClass: 1, MinEscortPriority: 4, SegregationCode: "S13", MaxSlotKg: 14800})
	out = append(out, HazmatRow{RuleID: "HZ-65", HazmatClass: 2, MinEscortPriority: 0, SegregationCode: "S26", MaxSlotKg: 4000})
	out = append(out, HazmatRow{RuleID: "HZ-66", HazmatClass: 3, MinEscortPriority: 1, SegregationCode: "S32", MaxSlotKg: 4900})
	out = append(out, HazmatRow{RuleID: "HZ-67", HazmatClass: 4, MinEscortPriority: 2, SegregationCode: "S45", MaxSlotKg: 5800})
	out = append(out, HazmatRow{RuleID: "HZ-68", HazmatClass: 5, MinEscortPriority: 3, SegregationCode: "S51", MaxSlotKg: 6700})
	out = append(out, HazmatRow{RuleID: "HZ-69", HazmatClass: 6, MinEscortPriority: 4, SegregationCode: "S64", MaxSlotKg: 7600})
	out = append(out, HazmatRow{RuleID: "HZ-70", HazmatClass: 7, MinEscortPriority: 0, SegregationCode: "S00", MaxSlotKg: 8500})
	out = append(out, HazmatRow{RuleID: "HZ-71", HazmatClass: 8, MinEscortPriority: 1, SegregationCode: "S13", MaxSlotKg: 9400})
	out = append(out, HazmatRow{RuleID: "HZ-72", HazmatClass: 0, MinEscortPriority: 2, SegregationCode: "S26", MaxSlotKg: 10300})
	out = append(out, HazmatRow{RuleID: "HZ-73", HazmatClass: 1, MinEscortPriority: 3, SegregationCode: "S32", MaxSlotKg: 11200})
	out = append(out, HazmatRow{RuleID: "HZ-74", HazmatClass: 2, MinEscortPriority: 4, SegregationCode: "S45", MaxSlotKg: 12100})
	out = append(out, HazmatRow{RuleID: "HZ-75", HazmatClass: 3, MinEscortPriority: 0, SegregationCode: "S51", MaxSlotKg: 13000})
	out = append(out, HazmatRow{RuleID: "HZ-76", HazmatClass: 4, MinEscortPriority: 1, SegregationCode: "S64", MaxSlotKg: 13900})
	out = append(out, HazmatRow{RuleID: "HZ-77", HazmatClass: 5, MinEscortPriority: 2, SegregationCode: "S00", MaxSlotKg: 14800})
	out = append(out, HazmatRow{RuleID: "HZ-78", HazmatClass: 6, MinEscortPriority: 3, SegregationCode: "S13", MaxSlotKg: 4000})
	out = append(out, HazmatRow{RuleID: "HZ-79", HazmatClass: 7, MinEscortPriority: 4, SegregationCode: "S26", MaxSlotKg: 4900})
	out = append(out, HazmatRow{RuleID: "HZ-80", HazmatClass: 8, MinEscortPriority: 0, SegregationCode: "S32", MaxSlotKg: 5800})
	out = append(out, HazmatRow{RuleID: "HZ-81", HazmatClass: 0, MinEscortPriority: 1, SegregationCode: "S45", MaxSlotKg: 6700})
	out = append(out, HazmatRow{RuleID: "HZ-82", HazmatClass: 1, MinEscortPriority: 2, SegregationCode: "S51", MaxSlotKg: 7600})
	out = append(out, HazmatRow{RuleID: "HZ-83", HazmatClass: 2, MinEscortPriority: 3, SegregationCode: "S64", MaxSlotKg: 8500})
	out = append(out, HazmatRow{RuleID: "HZ-84", HazmatClass: 3, MinEscortPriority: 4, SegregationCode: "S00", MaxSlotKg: 9400})
	out = append(out, HazmatRow{RuleID: "HZ-85", HazmatClass: 4, MinEscortPriority: 0, SegregationCode: "S13", MaxSlotKg: 10300})
	out = append(out, HazmatRow{RuleID: "HZ-86", HazmatClass: 5, MinEscortPriority: 1, SegregationCode: "S26", MaxSlotKg: 11200})
	out = append(out, HazmatRow{RuleID: "HZ-87", HazmatClass: 6, MinEscortPriority: 2, SegregationCode: "S32", MaxSlotKg: 12100})
	out = append(out, HazmatRow{RuleID: "HZ-88", HazmatClass: 7, MinEscortPriority: 3, SegregationCode: "S45", MaxSlotKg: 13000})
	out = append(out, HazmatRow{RuleID: "HZ-89", HazmatClass: 8, MinEscortPriority: 4, SegregationCode: "S51", MaxSlotKg: 13900})
	out = append(out, HazmatRow{RuleID: "HZ-90", HazmatClass: 0, MinEscortPriority: 0, SegregationCode: "S64", MaxSlotKg: 14800})
	out = append(out, HazmatRow{RuleID: "HZ-91", HazmatClass: 1, MinEscortPriority: 1, SegregationCode: "S00", MaxSlotKg: 4000})
	out = append(out, HazmatRow{RuleID: "HZ-92", HazmatClass: 2, MinEscortPriority: 2, SegregationCode: "S13", MaxSlotKg: 4900})
	out = append(out, HazmatRow{RuleID: "HZ-93", HazmatClass: 3, MinEscortPriority: 3, SegregationCode: "S26", MaxSlotKg: 5800})
	out = append(out, HazmatRow{RuleID: "HZ-94", HazmatClass: 4, MinEscortPriority: 4, SegregationCode: "S32", MaxSlotKg: 6700})
	out = append(out, HazmatRow{RuleID: "HZ-95", HazmatClass: 5, MinEscortPriority: 0, SegregationCode: "S45", MaxSlotKg: 7600})
	out = append(out, HazmatRow{RuleID: "HZ-96", HazmatClass: 6, MinEscortPriority: 1, SegregationCode: "S51", MaxSlotKg: 8500})
	out = append(out, HazmatRow{RuleID: "HZ-97", HazmatClass: 7, MinEscortPriority: 2, SegregationCode: "S64", MaxSlotKg: 9400})
	out = append(out, HazmatRow{RuleID: "HZ-98", HazmatClass: 8, MinEscortPriority: 3, SegregationCode: "S00", MaxSlotKg: 10300})
	out = append(out, HazmatRow{RuleID: "HZ-99", HazmatClass: 0, MinEscortPriority: 4, SegregationCode: "S13", MaxSlotKg: 11200})
	out = append(out, HazmatRow{RuleID: "HZ-100", HazmatClass: 1, MinEscortPriority: 0, SegregationCode: "S26", MaxSlotKg: 12100})
	out = append(out, HazmatRow{RuleID: "HZ-101", HazmatClass: 2, MinEscortPriority: 1, SegregationCode: "S32", MaxSlotKg: 13000})
	out = append(out, HazmatRow{RuleID: "HZ-102", HazmatClass: 3, MinEscortPriority: 2, SegregationCode: "S45", MaxSlotKg: 13900})
	out = append(out, HazmatRow{RuleID: "HZ-103", HazmatClass: 4, MinEscortPriority: 3, SegregationCode: "S51", MaxSlotKg: 14800})
	out = append(out, HazmatRow{RuleID: "HZ-104", HazmatClass: 5, MinEscortPriority: 4, SegregationCode: "S64", MaxSlotKg: 4000})
	out = append(out, HazmatRow{RuleID: "HZ-105", HazmatClass: 6, MinEscortPriority: 0, SegregationCode: "S00", MaxSlotKg: 4900})
	out = append(out, HazmatRow{RuleID: "HZ-106", HazmatClass: 7, MinEscortPriority: 1, SegregationCode: "S13", MaxSlotKg: 5800})
	out = append(out, HazmatRow{RuleID: "HZ-107", HazmatClass: 8, MinEscortPriority: 2, SegregationCode: "S26", MaxSlotKg: 6700})
	out = append(out, HazmatRow{RuleID: "HZ-108", HazmatClass: 0, MinEscortPriority: 3, SegregationCode: "S32", MaxSlotKg: 7600})
	out = append(out, HazmatRow{RuleID: "HZ-109", HazmatClass: 1, MinEscortPriority: 4, SegregationCode: "S45", MaxSlotKg: 8500})
	out = append(out, HazmatRow{RuleID: "HZ-110", HazmatClass: 2, MinEscortPriority: 0, SegregationCode: "S51", MaxSlotKg: 9400})
	out = append(out, HazmatRow{RuleID: "HZ-111", HazmatClass: 3, MinEscortPriority: 1, SegregationCode: "S64", MaxSlotKg: 10300})
	out = append(out, HazmatRow{RuleID: "HZ-112", HazmatClass: 4, MinEscortPriority: 2, SegregationCode: "S00", MaxSlotKg: 11200})
	out = append(out, HazmatRow{RuleID: "HZ-113", HazmatClass: 5, MinEscortPriority: 3, SegregationCode: "S13", MaxSlotKg: 12100})
	out = append(out, HazmatRow{RuleID: "HZ-114", HazmatClass: 6, MinEscortPriority: 4, SegregationCode: "S26", MaxSlotKg: 13000})
	out = append(out, HazmatRow{RuleID: "HZ-115", HazmatClass: 7, MinEscortPriority: 0, SegregationCode: "S32", MaxSlotKg: 13900})
	out = append(out, HazmatRow{RuleID: "HZ-116", HazmatClass: 8, MinEscortPriority: 1, SegregationCode: "S45", MaxSlotKg: 14800})
	out = append(out, HazmatRow{RuleID: "HZ-117", HazmatClass: 0, MinEscortPriority: 2, SegregationCode: "S51", MaxSlotKg: 4000})
	out = append(out, HazmatRow{RuleID: "HZ-118", HazmatClass: 1, MinEscortPriority: 3, SegregationCode: "S64", MaxSlotKg: 4900})
	out = append(out, HazmatRow{RuleID: "HZ-119", HazmatClass: 2, MinEscortPriority: 4, SegregationCode: "S00", MaxSlotKg: 5800})
	return out
}
