package tablex

// laneFill07 appends lane rows 420..479.
func laneFill07(out []LaneRow) []LaneRow {
	out = append(out, LaneRow{LaneID: "LN-420", OriginHub: "ATL", DestHub: "MEM", ServiceClass: "bonded", SlotCount: 1, SlotCapacityKg: 11000, TransitMinutes: 1260, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-421", OriginHub: "DFW", DestHub: "SEA", ServiceClass: "bonded", SlotCount: 2, SlotCapacityKg: 12500, TransitMinutes: 1305, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-422", OriginHub: "PHX", DestHub: "RNO", ServiceClass: "bonded", SlotCount: 3, SlotCapacityKg: 14000, TransitMinutes: 1350, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-423", OriginHub: "YYZ", DestHub: "YVR", ServiceClass: "expedite", SlotCount: 4, SlotCapacityKg: 15500, TransitMinutes: 1395, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-424", OriginHub: "JAX", DestHub: "PDX", ServiceClass: "intermodal", SlotCount: 5, SlotCapacityKg: 17000, TransitMinutes: 1440, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-425", OriginHub: "RNO", DestHub: "YYZ", ServiceClass: "flatbed", SlotCount: 6, SlotCapacityKg: 18500, TransitMinutes: 1485, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-426", OriginHub: "YVR", DestHub: "CHI", ServiceClass: "reefer", SlotCount: 1, SlotCapacityKg: 20000, TransitMinutes: 1530, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-427", OriginHub: "DTW", DestHub: "YVR", ServiceClass: "flatbed", SlotCount: 2, SlotCapacityKg: 21500, TransitMinutes: 1575, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-428", OriginHub: "OKC", DestHub: "NSH", ServiceClass: "bonded", SlotCount: 3, SlotCapacityKg: 23000, TransitMinutes: 1620, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-429", OriginHub: "IND", DestHub: "CHI", ServiceClass: "expedite", SlotCount: 4, SlotCapacityKg: 8000, TransitMinutes: 1665, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-430", OriginHub: "NSH", DestHub: "DTW", ServiceClass: "standard", SlotCount: 5, SlotCapacityKg: 9500, TransitMinutes: 1710, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-431", OriginHub: "RNO", DestHub: "NSH", ServiceClass: "standard", SlotCount: 6, SlotCapacityKg: 11000, TransitMinutes: 1755, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-432", OriginHub: "SLC", DestHub: "DEN", ServiceClass: "flatbed", SlotCount: 1, SlotCapacityKg: 12500, TransitMinutes: 1800, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-433", OriginHub: "IND", DestHub: "HOU", ServiceClass: "expedite", SlotCount: 2, SlotCapacityKg: 14000, TransitMinutes: 1845, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-434", OriginHub: "RNO", DestHub: "MEM", ServiceClass: "bonded", SlotCount: 3, SlotCapacityKg: 15500, TransitMinutes: 1890, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-435", OriginHub: "DTW", DestHub: "PHX", ServiceClass: "expedite", SlotCount: 4, SlotCapacityKg: 17000, TransitMinutes: 1935, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-436", OriginHub: "YYZ", DestHub: "DTW", ServiceClass: "reefer", SlotCount: 5, SlotCapacityKg: 18500, TransitMinutes: 1980, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-437", OriginHub: "PHX", DestHub: "OKC", ServiceClass: "intermodal", SlotCount: 6, SlotCapacityKg: 20000, TransitMinutes: 2025, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-438", OriginHub: "SEA", DestHub: "HOU", ServiceClass: "flatbed", SlotCount: 1, SlotCapacityKg: 21500, TransitMinutes: 2070, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-439", OriginHub: "LAX", DestHub: "KCK", ServiceClass: "reefer", SlotCount: 2, SlotCapacityKg: 23000, TransitMinutes: 2115, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-440", OriginHub: "PHX", DestHub: "LAX", ServiceClass: "intermodal", SlotCount: 3, SlotCapacityKg: 8000, TransitMinutes: 360, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-441", OriginHub: "DEN", DestHub: "CHI", ServiceClass: "expedite", SlotCount: 4, SlotCapacityKg: 9500, TransitMinutes: 405, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-442", OriginHub: "HOU", DestHub: "SLC", ServiceClass: "flatbed", SlotCount: 5, SlotCapacityKg: 11000, TransitMinutes: 450, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-443", OriginHub: "IND", DestHub: "PDX", ServiceClass: "standard", SlotCount: 6, SlotCapacityKg: 12500, TransitMinutes: 495, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-444", OriginHub: "SLC", DestHub: "SLC", ServiceClass: "flatbed", SlotCount: 1, SlotCapacityKg: 14000, TransitMinutes: 540, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-445", OriginHub: "DEN", DestHub: "TPA", ServiceClass: "flatbed", SlotCount: 2, SlotCapacityKg: 15500, TransitMinutes: 585, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-446", OriginHub: "LAX", DestHub: "DTW", ServiceClass: "expedite", SlotCount: 3, SlotCapacityKg: 17000, TransitMinutes: 630, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-447", OriginHub: "MSP", DestHub: "KCK", ServiceClass: "standard", SlotCount: 4, SlotCapacityKg: 18500, TransitMinutes: 675, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-448", OriginHub: "RNO", DestHub: "HOU", ServiceClass: "standard", SlotCount: 5, SlotCapacityKg: 20000, TransitMinutes: 720, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-449", OriginHub: "DEN", DestHub: "YVR", ServiceClass: "bonded", SlotCount: 6, SlotCapacityKg: 21500, TransitMinutes: 765, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-450", OriginHub: "MEM", DestHub: "NSH", ServiceClass: "standard", SlotCount: 1, SlotCapacityKg: 23000, TransitMinutes: 810, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-451", OriginHub: "PHX", DestHub: "DTW", ServiceClass: "reefer", SlotCount: 2, SlotCapacityKg: 8000, TransitMinutes: 855, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-452", OriginHub: "STL", DestHub: "OKC", ServiceClass: "standard", SlotCount: 3, SlotCapacityKg: 9500, TransitMinutes: 900, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-453", OriginHub: "NSH", DestHub: "NSH", ServiceClass: "intermodal", SlotCount: 4, SlotCapacityKg: 11000, TransitMinutes: 945, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-454", OriginHub: "CHI", DestHub: "PHX", ServiceClass: "flatbed", SlotCount: 5, SlotCapacityKg: 12500, TransitMinutes: 990, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-455", OriginHub: "DTW", DestHub: "SLC", ServiceClass: "expedite", SlotCount: 6, SlotCapacityKg: 14000, TransitMinutes: 1035, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-456", OriginHub: "BOS", DestHub: "ATL", ServiceClass: "reefer", SlotCount: 1, SlotCapacityKg: 15500, TransitMinutes: 1080, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-457", OriginHub: "DTW", DestHub: "KCK", ServiceClass: "standard", SlotCount: 2, SlotCapacityKg: 17000, TransitMinutes: 1125, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-458", OriginHub: "CHI", DestHub: "TPA", ServiceClass: "flatbed", SlotCount: 3, SlotCapacityKg: 18500, TransitMinutes: 1170, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-459", OriginHub: "MEM", DestHub: "IND", ServiceClass: "flatbed", SlotCount: 4, SlotCapacityKg: 20000, TransitMinutes: 1215, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-460", OriginHub: "JAX", DestHub: "BOS", ServiceClass: "standard", SlotCount: 5, SlotCapacityKg: 21500, TransitMinutes: 1260, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-461", OriginHub: "IND", DestHub: "DTW", ServiceClass: "reefer", SlotCount: 6, SlotCapacityKg: 23000, TransitMinutes: 1305, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-462", OriginHub: "MSP", DestHub: "STL", ServiceClass: "intermodal", SlotCount: 1, SlotCapacityKg: 8000, TransitMinutes: 1350, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-463", OriginHub: "SEA", DestHub: "CHI", ServiceClass: "standard", SlotCount: 2, SlotCapacityKg: 9500, TransitMinutes: 1395, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-464", OriginHub: "YVR", DestHub: "STL", ServiceClass: "intermodal", SlotCount: 3, SlotCapacityKg: 11000, TransitMinutes: 1440, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-465", OriginHub: "YYZ", DestHub: "OKC", ServiceClass: "bonded", SlotCount: 4, SlotCapacityKg: 12500, TransitMinutes: 1485, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-466", OriginHub: "JAX", DestHub: "YVR", ServiceClass: "flatbed", SlotCount: 5, SlotCapacityKg: 14000, TransitMinutes: 1530, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-467", OriginHub: "SEA", DestHub: "CHI", ServiceClass: "standard", SlotCount: 6, SlotCapacityKg: 15500, TransitMinutes: 1575, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-468", OriginHub: "NSH", DestHub: "YVR", ServiceClass: "expedite", SlotCount: 1, SlotCapacityKg: 17000, TransitMinutes: 1620, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-469", OriginHub: "MSP", DestHub: "LAX", ServiceClass: "standard", SlotCount: 2, SlotCapacityKg: 18500, TransitMinutes: 1665, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-470", OriginHub: "KCK", DestHub: "SEA", ServiceClass: "flatbed", SlotCount: 3, SlotCapacityKg: 20000, TransitMinutes: 1710, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-471", OriginHub: "YYZ", DestHub: "TPA", ServiceClass: "intermodal", SlotCount: 4, SlotCapacityKg: 21500, TransitMinutes: 1755, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-472", OriginHub: "STL", DestHub: "SEA", ServiceClass: "expedite", SlotCount: 5, SlotCapacityKg: 23000, TransitMinutes: 1800, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-473", OriginHub: "STL", DestHub: "TPA", ServiceClass: "expedite", SlotCount: 6, SlotCapacityKg: 8000, TransitMinutes: 1845, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-474", OriginHub: "KCK", DestHub: "BOS", ServiceClass: "standard", SlotCount: 1, SlotCapacityKg: 9500, TransitMinutes: 1890, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-475", OriginHub: "IND", DestHub: "BOS", ServiceClass: "flatbed", SlotCount: 2, SlotCapacityKg: 11000, TransitMinutes: 1935, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-476", OriginHub: "PHX", DestHub: "YYZ", ServiceClass: "flatbed", SlotCount: 3, SlotCapacityKg: 12500, TransitMinutes: 1980, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-477", OriginHub: "NSH", DestHub: "NSH", ServiceClass: "standard", SlotCount: 4, SlotCapacityKg: 14000, TransitMinutes: 2025, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-478", OriginHub: "CHI", DestHub: "SLC", ServiceClass: "expedite", SlotCount: 5, SlotCapacityKg: 15500, TransitMinutes: 2070, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-479", OriginHub: "STL", DestHub: "DTW", ServiceClass: "standard", SlotCount: 6, SlotCapacityKg: 17000, TransitMinutes: 2115, CrossDock: false})
	return out
}
