package tablex

// laneFill05 appends lane rows 300..359.
func laneFill05(out []LaneRow) []LaneRow {
	out = append(out, LaneRow{LaneID: "LN-300", OriginHub: "DFW", DestHub: "ATL", ServiceClass: "flatbed", SlotCount: 1, SlotCapacityKg: 12500, TransitMinutes: 1260, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-301", OriginHub: "CHI", DestHub: "MSP", ServiceClass: "standard", SlotCount: 2, SlotCapacityKg: 14000, TransitMinutes: 1305, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-302", OriginHub: "KCK", DestHub: "NSH", ServiceClass: "reefer", SlotCount: 3, SlotCapacityKg: 15500, TransitMinutes: 1350, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-303", OriginHub: "TPA", DestHub: "ATL", ServiceClass: "reefer", SlotCount: 4, SlotCapacityKg: 17000, TransitMinutes: 1395, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-304", OriginHub: "CHI", DestHub: "NSH", ServiceClass: "reefer", SlotCount: 5, SlotCapacityKg: 18500, TransitMinutes: 1440, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-305", OriginHub: "JAX", DestHub: "SEA", ServiceClass: "flatbed", SlotCount: 6, SlotCapacityKg: 20000, TransitMinutes: 1485, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-306", OriginHub: "DTW", DestHub: "OKC", ServiceClass: "bonded", SlotCount: 1, SlotCapacityKg: 21500, TransitMinutes: 1530, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-307", OriginHub: "PHX", DestHub: "YYZ", ServiceClass: "flatbed", SlotCount: 2, SlotCapacityKg: 23000, TransitMinutes: 1575, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-308", OriginHub: "YVR", DestHub: "JAX", ServiceClass: "bonded", SlotCount: 3, SlotCapacityKg: 8000, TransitMinutes: 1620, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-309", OriginHub: "STL", DestHub: "YVR", ServiceClass: "bonded", SlotCount: 4, SlotCapacityKg: 9500, TransitMinutes: 1665, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-310", OriginHub: "RNO", DestHub: "YYZ", ServiceClass: "bonded", SlotCount: 5, SlotCapacityKg: 11000, TransitMinutes: 1710, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-311", OriginHub: "KCK", DestHub: "JAX", ServiceClass: "reefer", SlotCount: 6, SlotCapacityKg: 12500, TransitMinutes: 1755, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-312", OriginHub: "BOS", DestHub: "PDX", ServiceClass: "intermodal", SlotCount: 1, SlotCapacityKg: 14000, TransitMinutes: 1800, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-313", OriginHub: "MEM", DestHub: "PDX", ServiceClass: "reefer", SlotCount: 2, SlotCapacityKg: 15500, TransitMinutes: 1845, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-314", OriginHub: "MSP", DestHub: "STL", ServiceClass: "flatbed", SlotCount: 3, SlotCapacityKg: 17000, TransitMinutes: 1890, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-315", OriginHub: "YVR", DestHub: "RNO", ServiceClass: "flatbed", SlotCount: 4, SlotCapacityKg: 18500, TransitMinutes: 1935, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-316", OriginHub: "JAX", DestHub: "DEN", ServiceClass: "flatbed", SlotCount: 5, SlotCapacityKg: 20000, TransitMinutes: 1980, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-317", OriginHub: "YVR", DestHub: "DTW", ServiceClass: "flatbed", SlotCount: 6, SlotCapacityKg: 21500, TransitMinutes: 2025, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-318", OriginHub: "CHI", DestHub: "RNO", ServiceClass: "flatbed", SlotCount: 1, SlotCapacityKg: 23000, TransitMinutes: 2070, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-319", OriginHub: "DTW", DestHub: "RNO", ServiceClass: "expedite", SlotCount: 2, SlotCapacityKg: 8000, TransitMinutes: 2115, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-320", OriginHub: "BOS", DestHub: "LAX", ServiceClass: "standard", SlotCount: 3, SlotCapacityKg: 9500, TransitMinutes: 360, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-321", OriginHub: "TPA", DestHub: "MEM", ServiceClass: "reefer", SlotCount: 4, SlotCapacityKg: 11000, TransitMinutes: 405, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-322", OriginHub: "RNO", DestHub: "PHX", ServiceClass: "flatbed", SlotCount: 5, SlotCapacityKg: 12500, TransitMinutes: 450, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-323", OriginHub: "RNO", DestHub: "STL", ServiceClass: "flatbed", SlotCount: 6, SlotCapacityKg: 14000, TransitMinutes: 495, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-324", OriginHub: "PHX", DestHub: "LAX", ServiceClass: "reefer", SlotCount: 1, SlotCapacityKg: 15500, TransitMinutes: 540, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-325", OriginHub: "HOU", DestHub: "DEN", ServiceClass: "standard", SlotCount: 2, SlotCapacityKg: 17000, TransitMinutes: 585, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-326", OriginHub: "HOU", DestHub: "ATL", ServiceClass: "reefer", SlotCount: 3, SlotCapacityKg: 18500, TransitMinutes: 630, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-327", OriginHub: "DTW", DestHub: "KCK", ServiceClass: "bonded", SlotCount: 4, SlotCapacityKg: 20000, TransitMinutes: 675, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-328", OriginHub: "SEA", DestHub: "SEA", ServiceClass: "expedite", SlotCount: 5, SlotCapacityKg: 21500, TransitMinutes: 720, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-329", OriginHub: "DTW", DestHub: "SLC", ServiceClass: "intermodal", SlotCount: 6, SlotCapacityKg: 23000, TransitMinutes: 765, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-330", OriginHub: "CHI", DestHub: "OKC", ServiceClass: "standard", SlotCount: 1, SlotCapacityKg: 8000, TransitMinutes: 810, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-331", OriginHub: "BOS", DestHub: "DTW", ServiceClass: "expedite", SlotCount: 2, SlotCapacityKg: 9500, TransitMinutes: 855, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-332", OriginHub: "JAX", DestHub: "BOS", ServiceClass: "flatbed", SlotCount: 3, SlotCapacityKg: 11000, TransitMinutes: 900, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-333", OriginHub: "NSH", DestHub: "LAX", ServiceClass: "reefer", SlotCount: 4, SlotCapacityKg: 12500, TransitMinutes: 945, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-334", OriginHub: "MSP", DestHub: "BOS", ServiceClass: "flatbed", SlotCount: 5, SlotCapacityKg: 14000, TransitMinutes: 990, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-335", OriginHub: "YVR", DestHub: "DEN", ServiceClass: "flatbed", SlotCount: 6, SlotCapacityKg: 15500, TransitMinutes: 1035, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-336", OriginHub: "YVR", DestHub: "SEA", ServiceClass: "flatbed", SlotCount: 1, SlotCapacityKg: 17000, TransitMinutes: 1080, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-337", OriginHub: "PHX", DestHub: "BOS", ServiceClass: "standard", SlotCount: 2, SlotCapacityKg: 18500, TransitMinutes: 1125, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-338", OriginHub: "OKC", DestHub: "PDX", ServiceClass: "reefer", SlotCount: 3, SlotCapacityKg: 20000, TransitMinutes: 1170, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-339", OriginHub: "SEA", DestHub: "HOU", ServiceClass: "standard", SlotCount: 4, SlotCapacityKg: 21500, TransitMinutes: 1215, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-340", OriginHub: "PDX", DestHub: "MEM", ServiceClass: "bonded", SlotCount: 5, SlotCapacityKg: 23000, TransitMinutes: 1260, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-341", OriginHub: "KCK", DestHub: "BOS", ServiceClass: "flatbed", SlotCount: 6, SlotCapacityKg: 8000, TransitMinutes: 1305, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-342", OriginHub: "OKC", DestHub: "PHX", ServiceClass: "intermodal", SlotCount: 1, SlotCapacityKg: 9500, TransitMinutes: 1350, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-343", OriginHub: "HOU", DestHub: "BOS", ServiceClass: "flatbed", SlotCount: 2, SlotCapacityKg: 11000, TransitMinutes: 1395, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-344", OriginHub: "BOS", DestHub: "DFW", ServiceClass: "flatbed", SlotCount: 3, SlotCapacityKg: 12500, TransitMinutes: 1440, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-345", OriginHub: "LAX", DestHub: "BOS", ServiceClass: "reefer", SlotCount: 4, SlotCapacityKg: 14000, TransitMinutes: 1485, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-346", OriginHub: "YYZ", DestHub: "BOS", ServiceClass: "flatbed", SlotCount: 5, SlotCapacityKg: 15500, TransitMinutes: 1530, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-347", OriginHub: "DEN", DestHub: "ATL", ServiceClass: "reefer", SlotCount: 6, SlotCapacityKg: 17000, TransitMinutes: 1575, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-348", OriginHub: "PHX", DestHub: "YVR", ServiceClass: "expedite", SlotCount: 1, SlotCapacityKg: 18500, TransitMinutes: 1620, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-349", OriginHub: "SEA", DestHub: "KCK", ServiceClass: "standard", SlotCount: 2, SlotCapacityKg: 20000, TransitMinutes: 1665, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-350", OriginHub: "YVR", DestHub: "OKC", ServiceClass: "reefer", SlotCount: 3, SlotCapacityKg: 21500, TransitMinutes: 1710, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-351", OriginHub: "DFW", DestHub: "HOU", ServiceClass: "expedite", SlotCount: 4, SlotCapacityKg: 23000, TransitMinutes: 1755, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-352", OriginHub: "OKC", DestHub: "MEM", ServiceClass: "intermodal", SlotCount: 5, SlotCapacityKg: 8000, TransitMinutes: 1800, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-353", OriginHub: "SLC", DestHub: "MEM", ServiceClass: "intermodal", SlotCount: 6, SlotCapacityKg: 9500, TransitMinutes: 1845, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-354", OriginHub: "YYZ", DestHub: "MSP", ServiceClass: "reefer", SlotCount: 1, SlotCapacityKg: 11000, TransitMinutes: 1890, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-355", OriginHub: "OKC", DestHub: "PDX", ServiceClass: "reefer", SlotCount: 2, SlotCapacityKg: 12500, TransitMinutes: 1935, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-356", OriginHub: "IND", DestHub: "NSH", ServiceClass: "standard", SlotCount: 3, SlotCapacityKg: 14000, TransitMinutes: 1980, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-357", OriginHub: "CHI", DestHub: "ATL", ServiceClass: "flatbed", SlotCount: 4, SlotCapacityKg: 15500, TransitMinutes: 2025, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-358", OriginHub: "TPA", DestHub: "PHX", ServiceClass: "intermodal", SlotCount: 5, SlotCapacityKg: 17000, TransitMinutes: 2070, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-359", OriginHub: "MEM", DestHub: "SLC", ServiceClass: "flatbed", SlotCount: 6, SlotCapacityKg: 18500, TransitMinutes: 2115, CrossDock: false})
	return out
}
