package tablex

// laneFill06 appends lane rows 360..419.
func laneFill06(out []LaneRow) []LaneRow {
	out = append(out, LaneRow{LaneID: "LN-360", OriginHub: "DEN", DestHub: "BOS", ServiceClass: "expedite", SlotCount: 1, SlotCapacityKg: 20000, TransitMinutes: 360, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-361", OriginHub: "OKC", DestHub: "SEA", ServiceClass: "flatbed", SlotCount: 2, SlotCapacityKg: 21500, TransitMinutes: 405, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-362", OriginHub: "CHI", DestHub: "SLC", ServiceClass: "expedite", SlotCount: 3, SlotCapacityKg: 23000, TransitMinutes: 450, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-363", OriginHub: "YVR", DestHub: "RNO", ServiceClass: "intermodal", SlotCount: 4, SlotCapacityKg: 8000, TransitMinutes: 495, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-364", OriginHub: "IND", DestHub: "IND", ServiceClass: "reefer", SlotCount: 5, SlotCapacityKg: 9500, TransitMinutes: 540, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-365", OriginHub: "LAX", DestHub: "PHX", ServiceClass: "intermodal", SlotCount: 6, SlotCapacityKg: 11000, TransitMinutes: 585, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-366", OriginHub: "BOS", DestHub: "DFW", ServiceClass: "reefer", SlotCount: 1, SlotCapacityKg: 12500, TransitMinutes: 630, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-367", OriginHub: "SLC", DestHub: "BOS", ServiceClass: "standard", SlotCount: 2, SlotCapacityKg: 14000, TransitMinutes: 675, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-368", OriginHub: "MSP", DestHub: "HOU", ServiceClass: "reefer", SlotCount: 3, SlotCapacityKg: 15500, TransitMinutes: 720, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-369", OriginHub: "YVR", DestHub: "BOS", ServiceClass: "standard", SlotCount: 4, SlotCapacityKg: 17000, TransitMinutes: 765, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-370", OriginHub: "ATL", DestHub: "NSH", ServiceClass: "bonded", SlotCount: 5, SlotCapacityKg: 18500, TransitMinutes: 810, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-371", OriginHub: "ATL", DestHub: "DFW", ServiceClass: "flatbed", SlotCount: 6, SlotCapacityKg: 20000, TransitMinutes: 855, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-372", OriginHub: "DTW", DestHub: "MEM", ServiceClass: "intermodal", SlotCount: 1, SlotCapacityKg: 21500, TransitMinutes: 900, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-373", OriginHub: "HOU", DestHub: "PDX", ServiceClass: "intermodal", SlotCount: 2, SlotCapacityKg: 23000, TransitMinutes: 945, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-374", OriginHub: "KCK", DestHub: "RNO", ServiceClass: "expedite", SlotCount: 3, SlotCapacityKg: 8000, TransitMinutes: 990, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-375", OriginHub: "CHI", DestHub: "OKC", ServiceClass: "standard", SlotCount: 4, SlotCapacityKg: 9500, TransitMinutes: 1035, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-376", OriginHub: "TPA", DestHub: "DFW", ServiceClass: "expedite", SlotCount: 5, SlotCapacityKg: 11000, TransitMinutes: 1080, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-377", OriginHub: "DFW", DestHub: "DEN", ServiceClass: "reefer", SlotCount: 6, SlotCapacityKg: 12500, TransitMinutes: 1125, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-378", OriginHub: "YVR", DestHub: "MSP", ServiceClass: "bonded", SlotCount: 1, SlotCapacityKg: 14000, TransitMinutes: 1170, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-379", OriginHub: "MEM", DestHub: "OKC", ServiceClass: "intermodal", SlotCount: 2, SlotCapacityKg: 15500, TransitMinutes: 1215, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-380", OriginHub: "HOU", DestHub: "MEM", ServiceClass: "reefer", SlotCount: 3, SlotCapacityKg: 17000, TransitMinutes: 1260, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-381", OriginHub: "YYZ", DestHub: "KCK", ServiceClass: "reefer", SlotCount: 4, SlotCapacityKg: 18500, TransitMinutes: 1305, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-382", OriginHub: "YYZ", DestHub: "PHX", ServiceClass: "expedite", SlotCount: 5, SlotCapacityKg: 20000, TransitMinutes: 1350, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-383", OriginHub: "STL", DestHub: "MSP", ServiceClass: "intermodal", SlotCount: 6, SlotCapacityKg: 21500, TransitMinutes: 1395, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-384", OriginHub: "TPA", DestHub: "MSP", ServiceClass: "bonded", SlotCount: 1, SlotCapacityKg: 23000, TransitMinutes: 1440, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-385", OriginHub: "LAX", DestHub: "PHX", ServiceClass: "bonded", SlotCount: 2, SlotCapacityKg: 8000, TransitMinutes: 1485, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-386", OriginHub: "IND", DestHub: "RNO", ServiceClass: "expedite", SlotCount: 3, SlotCapacityKg: 9500, TransitMinutes: 1530, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-387", OriginHub: "CHI", DestHub: "TPA", ServiceClass: "expedite", SlotCount: 4, SlotCapacityKg: 11000, TransitMinutes: 1575, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-388", OriginHub: "PDX", DestHub: "BOS", ServiceClass: "standard", SlotCount: 5, SlotCapacityKg: 12500, TransitMinutes: 1620, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-389", OriginHub: "JAX", DestHub: "BOS", ServiceClass: "flatbed", SlotCount: 6, SlotCapacityKg: 14000, TransitMinutes: 1665, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-390", OriginHub: "YYZ", DestHub: "OKC", ServiceClass: "standard", SlotCount: 1, SlotCapacityKg: 15500, TransitMinutes: 1710, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-391", OriginHub: "BOS", DestHub: "YVR", ServiceClass: "intermodal", SlotCount: 2, SlotCapacityKg: 17000, TransitMinutes: 1755, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-392", OriginHub: "NSH", DestHub: "IND", ServiceClass: "flatbed", SlotCount: 3, SlotCapacityKg: 18500, TransitMinutes: 1800, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-393", OriginHub: "KCK", DestHub: "PHX", ServiceClass: "bonded", SlotCount: 4, SlotCapacityKg: 20000, TransitMinutes: 1845, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-394", OriginHub: "PDX", DestHub: "DFW", ServiceClass: "expedite", SlotCount: 5, SlotCapacityKg: 21500, TransitMinutes: 1890, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-395", OriginHub: "PHX", DestHub: "OKC", ServiceClass: "intermodal", SlotCount: 6, SlotCapacityKg: 23000, TransitMinutes: 1935, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-396", OriginHub: "JAX", DestHub: "DFW", ServiceClass: "expedite", SlotCount: 1, SlotCapacityKg: 8000, TransitMinutes: 1980, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-397", OriginHub: "CHI", DestHub: "SLC", ServiceClass: "bonded", SlotCount: 2, SlotCapacityKg: 9500, TransitMinutes: 2025, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-398", OriginHub: "CHI", DestHub: "ATL", ServiceClass: "reefer", SlotCount: 3, SlotCapacityKg: 11000, TransitMinutes: 2070, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-399", OriginHub: "LAX", DestHub: "IND", ServiceClass: "flatbed", SlotCount: 4, SlotCapacityKg: 12500, TransitMinutes: 2115, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-400", OriginHub: "JAX", DestHub: "DEN", ServiceClass: "flatbed", SlotCount: 5, SlotCapacityKg: 14000, TransitMinutes: 360, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-401", OriginHub: "OKC", DestHub: "MEM", ServiceClass: "reefer", SlotCount: 6, SlotCapacityKg: 15500, TransitMinutes: 405, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-402", OriginHub: "DEN", DestHub: "OKC", ServiceClass: "reefer", SlotCount: 1, SlotCapacityKg: 17000, TransitMinutes: 450, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-403", OriginHub: "JAX", DestHub: "NSH", ServiceClass: "intermodal", SlotCount: 2, SlotCapacityKg: 18500, TransitMinutes: 495, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-404", OriginHub: "JAX", DestHub: "NSH", ServiceClass: "bonded", SlotCount: 3, SlotCapacityKg: 20000, TransitMinutes: 540, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-405", OriginHub: "SLC", DestHub: "DTW", ServiceClass: "flatbed", SlotCount: 4, SlotCapacityKg: 21500, TransitMinutes: 585, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-406", OriginHub: "PDX", DestHub: "TPA", ServiceClass: "intermodal", SlotCount: 5, SlotCapacityKg: 23000, TransitMinutes: 630, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-407", OriginHub: "STL", DestHub: "YVR", ServiceClass: "bonded", SlotCount: 6, SlotCapacityKg: 8000, TransitMinutes: 675, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-408", OriginHub: "SEA", DestHub: "SLC", ServiceClass: "flatbed", SlotCount: 1, SlotCapacityKg: 9500, TransitMinutes: 720, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-409", OriginHub: "PHX", DestHub: "YVR", ServiceClass: "bonded", SlotCount: 2, SlotCapacityKg: 11000, TransitMinutes: 765, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-410", OriginHub: "SLC", DestHub: "MSP", ServiceClass: "intermodal", SlotCount: 3, SlotCapacityKg: 12500, TransitMinutes: 810, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-411", OriginHub: "DFW", DestHub: "HOU", ServiceClass: "flatbed", SlotCount: 4, SlotCapacityKg: 14000, TransitMinutes: 855, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-412", OriginHub: "ATL", DestHub: "NSH", ServiceClass: "reefer", SlotCount: 5, SlotCapacityKg: 15500, TransitMinutes: 900, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-413", OriginHub: "JAX", DestHub: "SEA", ServiceClass: "flatbed", SlotCount: 6, SlotCapacityKg: 17000, TransitMinutes: 945, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-414", OriginHub: "KCK", DestHub: "BOS", ServiceClass: "reefer", SlotCount: 1, SlotCapacityKg: 18500, TransitMinutes: 990, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-415", OriginHub: "JAX", DestHub: "BOS", ServiceClass: "expedite", SlotCount: 2, SlotCapacityKg: 20000, TransitMinutes: 1035, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-416", OriginHub: "TPA", DestHub: "DTW", ServiceClass: "reefer", SlotCount: 3, SlotCapacityKg: 21500, TransitMinutes: 1080, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-417", OriginHub: "STL", DestHub: "KCK", ServiceClass: "reefer", SlotCount: 4, SlotCapacityKg: 23000, TransitMinutes: 1125, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-418", OriginHub: "NSH", DestHub: "PHX", ServiceClass: "expedite", SlotCount: 5, SlotCapacityKg: 8000, TransitMinutes: 1170, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-419", OriginHub: "PHX", DestHub: "SLC", ServiceClass: "intermodal", SlotCount: 6, SlotCapacityKg: 9500, TransitMinutes: 1215, CrossDock: false})
	return out
}
