package tablex

// laneFill04 appends lane rows 240..299.
func laneFill04(out []LaneRow) []LaneRow {
	out = append(out, LaneRow{LaneID: "LN-240", OriginHub: "RNO", DestHub: "OKC", ServiceClass: "bonded", SlotCount: 1, SlotCapacityKg: 21500, TransitMinutes: 360, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-241", OriginHub: "OKC", DestHub: "KCK", ServiceClass: "bonded", SlotCount: 2, SlotCapacityKg: 23000, TransitMinutes: 405, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-242", OriginHub: "NSH", DestHub: "JAX", ServiceClass: "standard", SlotCount: 3, SlotCapacityKg: 8000, TransitMinutes: 450, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-243", OriginHub: "JAX", DestHub: "PHX", ServiceClass: "intermodal", SlotCount: 4, SlotCapacityKg: 9500, TransitMinutes: 495, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-244", OriginHub: "CHI", DestHub: "DTW", ServiceClass: "flatbed", SlotCount: 5, SlotCapacityKg: 11000, TransitMinutes: 540, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-245", OriginHub: "SEA", DestHub: "MSP", ServiceClass: "standard", SlotCount: 6, SlotCapacityKg: 12500, TransitMinutes: 585, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-246", OriginHub: "CHI", DestHub: "HOU", ServiceClass: "flatbed", SlotCount: 1, SlotCapacityKg: 14000, TransitMinutes: 630, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-247", OriginHub: "PDX", DestHub: "IND", ServiceClass: "reefer", SlotCount: 2, SlotCapacityKg: 15500, TransitMinutes: 675, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-248", OriginHub: "BOS", DestHub: "PDX", ServiceClass: "standard", SlotCount: 3, SlotCapacityKg: 17000, TransitMinutes: 720, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-249", OriginHub: "SEA", DestHub: "NSH", ServiceClass: "intermodal", SlotCount: 4, SlotCapacityKg: 18500, TransitMinutes: 765, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-250", OriginHub: "DTW", DestHub: "SEA", ServiceClass: "bonded", SlotCount: 5, SlotCapacityKg: 20000, TransitMinutes: 810, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-251", OriginHub: "ATL", DestHub: "TPA", ServiceClass: "intermodal", SlotCount: 6, SlotCapacityKg: 21500, TransitMinutes: 855, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-252", OriginHub: "OKC", DestHub: "MSP", ServiceClass: "bonded", SlotCount: 1, SlotCapacityKg: 23000, TransitMinutes: 900, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-253", OriginHub: "DTW", DestHub: "PDX", ServiceClass: "standard", SlotCount: 2, SlotCapacityKg: 8000, TransitMinutes: 945, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-254", OriginHub: "MSP", DestHub: "PHX", ServiceClass: "intermodal", SlotCount: 3, SlotCapacityKg: 9500, TransitMinutes: 990, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-255", OriginHub: "CHI", DestHub: "SLC", ServiceClass: "expedite", SlotCount: 4, SlotCapacityKg: 11000, TransitMinutes: 1035, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-256", OriginHub: "IND", DestHub: "HOU", ServiceClass: "flatbed", SlotCount: 5, SlotCapacityKg: 12500, TransitMinutes: 1080, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-257", OriginHub: "CHI", DestHub: "TPA", ServiceClass: "expedite", SlotCount: 6, SlotCapacityKg: 14000, TransitMinutes: 1125, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-258", OriginHub: "YYZ", DestHub: "MSP", ServiceClass: "intermodal", SlotCount: 1, SlotCapacityKg: 15500, TransitMinutes: 1170, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-259", OriginHub: "CHI", DestHub: "PDX", ServiceClass: "reefer", SlotCount: 2, SlotCapacityKg: 17000, TransitMinutes: 1215, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-260", OriginHub: "ATL", DestHub: "YVR", ServiceClass: "intermodal", SlotCount: 3, SlotCapacityKg: 18500, TransitMinutes: 1260, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-261", OriginHub: "ATL", DestHub: "CHI", ServiceClass: "expedite", SlotCount: 4, SlotCapacityKg: 20000, TransitMinutes: 1305, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-262", OriginHub: "NSH", DestHub: "YVR", ServiceClass: "expedite", SlotCount: 5, SlotCapacityKg: 21500, TransitMinutes: 1350, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-263", OriginHub: "MSP", DestHub: "YYZ", ServiceClass: "bonded", SlotCount: 6, SlotCapacityKg: 23000, TransitMinutes: 1395, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-264", OriginHub: "DEN", DestHub: "HOU", ServiceClass: "expedite", SlotCount: 1, SlotCapacityKg: 8000, TransitMinutes: 1440, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-265", OriginHub: "OKC", DestHub: "MSP", ServiceClass: "standard", SlotCount: 2, SlotCapacityKg: 9500, TransitMinutes: 1485, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-266", OriginHub: "MEM", DestHub: "JAX", ServiceClass: "reefer", SlotCount: 3, SlotCapacityKg: 11000, TransitMinutes: 1530, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-267", OriginHub: "SEA", DestHub: "DFW", ServiceClass: "standard", SlotCount: 4, SlotCapacityKg: 12500, TransitMinutes: 1575, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-268", OriginHub: "JAX", DestHub: "RNO", ServiceClass: "flatbed", SlotCount: 5, SlotCapacityKg: 14000, TransitMinutes: 1620, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-269", OriginHub: "STL", DestHub: "MEM", ServiceClass: "reefer", SlotCount: 6, SlotCapacityKg: 15500, TransitMinutes: 1665, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-270", OriginHub: "HOU", DestHub: "YVR", ServiceClass: "expedite", SlotCount: 1, SlotCapacityKg: 17000, TransitMinutes: 1710, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-271", OriginHub: "ATL", DestHub: "HOU", ServiceClass: "expedite", SlotCount: 2, SlotCapacityKg: 18500, TransitMinutes: 1755, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-272", OriginHub: "MSP", DestHub: "OKC", ServiceClass: "intermodal", SlotCount: 3, SlotCapacityKg: 20000, TransitMinutes: 1800, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-273", OriginHub: "JAX", DestHub: "MEM", ServiceClass: "reefer", SlotCount: 4, SlotCapacityKg: 21500, TransitMinutes: 1845, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-274", OriginHub: "PHX", DestHub: "YVR", ServiceClass: "flatbed", SlotCount: 5, SlotCapacityKg: 23000, TransitMinutes: 1890, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-275", OriginHub: "SEA", DestHub: "YYZ", ServiceClass: "flatbed", SlotCount: 6, SlotCapacityKg: 8000, TransitMinutes: 1935, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-276", OriginHub: "MSP", DestHub: "HOU", ServiceClass: "reefer", SlotCount: 1, SlotCapacityKg: 9500, TransitMinutes: 1980, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-277", OriginHub: "STL", DestHub: "DFW", ServiceClass: "standard", SlotCount: 2, SlotCapacityKg: 11000, TransitMinutes: 2025, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-278", OriginHub: "HOU", DestHub: "SLC", ServiceClass: "intermodal", SlotCount: 3, SlotCapacityKg: 12500, TransitMinutes: 2070, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-279", OriginHub: "STL", DestHub: "JAX", ServiceClass: "intermodal", SlotCount: 4, SlotCapacityKg: 14000, TransitMinutes: 2115, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-280", OriginHub: "HOU", DestHub: "YYZ", ServiceClass: "flatbed", SlotCount: 5, SlotCapacityKg: 15500, TransitMinutes: 360, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-281", OriginHub: "HOU", DestHub: "STL", ServiceClass: "intermodal", SlotCount: 6, SlotCapacityKg: 17000, TransitMinutes: 405, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-282", OriginHub: "SLC", DestHub: "IND", ServiceClass: "flatbed", SlotCount: 1, SlotCapacityKg: 18500, TransitMinutes: 450, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-283", OriginHub: "HOU", DestHub: "KCK", ServiceClass: "reefer", SlotCount: 2, SlotCapacityKg: 20000, TransitMinutes: 495, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-284", OriginHub: "SLC", DestHub: "STL", ServiceClass: "bonded", SlotCount: 3, SlotCapacityKg: 21500, TransitMinutes: 540, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-285", OriginHub: "STL", DestHub: "MEM", ServiceClass: "intermodal", SlotCount: 4, SlotCapacityKg: 23000, TransitMinutes: 585, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-286", OriginHub: "BOS", DestHub: "HOU", ServiceClass: "expedite", SlotCount: 5, SlotCapacityKg: 8000, TransitMinutes: 630, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-287", OriginHub: "SLC", DestHub: "DTW", ServiceClass: "standard", SlotCount: 6, SlotCapacityKg: 9500, TransitMinutes: 675, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-288", OriginHub: "RNO", DestHub: "DTW", ServiceClass: "reefer", SlotCount: 1, SlotCapacityKg: 11000, TransitMinutes: 720, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-289", OriginHub: "SEA", DestHub: "MEM", ServiceClass: "reefer", SlotCount: 2, SlotCapacityKg: 12500, TransitMinutes: 765, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-290", OriginHub: "JAX", DestHub: "MSP", ServiceClass: "reefer", SlotCount: 3, SlotCapacityKg: 14000, TransitMinutes: 810, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-291", OriginHub: "YYZ", DestHub: "STL", ServiceClass: "expedite", SlotCount: 4, SlotCapacityKg: 15500, TransitMinutes: 855, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-292", OriginHub: "YYZ", DestHub: "SEA", ServiceClass: "flatbed", SlotCount: 5, SlotCapacityKg: 17000, TransitMinutes: 900, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-293", OriginHub: "STL", DestHub: "KCK", ServiceClass: "reefer", SlotCount: 6, SlotCapacityKg: 18500, TransitMinutes: 945, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-294", OriginHub: "IND", DestHub: "JAX", ServiceClass: "bonded", SlotCount: 1, SlotCapacityKg: 20000, TransitMinutes: 990, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-295", OriginHub: "SLC", DestHub: "DEN", ServiceClass: "standard", SlotCount: 2, SlotCapacityKg: 21500, TransitMinutes: 1035, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-296", OriginHub: "DEN", DestHub: "ATL", ServiceClass: "expedite", SlotCount: 3, SlotCapacityKg: 23000, TransitMinutes: 1080, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-297", OriginHub: "SEA", DestHub: "CHI", ServiceClass: "expedite", SlotCount: 4, SlotCapacityKg: 8000, TransitMinutes: 1125, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-298", OriginHub: "HOU", DestHub: "MSP", ServiceClass: "bonded", SlotCount: 5, SlotCapacityKg: 9500, TransitMinutes: 1170, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-299", OriginHub: "BOS", DestHub: "YYZ", ServiceClass: "expedite", SlotCount: 6, SlotCapacityKg: 11000, TransitMinutes: 1215, CrossDock: false})
	return out
}
