package tablex

// laneFill08 appends lane rows 480..519.
func laneFill08(out []LaneRow) []LaneRow {
	out = append(out, LaneRow{LaneID: "LN-480", OriginHub: "DTW", DestHub: "PDX", ServiceClass: "standard", SlotCount: 1, SlotCapacityKg: 18500, TransitMinutes: 360, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-481", OriginHub: "BOS", DestHub: "KCK", ServiceClass: "reefer", SlotCount: 2, SlotCapacityKg: 20000, TransitMinutes: 405, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-482", OriginHub: "PHX", DestHub: "YYZ", ServiceClass: "intermodal", SlotCount: 3, SlotCapacityKg: 21500, TransitMinutes: 450, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-483", OriginHub: "SEA", DestHub: "YVR", ServiceClass: "expedite", SlotCount: 4, SlotCapacityKg: 23000, TransitMinutes: 495, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-484", OriginHub: "KCK", DestHub: "IND", ServiceClass: "expedite", SlotCount: 5, SlotCapacityKg: 8000, TransitMinutes: 540, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-485", OriginHub: "JAX", DestHub: "LAX", ServiceClass: "reefer", SlotCount: 6, SlotCapacityKg: 9500, TransitMinutes: 585, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-486", OriginHub: "BOS", DestHub: "PHX", ServiceClass: "intermodal", SlotCount: 1, SlotCapacityKg: 11000, TransitMinutes: 630, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-487", OriginHub: "TPA", DestHub: "OKC", ServiceClass: "intermodal", SlotCount: 2, SlotCapacityKg: 12500, TransitMinutes: 675, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-488", OriginHub: "DFW", DestHub: "IND", ServiceClass: "expedite", SlotCount: 3, SlotCapacityKg: 14000, TransitMinutes: 720, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-489", OriginHub: "RNO", DestHub: "STL", ServiceClass: "expedite", SlotCount: 4, SlotCapacityKg: 15500, TransitMinutes: 765, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-490", OriginHub: "STL", DestHub: "KCK", ServiceClass: "reefer", SlotCount: 5, SlotCapacityKg: 17000, TransitMinutes: 810, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-491", OriginHub: "KCK", DestHub: "SEA", ServiceClass: "bonded", SlotCount: 6, SlotCapacityKg: 18500, TransitMinutes: 855, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-492", OriginHub: "KCK", DestHub: "PHX", ServiceClass: "bonded", SlotCount: 1, SlotCapacityKg: 20000, TransitMinutes: 900, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-493", OriginHub: "CHI", DestHub: "PHX", ServiceClass: "intermodal", SlotCount: 2, SlotCapacityKg: 21500, TransitMinutes: 945, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-494", OriginHub: "YVR", DestHub: "NSH", ServiceClass: "reefer", SlotCount: 3, SlotCapacityKg: 23000, TransitMinutes: 990, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-495", OriginHub: "PHX", DestHub: "DTW", ServiceClass: "reefer", SlotCount: 4, SlotCapacityKg: 8000, TransitMinutes: 1035, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-496", OriginHub: "YVR", DestHub: "PHX", ServiceClass: "intermodal", SlotCount: 5, SlotCapacityKg: 9500, TransitMinutes: 1080, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-497", OriginHub: "PHX", DestHub: "LAX", ServiceClass: "reefer", SlotCount: 6, SlotCapacityKg: 11000, TransitMinutes: 1125, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-498", OriginHub: "JAX", DestHub: "PDX", ServiceClass: "standard", SlotCount: 1, SlotCapacityKg: 12500, TransitMinutes: 1170, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-499", OriginHub: "YYZ", DestHub: "SEA", ServiceClass: "flatbed", SlotCount: 2, SlotCapacityKg: 14000, TransitMinutes: 1215, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-500", OriginHub: "MSP", DestHub: "YYZ", ServiceClass: "expedite", SlotCount: 3, SlotCapacityKg: 15500, TransitMinutes: 1260, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-501", OriginHub: "IND", DestHub: "SLC", ServiceClass: "intermodal", SlotCount: 4, SlotCapacityKg: 17000, TransitMinutes: 1305, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-502", OriginHub: "OKC", DestHub: "PHX", ServiceClass: "bonded", SlotCount: 5, SlotCapacityKg: 18500, TransitMinutes: 1350, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-503", OriginHub: "LAX", DestHub: "MSP", ServiceClass: "bonded", SlotCount: 6, SlotCapacityKg: 20000, TransitMinutes: 1395, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-504", OriginHub: "SEA", DestHub: "DTW", ServiceClass: "expedite", SlotCount: 1, SlotCapacityKg: 21500, TransitMinutes: 1440, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-505", OriginHub: "DEN", DestHub: "STL", ServiceClass: "flatbed", SlotCount: 2, SlotCapacityKg: 23000, TransitMinutes: 1485, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-506", OriginHub: "BOS", DestHub: "MSP", ServiceClass: "reefer", SlotCount: 3, SlotCapacityKg: 8000, TransitMinutes: 1530, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-507", OriginHub: "YYZ", DestHub: "BOS", ServiceClass: "standard", SlotCount: 4, SlotCapacityKg: 9500, TransitMinutes: 1575, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-508", OriginHub: "LAX", DestHub: "KCK", ServiceClass: "bonded", SlotCount: 5, SlotCapacityKg: 11000, TransitMinutes: 1620, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-509", OriginHub: "YYZ", DestHub: "CHI", ServiceClass: "reefer", SlotCount: 6, SlotCapacityKg: 12500, TransitMinutes: 1665, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-510", OriginHub: "KCK", DestHub: "YVR", ServiceClass: "flatbed", SlotCount: 1, SlotCapacityKg: 14000, TransitMinutes: 1710, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-511", OriginHub: "DTW", DestHub: "DEN", ServiceClass: "reefer", SlotCount: 2, SlotCapacityKg: 15500, TransitMinutes: 1755, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-512", OriginHub: "SEA", DestHub: "OKC", ServiceClass: "intermodal", SlotCount: 3, SlotCapacityKg: 17000, TransitMinutes: 1800, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-513", OriginHub: "STL", DestHub: "MEM", ServiceClass: "reefer", SlotCount: 4, SlotCapacityKg: 18500, TransitMinutes: 1845, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-514", OriginHub: "CHI", DestHub: "RNO", ServiceClass: "flatbed", SlotCount: 5, SlotCapacityKg: 20000, TransitMinutes: 1890, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-515", OriginHub: "RNO", DestHub: "MSP", ServiceClass: "intermodal", SlotCount: 6, SlotCapacityKg: 21500, TransitMinutes: 1935, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-516", OriginHub: "LAX", DestHub: "DEN", ServiceClass: "reefer", SlotCount: 1, SlotCapacityKg: 23000, TransitMinutes: 1980, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-517", OriginHub: "KCK", DestHub: "PHX", ServiceClass: "flatbed", SlotCount: 2, SlotCapacityKg: 8000, TransitMinutes: 2025, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-518", OriginHub: "DFW", DestHub: "NSH", ServiceClass: "standard", SlotCount: 3, SlotCapacityKg: 9500, TransitMinutes: 2070, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-519", OriginHub: "YVR", DestHub: "RNO", ServiceClass: "intermodal", SlotCount: 4, SlotCapacityKg: 11000, TransitMinutes: 2115, CrossDock: false})
	return out
}
