package tablex

// laneFill03 appends lane rows 180..239.
func laneFill03(out []LaneRow) []LaneRow {
	out = append(out, LaneRow{LaneID: "LN-180", OriginHub: "YVR", DestHub: "DEN", ServiceClass: "reefer", SlotCount: 1, SlotCapacityKg: 14000, TransitMinutes: 1260, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-181", OriginHub: "HOU", DestHub: "LAX", ServiceClass: "bonded", SlotCount: 2, SlotCapacityKg: 15500, TransitMinutes: 1305, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-182", OriginHub: "TPA", DestHub: "YYZ", ServiceClass: "intermodal", SlotCount: 3, SlotCapacityKg: 17000, TransitMinutes: 1350, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-183", OriginHub: "PHX", DestHub: "JAX", ServiceClass: "reefer", SlotCount: 4, SlotCapacityKg: 18500, TransitMinutes: 1395, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-184", OriginHub: "STL", DestHub: "SEA", ServiceClass: "expedite", SlotCount: 5, SlotCapacityKg: 20000, TransitMinutes: 1440, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-185", OriginHub: "SEA", DestHub: "ATL", ServiceClass: "expedite", SlotCount: 6, SlotCapacityKg: 21500, TransitMinutes: 1485, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-186", OriginHub: "RNO", DestHub: "OKC", ServiceClass: "reefer", SlotCount: 1, SlotCapacityKg: 23000, TransitMinutes: 1530, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-187", OriginHub: "BOS", DestHub: "SLC", ServiceClass: "flatbed", SlotCount: 2, SlotCapacityKg: 8000, TransitMinutes: 1575, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-188", OriginHub: "NSH", DestHub: "YVR", ServiceClass: "bonded", SlotCount: 3, SlotCapacityKg: 9500, TransitMinutes: 1620, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-189", OriginHub: "HOU", DestHub: "SLC", ServiceClass: "bonded", SlotCount: 4, SlotCapacityKg: 11000, TransitMinutes: 1665, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-190", OriginHub: "KCK", DestHub: "PHX", ServiceClass: "expedite", SlotCount: 5, SlotCapacityKg: 12500, TransitMinutes: 1710, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-191", OriginHub: "OKC", DestHub: "YYZ", ServiceClass: "flatbed", SlotCount: 6, SlotCapacityKg: 14000, TransitMinutes: 1755, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-192", OriginHub: "MSP", DestHub: "BOS", ServiceClass: "flatbed", SlotCount: 1, SlotCapacityKg: 15500, TransitMinutes: 1800, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-193", OriginHub: "NSH", DestHub: "SEA", ServiceClass: "expedite", SlotCount: 2, SlotCapacityKg: 17000, TransitMinutes: 1845, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-194", OriginHub: "SEA", DestHub: "NSH", ServiceClass: "bonded", SlotCount: 3, SlotCapacityKg: 18500, TransitMinutes: 1890, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-195", OriginHub: "DFW", DestHub: "IND", ServiceClass: "standard", SlotCount: 4, SlotCapacityKg: 20000, TransitMinutes: 1935, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-196", OriginHub: "NSH", DestHub: "PHX", ServiceClass: "bonded", SlotCount: 5, SlotCapacityKg: 21500, TransitMinutes: 1980, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-197", OriginHub: "SEA", DestHub: "YVR", ServiceClass: "bonded", SlotCount: 6, SlotCapacityKg: 23000, TransitMinutes: 2025, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-198", OriginHub: "DTW", DestHub: "CHI", ServiceClass: "expedite", SlotCount: 1, SlotCapacityKg: 8000, TransitMinutes: 2070, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-199", OriginHub: "BOS", DestHub: "STL", ServiceClass: "bonded", SlotCount: 2, SlotCapacityKg: 9500, TransitMinutes: 2115, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-200", OriginHub: "DEN", DestHub: "PDX", ServiceClass: "standard", SlotCount: 3, SlotCapacityKg: 11000, TransitMinutes: 360, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-201", OriginHub: "BOS", DestHub: "OKC", ServiceClass: "reefer", SlotCount: 4, SlotCapacityKg: 12500, TransitMinutes: 405, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-202", OriginHub: "HOU", DestHub: "OKC", ServiceClass: "intermodal", SlotCount: 5, SlotCapacityKg: 14000, TransitMinutes: 450, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-203", OriginHub: "PDX", DestHub: "NSH", ServiceClass: "standard", SlotCount: 6, SlotCapacityKg: 15500, TransitMinutes: 495, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-204", OriginHub: "LAX", DestHub: "YVR", ServiceClass: "flatbed", SlotCount: 1, SlotCapacityKg: 17000, TransitMinutes: 540, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-205", OriginHub: "CHI", DestHub: "HOU", ServiceClass: "reefer", SlotCount: 2, SlotCapacityKg: 18500, TransitMinutes: 585, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-206", OriginHub: "SLC", DestHub: "YYZ", ServiceClass: "expedite", SlotCount: 3, SlotCapacityKg: 20000, TransitMinutes: 630, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-207", OriginHub: "SEA", DestHub: "STL", ServiceClass: "bonded", SlotCount: 4, SlotCapacityKg: 21500, TransitMinutes: 675, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-208", OriginHub: "STL", DestHub: "TPA", ServiceClass: "bonded", SlotCount: 5, SlotCapacityKg: 23000, TransitMinutes: 720, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-209", OriginHub: "DFW", DestHub: "DFW", ServiceClass: "expedite", SlotCount: 6, SlotCapacityKg: 8000, TransitMinutes: 765, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-210", OriginHub: "DFW", DestHub: "SLC", ServiceClass: "flatbed", SlotCount: 1, SlotCapacityKg: 9500, TransitMinutes: 810, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-211", OriginHub: "LAX", DestHub: "YYZ", ServiceClass: "intermodal", SlotCount: 2, SlotCapacityKg: 11000, TransitMinutes: 855, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-212", OriginHub: "NSH", DestHub: "BOS", ServiceClass: "expedite", SlotCount: 3, SlotCapacityKg: 12500, TransitMinutes: 900, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-213", OriginHub: "STL", DestHub: "RNO", ServiceClass: "expedite", SlotCount: 4, SlotCapacityKg: 14000, TransitMinutes: 945, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-214", OriginHub: "KCK", DestHub: "PHX", ServiceClass: "flatbed", SlotCount: 5, SlotCapacityKg: 15500, TransitMinutes: 990, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-215", OriginHub: "RNO", DestHub: "RNO", ServiceClass: "intermodal", SlotCount: 6, SlotCapacityKg: 17000, TransitMinutes: 1035, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-216", OriginHub: "PHX", DestHub: "SLC", ServiceClass: "intermodal", SlotCount: 1, SlotCapacityKg: 18500, TransitMinutes: 1080, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-217", OriginHub: "JAX", DestHub: "PHX", ServiceClass: "intermodal", SlotCount: 2, SlotCapacityKg: 20000, TransitMinutes: 1125, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-218", OriginHub: "DTW", DestHub: "STL", ServiceClass: "expedite", SlotCount: 3, SlotCapacityKg: 21500, TransitMinutes: 1170, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-219", OriginHub: "HOU", DestHub: "TPA", ServiceClass: "expedite", SlotCount: 4, SlotCapacityKg: 23000, TransitMinutes: 1215, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-220", OriginHub: "ATL", DestHub: "MEM", ServiceClass: "intermodal", SlotCount: 5, SlotCapacityKg: 8000, TransitMinutes: 1260, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-221", OriginHub: "SEA", DestHub: "HOU", ServiceClass: "flatbed", SlotCount: 6, SlotCapacityKg: 9500, TransitMinutes: 1305, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-222", OriginHub: "LAX", DestHub: "MEM", ServiceClass: "standard", SlotCount: 1, SlotCapacityKg: 11000, TransitMinutes: 1350, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-223", OriginHub: "MEM", DestHub: "DTW", ServiceClass: "expedite", SlotCount: 2, SlotCapacityKg: 12500, TransitMinutes: 1395, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-224", OriginHub: "CHI", DestHub: "TPA", ServiceClass: "bonded", SlotCount: 3, SlotCapacityKg: 14000, TransitMinutes: 1440, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-225", OriginHub: "RNO", DestHub: "JAX", ServiceClass: "intermodal", SlotCount: 4, SlotCapacityKg: 15500, TransitMinutes: 1485, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-226", OriginHub: "LAX", DestHub: "LAX", ServiceClass: "intermodal", SlotCount: 5, SlotCapacityKg: 17000, TransitMinutes: 1530, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-227", OriginHub: "PDX", DestHub: "KCK", ServiceClass: "intermodal", SlotCount: 6, SlotCapacityKg: 18500, TransitMinutes: 1575, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-228", OriginHub: "ATL", DestHub: "TPA", ServiceClass: "flatbed", SlotCount: 1, SlotCapacityKg: 20000, TransitMinutes: 1620, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-229", OriginHub: "RNO", DestHub: "STL", ServiceClass: "bonded", SlotCount: 2, SlotCapacityKg: 21500, TransitMinutes: 1665, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-230", OriginHub: "LAX", DestHub: "ATL", ServiceClass: "expedite", SlotCount: 3, SlotCapacityKg: 23000, TransitMinutes: 1710, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-231", OriginHub: "CHI", DestHub: "MSP", ServiceClass: "reefer", SlotCount: 4, SlotCapacityKg: 8000, TransitMinutes: 1755, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-232", OriginHub: "KCK", DestHub: "BOS", ServiceClass: "reefer", SlotCount: 5, SlotCapacityKg: 9500, TransitMinutes: 1800, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-233", OriginHub: "RNO", DestHub: "YVR", ServiceClass: "bonded", SlotCount: 6, SlotCapacityKg: 11000, TransitMinutes: 1845, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-234", OriginHub: "DTW", DestHub: "MEM", ServiceClass: "bonded", SlotCount: 1, SlotCapacityKg: 12500, TransitMinutes: 1890, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-235", OriginHub: "MEM", DestHub: "TPA", ServiceClass: "bonded", SlotCount: 2, SlotCapacityKg: 14000, TransitMinutes: 1935, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-236", OriginHub: "DFW", DestHub: "ATL", ServiceClass: "flatbed", SlotCount: 3, SlotCapacityKg: 15500, TransitMinutes: 1980, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-237", OriginHub: "STL", DestHub: "DFW", ServiceClass: "reefer", SlotCount: 4, SlotCapacityKg: 17000, TransitMinutes: 2025, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-238", OriginHub: "KCK", DestHub: "NSH", ServiceClass: "bonded", SlotCount: 5, SlotCapacityKg: 18500, TransitMinutes: 2070, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-239", OriginHub: "JAX", DestHub: "RNO", ServiceClass: "intermodal", SlotCount: 6, SlotCapacityKg: 20000, TransitMinutes: 2115, CrossDock: false})
	return out
}
