package tablex

// laneFill01 appends lane rows 60..119.
func laneFill01(out []LaneRow) []LaneRow {
	out = append(out, LaneRow{LaneID: "LN-060", OriginHub: "NSH", DestHub: "KCK", ServiceClass: "intermodal", SlotCount: 1, SlotCapacityKg: 15500, TransitMinutes: 1260, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-061", OriginHub: "MSP", DestHub: "NSH", ServiceClass: "standard", SlotCount: 2, SlotCapacityKg: 17000, TransitMinutes: 1305, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-062", OriginHub: "DTW", DestHub: "HOU", ServiceClass: "flatbed", SlotCount: 3, SlotCapacityKg: 18500, TransitMinutes: 1350, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-063", OriginHub: "YYZ", DestHub: "OKC", ServiceClass: "reefer", SlotCount: 4, SlotCapacityKg: 20000, TransitMinutes: 1395, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-064", OriginHub: "SEA", DestHub: "NSH", ServiceClass: "reefer", SlotCount: 5, SlotCapacityKg: 21500, TransitMinutes: 1440, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-065", OriginHub: "OKC", DestHub: "BOS", ServiceClass: "expedite", SlotCount: 6, SlotCapacityKg: 23000, TransitMinutes: 1485, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-066", OriginHub: "LAX", DestHub: "PHX", ServiceClass: "expedite", SlotCount: 1, SlotCapacityKg: 8000, TransitMinutes: 1530, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-067", OriginHub: "STL", DestHub: "HOU", ServiceClass: "expedite", SlotCount: 2, SlotCapacityKg: 9500, TransitMinutes: 1575, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-068", OriginHub: "MSP", DestHub: "ATL", ServiceClass: "flatbed", SlotCount: 3, SlotCapacityKg: 11000, TransitMinutes: 1620, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-069", OriginHub: "CHI", DestHub: "OKC", ServiceClass: "bonded", SlotCount: 4, SlotCapacityKg: 12500, TransitMinutes: 1665, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-070", OriginHub: "YVR", DestHub: "NSH", ServiceClass: "bonded", SlotCount: 5, SlotCapacityKg: 14000, TransitMinutes: 1710, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-071", OriginHub: "RNO", DestHub: "DTW", ServiceClass: "reefer", SlotCount: 6, SlotCapacityKg: 15500, TransitMinutes: 1755, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-072", OriginHub: "CHI", DestHub: "MEM", ServiceClass: "intermodal", SlotCount: 1, SlotCapacityKg: 17000, TransitMinutes: 1800, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-073", OriginHub: "STL", DestHub: "IND", ServiceClass: "reefer", SlotCount: 2, SlotCapacityKg: 18500, TransitMinutes: 1845, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-074", OriginHub: "HOU", DestHub: "KCK", ServiceClass: "intermodal", SlotCount: 3, SlotCapacityKg: 20000, TransitMinutes: 1890, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-075", OriginHub: "DFW", DestHub: "DFW", ServiceClass: "standard", SlotCount: 4, SlotCapacityKg: 21500, TransitMinutes: 1935, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-076", OriginHub: "IND", DestHub: "KCK", ServiceClass: "reefer", SlotCount: 5, SlotCapacityKg: 23000, TransitMinutes: 1980, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-077", OriginHub: "TPA", DestHub: "STL", ServiceClass: "intermodal", SlotCount: 6, SlotCapacityKg: 8000, TransitMinutes: 2025, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-078", OriginHub: "IND", DestHub: "KCK", ServiceClass: "bonded", SlotCount: 1, SlotCapacityKg: 9500, TransitMinutes: 2070, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-079", OriginHub: "DEN", DestHub: "JAX", ServiceClass: "bonded", SlotCount: 2, SlotCapacityKg: 11000, TransitMinutes: 2115, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-080", OriginHub: "LAX", DestHub: "PHX", ServiceClass: "intermodal", SlotCount: 3, SlotCapacityKg: 12500, TransitMinutes: 360, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-081", OriginHub: "CHI", DestHub: "YVR", ServiceClass: "expedite", SlotCount: 4, SlotCapacityKg: 14000, TransitMinutes: 405, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-082", OriginHub: "JAX", DestHub: "NSH", ServiceClass: "bonded", SlotCount: 5, SlotCapacityKg: 15500, TransitMinutes: 450, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-083", OriginHub: "STL", DestHub: "YYZ", ServiceClass: "expedite", SlotCount: 6, SlotCapacityKg: 17000, TransitMinutes: 495, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-084", OriginHub: "LAX", DestHub: "LAX", ServiceClass: "reefer", SlotCount: 1, SlotCapacityKg: 18500, TransitMinutes: 540, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-085", OriginHub: "DFW", DestHub: "HOU", ServiceClass: "expedite", SlotCount: 2, SlotCapacityKg: 20000, TransitMinutes: 585, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-086", OriginHub: "SLC", DestHub: "BOS", ServiceClass: "standard", SlotCount: 3, SlotCapacityKg: 21500, TransitMinutes: 630, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-087", OriginHub: "LAX", DestHub: "CHI", ServiceClass: "expedite", SlotCount: 4, SlotCapacityKg: 23000, TransitMinutes: 675, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-088", OriginHub: "DEN", DestHub: "BOS", ServiceClass: "standard", SlotCount: 5, SlotCapacityKg: 8000, TransitMinutes: 720, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-089", OriginHub: "SEA", DestHub: "STL", ServiceClass: "intermodal", SlotCount: 6, SlotCapacityKg: 9500, TransitMinutes: 765, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-090", OriginHub: "PDX", DestHub: "STL", ServiceClass: "expedite", SlotCount: 1, SlotCapacityKg: 11000, TransitMinutes: 810, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-091", OriginHub: "OKC", DestHub: "BOS", ServiceClass: "flatbed", SlotCount: 2, SlotCapacityKg: 12500, TransitMinutes: 855, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-092", OriginHub: "NSH", DestHub: "LAX", ServiceClass: "reefer", SlotCount: 3, SlotCapacityKg: 14000, TransitMinutes: 900, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-093", OriginHub: "KCK", DestHub: "ATL", ServiceClass: "reefer", SlotCount: 4, SlotCapacityKg: 15500, TransitMinutes: 945, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-094", OriginHub: "ATL", DestHub: "STL", ServiceClass: "expedite", SlotCount: 5, SlotCapacityKg: 17000, TransitMinutes: 990, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-095", OriginHub: "KCK", DestHub: "SEA", ServiceClass: "flatbed", SlotCount: 6, SlotCapacityKg: 18500, TransitMinutes: 1035, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-096", OriginHub: "CHI", DestHub: "LAX", ServiceClass: "intermodal", SlotCount: 1, SlotCapacityKg: 20000, TransitMinutes: 1080, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-097", OriginHub: "DTW", DestHub: "OKC", ServiceClass: "standard", SlotCount: 2, SlotCapacityKg: 21500, TransitMinutes: 1125, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-098", OriginHub: "BOS", DestHub: "STL", ServiceClass: "flatbed", SlotCount: 3, SlotCapacityKg: 23000, TransitMinutes: 1170, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-099", OriginHub: "DTW", DestHub: "OKC", ServiceClass: "bonded", SlotCount: 4, SlotCapacityKg: 8000, TransitMinutes: 1215, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-100", OriginHub: "CHI", DestHub: "BOS", ServiceClass: "standard", SlotCount: 5, SlotCapacityKg: 9500, TransitMinutes: 1260, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-101", OriginHub: "CHI", DestHub: "RNO", ServiceClass: "flatbed", SlotCount: 6, SlotCapacityKg: 11000, TransitMinutes: 1305, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-102", OriginHub: "PHX", DestHub: "DTW", ServiceClass: "reefer", SlotCount: 1, SlotCapacityKg: 12500, TransitMinutes: 1350, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-103", OriginHub: "MSP", DestHub: "LAX", ServiceClass: "bonded", SlotCount: 2, SlotCapacityKg: 14000, TransitMinutes: 1395, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-104", OriginHub: "PDX", DestHub: "CHI", ServiceClass: "flatbed", SlotCount: 3, SlotCapacityKg: 15500, TransitMinutes: 1440, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-105", OriginHub: "TPA", DestHub: "BOS", ServiceClass: "flatbed", SlotCount: 4, SlotCapacityKg: 17000, TransitMinutes: 1485, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-106", OriginHub: "MSP", DestHub: "STL", ServiceClass: "intermodal", SlotCount: 5, SlotCapacityKg: 18500, TransitMinutes: 1530, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-107", OriginHub: "OKC", DestHub: "LAX", ServiceClass: "bonded", SlotCount: 6, SlotCapacityKg: 20000, TransitMinutes: 1575, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-108", OriginHub: "LAX", DestHub: "YYZ", ServiceClass: "bonded", SlotCount: 1, SlotCapacityKg: 21500, TransitMinutes: 1620, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-109", OriginHub: "JAX", DestHub: "PHX", ServiceClass: "expedite", SlotCount: 2, SlotCapacityKg: 23000, TransitMinutes: 1665, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-110", OriginHub: "SLC", DestHub: "CHI", ServiceClass: "standard", SlotCount: 3, SlotCapacityKg: 8000, TransitMinutes: 1710, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-111", OriginHub: "HOU", DestHub: "SLC", ServiceClass: "flatbed", SlotCount: 4, SlotCapacityKg: 9500, TransitMinutes: 1755, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-112", OriginHub: "STL", DestHub: "PDX", ServiceClass: "reefer", SlotCount: 5, SlotCapacityKg: 11000, TransitMinutes: 1800, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-113", OriginHub: "MSP", DestHub: "OKC", ServiceClass: "reefer", SlotCount: 6, SlotCapacityKg: 12500, TransitMinutes: 1845, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-114", OriginHub: "NSH", DestHub: "YYZ", ServiceClass: "intermodal", SlotCount: 1, SlotCapacityKg: 14000, TransitMinutes: 1890, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-115", OriginHub: "IND", DestHub: "SLC", ServiceClass: "flatbed", SlotCount: 2, SlotCapacityKg: 15500, TransitMinutes: 1935, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-116", OriginHub: "PHX", DestHub: "JAX", ServiceClass: "standard", SlotCount: 3, SlotCapacityKg: 17000, TransitMinutes: 1980, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-117", OriginHub: "TPA", DestHub: "KCK", ServiceClass: "intermodal", SlotCount: 4, SlotCapacityKg: 18500, TransitMinutes: 2025, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-118", OriginHub: "SLC", DestHub: "HOU", ServiceClass: "flatbed", SlotCount: 5, SlotCapacityKg: 20000, TransitMinutes: 2070, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-119", OriginHub: "BOS", DestHub: "DFW", ServiceClass: "flatbed", SlotCount: 6, SlotCapacityKg: 21500, TransitMinutes: 2115, CrossDock: true})
	return out
}
