package tablex

// laneFill00 appends lane rows 0..59.
func laneFill00(out []LaneRow) []LaneRow {
	out = append(out, LaneRow{LaneID: "LN-000", OriginHub: "HOU", DestHub: "PDX", ServiceClass: "standard", SlotCount: 1, SlotCapacityKg: 8000, TransitMinutes: 360, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-001", OriginHub: "IND", DestHub: "OKC", ServiceClass: "standard", SlotCount: 2, SlotCapacityKg: 9500, TransitMinutes: 405, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-002", OriginHub: "CHI", DestHub: "DTW", ServiceClass: "flatbed", SlotCount: 3, SlotCapacityKg: 11000, TransitMinutes: 450, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-003", OriginHub: "IND", DestHub: "MSP", ServiceClass: "reefer", SlotCount: 4, SlotCapacityKg: 12500, TransitMinutes: 495, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-004", OriginHub: "PHX", DestHub: "PDX", ServiceClass: "intermodal", SlotCount: 5, SlotCapacityKg: 14000, TransitMinutes: 540, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-005", OriginHub: "SLC", DestHub: "OKC", ServiceClass: "standard", SlotCount: 6, SlotCapacityKg: 15500, TransitMinutes: 585, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-006", OriginHub: "YVR", DestHub: "NSH", ServiceClass: "bonded", SlotCount: 1, SlotCapacityKg: 17000, TransitMinutes: 630, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-007", OriginHub: "NSH", DestHub: "NSH", ServiceClass: "intermodal", SlotCount: 2, SlotCapacityKg: 18500, TransitMinutes: 675, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-008", OriginHub: "CHI", DestHub: "PDX", ServiceClass: "reefer", SlotCount: 3, SlotCapacityKg: 20000, TransitMinutes: 720, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-009", OriginHub: "JAX", DestHub: "CHI", ServiceClass: "expedite", SlotCount: 4, SlotCapacityKg: 21500, TransitMinutes: 765, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-010", OriginHub: "YVR", DestHub: "LAX", ServiceClass: "standard", SlotCount: 5, SlotCapacityKg: 23000, TransitMinutes: 810, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-011", OriginHub: "RNO", DestHub: "RNO", ServiceClass: "expedite", SlotCount: 6, SlotCapacityKg: 8000, TransitMinutes: 855, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-012", OriginHub: "ATL", DestHub: "DTW", ServiceClass: "expedite", SlotCount: 1, SlotCapacityKg: 9500, TransitMinutes: 900, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-013", OriginHub: "HOU", DestHub: "DFW", ServiceClass: "reefer", SlotCount: 2, SlotCapacityKg: 11000, TransitMinutes: 945, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-014", OriginHub: "SLC", DestHub: "OKC", ServiceClass: "reefer", SlotCount: 3, SlotCapacityKg: 12500, TransitMinutes: 990, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-015", OriginHub: "JAX", DestHub: "RNO", ServiceClass: "intermodal", SlotCount: 4, SlotCapacityKg: 14000, TransitMinutes: 1035, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-016", OriginHub: "DEN", DestHub: "TPA", ServiceClass: "expedite", SlotCount: 5, SlotCapacityKg: 15500, TransitMinutes: 1080, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-017", OriginHub: "RNO", DestHub: "LAX", ServiceClass: "standard", SlotCount: 6, SlotCapacityKg: 17000, TransitMinutes: 1125, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-018", OriginHub: "MSP", DestHub: "PDX", ServiceClass: "bonded", SlotCount: 1, SlotCapacityKg: 18500, TransitMinutes: 1170, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-019", OriginHub: "JAX", DestHub: "JAX", ServiceClass: "intermodal", SlotCount: 2, SlotCapacityKg: 20000, TransitMinutes: 1215, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-020", OriginHub: "RNO", DestHub: "DFW", ServiceClass: "expedite", SlotCount: 3, SlotCapacityKg: 21500, TransitMinutes: 1260, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-021", OriginHub: "KCK", DestHub: "IND", ServiceClass: "reefer", SlotCount: 4, SlotCapacityKg: 23000, TransitMinutes: 1305, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-022", OriginHub: "RNO", DestHub: "MEM", ServiceClass: "standard", SlotCount: 5, SlotCapacityKg: 8000, TransitMinutes: 1350, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-023", OriginHub: "DFW", DestHub: "TPA", ServiceClass: "flatbed", SlotCount: 6, SlotCapacityKg: 9500, TransitMinutes: 1395, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-024", OriginHub: "ATL", DestHub: "TPA", ServiceClass: "bonded", SlotCount: 1, SlotCapacityKg: 11000, TransitMinutes: 1440, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-025", OriginHub: "ATL", DestHub: "IND", ServiceClass: "standard", SlotCount: 2, SlotCapacityKg: 12500, TransitMinutes: 1485, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-026", OriginHub: "KCK", DestHub: "DTW", ServiceClass: "flatbed", SlotCount: 3, SlotCapacityKg: 14000, TransitMinutes: 1530, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-027", OriginHub: "JAX", DestHub: "RNO", ServiceClass: "expedite", SlotCount: 4, SlotCapacityKg: 15500, TransitMinutes: 1575, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-028", OriginHub: "YYZ", DestHub: "CHI", ServiceClass: "flatbed", SlotCount: 5, SlotCapacityKg: 17000, TransitMinutes: 1620, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-029", OriginHub: "STL", DestHub: "RNO", ServiceClass: "intermodal", SlotCount: 6, SlotCapacityKg: 18500, TransitMinutes: 1665, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-030", OriginHub: "RNO", DestHub: "MSP", ServiceClass: "bonded", SlotCount: 1, SlotCapacityKg: 20000, TransitMinutes: 1710, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-031", OriginHub: "LAX", DestHub: "LAX", ServiceClass: "standard", SlotCount: 2, SlotCapacityKg: 21500, TransitMinutes: 1755, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-032", OriginHub: "SLC", DestHub: "JAX", ServiceClass: "bonded", SlotCount: 3, SlotCapacityKg: 23000, TransitMinutes: 1800, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-033", OriginHub: "LAX", DestHub: "OKC", ServiceClass: "reefer", SlotCount: 4, SlotCapacityKg: 8000, TransitMinutes: 1845, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-034", OriginHub: "TPA", DestHub: "MEM", ServiceClass: "standard", SlotCount: 5, SlotCapacityKg: 9500, TransitMinutes: 1890, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-035", OriginHub: "STL", DestHub: "YYZ", ServiceClass: "flatbed", SlotCount: 6, SlotCapacityKg: 11000, TransitMinutes: 1935, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-036", OriginHub: "YVR", DestHub: "BOS", ServiceClass: "expedite", SlotCount: 1, SlotCapacityKg: 12500, TransitMinutes: 1980, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-037", OriginHub: "STL", DestHub: "MEM", ServiceClass: "reefer", SlotCount: 2, SlotCapacityKg: 14000, TransitMinutes: 2025, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-038", OriginHub: "YYZ", DestHub: "YVR", ServiceClass: "intermodal", SlotCount: 3, SlotCapacityKg: 15500, TransitMinutes: 2070, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-039", OriginHub: "CHI", DestHub: "DFW", ServiceClass: "standard", SlotCount: 4, SlotCapacityKg: 17000, TransitMinutes: 2115, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-040", OriginHub: "BOS", DestHub: "TPA", ServiceClass: "flatbed", SlotCount: 5, SlotCapacityKg: 18500, TransitMinutes: 360, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-041", OriginHub: "STL", DestHub: "BOS", ServiceClass: "flatbed", SlotCount: 6, SlotCapacityKg: 20000, TransitMinutes: 405, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-042", OriginHub: "PHX", DestHub: "TPA", ServiceClass: "intermodal", SlotCount: 1, SlotCapacityKg: 21500, TransitMinutes: 450, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-043", OriginHub: "RNO", DestHub: "RNO", ServiceClass: "expedite", SlotCount: 2, SlotCapacityKg: 23000, TransitMinutes: 495, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-044", OriginHub: "CHI", DestHub: "PDX", ServiceClass: "reefer", SlotCount: 3, SlotCapacityKg: 8000, TransitMinutes: 540, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-045", OriginHub: "PHX", DestHub: "DTW", ServiceClass: "flatbed", SlotCount: 4, SlotCapacityKg: 9500, TransitMinutes: 585, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-046", OriginHub: "HOU", DestHub: "DFW", ServiceClass: "reefer", SlotCount: 5, SlotCapacityKg: 11000, TransitMinutes: 630, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-047", OriginHub: "ATL", DestHub: "SLC", ServiceClass: "bonded", SlotCount: 6, SlotCapacityKg: 12500, TransitMinutes: 675, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-048", OriginHub: "SEA", DestHub: "DTW", ServiceClass: "flatbed", SlotCount: 1, SlotCapacityKg: 14000, TransitMinutes: 720, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-049", OriginHub: "YVR", DestHub: "RNO", ServiceClass: "intermodal", SlotCount: 2, SlotCapacityKg: 15500, TransitMinutes: 765, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-050", OriginHub: "STL", DestHub: "KCK", ServiceClass: "intermodal", SlotCount: 3, SlotCapacityKg: 17000, TransitMinutes: 810, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-051", OriginHub: "STL", DestHub: "NSH", ServiceClass: "standard", SlotCount: 4, SlotCapacityKg: 18500, TransitMinutes: 855, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-052", OriginHub: "OKC", DestHub: "DEN", ServiceClass: "flatbed", SlotCount: 5, SlotCapacityKg: 20000, TransitMinutes: 900, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-053", OriginHub: "TPA", DestHub: "JAX", ServiceClass: "reefer", SlotCount: 6, SlotCapacityKg: 21500, TransitMinutes: 945, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-054", OriginHub: "MSP", DestHub: "DEN", ServiceClass: "flatbed", SlotCount: 1, SlotCapacityKg: 23000, TransitMinutes: 990, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-055", OriginHub: "YVR", DestHub: "TPA", ServiceClass: "expedite", SlotCount: 2, SlotCapacityKg: 8000, TransitMinutes: 1035, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-056", OriginHub: "TPA", DestHub: "YYZ", ServiceClass: "flatbed", SlotCount: 3, SlotCapacityKg: 9500, TransitMinutes: 1080, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-057", OriginHub: "BOS", DestHub: "TPA", ServiceClass: "flatbed", SlotCount: 4, SlotCapacityKg: 11000, TransitMinutes: 1125, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-058", OriginHub: "TPA", DestHub: "MSP", ServiceClass: "reefer", SlotCount: 5, SlotCapacityKg: 12500, TransitMinutes: 1170, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-059", OriginHub: "MEM", DestHub: "NSH", ServiceClass: "standard", SlotCount: 6, SlotCapacityKg: 14000, TransitMinutes: 1215, CrossDock: false})
	return out
}
