package tablex

// laneFill02 appends lane rows 120..179.
func laneFill02(out []LaneRow) []LaneRow {
	out = append(out, LaneRow{LaneID: "LN-120", OriginHub: "NSH", DestHub: "MEM", ServiceClass: "standard", SlotCount: 1, SlotCapacityKg: 23000, TransitMinutes: 360, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-121", OriginHub: "MEM", DestHub: "YYZ", ServiceClass: "bonded", SlotCount: 2, SlotCapacityKg: 8000, TransitMinutes: 405, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-122", OriginHub: "SLC", DestHub: "RNO", ServiceClass: "intermodal", SlotCount: 3, SlotCapacityKg: 9500, TransitMinutes: 450, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-123", OriginHub: "PDX", DestHub: "STL", ServiceClass: "intermodal", SlotCount: 4, SlotCapacityKg: 11000, TransitMinutes: 495, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-124", OriginHub: "PHX", DestHub: "YYZ", ServiceClass: "bonded", SlotCount: 5, SlotCapacityKg: 12500, TransitMinutes: 540, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-125", OriginHub: "DFW", DestHub: "SLC", ServiceClass: "flatbed", SlotCount: 6, SlotCapacityKg: 14000, TransitMinutes: 585, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-126", OriginHub: "DTW", DestHub: "IND", ServiceClass: "expedite", SlotCount: 1, SlotCapacityKg: 15500, TransitMinutes: 630, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-127", OriginHub: "JAX", DestHub: "BOS", ServiceClass: "flatbed", SlotCount: 2, SlotCapacityKg: 17000, TransitMinutes: 675, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-128", OriginHub: "YYZ", DestHub: "DTW", ServiceClass: "reefer", SlotCount: 3, SlotCapacityKg: 18500, TransitMinutes: 720, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-129", OriginHub: "DFW", DestHub: "TPA", ServiceClass: "bonded", SlotCount: 4, SlotCapacityKg: 20000, TransitMinutes: 765, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-130", OriginHub: "OKC", DestHub: "STL", ServiceClass: "bonded", SlotCount: 5, SlotCapacityKg: 21500, TransitMinutes: 810, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-131", OriginHub: "YVR", DestHub: "YYZ", ServiceClass: "flatbed", SlotCount: 6, SlotCapacityKg: 23000, TransitMinutes: 855, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-132", OriginHub: "BOS", DestHub: "IND", ServiceClass: "reefer", SlotCount: 1, SlotCapacityKg: 8000, TransitMinutes: 900, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-133", OriginHub: "JAX", DestHub: "DEN", ServiceClass: "standard", SlotCount: 2, SlotCapacityKg: 9500, TransitMinutes: 945, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-134", OriginHub: "DFW", DestHub: "NSH", ServiceClass: "bonded", SlotCount: 3, SlotCapacityKg: 11000, TransitMinutes: 990, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-135", OriginHub: "HOU", DestHub: "PDX", ServiceClass: "bonded", SlotCount: 4, SlotCapacityKg: 12500, TransitMinutes: 1035, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-136", OriginHub: "IND", DestHub: "DFW", ServiceClass: "standard", SlotCount: 5, SlotCapacityKg: 14000, TransitMinutes: 1080, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-137", OriginHub: "JAX", DestHub: "STL", ServiceClass: "bonded", SlotCount: 6, SlotCapacityKg: 15500, TransitMinutes: 1125, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-138", OriginHub: "DFW", DestHub: "BOS", ServiceClass: "flatbed", SlotCount: 1, SlotCapacityKg: 17000, TransitMinutes: 1170, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-139", OriginHub: "TPA", DestHub: "MSP", ServiceClass: "intermodal", SlotCount: 2, SlotCapacityKg: 18500, TransitMinutes: 1215, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-140", OriginHub: "BOS", DestHub: "TPA", ServiceClass: "flatbed", SlotCount: 3, SlotCapacityKg: 20000, TransitMinutes: 1260, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-141", OriginHub: "RNO", DestHub: "DTW", ServiceClass: "flatbed", SlotCount: 4, SlotCapacityKg: 21500, TransitMinutes: 1305, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-142", OriginHub: "PHX", DestHub: "JAX", ServiceClass: "intermodal", SlotCount: 5, SlotCapacityKg: 23000, TransitMinutes: 1350, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-143", OriginHub: "MSP", DestHub: "YYZ", ServiceClass: "expedite", SlotCount: 6, SlotCapacityKg: 8000, TransitMinutes: 1395, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-144", OriginHub: "SEA", DestHub: "STL", ServiceClass: "bonded", SlotCount: 1, SlotCapacityKg: 9500, TransitMinutes: 1440, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-145", OriginHub: "PHX", DestHub: "CHI", ServiceClass: "reefer", SlotCount: 2, SlotCapacityKg: 11000, TransitMinutes: 1485, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-146", OriginHub: "STL", DestHub: "STL", ServiceClass: "bonded", SlotCount: 3, SlotCapacityKg: 12500, TransitMinutes: 1530, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-147", OriginHub: "MEM", DestHub: "NSH", ServiceClass: "intermodal", SlotCount: 4, SlotCapacityKg: 14000, TransitMinutes: 1575, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-148", OriginHub: "NSH", DestHub: "DEN", ServiceClass: "flatbed", SlotCount: 5, SlotCapacityKg: 15500, TransitMinutes: 1620, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-149", OriginHub: "BOS", DestHub: "PHX", ServiceClass: "intermodal", SlotCount: 6, SlotCapacityKg: 17000, TransitMinutes: 1665, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-150", OriginHub: "PDX", DestHub: "SEA", ServiceClass: "flatbed", SlotCount: 1, SlotCapacityKg: 18500, TransitMinutes: 1710, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-151", OriginHub: "MEM", DestHub: "SEA", ServiceClass: "expedite", SlotCount: 2, SlotCapacityKg: 20000, TransitMinutes: 1755, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-152", OriginHub: "MSP", DestHub: "PHX", ServiceClass: "bonded", SlotCount: 3, SlotCapacityKg: 21500, TransitMinutes: 1800, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-153", OriginHub: "DTW", DestHub: "STL", ServiceClass: "bonded", SlotCount: 4, SlotCapacityKg: 23000, TransitMinutes: 1845, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-154", OriginHub: "NSH", DestHub: "ATL", ServiceClass: "standard", SlotCount: 5, SlotCapacityKg: 8000, TransitMinutes: 1890, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-155", OriginHub: "YYZ", DestHub: "OKC", ServiceClass: "standard", SlotCount: 6, SlotCapacityKg: 9500, TransitMinutes: 1935, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-156", OriginHub: "YVR", DestHub: "PHX", ServiceClass: "flatbed", SlotCount: 1, SlotCapacityKg: 11000, TransitMinutes: 1980, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-157", OriginHub: "JAX", DestHub: "MSP", ServiceClass: "reefer", SlotCount: 2, SlotCapacityKg: 12500, TransitMinutes: 2025, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-158", OriginHub: "DTW", DestHub: "NSH", ServiceClass: "bonded", SlotCount: 3, SlotCapacityKg: 14000, TransitMinutes: 2070, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-159", OriginHub: "ATL", DestHub: "TPA", ServiceClass: "expedite", SlotCount: 4, SlotCapacityKg: 15500, TransitMinutes: 2115, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-160", OriginHub: "SEA", DestHub: "IND", ServiceClass: "flatbed", SlotCount: 5, SlotCapacityKg: 17000, TransitMinutes: 360, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-161", OriginHub: "DTW", DestHub: "SLC", ServiceClass: "intermodal", SlotCount: 6, SlotCapacityKg: 18500, TransitMinutes: 405, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-162", OriginHub: "SEA", DestHub: "ATL", ServiceClass: "flatbed", SlotCount: 1, SlotCapacityKg: 20000, TransitMinutes: 450, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-163", OriginHub: "TPA", DestHub: "TPA", ServiceClass: "intermodal", SlotCount: 2, SlotCapacityKg: 21500, TransitMinutes: 495, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-164", OriginHub: "TPA", DestHub: "JAX", ServiceClass: "intermodal", SlotCount: 3, SlotCapacityKg: 23000, TransitMinutes: 540, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-165", OriginHub: "CHI", DestHub: "JAX", ServiceClass: "standard", SlotCount: 4, SlotCapacityKg: 8000, TransitMinutes: 585, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-166", OriginHub: "KCK", DestHub: "SEA", ServiceClass: "flatbed", SlotCount: 5, SlotCapacityKg: 9500, TransitMinutes: 630, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-167", OriginHub: "IND", DestHub: "KCK", ServiceClass: "bonded", SlotCount: 6, SlotCapacityKg: 11000, TransitMinutes: 675, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-168", OriginHub: "MEM", DestHub: "CHI", ServiceClass: "standard", SlotCount: 1, SlotCapacityKg: 12500, TransitMinutes: 720, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-169", OriginHub: "BOS", DestHub: "ATL", ServiceClass: "expedite", SlotCount: 2, SlotCapacityKg: 14000, TransitMinutes: 765, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-170", OriginHub: "BOS", DestHub: "IND", ServiceClass: "flatbed", SlotCount: 3, SlotCapacityKg: 15500, TransitMinutes: 810, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-171", OriginHub: "NSH", DestHub: "IND", ServiceClass: "flatbed", SlotCount: 4, SlotCapacityKg: 17000, TransitMinutes: 855, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-172", OriginHub: "DEN", DestHub: "MSP", ServiceClass: "bonded", SlotCount: 5, SlotCapacityKg: 18500, TransitMinutes: 900, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-173", OriginHub: "CHI", DestHub: "IND", ServiceClass: "flatbed", SlotCount: 6, SlotCapacityKg: 20000, TransitMinutes: 945, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-174", OriginHub: "BOS", DestHub: "MSP", ServiceClass: "standard", SlotCount: 1, SlotCapacityKg: 21500, TransitMinutes: 990, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-175", OriginHub: "YYZ", DestHub: "DFW", ServiceClass: "expedite", SlotCount: 2, SlotCapacityKg: 23000, TransitMinutes: 1035, CrossDock: true})
	out = append(out, LaneRow{LaneID: "LN-176", OriginHub: "OKC", DestHub: "IND", ServiceClass: "standard", SlotCount: 3, SlotCapacityKg: 8000, TransitMinutes: 1080, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-177", OriginHub: "STL", DestHub: "MSP", ServiceClass: "standard", SlotCount: 4, SlotCapacityKg: 9500, TransitMinutes: 1125, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-178", OriginHub: "DFW", DestHub: "STL", ServiceClass: "flatbed", SlotCount: 5, SlotCapacityKg: 11000, TransitMinutes: 1170, CrossDock: false})
	out = append(out, LaneRow{LaneID: "LN-179", OriginHub: "SLC", DestHub: "YYZ", ServiceClass: "bonded", SlotCount: 6, SlotCapacityKg: 12500, TransitMinutes: 1215, CrossDock: false})
	return out
}
