package tablex

// tariffFill01 appends tariff rows 60..95.
func tariffFill01(out []TariffRow) []TariffRow {
	out = append(out, TariffRow{GroupCode: "G07", Band: "B4", RateCents: 1045})
	out = append(out, TariffRow{GroupCode: "G07", Band: "B5", RateCents: 1170})
	out = append(out, TariffRow{GroupCode: "G07", Band: "B6", RateCents: 1238})
	out = append(out, TariffRow{GroupCode: "G07", Band: "B7", RateCents: 1306})
	out = append(out, TariffRow{GroupCode: "G08", Band: "B0", RateCents: 696})
	out = append(out, TariffRow{GroupCode: "G08", Band: "B1", RateCents: 834})
	out = append(out, TariffRow{GroupCode: "G08", Band: "B2", RateCents: 915})
	out = append(out, TariffRow{GroupCode: "G08", Band: "B3", RateCents: 996})
	out = append(out, TariffRow{GroupCode: "G08", Band: "B4", RateCents: 1077})
	out = append(out, TariffRow{GroupCode: "G08", Band: "B5", RateCents: 1158})
	out = append(out, TariffRow{GroupCode: "G08", Band: "B6", RateCents: 1296})
	out = append(out, TariffRow{GroupCode: "G08", Band: "B7", RateCents: 1377})
	out = append(out, TariffRow{GroupCode: "G09", Band: "B0", RateCents: 733})
	out = append(out, TariffRow{GroupCode: "G09", Band: "B1", RateCents: 827})
	out = append(out, TariffRow{GroupCode: "G09", Band: "B2", RateCents: 921})
	out = append(out, TariffRow{GroupCode: "G09", Band: "B3", RateCents: 1015})
	out = append(out, TariffRow{GroupCode: "G09", Band: "B4", RateCents: 1109})
	out = append(out, TariffRow{GroupCode: "G09", Band: "B5", RateCents: 1203})
	out = append(out, TariffRow{GroupCode: "G09", Band: "B6", RateCents: 1297})
	out = append(out, TariffRow{GroupCode: "G09", Band: "B7", RateCents: 1391})
	out = append(out, TariffRow{GroupCode: "G10", Band: "B0", RateCents: 770})
	out = append(out, TariffRow{GroupCode: "G10", Band: "B1", RateCents: 877})
	out = append(out, TariffRow{GroupCode: "G10", Band: "B2", RateCents: 984})
	out = append(out, TariffRow{GroupCode: "G10", Band: "B3", RateCents: 1091})
	out = append(out, TariffRow{GroupCode: "G10", Band: "B4", RateCents: 1141})
	out = append(out, TariffRow{GroupCode: "G10", Band: "B5", RateCents: 1248})
	out = append(out, TariffRow{GroupCode: "G10", Band: "B6", RateCents: 1355})
	out = append(out, TariffRow{GroupCode: "G10", Band: "B7", RateCents: 1462})
	out = append(out, TariffRow{GroupCode: "G11", Band: "B0", RateCents: 807})
	out = append(out, TariffRow{GroupCode: "G11", Band: "B1", RateCents: 927})
	out = append(out, TariffRow{GroupCode: "G11", Band: "B2", RateCents: 990})
	out = append(out, TariffRow{GroupCode: "G11", Band: "B3", RateCents: 1110})
	out = append(out, TariffRow{GroupCode: "G11", Band: "B4", RateCents: 1173})
	out = append(out, TariffRow{GroupCode: "G11", Band: "B5", RateCents: 1293})
	out = append(out, TariffRow{GroupCode: "G11", Band: "B6", RateCents: 1356})
	out = append(out, TariffRow{GroupCode: "G11", Band: "B7", RateCents: 1476})
	return out
}
