package tablex

// tariffFill00 appends tariff rows 0..59.
func tariffFill00(out []TariffRow) []TariffRow {
	out = append(out, TariffRow{GroupCode: "G00", Band: "B0", RateCents: 400})
	out = append(out, TariffRow{GroupCode: "G00", Band: "B1", RateCents: 491})
	out = append(out, TariffRow{GroupCode: "G00", Band: "B2", RateCents: 582})
	out = append(out, TariffRow{GroupCode: "G00", Band: "B3", RateCents: 673})
	out = append(out, TariffRow{GroupCode: "G00", Band: "B4", RateCents: 764})
	out = append(out, TariffRow{GroupCode: "G00", Band: "B5", RateCents: 855})
	out = append(out, TariffRow{GroupCode: "G00", Band: "B6", RateCents: 946})
	out = append(out, TariffRow{GroupCode: "G00", Band: "B7", RateCents: 1037})
	out = append(out, TariffRow{GroupCode: "G01", Band: "B0", RateCents: 437})
	out = append(out, TariffRow{GroupCode: "G01", Band: "B1", RateCents: 541})
	out = append(out, TariffRow{GroupCode: "G01", Band: "B2", RateCents: 645})
	out = append(out, TariffRow{GroupCode: "G01", Band: "B3", RateCents: 749})
	out = append(out, TariffRow{GroupCode: "G01", Band: "B4", RateCents: 853})
	out = append(out, TariffRow{GroupCode: "G01", Band: "B5", RateCents: 900})
	out = append(out, TariffRow{GroupCode: "G01", Band: "B6", RateCents: 1004})
	out = append(out, TariffRow{GroupCode: "G01", Band: "B7", RateCents: 1108})
	out = append(out, TariffRow{GroupCode: "G02", Band: "B0", RateCents: 474})
	out = append(out, TariffRow{GroupCode: "G02", Band: "B1", RateCents: 591})
	out = append(out, TariffRow{GroupCode: "G02", Band: "B2", RateCents: 708})
	out = append(out, TariffRow{GroupCode: "G02", Band: "B3", RateCents: 768})
	out = append(out, TariffRow{GroupCode: "G02", Band: "B4", RateCents: 885})
	out = append(out, TariffRow{GroupCode: "G02", Band: "B5", RateCents: 945})
	out = append(out, TariffRow{GroupCode: "G02", Band: "B6", RateCents: 1062})
	out = append(out, TariffRow{GroupCode: "G02", Band: "B7", RateCents: 1122})
	out = append(out, TariffRow{GroupCode: "G03", Band: "B0", RateCents: 511})
	out = append(out, TariffRow{GroupCode: "G03", Band: "B1", RateCents: 641})
	out = append(out, TariffRow{GroupCode: "G03", Band: "B2", RateCents: 714})
	out = append(out, TariffRow{GroupCode: "G03", Band: "B3", RateCents: 787})
	out = append(out, TariffRow{GroupCode: "G03", Band: "B4", RateCents: 917})
	out = append(out, TariffRow{GroupCode: "G03", Band: "B5", RateCents: 990})
	out = append(out, TariffRow{GroupCode: "G03", Band: "B6", RateCents: 1063})
	out = append(out, TariffRow{GroupCode: "G03", Band: "B7", RateCents: 1193})
	out = append(out, TariffRow{GroupCode: "G04", Band: "B0", RateCents: 548})
	out = append(out, TariffRow{GroupCode: "G04", Band: "B1", RateCents: 691})
	out = append(out, TariffRow{GroupCode: "G04", Band: "B2", RateCents: 777})
	out = append(out, TariffRow{GroupCode: "G04", Band: "B3", RateCents: 863})
	out = append(out, TariffRow{GroupCode: "G04", Band: "B4", RateCents: 949})
	out = append(out, TariffRow{GroupCode: "G04", Band: "B5", RateCents: 1035})
	out = append(out, TariffRow{GroupCode: "G04", Band: "B6", RateCents: 1121})
	out = append(out, TariffRow{GroupCode: "G04", Band: "B7", RateCents: 1207})
	out = append(out, TariffRow{GroupCode: "G05", Band: "B0", RateCents: 585})
	out = append(out, TariffRow{GroupCode: "G05", Band: "B1", RateCents: 684})
	out = append(out, TariffRow{GroupCode: "G05", Band: "B2", RateCents: 783})
	out = append(out, TariffRow{GroupCode: "G05", Band: "B3", RateCents: 882})
	out = append(out, TariffRow{GroupCode: "G05", Band: "B4", RateCents: 981})
	out = append(out, TariffRow{GroupCode: "G05", Band: "B5", RateCents: 1080})
	out = append(out, TariffRow{GroupCode: "G05", Band: "B6", RateCents: 1179})
	out = append(out, TariffRow{GroupCode: "G05", Band: "B7", RateCents: 1278})
	out = append(out, TariffRow{GroupCode: "G06", Band: "B0", RateCents: 622})
	out = append(out, TariffRow{GroupCode: "G06", Band: "B1", RateCents: 734})
	out = append(out, TariffRow{GroupCode: "G06", Band: "B2", RateCents: 846})
	out = append(out, TariffRow{GroupCode: "G06", Band: "B3", RateCents: 901})
	out = append(out, TariffRow{GroupCode: "G06", Band: "B4", RateCents: 1013})
	out = append(out, TariffRow{GroupCode: "G06", Band: "B5", RateCents: 1125})
	out = append(out, TariffRow{GroupCode: "G06", Band: "B6", RateCents: 1180})
	out = append(out, TariffRow{GroupCode: "G06", Band: "B7", RateCents: 1292})
	out = append(out, TariffRow{GroupCode: "G07", Band: "B0", RateCents: 659})
	out = append(out, TariffRow{GroupCode: "G07", Band: "B1", RateCents: 784})
	out = append(out, TariffRow{GroupCode: "G07", Band: "B2", RateCents: 852})
	out = append(out, TariffRow{GroupCode: "G07", Band: "B3", RateCents: 977})
	return out
}
