package tablex

// zoneFill00 appends zone rows 0..59.
func zoneFill00(out []ZoneRow) []ZoneRow {
	out = append(out, ZoneRow{ZoneKey: "FZ-000", Abbrev: "Z00A", OffsetMinutes: -660, DstShiftMinutes: 60, Hub: "ATL"})
	out = append(out, ZoneRow{ZoneKey: "FZ-001", Abbrev: "Z01B", OffsetMinutes: -600, DstShiftMinutes: 0, Hub: "BOS"})
	out = append(out, ZoneRow{ZoneKey: "FZ-002", Abbrev: "Z02C", OffsetMinutes: -540, DstShiftMinutes: 0, Hub: "CHI"})
	out = append(out, ZoneRow{ZoneKey: "FZ-003", Abbrev: "Z03D", OffsetMinutes: -480, DstShiftMinutes: 0, Hub: "DFW"})
	out = append(out, ZoneRow{ZoneKey: "FZ-004", Abbrev: "Z04E", OffsetMinutes: -420, DstShiftMinutes: 60, Hub: "DEN"})
	out = append(out, ZoneRow{ZoneKey: "FZ-005", Abbrev: "Z05F", OffsetMinutes: -360, DstShiftMinutes: 0, Hub: "DTW"})
	out = append(out, ZoneRow{ZoneKey: "FZ-006", Abbrev: "Z06G", OffsetMinutes: -300, DstShiftMinutes: 0, Hub: "HOU"})
	out = append(out, ZoneRow{ZoneKey: "FZ-007", Abbrev: "Z07H", OffsetMinutes: -240, DstShiftMinutes: 0, Hub: "IND"})
	out = append(out, ZoneRow{ZoneKey: "FZ-008", Abbrev: "Z08I", OffsetMinutes: -210, DstShiftMinutes: 60, Hub: "JAX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-009", Abbrev: "Z09J", OffsetMinutes: -180, DstShiftMinutes: 0, Hub: "KCK"})
	out = append(out, ZoneRow{ZoneKey: "FZ-010", Abbrev: "Z10K", OffsetMinutes: -120, DstShiftMinutes: 0, Hub: "LAX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-011", Abbrev: "Z11L", OffsetMinutes: -60, DstShiftMinutes: 0, Hub: "MEM"})
	out = append(out, ZoneRow{ZoneKey: "FZ-012", Abbrev: "Z12M", OffsetMinutes: 0, DstShiftMinutes: 60, Hub: "MSP"})
	out = append(out, ZoneRow{ZoneKey: "FZ-013", Abbrev: "Z13N", OffsetMinutes: 60, DstShiftMinutes: 0, Hub: "NSH"})
	out = append(out, ZoneRow{ZoneKey: "FZ-014", Abbrev: "Z14O", OffsetMinutes: 120, DstShiftMinutes: 0, Hub: "OKC"})
	out = append(out, ZoneRow{ZoneKey: "FZ-015", Abbrev: "Z15P", OffsetMinutes: 180, DstShiftMinutes: 0, Hub: "PDX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-016", Abbrev: "Z16Q", OffsetMinutes: 210, DstShiftMinutes: 60, Hub: "PHX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-017", Abbrev: "Z17R", OffsetMinutes: 240, DstShiftMinutes: 0, Hub: "RNO"})
	out = append(out, ZoneRow{ZoneKey: "FZ-018", Abbrev: "Z18S", OffsetMinutes: 270, DstShiftMinutes: 0, Hub: "SLC"})
	out = append(out, ZoneRow{ZoneKey: "FZ-019", Abbrev: "Z19T", OffsetMinutes: 300, DstShiftMinutes: 0, Hub: "SEA"})
	out = append(out, ZoneRow{ZoneKey: "FZ-020", Abbrev: "Z20U", OffsetMinutes: 330, DstShiftMinutes: 60, Hub: "STL"})
	out = append(out, ZoneRow{ZoneKey: "FZ-021", Abbrev: "Z21V", OffsetMinutes: 345, DstShiftMinutes: 0, Hub: "TPA"})
	out = append(out, ZoneRow{ZoneKey: "FZ-022", Abbrev: "Z22W", OffsetMinutes: 360, DstShiftMinutes: 0, Hub: "YYZ"})
	out = append(out, ZoneRow{ZoneKey: "FZ-023", Abbrev: "Z23X", OffsetMinutes: 390, DstShiftMinutes: 0, Hub: "YVR"})
	out = append(out, ZoneRow{ZoneKey: "FZ-024", Abbrev: "Z24Y", OffsetMinutes: 420, DstShiftMinutes: 60, Hub: "ATL"})
	out = append(out, ZoneRow{ZoneKey: "FZ-025", Abbrev: "Z25Z", OffsetMinutes: 480, DstShiftMinutes: 0, Hub: "BOS"})
	out = append(out, ZoneRow{ZoneKey: "FZ-026", Abbrev: "Z26A", OffsetMinutes: 540, DstShiftMinutes: 0, Hub: "CHI"})
	out = append(out, ZoneRow{ZoneKey: "FZ-027", Abbrev: "Z27B", OffsetMinutes: 570, DstShiftMinutes: 0, Hub: "DFW"})
	out = append(out, ZoneRow{ZoneKey: "FZ-028", Abbrev: "Z28C", OffsetMinutes: 600, DstShiftMinutes: 60, Hub: "DEN"})
	out = append(out, ZoneRow{ZoneKey: "FZ-029", Abbrev: "Z29D", OffsetMinutes: 660, DstShiftMinutes: 0, Hub: "DTW"})
	out = append(out, ZoneRow{ZoneKey: "FZ-030", Abbrev: "Z30E", OffsetMinutes: 720, DstShiftMinutes: 0, Hub: "HOU"})
	out = append(out, ZoneRow{ZoneKey: "FZ-031", Abbrev: "Z31F", OffsetMinutes: 780, DstShiftMinutes: 0, Hub: "IND"})
	out = append(out, ZoneRow{ZoneKey: "FZ-032", Abbrev: "Z32G", OffsetMinutes: 840, DstShiftMinutes: 60, Hub: "JAX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-033", Abbrev: "Z33H", OffsetMinutes: -660, DstShiftMinutes: 0, Hub: "KCK"})
	out = append(out, ZoneRow{ZoneKey: "FZ-034", Abbrev: "Z34I", OffsetMinutes: -600, DstShiftMinutes: 0, Hub: "LAX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-035", Abbrev: "Z35J", OffsetMinutes: -540, DstShiftMinutes: 0, Hub: "MEM"})
	out = append(out, ZoneRow{ZoneKey: "FZ-036", Abbrev: "Z36K", OffsetMinutes: -480, DstShiftMinutes: 60, Hub: "MSP"})
	out = append(out, ZoneRow{ZoneKey: "FZ-037", Abbrev: "Z37L", OffsetMinutes: -420, DstShiftMinutes: 0, Hub: "NSH"})
	out = append(out, ZoneRow{ZoneKey: "FZ-038", Abbrev: "Z38M", OffsetMinutes: -360, DstShiftMinutes: 0, Hub: "OKC"})
	out = append(out, ZoneRow{ZoneKey: "FZ-039", Abbrev: "Z39N", OffsetMinutes: -300, DstShiftMinutes: 0, Hub: "PDX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-040", Abbrev: "Z40O", OffsetMinutes: -240, DstShiftMinutes: 60, Hub: "PHX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-041", Abbrev: "Z41P", OffsetMinutes: -210, DstShiftMinutes: 0, Hub: "RNO"})
	out = append(out, ZoneRow{ZoneKey: "FZ-042", Abbrev: "Z42Q", OffsetMinutes: -180, DstShiftMinutes: 0, Hub: "SLC"})
	out = append(out, ZoneRow{ZoneKey: "FZ-043", Abbrev: "Z43R", OffsetMinutes: -120, DstShiftMinutes: 0, Hub: "SEA"})
	out = append(out, ZoneRow{ZoneKey: "FZ-044", Abbrev: "Z44S", OffsetMinutes: -60, DstShiftMinutes: 60, Hub: "STL"})
	out = append(out, ZoneRow{ZoneKey: "FZ-045", Abbrev: "Z45T", OffsetMinutes: 0, DstShiftMinutes: 0, Hub: "TPA"})
	out = append(out, ZoneRow{ZoneKey: "FZ-046", Abbrev: "Z46U", OffsetMinutes: 60, DstShiftMinutes: 0, Hub: "YYZ"})
	out = append(out, ZoneRow{ZoneKey: "FZ-047", Abbrev: "Z47V", OffsetMinutes: 120, DstShiftMinutes: 0, Hub: "YVR"})
	out = append(out, ZoneRow{ZoneKey: "FZ-048", Abbrev: "Z48W", OffsetMinutes: 180, DstShiftMinutes: 60, Hub: "ATL"})
	out = append(out, ZoneRow{ZoneKey: "FZ-049", Abbrev: "Z49X", OffsetMinutes: 210, DstShiftMinutes: 0, Hub: "BOS"})
	out = append(out, ZoneRow{ZoneKey: "FZ-050", Abbrev: "Z50Y", OffsetMinutes: 240, DstShiftMinutes: 0, Hub: "CHI"})
	out = append(out, ZoneRow{ZoneKey: "FZ-051", Abbrev: "Z51Z", OffsetMinutes: 270, DstShiftMinutes: 0, Hub: "DFW"})
	out = append(out, ZoneRow{ZoneKey: "FZ-052", Abbrev: "Z52A", OffsetMinutes: 300, DstShiftMinutes: 60, Hub: "DEN"})
	out = append(out, ZoneRow{ZoneKey: "FZ-053", Abbrev: "Z53B", OffsetMinutes: 330, DstShiftMinutes: 0, Hub: "DTW"})
	out = append(out, ZoneRow{ZoneKey: "FZ-054", Abbrev: "Z54C", OffsetMinutes: 345, DstShiftMinutes: 0, Hub: "HOU"})
	out = append(out, ZoneRow{ZoneKey: "FZ-055", Abbrev: "Z55D", OffsetMinutes: 360, DstShiftMinutes: 0, Hub: "IND"})
	out = append(out, ZoneRow{ZoneKey: "FZ-056", Abbrev: "Z56E", OffsetMinutes: 390, DstShiftMinutes: 60, Hub: "JAX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-057", Abbrev: "Z57F", OffsetMinutes: 420, DstShiftMinutes: 0, Hub: "KCK"})
	out = append(out, ZoneRow{ZoneKey: "FZ-058", Abbrev: "Z58G", OffsetMinutes: 480, DstShiftMinutes: 0, Hub: "LAX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-059", Abbrev: "Z59H", OffsetMinutes: 540, DstShiftMinutes: 0, Hub: "MEM"})
	return out
}
