package tablex

// zoneFill01 appends zone rows 60..119.
func zoneFill01(out []ZoneRow) []ZoneRow {
	out = append(out, ZoneRow{ZoneKey: "FZ-060", Abbrev: "Z60I", OffsetMinutes: 570, DstShiftMinutes: 60, Hub: "MSP"})
	out = append(out, ZoneRow{ZoneKey: "FZ-061", Abbrev: "Z61J", OffsetMinutes: 600, DstShiftMinutes: 0, Hub: "NSH"})
	out = append(out, ZoneRow{ZoneKey: "FZ-062", Abbrev: "Z62K", OffsetMinutes: 660, DstShiftMinutes: 0, Hub: "OKC"})
	out = append(out, ZoneRow{ZoneKey: "FZ-063", Abbrev: "Z63L", OffsetMinutes: 720, DstShiftMinutes: 0, Hub: "PDX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-064", Abbrev: "Z64M", OffsetMinutes: 780, DstShiftMinutes: 60, Hub: "PHX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-065", Abbrev: "Z65N", OffsetMinutes: 840, DstShiftMinutes: 0, Hub: "RNO"})
	out = append(out, ZoneRow{ZoneKey: "FZ-066", Abbrev: "Z66O", OffsetMinutes: -660, DstShiftMinutes: 0, Hub: "SLC"})
	out = append(out, ZoneRow{ZoneKey: "FZ-067", Abbrev: "Z67P", OffsetMinutes: -600, DstShiftMinutes: 0, Hub: "SEA"})
	out = append(out, ZoneRow{ZoneKey: "FZ-068", Abbrev: "Z68Q", OffsetMinutes: -540, DstShiftMinutes: 60, Hub: "STL"})
	out = append(out, ZoneRow{ZoneKey: "FZ-069", Abbrev: "Z69R", OffsetMinutes: -480, DstShiftMinutes: 0, Hub: "TPA"})
	out = append(out, ZoneRow{ZoneKey: "FZ-070", Abbrev: "Z70S", OffsetMinutes: -420, DstShiftMinutes: 0, Hub: "YYZ"})
	out = append(out, ZoneRow{ZoneKey: "FZ-071", Abbrev: "Z71T", OffsetMinutes: -360, DstShiftMinutes: 0, Hub: "YVR"})
	out = append(out, ZoneRow{ZoneKey: "FZ-072", Abbrev: "Z72U", OffsetMinutes: -300, DstShiftMinutes: 60, Hub: "ATL"})
	out = append(out, ZoneRow{ZoneKey: "FZ-073", Abbrev: "Z73V", OffsetMinutes: -240, DstShiftMinutes: 0, Hub: "BOS"})
	out = append(out, ZoneRow{ZoneKey: "FZ-074", Abbrev: "Z74W", OffsetMinutes: -210, DstShiftMinutes: 0, Hub: "CHI"})
	out = append(out, ZoneRow{ZoneKey: "FZ-075", Abbrev: "Z75X", OffsetMinutes: -180, DstShiftMinutes: 0, Hub: "DFW"})
	out = append(out, ZoneRow{ZoneKey: "FZ-076", Abbrev: "Z76Y", OffsetMinutes: -120, DstShiftMinutes: 60, Hub: "DEN"})
	out = append(out, ZoneRow{ZoneKey: "FZ-077", Abbrev: "Z77Z", OffsetMinutes: -60, DstShiftMinutes: 0, Hub: "DTW"})
	out = append(out, ZoneRow{ZoneKey: "FZ-078", Abbrev: "Z78A", OffsetMinutes: 0, DstShiftMinutes: 0, Hub: "HOU"})
	out = append(out, ZoneRow{ZoneKey: "FZ-079", Abbrev: "Z79B", OffsetMinutes: 60, DstShiftMinutes: 0, Hub: "IND"})
	out = append(out, ZoneRow{ZoneKey: "FZ-080", Abbrev: "Z80C", OffsetMinutes: 120, DstShiftMinutes: 60, Hub: "JAX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-081", Abbrev: "Z81D", OffsetMinutes: 180, DstShiftMinutes: 0, Hub: "KCK"})
	out = append(out, ZoneRow{ZoneKey: "FZ-082", Abbrev: "Z82E", OffsetMinutes: 210, DstShiftMinutes: 0, Hub: "LAX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-083", Abbrev: "Z83F", OffsetMinutes: 240, DstShiftMinutes: 0, Hub: "MEM"})
	out = append(out, ZoneRow{ZoneKey: "FZ-084", Abbrev: "Z84G", OffsetMinutes: 270, DstShiftMinutes: 60, Hub: "MSP"})
	out = append(out, ZoneRow{ZoneKey: "FZ-085", Abbrev: "Z85H", OffsetMinutes: 300, DstShiftMinutes: 0, Hub: "NSH"})
	out = append(out, ZoneRow{ZoneKey: "FZ-086", Abbrev: "Z86I", OffsetMinutes: 330, DstShiftMinutes: 0, Hub: "OKC"})
	out = append(out, ZoneRow{ZoneKey: "FZ-087", Abbrev: "Z87J", OffsetMinutes: 345, DstShiftMinutes: 0, Hub: "PDX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-088", Abbrev: "Z88K", OffsetMinutes: 360, DstShiftMinutes: 60, Hub: "PHX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-089", Abbrev: "Z89L", OffsetMinutes: 390, DstShiftMinutes: 0, Hub: "RNO"})
	out = append(out, ZoneRow{ZoneKey: "FZ-090", Abbrev: "Z90M", OffsetMinutes: 420, DstShiftMinutes: 0, Hub: "SLC"})
	out = append(out, ZoneRow{ZoneKey: "FZ-091", Abbrev: "Z91N", OffsetMinutes: 480, DstShiftMinutes: 0, Hub: "SEA"})
	out = append(out, ZoneRow{ZoneKey: "FZ-092", Abbrev: "Z92O", OffsetMinutes: 540, DstShiftMinutes: 60, Hub: "STL"})
	out = append(out, ZoneRow{ZoneKey: "FZ-093", Abbrev: "Z93P", OffsetMinutes: 570, DstShiftMinutes: 0, Hub: "TPA"})
	out = append(out, ZoneRow{ZoneKey: "FZ-094", Abbrev: "Z94Q", OffsetMinutes: 600, DstShiftMinutes: 0, Hub: "YYZ"})
	out = append(out, ZoneRow{ZoneKey: "FZ-095", Abbrev: "Z95R", OffsetMinutes: 660, DstShiftMinutes: 0, Hub: "YVR"})
	out = append(out, ZoneRow{ZoneKey: "FZ-096", Abbrev: "Z96S", OffsetMinutes: 720, DstShiftMinutes: 60, Hub: "ATL"})
	out = append(out, ZoneRow{ZoneKey: "FZ-097", Abbrev: "Z97T", OffsetMinutes: 780, DstShiftMinutes: 0, Hub: "BOS"})
	out = append(out, ZoneRow{ZoneKey: "FZ-098", Abbrev: "Z98U", OffsetMinutes: 840, DstShiftMinutes: 0, Hub: "CHI"})
	out = append(out, ZoneRow{ZoneKey: "FZ-099", Abbrev: "Z99V", OffsetMinutes: -660, DstShiftMinutes: 0, Hub: "DFW"})
	out = append(out, ZoneRow{ZoneKey: "FZ-100", Abbrev: "Z00W", OffsetMinutes: -600, DstShiftMinutes: 60, Hub: "DEN"})
	out = append(out, ZoneRow{ZoneKey: "FZ-101", Abbrev: "Z01X", OffsetMinutes: -540, DstShiftMinutes: 0, Hub: "DTW"})
	out = append(out, ZoneRow{ZoneKey: "FZ-102", Abbrev: "Z02Y", OffsetMinutes: -480, DstShiftMinutes: 0, Hub: "HOU"})
	out = append(out, ZoneRow{ZoneKey: "FZ-103", Abbrev: "Z03Z", OffsetMinutes: -420, DstShiftMinutes: 0, Hub: "IND"})
	out = append(out, ZoneRow{ZoneKey: "FZ-104", Abbrev: "Z04A", OffsetMinutes: -360, DstShiftMinutes: 60, Hub: "JAX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-105", Abbrev: "Z05B", OffsetMinutes: -300, DstShiftMinutes: 0, Hub: "KCK"})
	out = append(out, ZoneRow{ZoneKey: "FZ-106", Abbrev: "Z06C", OffsetMinutes: -240, DstShiftMinutes: 0, Hub: "LAX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-107", Abbrev: "Z07D", OffsetMinutes: -210, DstShiftMinutes: 0, Hub: "MEM"})
	out = append(out, ZoneRow{ZoneKey: "FZ-108", Abbrev: "Z08E", OffsetMinutes: -180, DstShiftMinutes: 60, Hub: "MSP"})
	out = append(out, ZoneRow{ZoneKey: "FZ-109", Abbrev: "Z09F", OffsetMinutes: -120, DstShiftMinutes: 0, Hub: "NSH"})
	out = append(out, ZoneRow{ZoneKey: "FZ-110", Abbrev: "Z10G", OffsetMinutes: -60, DstShiftMinutes: 0, Hub: "OKC"})
	out = append(out, ZoneRow{ZoneKey: "FZ-111", Abbrev: "Z11H", OffsetMinutes: 0, DstShiftMinutes: 0, Hub: "PDX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-112", Abbrev: "Z12I", OffsetMinutes: 60, DstShiftMinutes: 60, Hub: "PHX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-113", Abbrev: "Z13J", OffsetMinutes: 120, DstShiftMinutes: 0, Hub: "RNO"})
	out = append(out, ZoneRow{ZoneKey: "FZ-114", Abbrev: "Z14K", OffsetMinutes: 180, DstShiftMinutes: 0, Hub: "SLC"})
	out = append(out, ZoneRow{ZoneKey: "FZ-115", Abbrev: "Z15L", OffsetMinutes: 210, DstShiftMinutes: 0, Hub: "SEA"})
	out = append(out, ZoneRow{ZoneKey: "FZ-116", Abbrev: "Z16M", OffsetMinutes: 240, DstShiftMinutes: 60, Hub: "STL"})
	out = append(out, ZoneRow{ZoneKey: "FZ-117", Abbrev: "Z17N", OffsetMinutes: 270, DstShiftMinutes: 0, Hub: "TPA"})
	out = append(out, ZoneRow{ZoneKey: "FZ-118", Abbrev: "Z18O", OffsetMinutes: 300, DstShiftMinutes: 0, Hub: "YYZ"})
	out = append(out, ZoneRow{ZoneKey: "FZ-119", Abbrev: "Z19P", OffsetMinutes: 330, DstShiftMinutes: 0, Hub: "YVR"})
	return out
}
