package tablex

// zoneFill04 appends zone rows 240..299.
func zoneFill04(out []ZoneRow) []ZoneRow {
	out = append(out, ZoneRow{ZoneKey: "FZ-240", Abbrev: "Z40G", OffsetMinutes: -180, DstShiftMinutes: 60, Hub: "ATL"})
	out = append(out, ZoneRow{ZoneKey: "FZ-241", Abbrev: "Z41H", OffsetMinutes: -120, DstShiftMinutes: 0, Hub: "BOS"})
	out = append(out, ZoneRow{ZoneKey: "FZ-242", Abbrev: "Z42I", OffsetMinutes: -60, DstShiftMinutes: 0, Hub: "CHI"})
	out = append(out, ZoneRow{ZoneKey: "FZ-243", Abbrev: "Z43J", OffsetMinutes: 0, DstShiftMinutes: 0, Hub: "DFW"})
	out = append(out, ZoneRow{ZoneKey: "FZ-244", Abbrev: "Z44K", OffsetMinutes: 60, DstShiftMinutes: 60, Hub: "DEN"})
	out = append(out, ZoneRow{ZoneKey: "FZ-245", Abbrev: "Z45L", OffsetMinutes: 120, DstShiftMinutes: 0, Hub: "DTW"})
	out = append(out, ZoneRow{ZoneKey: "FZ-246", Abbrev: "Z46M", OffsetMinutes: 180, DstShiftMinutes: 0, Hub: "HOU"})
	out = append(out, ZoneRow{ZoneKey: "FZ-247", Abbrev: "Z47N", OffsetMinutes: 210, DstShiftMinutes: 0, Hub: "IND"})
	out = append(out, ZoneRow{ZoneKey: "FZ-248", Abbrev: "Z48O", OffsetMinutes: 240, DstShiftMinutes: 60, Hub: "JAX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-249", Abbrev: "Z49P", OffsetMinutes: 270, DstShiftMinutes: 0, Hub: "KCK"})
	out = append(out, ZoneRow{ZoneKey: "FZ-250", Abbrev: "Z50Q", OffsetMinutes: 300, DstShiftMinutes: 0, Hub: "LAX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-251", Abbrev: "Z51R", OffsetMinutes: 330, DstShiftMinutes: 0, Hub: "MEM"})
	out = append(out, ZoneRow{ZoneKey: "FZ-252", Abbrev: "Z52S", OffsetMinutes: 345, DstShiftMinutes: 60, Hub: "MSP"})
	out = append(out, ZoneRow{ZoneKey: "FZ-253", Abbrev: "Z53T", OffsetMinutes: 360, DstShiftMinutes: 0, Hub: "NSH"})
	out = append(out, ZoneRow{ZoneKey: "FZ-254", Abbrev: "Z54U", OffsetMinutes: 390, DstShiftMinutes: 0, Hub: "OKC"})
	out = append(out, ZoneRow{ZoneKey: "FZ-255", Abbrev: "Z55V", OffsetMinutes: 420, DstShiftMinutes: 0, Hub: "PDX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-256", Abbrev: "Z56W", OffsetMinutes: 480, DstShiftMinutes: 60, Hub: "PHX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-257", Abbrev: "Z57X", OffsetMinutes: 540, DstShiftMinutes: 0, Hub: "RNO"})
	out = append(out, ZoneRow{ZoneKey: "FZ-258", Abbrev: "Z58Y", OffsetMinutes: 570, DstShiftMinutes: 0, Hub: "SLC"})
	out = append(out, ZoneRow{ZoneKey: "FZ-259", Abbrev: "Z59Z", OffsetMinutes: 600, DstShiftMinutes: 0, Hub: "SEA"})
	out = append(out, ZoneRow{ZoneKey: "FZ-260", Abbrev: "Z60A", OffsetMinutes: 660, DstShiftMinutes: 60, Hub: "STL"})
	out = append(out, ZoneRow{ZoneKey: "FZ-261", Abbrev: "Z61B", OffsetMinutes: 720, DstShiftMinutes: 0, Hub: "TPA"})
	out = append(out, ZoneRow{ZoneKey: "FZ-262", Abbrev: "Z62C", OffsetMinutes: 780, DstShiftMinutes: 0, Hub: "YYZ"})
	out = append(out, ZoneRow{ZoneKey: "FZ-263", Abbrev: "Z63D", OffsetMinutes: 840, DstShiftMinutes: 0, Hub: "YVR"})
	out = append(out, ZoneRow{ZoneKey: "FZ-264", Abbrev: "Z64E", OffsetMinutes: -660, DstShiftMinutes: 60, Hub: "ATL"})
	out = append(out, ZoneRow{ZoneKey: "FZ-265", Abbrev: "Z65F", OffsetMinutes: -600, DstShiftMinutes: 0, Hub: "BOS"})
	out = append(out, ZoneRow{ZoneKey: "FZ-266", Abbrev: "Z66G", OffsetMinutes: -540, DstShiftMinutes: 0, Hub: "CHI"})
	out = append(out, ZoneRow{ZoneKey: "FZ-267", Abbrev: "Z67H", OffsetMinutes: -480, DstShiftMinutes: 0, Hub: "DFW"})
	out = append(out, ZoneRow{ZoneKey: "FZ-268", Abbrev: "Z68I", OffsetMinutes: -420, DstShiftMinutes: 60, Hub: "DEN"})
	out = append(out, ZoneRow{ZoneKey: "FZ-269", Abbrev: "Z69J", OffsetMinutes: -360, DstShiftMinutes: 0, Hub: "DTW"})
	out = append(out, ZoneRow{ZoneKey: "FZ-270", Abbrev: "Z70K", OffsetMinutes: -300, DstShiftMinutes: 0, Hub: "HOU"})
	out = append(out, ZoneRow{ZoneKey: "FZ-271", Abbrev: "Z71L", OffsetMinutes: -240, DstShiftMinutes: 0, Hub: "IND"})
	out = append(out, ZoneRow{ZoneKey: "FZ-272", Abbrev: "Z72M", OffsetMinutes: -210, DstShiftMinutes: 60, Hub: "JAX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-273", Abbrev: "Z73N", OffsetMinutes: -180, DstShiftMinutes: 0, Hub: "KCK"})
	out = append(out, ZoneRow{ZoneKey: "FZ-274", Abbrev: "Z74O", OffsetMinutes: -120, DstShiftMinutes: 0, Hub: "LAX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-275", Abbrev: "Z75P", OffsetMinutes: -60, DstShiftMinutes: 0, Hub: "MEM"})
	out = append(out, ZoneRow{ZoneKey: "FZ-276", Abbrev: "Z76Q", OffsetMinutes: 0, DstShiftMinutes: 60, Hub: "MSP"})
	out = append(out, ZoneRow{ZoneKey: "FZ-277", Abbrev: "Z77R", OffsetMinutes: 60, DstShiftMinutes: 0, Hub: "NSH"})
	out = append(out, ZoneRow{ZoneKey: "FZ-278", Abbrev: "Z78S", OffsetMinutes: 120, DstShiftMinutes: 0, Hub: "OKC"})
	out = append(out, ZoneRow{ZoneKey: "FZ-279", Abbrev: "Z79T", OffsetMinutes: 180, DstShiftMinutes: 0, Hub: "PDX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-280", Abbrev: "Z80U", OffsetMinutes: 210, DstShiftMinutes: 60, Hub: "PHX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-281", Abbrev: "Z81V", OffsetMinutes: 240, DstShiftMinutes: 0, Hub: "RNO"})
	out = append(out, ZoneRow{ZoneKey: "FZ-282", Abbrev: "Z82W", OffsetMinutes: 270, DstShiftMinutes: 0, Hub: "SLC"})
	out = append(out, ZoneRow{ZoneKey: "FZ-283", Abbrev: "Z83X", OffsetMinutes: 300, DstShiftMinutes: 0, Hub: "SEA"})
	out = append(out, ZoneRow{ZoneKey: "FZ-284", Abbrev: "Z84Y", OffsetMinutes: 330, DstShiftMinutes: 60, Hub: "STL"})
	out = append(out, ZoneRow{ZoneKey: "FZ-285", Abbrev: "Z85Z", OffsetMinutes: 345, DstShiftMinutes: 0, Hub: "TPA"})
	out = append(out, ZoneRow{ZoneKey: "FZ-286", Abbrev: "Z86A", OffsetMinutes: 360, DstShiftMinutes: 0, Hub: "YYZ"})
	out = append(out, ZoneRow{ZoneKey: "FZ-287", Abbrev: "Z87B", OffsetMinutes: 390, DstShiftMinutes: 0, Hub: "YVR"})
	out = append(out, ZoneRow{ZoneKey: "FZ-288", Abbrev: "Z88C", OffsetMinutes: 420, DstShiftMinutes: 60, Hub: "ATL"})
	out = append(out, ZoneRow{ZoneKey: "FZ-289", Abbrev: "Z89D", OffsetMinutes: 480, DstShiftMinutes: 0, Hub: "BOS"})
	out = append(out, ZoneRow{ZoneKey: "FZ-290", Abbrev: "Z90E", OffsetMinutes: 540, DstShiftMinutes: 0, Hub: "CHI"})
	out = append(out, ZoneRow{ZoneKey: "FZ-291", Abbrev: "Z91F", OffsetMinutes: 570, DstShiftMinutes: 0, Hub: "DFW"})
	out = append(out, ZoneRow{ZoneKey: "FZ-292", Abbrev: "Z92G", OffsetMinutes: 600, DstShiftMinutes: 60, Hub: "DEN"})
	out = append(out, ZoneRow{ZoneKey: "FZ-293", Abbrev: "Z93H", OffsetMinutes: 660, DstShiftMinutes: 0, Hub: "DTW"})
	out = append(out, ZoneRow{ZoneKey: "FZ-294", Abbrev: "Z94I", OffsetMinutes: 720, DstShiftMinutes: 0, Hub: "HOU"})
	out = append(out, ZoneRow{ZoneKey: "FZ-295", Abbrev: "Z95J", OffsetMinutes: 780, DstShiftMinutes: 0, Hub: "IND"})
	out = append(out, ZoneRow{ZoneKey: "FZ-296", Abbrev: "Z96K", OffsetMinutes: 840, DstShiftMinutes: 60, Hub: "JAX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-297", Abbrev: "Z97L", OffsetMinutes: -660, DstShiftMinutes: 0, Hub: "KCK"})
	out = append(out, ZoneRow{ZoneKey: "FZ-298", Abbrev: "Z98M", OffsetMinutes: -600, DstShiftMinutes: 0, Hub: "LAX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-299", Abbrev: "Z99N", OffsetMinutes: -540, DstShiftMinutes: 0, Hub: "MEM"})
	return out
}
