package tablex

// zoneFill03 appends zone rows 180..239.
func zoneFill03(out []ZoneRow) []ZoneRow {
	out = append(out, ZoneRow{ZoneKey: "FZ-180", Abbrev: "Z80Y", OffsetMinutes: 180, DstShiftMinutes: 60, Hub: "MSP"})
	out = append(out, ZoneRow{ZoneKey: "FZ-181", Abbrev: "Z81Z", OffsetMinutes: 210, DstShiftMinutes: 0, Hub: "NSH"})
	out = append(out, ZoneRow{ZoneKey: "FZ-182", Abbrev: "Z82A", OffsetMinutes: 240, DstShiftMinutes: 0, Hub: "OKC"})
	out = append(out, ZoneRow{ZoneKey: "FZ-183", Abbrev: "Z83B", OffsetMinutes: 270, DstShiftMinutes: 0, Hub: "PDX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-184", Abbrev: "Z84C", OffsetMinutes: 300, DstShiftMinutes: 60, Hub: "PHX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-185", Abbrev: "Z85D", OffsetMinutes: 330, DstShiftMinutes: 0, Hub: "RNO"})
	out = append(out, ZoneRow{ZoneKey: "FZ-186", Abbrev: "Z86E", OffsetMinutes: 345, DstShiftMinutes: 0, Hub: "SLC"})
	out = append(out, ZoneRow{ZoneKey: "FZ-187", Abbrev: "Z87F", OffsetMinutes: 360, DstShiftMinutes: 0, Hub: "SEA"})
	out = append(out, ZoneRow{ZoneKey: "FZ-188", Abbrev: "Z88G", OffsetMinutes: 390, DstShiftMinutes: 60, Hub: "STL"})
	out = append(out, ZoneRow{ZoneKey: "FZ-189", Abbrev: "Z89H", OffsetMinutes: 420, DstShiftMinutes: 0, Hub: "TPA"})
	out = append(out, ZoneRow{ZoneKey: "FZ-190", Abbrev: "Z90I", OffsetMinutes: 480, DstShiftMinutes: 0, Hub: "YYZ"})
	out = append(out, ZoneRow{ZoneKey: "FZ-191", Abbrev: "Z91J", OffsetMinutes: 540, DstShiftMinutes: 0, Hub: "YVR"})
	out = append(out, ZoneRow{ZoneKey: "FZ-192", Abbrev: "Z92K", OffsetMinutes: 570, DstShiftMinutes: 60, Hub: "ATL"})
	out = append(out, ZoneRow{ZoneKey: "FZ-193", Abbrev: "Z93L", OffsetMinutes: 600, DstShiftMinutes: 0, Hub: "BOS"})
	out = append(out, ZoneRow{ZoneKey: "FZ-194", Abbrev: "Z94M", OffsetMinutes: 660, DstShiftMinutes: 0, Hub: "CHI"})
	out = append(out, ZoneRow{ZoneKey: "FZ-195", Abbrev: "Z95N", OffsetMinutes: 720, DstShiftMinutes: 0, Hub: "DFW"})
	out = append(out, ZoneRow{ZoneKey: "FZ-196", Abbrev: "Z96O", OffsetMinutes: 780, DstShiftMinutes: 60, Hub: "DEN"})
	out = append(out, ZoneRow{ZoneKey: "FZ-197", Abbrev: "Z97P", OffsetMinutes: 840, DstShiftMinutes: 0, Hub: "DTW"})
	out = append(out, ZoneRow{ZoneKey: "FZ-198", Abbrev: "Z98Q", OffsetMinutes: -660, DstShiftMinutes: 0, Hub: "HOU"})
	out = append(out, ZoneRow{ZoneKey: "FZ-199", Abbrev: "Z99R", OffsetMinutes: -600, DstShiftMinutes: 0, Hub: "IND"})
	out = append(out, ZoneRow{ZoneKey: "FZ-200", Abbrev: "Z00S", OffsetMinutes: -540, DstShiftMinutes: 60, Hub: "JAX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-201", Abbrev: "Z01T", OffsetMinutes: -480, DstShiftMinutes: 0, Hub: "KCK"})
	out = append(out, ZoneRow{ZoneKey: "FZ-202", Abbrev: "Z02U", OffsetMinutes: -420, DstShiftMinutes: 0, Hub: "LAX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-203", Abbrev: "Z03V", OffsetMinutes: -360, DstShiftMinutes: 0, Hub: "MEM"})
	out = append(out, ZoneRow{ZoneKey: "FZ-204", Abbrev: "Z04W", OffsetMinutes: -300, DstShiftMinutes: 60, Hub: "MSP"})
	out = append(out, ZoneRow{ZoneKey: "FZ-205", Abbrev: "Z05X", OffsetMinutes: -240, DstShiftMinutes: 0, Hub: "NSH"})
	out = append(out, ZoneRow{ZoneKey: "FZ-206", Abbrev: "Z06Y", OffsetMinutes: -210, DstShiftMinutes: 0, Hub: "OKC"})
	out = append(out, ZoneRow{ZoneKey: "FZ-207", Abbrev: "Z07Z", OffsetMinutes: -180, DstShiftMinutes: 0, Hub: "PDX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-208", Abbrev: "Z08A", OffsetMinutes: -120, DstShiftMinutes: 60, Hub: "PHX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-209", Abbrev: "Z09B", OffsetMinutes: -60, DstShiftMinutes: 0, Hub: "RNO"})
	out = append(out, ZoneRow{ZoneKey: "FZ-210", Abbrev: "Z10C", OffsetMinutes: 0, DstShiftMinutes: 0, Hub: "SLC"})
	out = append(out, ZoneRow{ZoneKey: "FZ-211", Abbrev: "Z11D", OffsetMinutes: 60, DstShiftMinutes: 0, Hub: "SEA"})
	out = append(out, ZoneRow{ZoneKey: "FZ-212", Abbrev: "Z12E", OffsetMinutes: 120, DstShiftMinutes: 60, Hub: "STL"})
	out = append(out, ZoneRow{ZoneKey: "FZ-213", Abbrev: "Z13F", OffsetMinutes: 180, DstShiftMinutes: 0, Hub: "TPA"})
	out = append(out, ZoneRow{ZoneKey: "FZ-214", Abbrev: "Z14G", OffsetMinutes: 210, DstShiftMinutes: 0, Hub: "YYZ"})
	out = append(out, ZoneRow{ZoneKey: "FZ-215", Abbrev: "Z15H", OffsetMinutes: 240, DstShiftMinutes: 0, Hub: "YVR"})
	out = append(out, ZoneRow{ZoneKey: "FZ-216", Abbrev: "Z16I", OffsetMinutes: 270, DstShiftMinutes: 60, Hub: "ATL"})
	out = append(out, ZoneRow{ZoneKey: "FZ-217", Abbrev: "Z17J", OffsetMinutes: 300, DstShiftMinutes: 0, Hub: "BOS"})
	out = append(out, ZoneRow{ZoneKey: "FZ-218", Abbrev: "Z18K", OffsetMinutes: 330, DstShiftMinutes: 0, Hub: "CHI"})
	out = append(out, ZoneRow{ZoneKey: "FZ-219", Abbrev: "Z19L", OffsetMinutes: 345, DstShiftMinutes: 0, Hub: "DFW"})
	out = append(out, ZoneRow{ZoneKey: "FZ-220", Abbrev: "Z20M", OffsetMinutes: 360, DstShiftMinutes: 60, Hub: "DEN"})
	out = append(out, ZoneRow{ZoneKey: "FZ-221", Abbrev: "Z21N", OffsetMinutes: 390, DstShiftMinutes: 0, Hub: "DTW"})
	out = append(out, ZoneRow{ZoneKey: "FZ-222", Abbrev: "Z22O", OffsetMinutes: 420, DstShiftMinutes: 0, Hub: "HOU"})
	out = append(out, ZoneRow{ZoneKey: "FZ-223", Abbrev: "Z23P", OffsetMinutes: 480, DstShiftMinutes: 0, Hub: "IND"})
	out = append(out, ZoneRow{ZoneKey: "FZ-224", Abbrev: "Z24Q", OffsetMinutes: 540, DstShiftMinutes: 60, Hub: "JAX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-225", Abbrev: "Z25R", OffsetMinutes: 570, DstShiftMinutes: 0, Hub: "KCK"})
	out = append(out, ZoneRow{ZoneKey: "FZ-226", Abbrev: "Z26S", OffsetMinutes: 600, DstShiftMinutes: 0, Hub: "LAX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-227", Abbrev: "Z27T", OffsetMinutes: 660, DstShiftMinutes: 0, Hub: "MEM"})
	out = append(out, ZoneRow{ZoneKey: "FZ-228", Abbrev: "Z28U", OffsetMinutes: 720, DstShiftMinutes: 60, Hub: "MSP"})
	out = append(out, ZoneRow{ZoneKey: "FZ-229", Abbrev: "Z29V", OffsetMinutes: 780, DstShiftMinutes: 0, Hub: "NSH"})
	out = append(out, ZoneRow{ZoneKey: "FZ-230", Abbrev: "Z30W", OffsetMinutes: 840, DstShiftMinutes: 0, Hub: "OKC"})
	out = append(out, ZoneRow{ZoneKey: "FZ-231", Abbrev: "Z31X", OffsetMinutes: -660, DstShiftMinutes: 0, Hub: "PDX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-232", Abbrev: "Z32Y", OffsetMinutes: -600, DstShiftMinutes: 60, Hub: "PHX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-233", Abbrev: "Z33Z", OffsetMinutes: -540, DstShiftMinutes: 0, Hub: "RNO"})
	out = append(out, ZoneRow{ZoneKey: "FZ-234", Abbrev: "Z34A", OffsetMinutes: -480, DstShiftMinutes: 0, Hub: "SLC"})
	out = append(out, ZoneRow{ZoneKey: "FZ-235", Abbrev: "Z35B", OffsetMinutes: -420, DstShiftMinutes: 0, Hub: "SEA"})
	out = append(out, ZoneRow{ZoneKey: "FZ-236", Abbrev: "Z36C", OffsetMinutes: -360, DstShiftMinutes: 60, Hub: "STL"})
	out = append(out, ZoneRow{ZoneKey: "FZ-237", Abbrev: "Z37D", OffsetMinutes: -300, DstShiftMinutes: 0, Hub: "TPA"})
	out = append(out, ZoneRow{ZoneKey: "FZ-238", Abbrev: "Z38E", OffsetMinutes: -240, DstShiftMinutes: 0, Hub: "YYZ"})
	out = append(out, ZoneRow{ZoneKey: "FZ-239", Abbrev: "Z39F", OffsetMinutes: -210, DstShiftMinutes: 0, Hub: "YVR"})
	return out
}
