package tablex

// zoneFill02 appends zone rows 120..179.
func zoneFill02(out []ZoneRow) []ZoneRow {
	out = append(out, ZoneRow{ZoneKey: "FZ-120", Abbrev: "Z20Q", OffsetMinutes: 345, DstShiftMinutes: 60, Hub: "ATL"})
	out = append(out, ZoneRow{ZoneKey: "FZ-121", Abbrev: "Z21R", OffsetMinutes: 360, DstShiftMinutes: 0, Hub: "BOS"})
	out = append(out, ZoneRow{ZoneKey: "FZ-122", Abbrev: "Z22S", OffsetMinutes: 390, DstShiftMinutes: 0, Hub: "CHI"})
	out = append(out, ZoneRow{ZoneKey: "FZ-123", Abbrev: "Z23T", OffsetMinutes: 420, DstShiftMinutes: 0, Hub: "DFW"})
	out = append(out, ZoneRow{ZoneKey: "FZ-124", Abbrev: "Z24U", OffsetMinutes: 480, DstShiftMinutes: 60, Hub: "DEN"})
	out = append(out, ZoneRow{ZoneKey: "FZ-125", Abbrev: "Z25V", OffsetMinutes: 540, DstShiftMinutes: 0, Hub: "DTW"})
	out = append(out, ZoneRow{ZoneKey: "FZ-126", Abbrev: "Z26W", OffsetMinutes: 570, DstShiftMinutes: 0, Hub: "HOU"})
	out = append(out, ZoneRow{ZoneKey: "FZ-127", Abbrev: "Z27X", OffsetMinutes: 600, DstShiftMinutes: 0, Hub: "IND"})
	out = append(out, ZoneRow{ZoneKey: "FZ-128", Abbrev: "Z28Y", OffsetMinutes: 660, DstShiftMinutes: 60, Hub: "JAX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-129", Abbrev: "Z29Z", OffsetMinutes: 720, DstShiftMinutes: 0, Hub: "KCK"})
	out = append(out, ZoneRow{ZoneKey: "FZ-130", Abbrev: "Z30A", OffsetMinutes: 780, DstShiftMinutes: 0, Hub: "LAX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-131", Abbrev: "Z31B", OffsetMinutes: 840, DstShiftMinutes: 0, Hub: "MEM"})
	out = append(out, ZoneRow{ZoneKey: "FZ-132", Abbrev: "Z32C", OffsetMinutes: -660, DstShiftMinutes: 60, Hub: "MSP"})
	out = append(out, ZoneRow{ZoneKey: "FZ-133", Abbrev: "Z33D", OffsetMinutes: -600, DstShiftMinutes: 0, Hub: "NSH"})
	out = append(out, ZoneRow{ZoneKey: "FZ-134", Abbrev: "Z34E", OffsetMinutes: -540, DstShiftMinutes: 0, Hub: "OKC"})
	out = append(out, ZoneRow{ZoneKey: "FZ-135", Abbrev: "Z35F", OffsetMinutes: -480, DstShiftMinutes: 0, Hub: "PDX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-136", Abbrev: "Z36G", OffsetMinutes: -420, DstShiftMinutes: 60, Hub: "PHX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-137", Abbrev: "Z37H", OffsetMinutes: -360, DstShiftMinutes: 0, Hub: "RNO"})
	out = append(out, ZoneRow{ZoneKey: "FZ-138", Abbrev: "Z38I", OffsetMinutes: -300, DstShiftMinutes: 0, Hub: "SLC"})
	out = append(out, ZoneRow{ZoneKey: "FZ-139", Abbrev: "Z39J", OffsetMinutes: -240, DstShiftMinutes: 0, Hub: "SEA"})
	out = append(out, ZoneRow{ZoneKey: "FZ-140", Abbrev: "Z40K", OffsetMinutes: -210, DstShiftMinutes: 60, Hub: "STL"})
	out = append(out, ZoneRow{ZoneKey: "FZ-141", Abbrev: "Z41L", OffsetMinutes: -180, DstShiftMinutes: 0, Hub: "TPA"})
	out = append(out, ZoneRow{ZoneKey: "FZ-142", Abbrev: "Z42M", OffsetMinutes: -120, DstShiftMinutes: 0, Hub: "YYZ"})
	out = append(out, ZoneRow{ZoneKey: "FZ-143", Abbrev: "Z43N", OffsetMinutes: -60, DstShiftMinutes: 0, Hub: "YVR"})
	out = append(out, ZoneRow{ZoneKey: "FZ-144", Abbrev: "Z44O", OffsetMinutes: 0, DstShiftMinutes: 60, Hub: "ATL"})
	out = append(out, ZoneRow{ZoneKey: "FZ-145", Abbrev: "Z45P", OffsetMinutes: 60, DstShiftMinutes: 0, Hub: "BOS"})
	out = append(out, ZoneRow{ZoneKey: "FZ-146", Abbrev: "Z46Q", OffsetMinutes: 120, DstShiftMinutes: 0, Hub: "CHI"})
	out = append(out, ZoneRow{ZoneKey: "FZ-147", Abbrev: "Z47R", OffsetMinutes: 180, DstShiftMinutes: 0, Hub: "DFW"})
	out = append(out, ZoneRow{ZoneKey: "FZ-148", Abbrev: "Z48S", OffsetMinutes: 210, DstShiftMinutes: 60, Hub: "DEN"})
	out = append(out, ZoneRow{ZoneKey: "FZ-149", Abbrev: "Z49T", OffsetMinutes: 240, DstShiftMinutes: 0, Hub: "DTW"})
	out = append(out, ZoneRow{ZoneKey: "FZ-150", Abbrev: "Z50U", OffsetMinutes: 270, DstShiftMinutes: 0, Hub: "HOU"})
	out = append(out, ZoneRow{ZoneKey: "FZ-151", Abbrev: "Z51V", OffsetMinutes: 300, DstShiftMinutes: 0, Hub: "IND"})
	out = append(out, ZoneRow{ZoneKey: "FZ-152", Abbrev: "Z52W", OffsetMinutes: 330, DstShiftMinutes: 60, Hub: "JAX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-153", Abbrev: "Z53X", OffsetMinutes: 345, DstShiftMinutes: 0, Hub: "KCK"})
	out = append(out, ZoneRow{ZoneKey: "FZ-154", Abbrev: "Z54Y", OffsetMinutes: 360, DstShiftMinutes: 0, Hub: "LAX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-155", Abbrev: "Z55Z", OffsetMinutes: 390, DstShiftMinutes: 0, Hub: "MEM"})
	out = append(out, ZoneRow{ZoneKey: "FZ-156", Abbrev: "Z56A", OffsetMinutes: 420, DstShiftMinutes: 60, Hub: "MSP"})
	out = append(out, ZoneRow{ZoneKey: "FZ-157", Abbrev: "Z57B", OffsetMinutes: 480, DstShiftMinutes: 0, Hub: "NSH"})
	out = append(out, ZoneRow{ZoneKey: "FZ-158", Abbrev: "Z58C", OffsetMinutes: 540, DstShiftMinutes: 0, Hub: "OKC"})
	out = append(out, ZoneRow{ZoneKey: "FZ-159", Abbrev: "Z59D", OffsetMinutes: 570, DstShiftMinutes: 0, Hub: "PDX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-160", Abbrev: "Z60E", OffsetMinutes: 600, DstShiftMinutes: 60, Hub: "PHX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-161", Abbrev: "Z61F", OffsetMinutes: 660, DstShiftMinutes: 0, Hub: "RNO"})
	out = append(out, ZoneRow{ZoneKey: "FZ-162", Abbrev: "Z62G", OffsetMinutes: 720, DstShiftMinutes: 0, Hub: "SLC"})
	out = append(out, ZoneRow{ZoneKey: "FZ-163", Abbrev: "Z63H", OffsetMinutes: 780, DstShiftMinutes: 0, Hub: "SEA"})
	out = append(out, ZoneRow{ZoneKey: "FZ-164", Abbrev: "Z64I", OffsetMinutes: 840, DstShiftMinutes: 60, Hub: "STL"})
	out = append(out, ZoneRow{ZoneKey: "FZ-165", Abbrev: "Z65J", OffsetMinutes: -660, DstShiftMinutes: 0, Hub: "TPA"})
	out = append(out, ZoneRow{ZoneKey: "FZ-166", Abbrev: "Z66K", OffsetMinutes: -600, DstShiftMinutes: 0, Hub: "YYZ"})
	out = append(out, ZoneRow{ZoneKey: "FZ-167", Abbrev: "Z67L", OffsetMinutes: -540, DstShiftMinutes: 0, Hub: "YVR"})
	out = append(out, ZoneRow{ZoneKey: "FZ-168", Abbrev: "Z68M", OffsetMinutes: -480, DstShiftMinutes: 60, Hub: "ATL"})
	out = append(out, ZoneRow{ZoneKey: "FZ-169", Abbrev: "Z69N", OffsetMinutes: -420, DstShiftMinutes: 0, Hub: "BOS"})
	out = append(out, ZoneRow{ZoneKey: "FZ-170", Abbrev: "Z70O", OffsetMinutes: -360, DstShiftMinutes: 0, Hub: "CHI"})
	out = append(out, ZoneRow{ZoneKey: "FZ-171", Abbrev: "Z71P", OffsetMinutes: -300, DstShiftMinutes: 0, Hub: "DFW"})
	out = append(out, ZoneRow{ZoneKey: "FZ-172", Abbrev: "Z72Q", OffsetMinutes: -240, DstShiftMinutes: 60, Hub: "DEN"})
	out = append(out, ZoneRow{ZoneKey: "FZ-173", Abbrev: "Z73R", OffsetMinutes: -210, DstShiftMinutes: 0, Hub: "DTW"})
	out = append(out, ZoneRow{ZoneKey: "FZ-174", Abbrev: "Z74S", OffsetMinutes: -180, DstShiftMinutes: 0, Hub: "HOU"})
	out = append(out, ZoneRow{ZoneKey: "FZ-175", Abbrev: "Z75T", OffsetMinutes: -120, DstShiftMinutes: 0, Hub: "IND"})
	out = append(out, ZoneRow{ZoneKey: "FZ-176", Abbrev: "Z76U", OffsetMinutes: -60, DstShiftMinutes: 60, Hub: "JAX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-177", Abbrev: "Z77V", OffsetMinutes: 0, DstShiftMinutes: 0, Hub: "KCK"})
	out = append(out, ZoneRow{ZoneKey: "FZ-178", Abbrev: "Z78W", OffsetMinutes: 60, DstShiftMinutes: 0, Hub: "LAX"})
	out = append(out, ZoneRow{ZoneKey: "FZ-179", Abbrev: "Z79X", OffsetMinutes: 120, DstShiftMinutes: 0, Hub: "MEM"})
	return out
}
