[control]
localhost ansible_connection=local

[edge_app]
edge-app ansible_connection=local

[edge_data]
edge-data ansible_connection=local

[edge_ops]
edge-ops ansible_connection=local

[edges:children]
edge_app
edge_data
edge_ops

