PROCESS-RECEIPT.
    IF FUNCTION TRIM(E-REF(WS-IDX)) = SPACES OR E-TRANSFER(WS-IDX) NOT = E-REF(WS-IDX)
        MOVE "ALREADY_VOID" TO WS-REASON EXIT PARAGRAPH
    END-IF
    PERFORM FIND-ACCEPTED-REFERENCE
    IF WS-REF-IDX = 0 OR E-TYPE(WS-REF-IDX) NOT = "D" OR E-VOIDED(WS-REF-IDX) = "Y"
        MOVE "BAD_REFERENCE" TO WS-REASON EXIT PARAGRAPH
    END-IF
    IF E-SOURCE(WS-IDX) NOT = E-SOURCE(WS-REF-IDX) OR E-DEST(WS-IDX) NOT = E-DEST(WS-REF-IDX) OR E-PART(WS-IDX) NOT = E-PART(WS-REF-IDX) OR E-COND(WS-IDX) NOT = E-COND(WS-REF-IDX)
        MOVE "INSUFFICIENT_STOCK" TO WS-REASON EXIT PARAGRAPH
    END-IF
    IF E-QTY-VALID(WS-IDX) NOT = "Y" OR E-QTY(WS-IDX) = 0
        MOVE "INACTIVE_PART" TO WS-REASON EXIT PARAGRAPH
    END-IF
    IF E-QTY(WS-IDX) > E-ORIGINAL(WS-REF-IDX)
        MOVE "EXCESS_RECEIPT" TO WS-REASON EXIT PARAGRAPH
    END-IF
    PERFORM FIND-STOCKS
    IF WS-DEST-IDX = 0 MOVE "BAD_QUANTITY" TO WS-REASON EXIT PARAGRAPH END-IF
    COMPUTE WS-PRODUCT = S-QTY(WS-DEST-IDX) + E-QTY(WS-IDX) ON SIZE ERROR MOVE "OVERFLOW" TO WS-REASON END-COMPUTE
    IF WS-REASON NOT = SPACES OR WS-PRODUCT >= 999999999
        MOVE "OVERFLOW" TO WS-REASON EXIT PARAGRAPH
    END-IF
    SUBTRACT E-QTY(WS-IDX) FROM E-OUTSTANDING(WS-REF-IDX)
    ADD E-QTY(WS-IDX) TO E-ACTIVE-RECEIVED(WS-REF-IDX)
    ADD E-QTY(WS-IDX) TO S-QTY(WS-DEST-IDX)
    MOVE WS-REF-IDX TO E-DISPATCH-INDEX(WS-IDX)
    MOVE "Y" TO E-ACCEPTED(WS-IDX)
    ADD 1 TO WS-ACCEPTED-COUNT.
